---@meta CreativeTabs
---@class CreativeTabs: Object
---@field ctor fun(): CreativeTabs
---@field Add fun(tab: CreativeTab): nil
---@field get_TabsByCode fun(): Orderedtable<any, any>
---@field GetTabByCode fun(code: string): CreativeTab
---@field get_Tabs fun(): any[]
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field TabsByCode Orderedtable<any, any>
---@field Tabs Orderedtable<any, any>
CreativeTabs = {}
