---@meta Packet_ServerSound
---@class Packet_ServerSound: Object
---@field ctor fun(): Packet_ServerSound
---@field SetName fun(value: string): nil
---@field SetX fun(value: number): nil
---@field SetY fun(value: number): nil
---@field SetZ fun(value: number): nil
---@field SetPitch fun(value: number): nil
---@field SetRange fun(value: number): nil
---@field SetVolume fun(value: number): nil
---@field SetSoundType fun(value: number): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_ServerSound = {}
