---@meta ISettings
---@class ISettings
---@field get_Bool fun(): ISettingsClass`1
---@field get_Int fun(): ISettingsClass`1
---@field get_Float fun(): ISettingsClass`1
---@field get_String fun(): ISettingsClass`1
---@field get_Strings fun(): ISettingsClass`1
---@field AddWatcher fun(key: string, OnValueChanged: OnSettingsChanged`1): nil
---@field Bool ISettingsClass`1
---@field Int ISettingsClass`1
---@field Float ISettingsClass`1
---@field String ISettingsClass`1
---@field Strings ISettingsClass`1
ISettings = {}
