---@meta ClassRegistryAPI
---@class ClassRegistryAPI: Object
---@field ctor fun(world: IWorldAccessor, registry: ClassRegistry): ClassRegistryAPI
---@field get_BlockClassToTypeMapping fun(): table<any, any>
---@field get_ItemClassToTypeMapping fun(): table<any, any>
---@field CreateBlock fun(blockclass: string): Block
---@field CreateBlockBehavior fun(block: Block, blockclass: string): BlockBehavior
---@field GetBlockBehaviorClass fun(blockclass: string): any
---@field CreateItem fun(itemclass: string): Item
---@field CreateItemstackAttribute fun(itemstack: ItemStack): IAttribute
---@field CreateStringAttribute fun(value: string): IAttribute
---@field CreateTreeAttribute fun(): ITreeAttribute
---@field CreateJsonTreeAttributeFromDict fun(attributes: table<any, any>): JsonTreeAttribute
---@field CreateEntity fun(entityClass: string): Entity
---@overload fun(entityType: EntityProperties): Entity
---@field CreateBlockEntity fun(blockEntityClass: string): BlockEntity
---@field GetBlockEntity fun(blockEntityClass: string): any
---@field CreateEntityBehavior fun(forEntity: Entity, entityBehaviorName: string): EntityBehavior
---@field GetBlockEntityClass fun(type: any): string
---@field CreateCropBehavior fun(forBlock: Block, cropBehaviorName: string): CropBehavior
---@field CreateInvNetworkUtil fun(inv: InventoryBase, api: ICoreAPI): IInventoryNetworkUtil
---@field CreateMountable fun(tree: TreeAttribute): IMountable
---@field GetBlockClass fun(blockclass: string): any
---@field GetItemClass fun(itemClass: string): any
---@field GetBlockBehaviorClassName fun(blockBehaviorType: any): string
---@field GetEntityClassName fun(entityType: any): string
---@field GetBlockEntityBehaviorClass fun(name: string): any
---@field CreateBlockEntityBehavior fun(blockEntity: BlockEntity, name: string): BlockEntityBehavior
---@field GetEntityBehaviorClass fun(entityBehaviorName: string): any
---@field CreateCollectibleBehavior fun(forCollectible: Collectibletable, code: string): CollectibleBehavior
---@field GetCollectibleBehaviorClass fun(code: string): any
---@field GetCollectibleBehaviorClassName fun(type: any): string
---@field RegisterParticlePropertyProvider fun(className: string, ParticleProvider: any): nil
---@field CreateParticlePropertyProvider fun(entityType: any): IParticlePropertiesProvider
---@overload fun(className: string): IParticlePropertiesProvider
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field BlockClassToTypeMapping table<any, any>
---@field ItemClassToTypeMapping table<any, any>
ClassRegistryAPI = {}
