---@meta ChunkIlluminator
---@class ChunkIlluminator: Object
---@field ctor fun(chunkProvider: IChunkProvider, readBlockAccess: IBlockAccessor, chunkSize: number): ChunkIlluminator
---@field IsValidPos fun(x: number, y: number, z: number): boolean
---@field InitForWorld fun(blockTypes: Iany[], defaultSunLight: UInt16, mapsizex: number, mapsizey: number, mapsizez: number): nil
---@field FullRelight fun(minPos: BlockPos, maxPos: BlockPos): nil
---@field Sunlight fun(chunks: IWorldChunk[], chunkX: number, chunkY: number, chunkZ: number): nil
---@field SunlightFlood fun(chunks: IWorldChunk[], chunkX: number, chunkY: number, chunkZ: number): nil
---@field SunLightFloodNeighbourChunks fun(curChunks: IWorldChunk[], chunkX: number, chunkY: number, chunkZ: number): number
---@field SpreadSunLightInColumn fun(stack: Stack`1, chunks: IWorldChunk[]): nil
---@field UpdateSunLight fun(posX: number, posY: number, posZ: number, oldAbsorb: number, newAbsorb: number): FastSetOfLongs
---@field IsDirectlyIlluminated fun(posX: number, posY: number, posZ: number): boolean
---@field SpreadSunlightAt fun(unhandledPositions: QueueOfInt, centerPos: BlockPos, isDirectlyIlluminated: boolean, touchedChunks: FastSetOfLongs): nil
---@field ClearSunlightAt fun(positionsToClear: QueueOfInt, centerPos: BlockPos, isDirectlyIlluminated: boolean, needTospreadQueue: QueueOfInt, touchedChunks: FastSetOfLongs): nil
---@field PlaceBlockLight fun(lightHsv: number[], posX: number, posY: number, posZ: number): FastSetOfLongs
---@field PlaceNonBlendingBlockLight fun(lightHsv: number[], posX: number, posY: number, posZ: number): nil
---@field RemoveBlockLight fun(oldLightHsv: number[], posX: number, posY: number, posZ: number): FastSetOfLongs
---@field UpdateBlockLight fun(oldLightAbsorb: number, newLightAbsorb: number, posX: number, posY: number, posZ: number): FastSetOfLongs
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
ChunkIlluminator = {}
