---@meta Packet_ClientServerQuerySerializer
---@class Packet_ClientServerQuerySerializer: Object
---@field ctor fun(): Packet_ClientServerQuerySerializer
---@field DeserializeLengthDelimitedNew fun(stream: CitoMemoryStream): Packet_ClientServerQuery
---@field DeserializeBuffer fun(buffer: number[], length: number, instance: Packet_ClientServerQuery): Packet_ClientServerQuery
---@field Deserialize fun(stream: CitoMemoryStream, instance: Packet_ClientServerQuery): Packet_ClientServerQuery
---@field DeserializeLengthDelimited fun(stream: CitoMemoryStream, instance: Packet_ClientServerQuery): Packet_ClientServerQuery
---@field Serialize fun(stream: CitoStream, instance: Packet_ClientServerQuery): nil
---@field SerializeToBytes fun(instance: Packet_ClientServerQuery): number[]
---@field SerializeLengthDelimited fun(stream: CitoStream, instance: Packet_ClientServerQuery): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_ClientServerQuerySerializer = {}
