---@meta Packet_ServerLevelInitialize
---@class Packet_ServerLevelInitialize: Object
---@field ctor fun(): Packet_ServerLevelInitialize
---@field SetServerChunkSize fun(value: number): nil
---@field SetServerMapChunkSize fun(value: number): nil
---@field SetServerMapRegionSize fun(value: number): nil
---@field SetMaxViewDistance fun(value: number): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_ServerLevelInitialize = {}
