---@meta AABBIntersectionTest
---@class AABBIntersectionTest: Object
---@field ctor fun(blockSelectionTester: IWorldIntersectionSupplier): AABBIntersectionTest
---@field LoadRayAndPos fun(line3d: Line3D): nil
---@overload fun(ray: Ray): nil
---@field GetSelectedBlock fun(from: Vec3d, to: Vec3d, filter: BlockFilter): BlockSelection
---@overload fun(maxDistance: Single, filter: BlockFilter): BlockSelection
---@field RayIntersectsBlockSelectionBox fun(pos: BlockPos, filter: BlockFilter): boolean
---@field RayIntersectsWithCuboid fun(selectionBox: Cuboidf, posX: Double, posY: Double, posZ: Double): boolean
---@overload fun(selectionBox: Cuboidd, hitOnBlockFace: BlockFacing&, hitPosition: Vec3d&): boolean
---@field RayInteresectWithCuboidSlabMethod fun(b: Cuboidd, r: Ray): boolean
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
AABBIntersectionTest = {}
