---@meta IWorldPlayerData
---@class IWorldPlayerData
---@field get_PlayerUID fun(): string
---@field get_EntityPlayer fun(): EntityPlayer
---@field get_EntityControls fun(): EntityControls
---@field get_LastApprovedViewDistance fun(): number
---@field set_LastApprovedViewDistance fun(value: number): nil
---@field get_DesiredViewDistance fun(): number
---@field set_DesiredViewDistance fun(value: number): nil
---@field get_CurrentGameMode fun(): EnumGameMode
---@field set_CurrentGameMode fun(value: EnumGameMode): nil
---@field get_FreeMove fun(): boolean
---@field set_FreeMove fun(value: boolean): nil
---@field get_FreeMovePlaneLock fun(): EnumFreeMovAxisLock
---@field set_FreeMovePlaneLock fun(value: EnumFreeMovAxisLock): nil
---@field get_NoClip fun(): boolean
---@field set_NoClip fun(value: boolean): nil
---@field get_MoveSpeedMultiplier fun(): Single
---@field set_MoveSpeedMultiplier fun(value: Single): nil
---@field get_PickingRange fun(): Single
---@field set_PickingRange fun(value: Single): nil
---@field get_AreaSelectionMode fun(): boolean
---@field set_AreaSelectionMode fun(value: boolean): nil
---@field get_Deaths fun(): number
---@field SetModdata fun(key: string, data: number[]): nil
---@field RemoveModdata fun(key: string): nil
---@field GetModdata fun(key: string): number[]
---@field PlayerUID string
---@field EntityPlayer string
---@field EntityControls string
---@field LastApprovedViewDistance string
---@field DesiredViewDistance string
---@field CurrentGameMode string
---@field FreeMove string
---@field FreeMovePlaneLock string
---@field NoClip string
---@field MoveSpeedMultiplier string
---@field PickingRange string
---@field AreaSelectionMode string
---@field Deaths string
IWorldPlayerData = {}
