---@meta NoAnimationManager
---@class NoAnimationManager: Object
---@field ctor fun(): NoAnimationManager
---@field get_Animator fun(): IAnimator
---@field set_Animator fun(value: IAnimator): nil
---@field get_AnimationsDirty fun(): boolean
---@field set_AnimationsDirty fun(value: boolean): nil
---@field get_ActiveAnimationsByAnimCode fun(): table<any, any>
---@field get_HeadController fun(): EntityHeadController
---@field set_HeadController fun(value: EntityHeadController): nil
---@field Dispose fun(): nil
---@field FromAttributes fun(tree: ITreeAttribute, version: string): nil
---@field GetAnimationState fun(anim: string): RunningAnimation
---@field Init fun(api: ICoreAPI, entity: Entity): nil
---@field IsAnimationActive fun(anims: string[]): boolean
---@field OnAnimationStopped fun(code: string): nil
---@field OnClientFrame fun(dt: Single): nil
---@field OnReceivedServerAnimations fun(activeAnimations: number[], activeAnimationsCount: number, activeAnimationSpeeds: Single[]): nil
---@field OnServerTick fun(dt: Single): nil
---@field RegisterFrameCallback fun(trigger: AnimFrameCallback): nil
---@field ResetAnimation fun(beginholdAnim: string): nil
---@field StartAnimation fun(animdata: AnimationMetaData): boolean
---@overload fun(configCode: string): boolean
---@field StopAnimation fun(code: string): nil
---@field ToAttributes fun(tree: ITreeAttribute, forClient: boolean): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field Animator IAnimator
---@field AnimationsDirty IAnimator
---@field ActiveAnimationsByAnimCode IAnimator
---@field HeadController IAnimator
NoAnimationManager = {}
