---@meta Ray
---@class Ray: Object
---@field ctor fun(): Ray
---@overload fun(o: Vec3d, d: Vec3d): Ray
---@field get_Length fun(): Double
---@field LimitToWalls fun(minx: number, miny: number, minz: number, maxx: number, maxy: number, maxz: number): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field Length Double
---@field origin Double
---@field dir Double
Ray = {}
