---@meta Packet_ClientLoadedSerializer
---@class Packet_ClientLoadedSerializer: Object
---@field ctor fun(): Packet_ClientLoadedSerializer
---@field DeserializeLengthDelimitedNew fun(stream: CitoMemoryStream): Packet_ClientLoaded
---@field DeserializeBuffer fun(buffer: number[], length: number, instance: Packet_ClientLoaded): Packet_ClientLoaded
---@field Deserialize fun(stream: CitoMemoryStream, instance: Packet_ClientLoaded): Packet_ClientLoaded
---@field DeserializeLengthDelimited fun(stream: CitoMemoryStream, instance: Packet_ClientLoaded): Packet_ClientLoaded
---@field Serialize fun(stream: CitoStream, instance: Packet_ClientLoaded): nil
---@field SerializeToBytes fun(instance: Packet_ClientLoaded): number[]
---@field SerializeLengthDelimited fun(stream: CitoStream, instance: Packet_ClientLoaded): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_ClientLoadedSerializer = {}
