---@meta CropBehavior
---@class CropBehavior: Object
---@field ctor fun(block: Block): CropBehavior
---@field Initialize fun(properties: Jsontable): nil
---@field TryGrowCrop fun(api: ICoreAPI, farmland: IFarmlandBlockEntity, currentTotalHours: Double, newGrowthStage: number, handling: EnumHandling&): boolean
---@field OnPlanted fun(api: ICoreAPI): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
CropBehavior = {}
