---@meta IConvertible
---@class IConvertible
---@field GetTypeCode fun(): anyCode
---@field ToBoolean fun(provider: IFormatProvider): boolean
---@field ToChar fun(provider: IFormatProvider): Char
---@field ToSByte fun(provider: IFormatProvider): Snumber
---@field ToByte fun(provider: IFormatProvider): number
---@field ToInt16 fun(provider: IFormatProvider): Int16
---@field ToUInt16 fun(provider: IFormatProvider): UInt16
---@field ToInt32 fun(provider: IFormatProvider): number
---@field ToUInt32 fun(provider: IFormatProvider): Unumber
---@field ToInt64 fun(provider: IFormatProvider): Int64
---@field ToUInt64 fun(provider: IFormatProvider): UInt64
---@field ToSingle fun(provider: IFormatProvider): Single
---@field ToDouble fun(provider: IFormatProvider): Double
---@field ToDecimal fun(provider: IFormatProvider): Decimal
---@field ToDateTime fun(provider: IFormatProvider): DateTime
---@field ToString fun(provider: IFormatProvider): string
---@field ToType fun(conversionType: any, provider: IFormatProvider): table
IConvertible = {}
