---@meta SemVer
---@class SemVer: Object
---@field ctor fun(major: number, minor: number, patch: number): SemVer
---@overload fun(major: number, minor: number, patch: number, preRelease: string, buildMetadata: string): SemVer
---@overload fun(major: number, minor: number, patch: number, preReleaseIdentifiers: string[], buildMetadataIdentifiers: string[]): SemVer
---@field get_Major fun(): number
---@field get_Minor fun(): number
---@field get_Patch fun(): number
---@field get_PreReleaseIdentifiers fun(): string[]
---@field get_BuildMetadataIdentifiers fun(): string[]
---@field get_PreRelease fun(): string
---@field get_BuildMetadata fun(): string
---@field Parse fun(s: string): SemVer
---@field TryParse fun(s: string, result: SemVer&): boolean
---@overload fun(s: string, result: SemVer&, error: string&): boolean
---@field ToString fun(): string
---@field op_Equality fun(left: SemVer, right: SemVer): boolean
---@field op_Inequality fun(left: SemVer, right: SemVer): boolean
---@field op_GreaterThan fun(left: SemVer, right: SemVer): boolean
---@field op_LessThan fun(left: SemVer, right: SemVer): boolean
---@field op_GreaterThanOrEqual fun(left: SemVer, right: SemVer): boolean
---@field op_LessThanOrEqual fun(left: SemVer, right: SemVer): boolean
---@field CompareTo fun(other: SemVer): number
---@field Compare fun(left: SemVer, right: SemVer): number
---@field Equals fun(other: SemVer): boolean
---@overload fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field GetType fun(): any
---@field Major number
---@field Minor number
---@field Patch number
---@field PreReleaseIdentifiers number
---@field BuildMetadataIdentifiers number
---@field PreRelease number
---@field BuildMetadata number
SemVer = {}
