---@meta RecipeRegistryGeneric`1
---@class RecipeRegistryGeneric`1: RecipeRegistryBase
---@field ctor fun(): RecipeRegistryGeneric`1
---@overload fun(recipes: any[]): RecipeRegistryGeneric`1
---@field FromBytes fun(resolver: IWorldAccessor, quantity: number, data: number[]): nil
---@field ToBytes fun(resolver: IWorldAccessor, data: number[]&, quantity: number&): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
RecipeRegistryGeneric`1 = {}
