---@meta NetServer
---@class NetServer: Object
---@field get_Name fun(): string
---@field get_LocalEndpoint fun(): string
---@field SetIpAndPort fun(ip: string, port: number): nil
---@field Start fun(): nil
---@field ReadMessage fun(): NetIncomingMessage
---@field Dispose fun(): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field Name string
---@field LocalEndpoint string
NetServer = {}
