---@meta ITreeAttribute
---@class ITreeAttribute
---@field get_Item fun(key: string): IAttribute
---@field set_Item fun(key: string, value: IAttribute): nil
---@field get_Count fun(): number
---@field get_Values fun(): IAttribute[]
---@field HasAttribute fun(key: string): boolean
---@field RemoveAttribute fun(key: string): nil
---@field SetBool fun(key: string, value: boolean): nil
---@field SetInt fun(key: string, value: number): nil
---@field SetLong fun(key: string, value: Int64): nil
---@field SetDouble fun(key: string, value: Double): nil
---@field SetFloat fun(key: string, value: Single): nil
---@field SetString fun(key: string, value: string): nil
---@field SetBytes fun(key: string, value: number[]): nil
---@field SetItemstack fun(key: string, itemstack: ItemStack): nil
---@field TryGetBool fun(key: string): Nullable`1
---@field GetBool fun(key: string, defaultValue: boolean): boolean
---@field TryGetInt fun(key: string): Nullable`1
---@field GetInt fun(key: string, defaultValue: number): number
---@field GetAsInt fun(key: string, defaultValue: number): number
---@field GetAsBool fun(key: string, defaultValue: boolean): boolean
---@field GetDecimal fun(key: string, defaultValue: Double): Double
---@field GetAsString fun(key: string, defaultValue: string): string
---@field TryGetLong fun(key: string): Nullable`1
---@field GetLong fun(key: string, defaultValue: Int64): Int64
---@field TryGetFloat fun(key: string): Nullable`1
---@field GetFloat fun(key: string, defaultValue: Single): Single
---@field TryGetDouble fun(key: string): Nullable`1
---@field GetDouble fun(key: string, defaultValue: Double): Double
---@field GetString fun(key: string, defaultValue: string): string
---@field GetBytes fun(key: string, defaultValue: number[]): number[]
---@field GetItemstack fun(key: string, defaultValue: ItemStack): ItemStack
---@field GetTreeAttribute fun(key: string): ITreeAttribute
---@field GetOrAddTreeAttribute fun(key: string): ITreeAttribute
---@field Clone fun(): ITreeAttribute
---@field MergeTree fun(tree: ITreeAttribute): nil
---@field SortedCopy fun(recursive: boolean): ITreeAttribute
---@field Equals fun(worldForResolve: IWorldAccessor, attr: IAttribute, ignoreSubTrees: string[]): boolean
---@field IsSubSetOf fun(worldForResolve: IWorldAccessor, other: IAttribute): boolean
---@field GetHashCode fun(ignoredAttributes: string[]): number
---@field Item IAttribute
---@field Count IAttribute
---@field Values IAttribute
ITreeAttribute = {}
