---@meta Size3d
---@class Size3d: Object
---@field ctor fun(): Size3d
---@overload fun(width: Double, height: Double, length: Double): Size3d
---@field Clone fun(): Size3d
---@field CanContain fun(obj: Size3d): boolean
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Size3d = {}
