---@meta Packet_CreateItemstackSerializer
---@class Packet_CreateItemstackSerializer: Object
---@field ctor fun(): Packet_CreateItemstackSerializer
---@field DeserializeLengthDelimitedNew fun(stream: CitoMemoryStream): Packet_CreateItemstack
---@field DeserializeBuffer fun(buffer: number[], length: number, instance: Packet_CreateItemstack): Packet_CreateItemstack
---@field Deserialize fun(stream: CitoMemoryStream, instance: Packet_CreateItemstack): Packet_CreateItemstack
---@field DeserializeLengthDelimited fun(stream: CitoMemoryStream, instance: Packet_CreateItemstack): Packet_CreateItemstack
---@field Serialize fun(stream: CitoStream, instance: Packet_CreateItemstack): nil
---@field SerializeToBytes fun(instance: Packet_CreateItemstack): number[]
---@field SerializeLengthDelimited fun(stream: CitoStream, instance: Packet_CreateItemstack): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_CreateItemstackSerializer = {}
