---@meta GltfImage
---@class GltfImage: Object
---@field ctor fun(): GltfImage
---@field get_BufferView fun(): Int64
---@field set_BufferView fun(value: Int64): nil
---@field get_MimeType fun(): string
---@field set_MimeType fun(value: string): nil
---@field get_Name fun(): string
---@field set_Name fun(value: string): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field BufferView Int64
---@field MimeType Int64
---@field Name Int64
GltfImage = {}
