---@meta GuiElementRichtext
---@class GuiElementRichtext: GuiElement
---@field ctor fun(capi: ICoreClientAPI, components: RichTextComponentBase[], bounds: ElementBounds): GuiElementRichtext
---@field get_MaxLineWidth fun(): Double
---@field get_TotalHeight fun(): Double
---@field BeforeCalcBounds fun(): nil
---@field ComposeElements fun(ctxStatic: Context, surfaceStatic: ImageSurface): nil
---@field Compose fun(genTextureLater: boolean): nil
---@field genTexture fun(): nil
---@field CalcHeightAndPositions fun(): nil
---@field ComposeFor fun(bounds: ElementBounds, ctx: Context, surface: ImageSurface): nil
---@field RecomposeText fun(): nil
---@field RenderInteractiveElements fun(deltaTime: Single): nil
---@field OnMouseMove fun(api: ICoreClientAPI, args: MouseEvent): nil
---@field OnMouseDownOnElement fun(api: ICoreClientAPI, args: MouseEvent): nil
---@field OnMouseUp fun(api: ICoreClientAPI, args: MouseEvent): nil
---@field SetNewText fun(vtmlCode: string, baseFont: CairoFont, didClickLink: any`1): nil
---@overload fun(comps: RichTextComponentBase[]): nil
---@field AppendText fun(comps: RichTextComponent[]): nil
---@field SetNewTextWithoutRecompose fun(vtmlCode: string, baseFont: CairoFont, didClickLink: any`1, recalcBounds: boolean): nil
---@field RecomposeInto fun(surface: ImageSurface, ctx: Context): nil
---@field Dispose fun(): nil
---@field get_InsideClipBounds fun(): ElementBounds
---@field set_InsideClipBounds fun(value: ElementBounds): nil
---@field get_RenderAsPremultipliedAlpha fun(): boolean
---@field set_RenderAsPremultipliedAlpha fun(value: boolean): nil
---@field get_HasFocus fun(): boolean
---@field get_DrawOrder fun(): Double
---@field get_Focusable fun(): boolean
---@field get_Scale fun(): Double
---@field set_Scale fun(value: Double): nil
---@field OnFocusGained fun(): nil
---@field OnFocusLost fun(): nil
---@field PostRenderInteractiveElements fun(deltaTime: Single): nil
---@field RenderFocusOverlay fun(deltaTime: Single): nil
---@field DialogRoundRectangle fun(ctx: Context, bounds: ElementBounds): nil
---@field ElementRoundRectangle fun(ctx: Context, bounds: ElementBounds, isBackground: boolean, radius: Double): nil
---@field ShadePath fun(ctx: Context, thickness: Double): nil
---@field EmbossRoundRectangleDialog fun(ctx: Context, x: Double, y: Double, width: Double, height: Double, inverse: boolean): nil
---@field EmbossRoundRectangleElement fun(ctx: Context, x: Double, y: Double, width: Double, height: Double, inverse: boolean, depth: number, radius: number): nil
---@overload fun(ctx: Context, bounds: ElementBounds, inverse: boolean, depth: number, radius: number): nil
---@field RenderBoundsDebug fun(): nil
---@field OnMouseDown fun(api: ICoreClientAPI, mouse: MouseEvent): nil
---@field OnMouseUpOnElement fun(api: ICoreClientAPI, args: MouseEvent): nil
---@field OnMouseEnterSlot fun(api: ICoreClientAPI, slot: ItemSlot): boolean
---@field OnMouseLeaveSlot fun(api: ICoreClientAPI, slot: ItemSlot): boolean
---@field OnMouseWheel fun(api: ICoreClientAPI, args: MouseWheelEventArgs): nil
---@field OnKeyDown fun(api: ICoreClientAPI, args: KeyEvent): nil
---@field OnKeyUp fun(api: ICoreClientAPI, args: KeyEvent): nil
---@field OnKeyPress fun(api: ICoreClientAPI, args: KeyEvent): nil
---@field IsPositionInside fun(posX: number, posY: number): boolean
---@field get_MouseOverCursor fun(): string
---@field OutlineColor fun(): number
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field MaxLineWidth Double
---@field TotalHeight Double
---@field InsideClipBounds Double
---@field RenderAsPremultipliedAlpha Double
---@field HasFocus Double
---@field DrawOrder Double
---@field Focusable Double
---@field Scale Double
---@field MouseOverCursor Double
---@field Components Double
---@field zPos Double
---@field richtTextTexture Double
---@field Debug Double
---@field RenderColor Double
---@field HalfComposed Double
---@field DebugLogging Double
---@field Bounds Double
---@field TabIndex Double
GuiElementRichtext = {}
