---@meta GltfMatTexture
---@class GltfMatTexture: Object
---@field ctor fun(): GltfMatTexture
---@field get_Index fun(): Int64
---@field set_Index fun(value: Int64): nil
---@field get_TexCoord fun(): Int64
---@field set_TexCoord fun(value: Int64): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field Index Int64
---@field TexCoord Int64
GltfMatTexture = {}
