---@meta ExifData
---@class ExifData: Object
---@field ctor fun(FileNameWithPath: string, Options: ExifLoadOptions): ExifData
---@overload fun(ImageStream: Stream, Options: ExifLoadOptions): ExifData
---@field get_MakerNoteOriginalOffset fun(): number
---@field Empty fun(): ExifData
---@field Save fun(DestFileNameWithPath: string, SaveOptions: ExifSaveOptions): nil
---@overload fun(SourceStream: Stream, DestStream: Stream, SaveOptions: ExifSaveOptions): nil
---@field GetTagValue fun(TagSpec: ExifTag, Value: string&, Coding: StrCoding): boolean
---@field SetTagValue fun(TagSpec: ExifTag, Value: string, Coding: StrCoding): boolean
---@overload fun(TagSpec: ExifTag, Value: number&, Index: number): boolean
---@overload fun(TagSpec: ExifTag, Value: number, TagType: ExifTagany, Index: number): boolean
---@overload fun(TagSpec: ExifTag, Value: Unumber&, Index: number): boolean
---@overload fun(TagSpec: ExifTag, Value: Unumber, TagType: ExifTagany, Index: number): boolean
---@overload fun(TagSpec: ExifTag, Value: ExifRational&, Index: number): boolean
---@overload fun(TagSpec: ExifTag, Value: ExifRational, TagType: ExifTagany, Index: number): boolean
---@overload fun(TagSpec: ExifTag, Value: DateTime&, Format: ExifDateFormat): boolean
---@overload fun(TagSpec: ExifTag, Value: DateTime, Format: ExifDateFormat): boolean
---@field GetTagRawData fun(TagSpec: ExifTag, TagType: ExifTagany&, ValueCount: number&, RawData: number[]&, RawDataIndex: number&): boolean
---@overload fun(TagSpec: ExifTag, TagType: ExifTagany&, ValueCount: number&, RawData: number[]&): boolean
---@field SetTagRawData fun(TagSpec: ExifTag, TagType: ExifTagany, ValueCount: number, RawData: number[], RawDataIndex: number): boolean
---@field GetTagValueCount fun(TagSpec: ExifTag, ValueCount: number&): boolean
---@field SetTagValueCount fun(TagSpec: ExifTag, ValueCount: number): boolean
---@overload fun(TagSpec: ExifTag, ValueCount: number, TagType: ExifTagany): boolean
---@field GetTagType fun(TagSpec: ExifTag, TagType: ExifTagany&): boolean
---@field TagExists fun(TagSpec: ExifTag): boolean
---@field IfdExists fun(Ifd: ExifIfd): boolean
---@field ImageFileBlockExists fun(BlockType: ImageFileBlock): boolean
---@field RemoveTag fun(TagSpec: ExifTag): boolean
---@field RemoveAllTagsFromIfd fun(Ifd: ExifIfd): boolean
---@field RemoveAllTags fun(): nil
---@field RemoveImageFileBlock fun(BlockType: ImageFileBlock): nil
---@field ReplaceAllTagsBy fun(SourceExifData: ExifData): nil
---@field ThumbnailImageExists fun(): boolean
---@field GetThumbnailImage fun(ThumbnailData: number[]&, ThumbnailIndex: number&, ThumbnailByteCount: number&): boolean
---@field SetThumbnailImage fun(ThumbnailData: number[], ThumbnailIndex: number, ThumbnailByteCount: number): boolean
---@field RemoveThumbnailImage fun(RemoveAlsoThumbnailTags: boolean): nil
---@field get_ByteOrder fun(): ExifnumberOrder
---@field ExtractIfd fun(TagSpec: ExifTag): ExifIfd
---@field ExtractTagId fun(TagSpec: ExifTag): ExifTagId
---@field ComposeTagSpec fun(Ifd: ExifIfd, TagId: ExifTagId): ExifTag
---@field GetTagByteCount fun(TagType: ExifTagany, ValueCount: number): number
---@field ExifReadUInt16 fun(Data: number[], StartIndex: number): UInt16
---@field ExifWriteUInt16 fun(Data: number[], StartIndex: number, Value: UInt16): nil
---@field ExifReadUInt32 fun(Data: number[], StartIndex: number): Unumber
---@field ExifWriteUInt32 fun(Data: number[], StartIndex: number, Value: Unumber): nil
---@field InitTagEnumeration fun(Ifd: ExifIfd): boolean
---@field EnumerateNextTag fun(TagSpec: ExifTag&): boolean
---@field GetDateTaken fun(Value: DateTime&): boolean
---@field SetDateTaken fun(Value: DateTime): boolean
---@field RemoveDateTaken fun(): nil
---@field GetDateDigitized fun(Value: DateTime&): boolean
---@field SetDateDigitized fun(Value: DateTime): boolean
---@field RemoveDateDigitized fun(): nil
---@field GetDateChanged fun(Value: DateTime&): boolean
---@field SetDateChanged fun(Value: DateTime): boolean
---@field RemoveDateChanged fun(): nil
---@field GetGpsLongitude fun(Value: GeoCoordinate&): boolean
---@field SetGpsLongitude fun(Value: GeoCoordinate): boolean
---@field RemoveGpsLongitude fun(): nil
---@field GetGpsLatitude fun(Value: GeoCoordinate&): boolean
---@field SetGpsLatitude fun(Value: GeoCoordinate): boolean
---@field RemoveGpsLatitude fun(): nil
---@field GetGpsAltitude fun(Value: Decimal&): boolean
---@field SetGpsAltitude fun(Value: Decimal): boolean
---@field RemoveGpsAltitude fun(): nil
---@field GetGpsDateTimeStamp fun(Value: DateTime&): boolean
---@field SetGpsDateTimeStamp fun(Value: DateTime): boolean
---@field RemoveGpsDateTimeStamp fun(): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field MakerNoteOriginalOffset number
---@field ByteOrder number
---@field ImageType number
---@field IfdShift number
ExifData = {}
