---@meta IClientNetworkAPI
---@class IClientNetworkAPI
---@field RegisterChannel fun(channelName: string): IClientNetworkChannel
---@field GetChannel fun(channelName: string): IClientNetworkChannel
---@field GetChannelState fun(channelName: string): EnumChannelState
---@field SendBlockEntityPacket fun(x: number, y: number, z: number, packetId: number, data: number[]): nil
---@overload fun(pos: BlockPos, packetId: number, data: number[]): nil
---@field SendEntityPacket fun(entityid: Int64, packetId: number, data: number[]): nil
---@overload fun(x: number, y: number, z: number, internalPacket: table): nil
---@overload fun(entityid: Int64, internalPacket: table): nil
---@field SendArbitraryPacket fun(data: number[]): nil
---@field SendPacketClient fun(packetClient: table): nil
---@field SendHandInteraction fun(mouseButton: number, blockSelection: BlockSelection, entitySelection: EntitySelection, beforeUseType: EnumHandInteract, state: number, firstEvent: boolean, cancelReason: EnumItemUseCancelReason): nil
---@field SendPlayerNowReady fun(): nil
---@field SendBlockEntityPacket fun(pos: BlockPos, packetId: number, data: T): nil
IClientNetworkAPI = {}
