---@meta EntityRenderer
---@class EntityRenderer: Object
---@field ctor fun(entity: Entity, api: ICoreClientAPI): EntityRenderer
---@field OnEntityLoaded fun(): nil
---@field DoRender3DOpaque fun(dt: Single, isShadowPass: boolean): nil
---@field DoRender3DOpaqueBatched fun(dt: Single, isShadowPass: boolean): nil
---@field DoRender3DAfterOIT fun(dt: Single, isShadowPass: boolean): nil
---@field DoRender2D fun(dt: Single): nil
---@field RenderToGui fun(dt: Single, posX: Double, posY: Double, posZ: Double, yawDelta: Single, size: Single): nil
---@field BeforeRender fun(dt: Single): nil
---@field Dispose fun(): nil
---@field DoRender3DOIT fun(dt: Single): nil
---@field DoRender3DOITBatched fun(dt: Single): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
EntityRenderer = {}
