---@meta Packet_BlockSoundSet
---@class Packet_BlockSoundSet: Object
---@field ctor fun(): Packet_BlockSoundSet
---@field SetWalk fun(value: string): nil
---@field SetBreak fun(value: string): nil
---@field SetPlace fun(value: string): nil
---@field SetHit fun(value: string): nil
---@field SetInside fun(value: string): nil
---@field SetAmbient fun(value: string): nil
---@field SetAmbientBlockCount fun(value: number): nil
---@field GetByToolTool fun(): number[]
---@field SetByToolTool fun(value: number[], count: number, length: number): nil
---@overload fun(value: number[]): nil
---@field GetByToolToolCount fun(): number
---@field ByToolToolAdd fun(value: number): nil
---@field GetByToolSound fun(): Packet_BlockSoundSet[]
---@field SetByToolSound fun(value: Packet_BlockSoundSet[], count: number, length: number): nil
---@overload fun(value: Packet_BlockSoundSet[]): nil
---@field GetByToolSoundCount fun(): number
---@field ByToolSoundAdd fun(value: Packet_BlockSoundSet): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_BlockSoundSet = {}
