---@meta EntityControls
---@class EntityControls: Object
---@field ctor fun(): EntityControls
---@field get_Flags fun(): boolean[]
---@field get_TriesToMove fun(): boolean
---@field get_Forward fun(): boolean
---@field set_Forward fun(value: boolean): nil
---@field get_Backward fun(): boolean
---@field set_Backward fun(value: boolean): nil
---@field get_Left fun(): boolean
---@field set_Left fun(value: boolean): nil
---@field get_Right fun(): boolean
---@field set_Right fun(value: boolean): nil
---@field get_Jump fun(): boolean
---@field set_Jump fun(value: boolean): nil
---@field get_Sneak fun(): boolean
---@field set_Sneak fun(value: boolean): nil
---@field get_Gliding fun(): boolean
---@field set_Gliding fun(value: boolean): nil
---@field get_FloorSitting fun(): boolean
---@field set_FloorSitting fun(value: boolean): nil
---@field get_Sprint fun(): boolean
---@field set_Sprint fun(value: boolean): nil
---@field get_Up fun(): boolean
---@field set_Up fun(value: boolean): nil
---@field get_Down fun(): boolean
---@field set_Down fun(value: boolean): nil
---@field get_LeftMouseDown fun(): boolean
---@field set_LeftMouseDown fun(value: boolean): nil
---@field get_RightMouseDown fun(): boolean
---@field set_RightMouseDown fun(value: boolean): nil
---@field get_CtrlKey fun(): boolean
---@field set_CtrlKey fun(value: boolean): nil
---@field get_ShiftKey fun(): boolean
---@field set_ShiftKey fun(value: boolean): nil
---@field get_Item fun(action: EnumEntityAction): boolean
---@field set_Item fun(action: EnumEntityAction, value: boolean): nil
---@field CalcMovementVectors fun(pos: EntityPos, dt: Single): nil
---@field SetFrom fun(controls: EntityControls): nil
---@field UpdateFromPacket fun(pressed: boolean, action: number): nil
---@field StopAllMovement fun(): nil
---@field ToInt fun(): number
---@field FromInt fun(flagsInt: number): nil
---@field ToBytes fun(writer: BinaryWriter): nil
---@field FromBytes fun(reader: BinaryReader, ignoreData: boolean): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field Flags boolean[]
---@field TriesToMove boolean[]
---@field Forward boolean[]
---@field Backward boolean[]
---@field Left boolean[]
---@field Right boolean[]
---@field Jump boolean[]
---@field Sneak boolean[]
---@field Gliding boolean[]
---@field FloorSitting boolean[]
---@field Sprint boolean[]
---@field Up boolean[]
---@field Down boolean[]
---@field LeftMouseDown boolean[]
---@field RightMouseDown boolean[]
---@field CtrlKey boolean[]
---@field ShiftKey boolean[]
---@field Item boolean[]
---@field OnAction boolean[]
---@field DetachedMode boolean[]
---@field NoClip boolean[]
---@field FlyPlaneLock boolean[]
---@field WalkVector boolean[]
---@field FlyVector boolean[]
---@field IsFlying boolean[]
---@field IsClimbing boolean[]
---@field IsAiming boolean[]
---@field IsStepping boolean[]
---@field HandUse boolean[]
---@field HandUsingBlockSel boolean[]
---@field UsingCount boolean[]
---@field UsingBeginMS boolean[]
---@field LeftUsingHeldItemTransformBefore boolean[]
---@field UsingHeldItemTransformBefore boolean[]
---@field UsingHeldItemTransformAfter boolean[]
---@field MovespeedMultiplier boolean[]
---@field Dirty boolean[]
---@field GlideSpeed boolean[]
EntityControls = {}
