---@meta Packet_UnloadMapRegionSerializer
---@class Packet_UnloadMapRegionSerializer: Object
---@field ctor fun(): Packet_UnloadMapRegionSerializer
---@field DeserializeLengthDelimitedNew fun(stream: CitoMemoryStream): Packet_UnloadMapRegion
---@field DeserializeBuffer fun(buffer: number[], length: number, instance: Packet_UnloadMapRegion): Packet_UnloadMapRegion
---@field Deserialize fun(stream: CitoMemoryStream, instance: Packet_UnloadMapRegion): Packet_UnloadMapRegion
---@field DeserializeLengthDelimited fun(stream: CitoMemoryStream, instance: Packet_UnloadMapRegion): Packet_UnloadMapRegion
---@field Serialize fun(stream: CitoStream, instance: Packet_UnloadMapRegion): nil
---@field SerializeToBytes fun(instance: Packet_UnloadMapRegion): number[]
---@field SerializeLengthDelimited fun(stream: CitoStream, instance: Packet_UnloadMapRegion): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_UnloadMapRegionSerializer = {}
