---@meta ParticlesProviderBase
---@class ParticlesProviderBase: Object
---@field get_Async fun(): boolean
---@field get_Bounciness fun(): Single
---@field set_Bounciness fun(value: Single): nil
---@field get_RandomVelocityChange fun(): boolean
---@field set_RandomVelocityChange fun(value: boolean): nil
---@field get_DieOnRainHeightmap fun(): boolean
---@field set_DieOnRainHeightmap fun(value: boolean): nil
---@field get_DieInLiquid fun(): boolean
---@field get_SwimOnLiquid fun(): boolean
---@field get_DieInAir fun(): boolean
---@field get_Quantity fun(): Single
---@field get_Pos fun(): Vec3d
---@field GetVelocity fun(pos: Vec3d): Vec3f
---@field GetRgbaColor fun(capi: ICoreClientAPI): number
---@field get_OpacityEvolve fun(): EvolvingNatFloat
---@field get_RedEvolve fun(): EvolvingNatFloat
---@field get_GreenEvolve fun(): EvolvingNatFloat
---@field get_BlueEvolve fun(): EvolvingNatFloat
---@field get_ParticleModel fun(): EnumParticleModel
---@field get_Size fun(): Single
---@field get_SizeEvolve fun(): EvolvingNatFloat
---@field get_VelocityEvolve fun(): EvolvingNatFloat[]
---@field get_GravityEffect fun(): Single
---@field get_LifeLength fun(): Single
---@field get_VertexFlags fun(): number
---@field get_SelfPropelled fun(): boolean
---@field get_TerrainCollision fun(): boolean
---@field ToBytes fun(writer: BinaryWriter): nil
---@field FromBytes fun(reader: BinaryReader, resolver: IWorldAccessor): nil
---@field get_SecondarySpawnInterval fun(): Single
---@field get_SecondaryParticles fun(): IParticlePropertiesProvider[]
---@field get_DeathParticles fun(): IParticlePropertiesProvider[]
---@field BeginParticle fun(): nil
---@field PrepareForSecondarySpawn fun(particleInstance: ParticleBase): nil
---@field Init fun(api: ICoreAPI): nil
---@field get_ParentVelocity fun(): Vec3f
---@field set_ParentVelocity fun(value: Vec3f): nil
---@field get_WindAffected fun(): boolean
---@field set_WindAffected fun(value: boolean): nil
---@field get_ParentVelocityWeight fun(): Single
---@field set_ParentVelocityWeight fun(value: Single): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field Async boolean
---@field Bounciness boolean
---@field RandomVelocityChange boolean
---@field DieOnRainHeightmap boolean
---@field DieInLiquid boolean
---@field SwimOnLiquid boolean
---@field DieInAir boolean
---@field Quantity boolean
---@field Pos boolean
---@field OpacityEvolve boolean
---@field RedEvolve boolean
---@field GreenEvolve boolean
---@field BlueEvolve boolean
---@field ParticleModel boolean
---@field Size boolean
---@field SizeEvolve boolean
---@field VelocityEvolve boolean
---@field GravityEffect boolean
---@field LifeLength boolean
---@field VertexFlags boolean
---@field SelfPropelled boolean
---@field TerrainCollision boolean
---@field SecondarySpawnInterval boolean
---@field SecondaryParticles boolean
---@field DeathParticles boolean
---@field ParentVelocity boolean
---@field WindAffected boolean
---@field ParentVelocityWeight boolean
ParticlesProviderBase = {}
