---@meta MeshRef
---@class MeshRef: Object
---@field get_MultidrawByTextureId fun(): boolean
---@field get_Initialized fun(): boolean
---@field get_Disposed fun(): boolean
---@field Dispose fun(): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field MultidrawByTextureId boolean
---@field Initialized boolean
---@field Disposed boolean
MeshRef = {}
