---@meta IShader
---@class IShader
---@field get_Type fun(): EnumShaderany
---@field get_PrefixCode fun(): string
---@field set_PrefixCode fun(value: string): nil
---@field get_Code fun(): string
---@field set_Code fun(value: string): nil
---@field Type EnumShaderany
---@field PrefixCode EnumShaderany
---@field Code EnumShaderany
IShader = {}
