---@meta IParticlePool
---@class IParticlePool
---@field get_Model fun(): MeshRef
---@field get_QuantityAlive fun(): number
---@field SpawnParticles fun(properties: IParticlePropertiesProvider): number
---@field ShouldRender fun(): boolean
---@field OnNewFrame fun(dt: Single, playerPos: Vec3d): nil
---@field OnNewFrameOffThread fun(dt: Single, playerPos: Vec3d): nil
---@field Dipose fun(): nil
---@field Model MeshRef
---@field QuantityAlive MeshRef
IParticlePool = {}
