---@meta IconUtil
---@class IconUtil: Object
---@field ctor fun(capi: ICoreClientAPI): IconUtil
---@field SvgIconSource fun(loc: AssetLocation): IconRendererDelegate
---@overload fun(asset: IAsset): IconRendererDelegate
---@field GenTexture fun(width: number, height: number, asset: IAsset, rgba: Double[]): LoadedTexture
---@overload fun(width: number, height: number, drawHandler: DrawDelegate): LoadedTexture
---@field DrawIcon fun(cr: Context, type: string, x: Double, y: Double, width: Double, height: Double, rgba: Double[]): nil
---@field DrawIconInt fun(cr: Context, type: string, x: number, y: number, width: Single, height: Single, rgba: Double[]): nil
---@field DrawRightMouseButton fun(cr: Context, x: number, y: number, width: Single, height: Single, rgba: Double[]): nil
---@field DrawLeftMouseButton fun(cr: Context, x: number, y: number, width: Single, height: Single, rgba: Double[]): nil
---@field Drawapple_svg fun(cr: Context, x: number, y: number, width: Single, height: Single, rgba: Double[]): nil
---@field Drawhealth_svg fun(cr: Context, x: number, y: number, width: Single, height: Single, rgba: Double[]): nil
---@field Drawoffhand_svg fun(cr: Context, x: number, y: number, width: Single, height: Single, rgba: Double[]): nil
---@field Drawmask_svg fun(cr: Context, x: number, y: number, width: Single, height: Single, rgba: Double[]): nil
---@field Drawbracers_svg fun(cr: Context, x: number, y: number, width: Single, height: Single, rgba: Double[]): nil
---@field Drawpullover_svg fun(cr: Context, x: number, y: number, width: Single, height: Single, rgba: Double[]): nil
---@field Drawhandheld_svg fun(cr: Context, x: number, y: number, width: Single, height: Single, rgba: Double[]): nil
---@field Drawdice_svg fun(cr: Context, x: number, y: number, width: Single, height: Single, rgba: Double[]): nil
---@field Drawright_svg fun(cr: Context, x: number, y: number, width: Single, height: Single, rgba: Double[]): nil
---@field Drawleft_svg fun(cr: Context, x: number, y: number, width: Single, height: Single, rgba: Double[]): nil
---@field Drawnecklace_svg fun(cr: Context, x: number, y: number, width: Single, height: Single, rgba: Double[]): nil
---@field Drawbasket_svg fun(cr: Context, x: number, y: number, width: Single, height: Single, rgba: Double[]): nil
---@field Drawbelt_svg fun(cr: Context, x: number, y: number, width: Single, height: Single, rgba: Double[]): nil
---@field Drawmedal_svg fun(cr: Context, x: number, y: number, width: Single, height: Single, rgba: Double[]): nil
---@field Drawring_svg fun(cr: Context, x: number, y: number, width: Single, height: Single, rgba: Double[]): nil
---@field Drawcape_svg fun(cr: Context, x: number, y: number, width: Single, height: Single, rgba: Double[]): nil
---@field Drawshirt_svg fun(cr: Context, x: number, y: number, width: Single, height: Single, rgba: Double[]): nil
---@field Drawboots_svg fun(cr: Context, x: number, y: number, width: Single, height: Single, rgba: Double[]): nil
---@field Drawhat_svg fun(cr: Context, x: number, y: number, width: Single, height: Single, rgba: Double[]): nil
---@field Drawgloves_svg fun(cr: Context, x: number, y: number, width: Single, height: Single, rgba: Double[]): nil
---@field Drawtrousers_svg fun(cr: Context, x: number, y: number, width: Single, height: Single, rgba: Double[]): nil
---@field DrawArrowRight fun(cr: Context, lineWidth: Double, strokeOrFill: boolean, defaultPattern: boolean): nil
---@field DrawFlame fun(cr: Context, lineWidth: Double, strokeOrFill: boolean, defaultPattern: boolean): nil
---@field DrawConnectionQuality fun(ctx: Context, x: Double, y: Double, quality: number, size: Double): nil
---@field Drawmenuicon_svg fun(cr: Context, x: Double, y: Double, width: Single, height: Single, rgba: Double[]): nil
---@field DrawMapMarker fun(cr: Context, x: number, y: number, width: Single, height: Single, rgba: Double[]): nil
---@field DrawMapPlayer fun(cr: Context, x: number, y: number, width: Single, height: Single, strokeRgba: Double[], fillRgba: Double[]): nil
---@field DrawPlus fun(ctx: Context, x: number, y: number, width: Single, height: Single, strokeRgba: Double[], lineWidth: Double): nil
---@field DrawCross fun(ctx: Context, x: Double, y: Double, lineWidth: Double, size: Double, preserverePath: boolean): nil
---@field DrawPen fun(ctx: Context, x: Double, y: Double, lineWidth: Double, size: Double): nil
---@field DrawRandomSymbol fun(ctx: Context, x: Double, y: Double, size: Double, color: Double[], lineWidth: Double, seed: number, addLines: number): nil
---@field DrawVSGear fun(cr: Context, surface: ImageSurface, x: number, y: number, width: Single, height: Single, rgba: Double[]): nil
---@field DrawWaypointPlayer fun(cr: Context, x: number, y: number, width: Single, height: Single, rgba: Double[]): nil
---@field DrawWaypointCircle fun(cr: Context, x: number, y: number, width: Single, height: Single, rgba: Double[]): nil
---@field DrawWaypointPick fun(cr: Context, x: number, y: number, width: Single, height: Single, rgba: Double[]): nil
---@field DrawWaypointLadder fun(cr: Context, x: number, y: number, width: Single, height: Single, rgba: Double[]): nil
---@field DrawWaypointHome fun(cr: Context, x: number, y: number, width: Single, height: Single, rgba: Double[]): nil
---@field DrawWaypointCave fun(cr: Context, x: number, y: number, width: Single, height: Single, rgba: Double[]): nil
---@field DrawWaypointVessel fun(cr: Context, x: number, y: number, width: Single, height: Single, rgba: Double[]): nil
---@field DrawWaypointTrader fun(cr: Context, x: number, y: number, width: Single, height: Single, rgba: Double[]): nil
---@field DrawWaypointStar2 fun(cr: Context, x: number, y: number, width: Single, height: Single, rgba: Double[]): nil
---@field DrawWaypointStar1 fun(cr: Context, x: number, y: number, width: Single, height: Single, rgba: Double[]): nil
---@field DrawWaypointSpiral fun(cr: Context, x: number, y: number, width: Single, height: Single, rgba: Double[]): nil
---@field DrawWaypointRuins fun(cr: Context, x: number, y: number, width: Single, height: Single, rgba: Double[]): nil
---@field DrawWaypointRocks fun(cr: Context, x: number, y: number, width: Single, height: Single, rgba: Double[]): nil
---@field DrawWayointBee fun(cr: Context, x: number, y: number, width: Single, height: Single, rgba: Double[]): nil
---@field Drawundo_svg fun(cr: Context, x: number, y: number, width: Single, height: Single, rgba: Double[]): nil
---@field Drawcursor_svg fun(cr: Context, x: number, y: number, width: Single, height: Single, rgba: Double[]): nil
---@field Drawrepeat_svg fun(cr: Context, x: number, y: number, width: Single, height: Single, rgba: Double[]): nil
---@field Drawselect_svg fun(cr: Context, x: number, y: number, width: Single, height: Single, rgba: Double[]): nil
---@field Drawredo_svg fun(cr: Context, x: number, y: number, width: Single, height: Single, rgba: Double[]): nil
---@field Drawduplicate_svg fun(cr: Context, x: number, y: number, width: Single, height: Single, rgba: Double[]): nil
---@field Drawairbrush_svg fun(cr: Context, x: number, y: number, width: Single, height: Single, rgba: Double[]): nil
---@field Drawbrush_svg fun(cr: Context, x: number, y: number, width: Single, height: Single, rgba: Double[]): nil
---@field Draweraser_svg fun(cr: Context, x: number, y: number, width: Single, height: Single, rgba: Double[]): nil
---@field Drawerode_svg fun(cr: Context, x: number, y: number, width: Single, height: Single, rgba: Double[]): nil
---@field Drawfloodfill_svg fun(cr: Context, x: number, y: number, width: Single, height: Single, rgba: Double[]): nil
---@field Drawgrowshrink_svg fun(cr: Context, x: number, y: number, width: Single, height: Single, rgba: Double[]): nil
---@field Drawimport_svg fun(cr: Context, x: number, y: number, width: Single, height: Single, rgba: Double[]): nil
---@field Drawline_svg fun(cr: Context, x: number, y: number, width: Single, height: Single, rgba: Double[]): nil
---@field Drawraiselower_svg fun(cr: Context, x: number, y: number, width: Single, height: Single, rgba: Double[]): nil
---@field Drawtree_svg fun(cr: Context, x: number, y: number, width: Single, height: Single, rgba: Double[]): nil
---@field Drawnone_svg fun(cr: Context, x: number, y: number, width: Single, height: Single, rgba: Double[]): nil
---@field Drawlake_svg fun(cr: Context, x: number, y: number, width: Single, height: Single, rgba: Double[]): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
IconUtil = {}
