---@meta AnimationKeyFrameElement
---@class AnimationKeyFrameElement: Object
---@field ctor fun(): AnimationKeyFrameElement
---@field get_AnySet fun(): boolean
---@field get_PositionSet fun(): boolean
---@field get_StretchSet fun(): boolean
---@field get_RotationSet fun(): boolean
---@field get_OriginSet fun(): boolean
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field AnySet boolean
---@field PositionSet boolean
---@field StretchSet boolean
---@field RotationSet boolean
---@field OriginSet boolean
---@field OffsetX boolean
---@field OffsetY boolean
---@field OffsetZ boolean
---@field StretchX boolean
---@field StretchY boolean
---@field StretchZ boolean
---@field RotationX boolean
---@field RotationY boolean
---@field RotationZ boolean
---@field OriginX boolean
---@field OriginY boolean
---@field OriginZ boolean
---@field RotShortestDistanceX boolean
---@field RotShortestDistanceY boolean
---@field RotShortestDistanceZ boolean
---@field ForElement boolean
AnimationKeyFrameElement = {}
