---@meta ServerCtrlBackendInterface
---@class ServerCtrlBackendInterface: Object
---@field ctor fun(): ServerCtrlBackendInterface
---@field Start fun(onComplete: OnSrvActionComplete`1): nil
---@field Stop fun(onComplete: OnSrvActionComplete`1): nil
---@field ForceStop fun(onComplete: OnSrvActionComplete`1): nil
---@field DeleteSaves fun(onComplete: OnSrvActionComplete`1): nil
---@field DeleteAll fun(onComplete: OnSrvActionComplete`1): nil
---@field GetLog fun(onComplete: OnSrvActionComplete`1): nil
---@field GetGameVersions fun(onComplete: OnActionComplete`1): nil
---@field GetVSHostingUnsupportedGameVersions fun(onComplete: OnActionComplete`1): nil
---@field RequestDownload fun(onComplete: OnSrvActionComplete`1): nil
---@field GetStatus fun(onComplete: OnSrvActionComplete`1): nil
---@field GetConfig fun(onComplete: OnSrvActionComplete`1): nil
---@field SetConfig fun(onComplete: OnSrvActionComplete`1, serverconfig: string, worldconfig: string): nil
---@field SelectRegion fun(region: string, onComplete: OnSrvActionComplete`1): nil
---@field SelectVersion fun(version: string, onComplete: OnSrvActionComplete`1): nil
---@field DeleteMod fun(mod: string, onComplete: OnSrvActionComplete`1): nil
---@field DeleteAllMods fun(onComplete: OnSrvActionComplete`1): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
ServerCtrlBackendInterface = {}
