---@meta ChatCommandApi
---@class ChatCommandApi: Object
---@field ctor fun(api: ICoreAPI): ChatCommandApi
---@field get_CommandPrefix fun(): string
---@field get_Parsers fun(): CommandArgumentParsers
---@field get_Count fun(): number
---@field GetEnumerator fun(): IEnumerator`1
---@field get_Item fun(name: string): IChatCommand
---@field Get fun(name: string): IChatCommand
---@field Create fun(): IChatCommand
---@overload fun(commandName: string): IChatCommand
---@field GetOrCreate fun(commandName: string): IChatCommand
---@field ListAll fun(): any[]
---@field AllSubcommands fun(): table<any, any>
---@field Execute fun(commandName: string, args: TextCommandCallingArgs, onCommandComplete: any`1): nil
---@field ExecuteUnparsed fun(message: string, args: TextCommandCallingArgs, onCommandComplete: any`1): nil
---@field Execute fun(commandName: string, player: IServerPlayer, groupId: number, args: string, onCommandComplete: any`1): nil
---@overload fun(commandName: string, player: IClientPlayer, groupId: number, args: string, onCommandComplete: any`1): nil
---@field LevenshteinDistance fun(source1: string, source2: string): number
---@field RegisterCommand fun(command: string, descriptionMsg: string, syntaxMsg: string, handler: ServerChatCommandDelegate, requiredPrivilege: string): boolean
---@overload fun(command: string, descriptionMsg: string, syntaxMsg: string, handler: ClientChatCommandDelegate): boolean
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field CommandPrefix string
---@field Parsers string
---@field Count string
---@field Item string
---@field ClientCommandPrefix string
---@field ServerCommandPrefix string
ChatCommandApi = {}
