---@meta Packet_LandClaimsSerializer
---@class Packet_LandClaimsSerializer: Object
---@field ctor fun(): Packet_LandClaimsSerializer
---@field DeserializeLengthDelimitedNew fun(stream: CitoMemoryStream): Packet_LandClaims
---@field DeserializeBuffer fun(buffer: number[], length: number, instance: Packet_LandClaims): Packet_LandClaims
---@field Deserialize fun(stream: CitoMemoryStream, instance: Packet_LandClaims): Packet_LandClaims
---@field DeserializeLengthDelimited fun(stream: CitoMemoryStream, instance: Packet_LandClaims): Packet_LandClaims
---@field Serialize fun(stream: CitoStream, instance: Packet_LandClaims): nil
---@field SerializeToBytes fun(instance: Packet_LandClaims): number[]
---@field SerializeLengthDelimited fun(stream: CitoStream, instance: Packet_LandClaims): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_LandClaimsSerializer = {}
