---@meta Packet_RuntimeSettingSerializer
---@class Packet_RuntimeSettingSerializer: Object
---@field ctor fun(): Packet_RuntimeSettingSerializer
---@field DeserializeLengthDelimitedNew fun(stream: CitoMemoryStream): Packet_RuntimeSetting
---@field DeserializeBuffer fun(buffer: number[], length: number, instance: Packet_RuntimeSetting): Packet_RuntimeSetting
---@field Deserialize fun(stream: CitoMemoryStream, instance: Packet_RuntimeSetting): Packet_RuntimeSetting
---@field DeserializeLengthDelimited fun(stream: CitoMemoryStream, instance: Packet_RuntimeSetting): Packet_RuntimeSetting
---@field Serialize fun(stream: CitoStream, instance: Packet_RuntimeSetting): nil
---@field SerializeToBytes fun(instance: Packet_RuntimeSetting): number[]
---@field SerializeLengthDelimited fun(stream: CitoStream, instance: Packet_RuntimeSetting): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_RuntimeSettingSerializer = {}
