---@meta CitoMemoryStream
---@class CitoMemoryStream: CitoStream
---@field ctor fun(): CitoMemoryStream
---@overload fun(reusableBuffer: BoxedArray): CitoMemoryStream
---@overload fun(buffer: number[], length: number): CitoMemoryStream
---@field Position fun(): number
---@field ToArray fun(): number[]
---@field GetBuffer fun(): number[]
---@field Read fun(buffer: number[], offset: number, count: number): number
---@field CanSeek fun(): boolean
---@field Seek fun(length: number, seekOrigin: CitoSeekOrigin): nil
---@field Write fun(buffer: number[], offset: number, count: number): nil
---@field Seek_ fun(p: number, seekOrigin: CitoSeekOrigin): nil
---@field ReadByte fun(): number
---@field WriteByte fun(p: number): nil
---@field WriteSmallInt fun(v: number): nil
---@field WriteKey fun(k: number, wiretype: number): nil
---@field NetworkTest fun(Logger: ILogger): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
CitoMemoryStream = {}
