---@meta Packet_InvOpenCloseSerializer
---@class Packet_InvOpenCloseSerializer: Object
---@field ctor fun(): Packet_InvOpenCloseSerializer
---@field DeserializeLengthDelimitedNew fun(stream: CitoMemoryStream): Packet_InvOpenClose
---@field DeserializeBuffer fun(buffer: number[], length: number, instance: Packet_InvOpenClose): Packet_InvOpenClose
---@field Deserialize fun(stream: CitoMemoryStream, instance: Packet_InvOpenClose): Packet_InvOpenClose
---@field DeserializeLengthDelimited fun(stream: CitoMemoryStream, instance: Packet_InvOpenClose): Packet_InvOpenClose
---@field Serialize fun(stream: CitoStream, instance: Packet_InvOpenClose): nil
---@field SerializeToBytes fun(instance: Packet_InvOpenClose): number[]
---@field SerializeLengthDelimited fun(stream: CitoStream, instance: Packet_InvOpenClose): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_InvOpenCloseSerializer = {}
