---@meta NoAnimator
---@class NoAnimator: Object
---@field ctor fun(): NoAnimator
---@field get_Matrices4x3 fun(): Single[]
---@field get_ActiveAnimationCount fun(): number
---@field get_CalculateMatrices fun(): boolean
---@field set_CalculateMatrices fun(value: boolean): nil
---@field get_RunningAnimations fun(): RunningAnimation[]
---@field DumpCurrentState fun(): string
---@field GetAnimationState fun(code: string): RunningAnimation
---@field GetAttachmentPointPose fun(code: string): AttachmentPointAndPose
---@field GetPosebyName fun(name: string, stringComparison: stringComparison): ElementPose
---@field OnFrame fun(activeAnimationsByAnimCode: table<any, any>, dt: Single): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field Matrices4x3 Single[]
---@field ActiveAnimationCount Single[]
---@field CalculateMatrices Single[]
---@field RunningAnimations Single[]
NoAnimator = {}
