---@meta DoubleArrayAttribute
---@class DoubleArrayAttribute: ArrayAttribute`1
---@field ctor fun(): DoubleArrayAttribute
---@overload fun(value: Double[]): DoubleArrayAttribute
---@field ToBytes fun(stream: BinaryWriter): nil
---@field FromBytes fun(stream: BinaryReader): nil
---@field GetAttributeId fun(): number
---@field ToJsonToken fun(): string
---@field Clone fun(): IAttribute
---@field Equals fun(worldForResolve: IWorldAccessor, attr: IAttribute): boolean
---@field GetValue fun(): table
---@field ToString fun(): string
---@field GetHashCode fun(): number
---@field GetType fun(): any
---@field Equals fun(obj: table): boolean
DoubleArrayAttribute = {}
