---@meta IVec3
---@class IVec3
---@field get_XAsInt fun(): number
---@field get_YAsInt fun(): number
---@field get_ZAsInt fun(): number
---@field get_XAsDouble fun(): Double
---@field get_YAsDouble fun(): Double
---@field get_ZAsDouble fun(): Double
---@field get_XAsFloat fun(): Single
---@field get_YAsFloat fun(): Single
---@field get_ZAsFloat fun(): Single
---@field get_AsVec3i fun(): Vec3i
---@field XAsInt number
---@field YAsInt number
---@field ZAsInt number
---@field XAsDouble number
---@field YAsDouble number
---@field ZAsDouble number
---@field XAsFloat number
---@field YAsFloat number
---@field ZAsFloat number
---@field AsVec3i number
IVec3 = {}
