---@meta TcpNetConnection
---@class TcpNetConnection: NetConnection
---@field ctor fun(): TcpNetConnection
---@field RemoteEndPoint fun(): IPEndPointCi
---@field Send fun(data: number[], compressedFlag: boolean): EnumSendResult
---@field HiPerformanceSend fun(box: BoxedPacket, Logger: ILogger, compressionAllowed: boolean): EnumSendResult
---@field EqualsConnection fun(connection: NetConnection): boolean
---@field Close fun(): nil
---@field Shutdown fun(): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
TcpNetConnection = {}
