---@meta LinkTextComponent
---@class LinkTextComponent: RichTextComponent
---@field ctor fun(api: ICoreClientAPI, displayText: string, font: CairoFont, onLinkClicked: any`1): LinkTextComponent
---@field get_Clickable fun(): boolean
---@field set_Clickable fun(value: boolean): nil
---@field CalcBounds fun(flowPath: TextFlowPath[], currentLineHeight: Double, offsetX: Double, lineY: Double, nextOffsetX: Double&): EnumCalcBoundsResult
---@field ComposeElements fun(ctxStatic: Context, surfaceStatic: ImageSurface): nil
---@field RenderInteractiveElements fun(deltaTime: Single, renderX: Double, renderY: Double, renderZ: Double): nil
---@field UseMouseOverCursor fun(richtextBounds: ElementBounds): boolean
---@field OnMouseDown fun(args: MouseEvent): nil
---@field OnMouseUp fun(args: MouseEvent): nil
---@field SetHref fun(href: string): LinkTextComponent
---@field Trigger fun(): nil
---@field HandleLink fun(): nil
---@field Dispose fun(): nil
---@field get_MouseOverCursor fun(): string
---@field get_BoundsPerLine fun(): LineRectangled[]
---@field get_UnscaledMarginTop fun(): Double
---@field set_UnscaledMarginTop fun(value: Double): nil
---@field get_PaddingRight fun(): Double
---@field set_PaddingRight fun(value: Double): nil
---@field get_PaddingLeft fun(): Double
---@field set_PaddingLeft fun(value: Double): nil
---@field get_Float fun(): EnumFloat
---@field set_Float fun(value: EnumFloat): nil
---@field get_RenderColor fun(): Vec4f
---@field set_RenderColor fun(value: Vec4f): nil
---@field get_VerticalAlign fun(): EnumVerticalAlign
---@field set_VerticalAlign fun(value: EnumVerticalAlign): nil
---@field OnMouseMove fun(args: MouseEvent): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field Clickable boolean
---@field MouseOverCursor boolean
---@field BoundsPerLine boolean
---@field UnscaledMarginTop boolean
---@field PaddingRight boolean
---@field PaddingLeft boolean
---@field Float boolean
---@field RenderColor boolean
---@field VerticalAlign boolean
---@field Href boolean
---@field DisplayText boolean
---@field Font boolean
---@field Lines boolean
LinkTextComponent = {}
