---@meta Packet_InventoryContentsSerializer
---@class Packet_InventoryContentsSerializer: Object
---@field ctor fun(): Packet_InventoryContentsSerializer
---@field DeserializeLengthDelimitedNew fun(stream: CitoMemoryStream): Packet_InventoryContents
---@field DeserializeBuffer fun(buffer: number[], length: number, instance: Packet_InventoryContents): Packet_InventoryContents
---@field Deserialize fun(stream: CitoMemoryStream, instance: Packet_InventoryContents): Packet_InventoryContents
---@field DeserializeLengthDelimited fun(stream: CitoMemoryStream, instance: Packet_InventoryContents): Packet_InventoryContents
---@field Serialize fun(stream: CitoStream, instance: Packet_InventoryContents): nil
---@field SerializeToBytes fun(instance: Packet_InventoryContents): number[]
---@field SerializeLengthDelimited fun(stream: CitoStream, instance: Packet_InventoryContents): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_InventoryContentsSerializer = {}
