---@meta Packet_Behavior
---@class Packet_Behavior: Object
---@field ctor fun(): Packet_Behavior
---@field SetCode fun(value: string): nil
---@field SetAttributes fun(value: string): nil
---@field SetClientSideOptional fun(value: number): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_Behavior = {}
