---@meta IBulkBlockAccessor
---@class IBulkBlockAccessor
---@field add_BeforeCommit fun(value: any`1): nil
---@field remove_BeforeCommit fun(value: any`1): nil
---@field get_StagedBlocks fun(): table<any, any>
---@field get_ReadFromStagedByDefault fun(): boolean
---@field set_ReadFromStagedByDefault fun(value: boolean): nil
---@field GetStagedBlockId fun(posX: number, posY: number, posZ: number): number
---@overload fun(pos: BlockPos): number
---@field SetChunks fun(chunkCoord: Vec2i, chunksCol: IWorldChunk[]): nil
---@field SetDecorsBulk fun(chunkIndex: Int64, newDecors: table<any, any>): nil
---@field PostCommitCleanup fun(updatedBlocks: any[]): nil
---@field StagedBlocks table<any, any>
---@field ReadFromStagedByDefault table<any, any>
---@field BeforeCommit table<any, any>
IBulkBlockAccessor = {}
