---@meta ClientProgramArgs
---@class ClientProgramArgs: Object
---@field ctor fun(): ClientProgramArgs
---@field get_PrintVersion fun(): boolean
---@field set_PrintVersion fun(value: boolean): nil
---@field get_PrintHelp fun(): boolean
---@field set_PrintHelp fun(value: boolean): nil
---@field get_TraceLog fun(): boolean
---@field set_TraceLog fun(value: boolean): nil
---@field get_OpenWorldName fun(): string
---@field set_OpenWorldName fun(value: string): nil
---@field get_ConnectServerAddress fun(): string
---@field set_ConnectServerAddress fun(value: string): nil
---@field get_InstallModId fun(): string
---@field set_InstallModId fun(value: string): nil
---@field get_Password fun(): string
---@field set_Password fun(value: string): nil
---@field get_CreateRndWorld fun(): boolean
---@field set_CreateRndWorld fun(value: boolean): nil
---@field get_PlayStyle fun(): string
---@field set_PlayStyle fun(value: string): nil
---@field get_DataPath fun(): string
---@field set_DataPath fun(value: string): nil
---@field get_LogPath fun(): string
---@field set_LogPath fun(value: string): nil
---@field get_AddOrigin fun(): any[]
---@field set_AddOrigin fun(value: any[]): nil
---@field get_AddModPath fun(): any[]
---@field set_AddModPath fun(value: any[]): nil
---@field GetUsage fun(parser: ParserResult`1): string
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field PrintVersion boolean
---@field PrintHelp boolean
---@field TraceLog boolean
---@field OpenWorldName boolean
---@field ConnectServerAddress boolean
---@field InstallModId boolean
---@field Password boolean
---@field CreateRndWorld boolean
---@field PlayStyle boolean
---@field DataPath boolean
---@field LogPath boolean
---@field AddOrigin boolean
---@field AddModPath boolean
ClientProgramArgs = {}
