---@meta GuiComposerHelpers
---@class GuiComposerHelpers: Object
---@field GetColorListPicker fun(composer: GuiComposer, key: string): GuiElementColorListPicker
---@field ColorListPickerSetValue fun(composer: GuiComposer, key: string, selectedIndex: number): nil
---@field AddColorListPicker fun(composer: GuiComposer, colors: number[], onToggle: any`1, startBounds: ElementBounds, maxLineWidth: number, key: string): GuiComposer
---@field AddCompactVerticalScrollbar fun(composer: GuiComposer, onNewScrollbarValue: any`1, bounds: ElementBounds, key: string): GuiComposer
---@field GetCompactScrollbar fun(composer: GuiComposer, key: string): GuiElementCompactScrollbar
---@field AddMultiSelectDropDown fun(composer: GuiComposer, values: string[], names: string[], selectedIndex: number, onSelectionChanged: SelectionChangedDelegate, bounds: ElementBounds, key: string): GuiComposer
---@field AddDropDown fun(composer: GuiComposer, values: string[], names: string[], selectedIndex: number, onSelectionChanged: SelectionChangedDelegate, bounds: ElementBounds, key: string): GuiComposer
---@overload fun(composer: GuiComposer, values: string[], names: string[], selectedIndex: number, onSelectionChanged: SelectionChangedDelegate, bounds: ElementBounds, font: CairoFont, key: string): GuiComposer
---@field GetDropDown fun(composer: GuiComposer, key: string): GuiElementDropDown
---@field AddElementListPicker fun(composer: GuiComposer, pickertype: any, elems: T[], onToggle: any`1, startBounds: ElementBounds, maxLineWidth: number, key: string): GuiComposer
---@field AddHorizontalTabs fun(composer: GuiComposer, tabs: GuiTab[], bounds: ElementBounds, onTabClicked: any`1, font: CairoFont, selectedFont: CairoFont, key: string): GuiComposer
---@field GetHorizontalTabs fun(composer: GuiComposer, key: string): GuiElementHorizontalTabs
---@field GetIconListPicker fun(composer: GuiComposer, key: string): GuiElementIconListPicker
---@field IconListPickerSetValue fun(composer: GuiComposer, key: string, selectedIndex: number): nil
---@field AddIconListPicker fun(composer: GuiComposer, icons: string[], onToggle: any`1, startBounds: ElementBounds, maxLineWidth: number, key: string): GuiComposer
---@field AddVerticalScrollbar fun(composer: GuiComposer, onNewScrollbarValue: any`1, bounds: ElementBounds, key: string): GuiComposer
---@field GetScrollbar fun(composer: GuiComposer, key: string): GuiElementScrollbar
---@field AddSlider fun(composer: GuiComposer, onNewSliderValue: ActionConsumable`1, bounds: ElementBounds, key: string): GuiComposer
---@field GetSlider fun(composer: GuiComposer, key: string): GuiElementSlider
---@field AddSwitch fun(composer: GuiComposer, onToggle: any`1, bounds: ElementBounds, key: string, size: Double, padding: Double): GuiComposer
---@field GetSwitch fun(composer: GuiComposer, key: string): GuiElementSwitch
---@field AddButton fun(composer: GuiComposer, text: string, onClick: ActionConsumable, bounds: ElementBounds, buttonFont: CairoFont, style: EnumButtonStyle, orientation: EnumTextOrientation, key: string): GuiComposer
---@overload fun(composer: GuiComposer, text: string, onClick: ActionConsumable, bounds: ElementBounds, style: EnumButtonStyle, orientation: EnumTextOrientation, key: string): GuiComposer
---@field AddSmallButton fun(composer: GuiComposer, text: string, onClick: ActionConsumable, bounds: ElementBounds, style: EnumButtonStyle, orientation: EnumTextOrientation, key: string): GuiComposer
---@overload fun(composer: GuiComposer, text: string, onClick: ActionConsumable, bounds: ElementBounds, buttonFont: CairoFont, style: EnumButtonStyle, key: string): GuiComposer
---@overload fun(composer: GuiComposer, text: string, onClick: ActionConsumable, bounds: ElementBounds, style: EnumButtonStyle, key: string): GuiComposer
---@overload fun(composer: GuiComposer, text: string, onClick: ActionConsumable, bounds: ElementBounds, style: EnumButtonStyle, key: string): GuiComposer
---@field GetButton fun(composer: GuiComposer, key: string): GuiElementTextButton
---@field GetToggleButton fun(composer: GuiComposer, key: string): GuiElementToggleButton
---@field AddToggleButton fun(composer: GuiComposer, text: string, font: CairoFont, onToggle: any`1, bounds: ElementBounds, key: string): GuiComposer
---@field AddIconButton fun(composer: GuiComposer, icon: string, onToggle: any`1, bounds: ElementBounds, key: string): GuiComposer
---@field ToggleButtonsSetValue fun(composer: GuiComposer, key: string, selectedIndex: number): nil
---@field AddIconToggleButtons fun(composer: GuiComposer, icons: string[], font: CairoFont, onToggle: any`1, bounds: ElementBounds[], key: string): GuiComposer
---@field AddTextToggleButtons fun(composer: GuiComposer, texts: string[], font: CairoFont, onToggle: any`1, bounds: ElementBounds[], key: string): GuiComposer
---@field AddVerticalToggleTabs fun(composer: GuiComposer, tabs: GuiTab[], bounds: ElementBounds, onTabClicked: Action`2, key: string): GuiComposer
---@field AddVerticalTabs fun(composer: GuiComposer, tabs: GuiTab[], bounds: ElementBounds, onTabClicked: Action`2, key: string): GuiComposer
---@field GetVerticalTab fun(composer: GuiComposer, key: string): GuiElementVerticalTabs
---@field AddCellList fun(composer: GuiComposer, bounds: ElementBounds, cellCreator: OnRequireCell`1, cells: any[], key: string): GuiComposer
---@field GetCellList fun(composer: GuiComposer, key: string): GuiElementCellany[]
---@field AddChatInput fun(composer: GuiComposer, bounds: ElementBounds, onTextChanged: any`1, key: string): GuiComposer
---@field GetChatInput fun(composer: GuiComposer, key: string): GuiElementChatInput
---@field AddConfigList fun(composer: GuiComposer, items: any[], onItemClick: ConfigItemClickDelegate, font: CairoFont, bounds: ElementBounds, key: string): GuiComposer
---@field GetConfigList fun(composer: GuiComposer, key: string): GuiElementConfigList
---@field AddContainer fun(composer: GuiComposer, bounds: ElementBounds, key: string): GuiComposer
---@field GetContainer fun(composer: GuiComposer, key: string): GuiElementContainer
---@field AddDialogTitleBar fun(composer: GuiComposer, text: string, onClose: Action, font: CairoFont, bounds: ElementBounds): GuiComposer
---@field AddDialogTitleBarWithBg fun(composer: GuiComposer, text: string, onClose: Action, font: CairoFont, bounds: ElementBounds): GuiComposer
---@field GetTitleBar fun(composer: GuiComposer, key: string): GuiElementDialogTitleBar
---@field AddNumberInput fun(composer: GuiComposer, bounds: ElementBounds, onTextChanged: any`1, font: CairoFont, key: string): GuiComposer
---@field GetNumberInput fun(composer: GuiComposer, key: string): GuiElementNumberInput
---@field AddStatbar fun(composer: GuiComposer, bounds: ElementBounds, color: Double[], hideable: boolean, key: string): GuiComposer
---@overload fun(composer: GuiComposer, bounds: ElementBounds, color: Double[], key: string): GuiComposer
---@field AddInvStatbar fun(composer: GuiComposer, bounds: ElementBounds, color: Double[], key: string): GuiComposer
---@field GetStatbar fun(composer: GuiComposer, key: string): GuiElementStatbar
---@field AddTextArea fun(composer: GuiComposer, bounds: ElementBounds, onTextChanged: any`1, font: CairoFont, key: string): GuiComposer
---@field GetTextArea fun(composer: GuiComposer, key: string): GuiElementTextArea
---@field AddTextInput fun(composer: GuiComposer, bounds: ElementBounds, onTextChanged: any`1, font: CairoFont, key: string): GuiComposer
---@field GetTextInput fun(composer: GuiComposer, key: string): GuiElementTextInput
---@field AddItemSlotGrid fun(composer: GuiComposer, inventory: IInventory, sendPacket: any`1, columns: number, bounds: ElementBounds, key: string): GuiComposer
---@overload fun(composer: GuiComposer, inventory: IInventory, sendPacket: any`1, columns: number, selectiveSlots: number[], bounds: ElementBounds, key: string): GuiComposer
---@field GetSlotGrid fun(composer: GuiComposer, key: string): GuiElementItemSlotGrid
---@field AddItemSlotGridExcl fun(composer: GuiComposer, inventory: IInventory, sendPacket: any`1, columns: number, excludingSlots: number[], bounds: ElementBounds, key: string): GuiComposer
---@field GetSlotGridExcl fun(composer: GuiComposer, key: string): GuiElementItemSlotGridExcl
---@field AddPassiveItemSlot fun(composer: GuiComposer, bounds: ElementBounds, inventory: IInventory, slot: ItemSlot, drawBackground: boolean): GuiComposer
---@field AddSkillItemGrid fun(composer: GuiComposer, skillItems: any[], columns: number, rows: number, onSlotClick: any`1, bounds: ElementBounds, key: string): GuiComposer
---@field GetSkillItemGrid fun(composer: GuiComposer, key: string): GuiElementSkillItemGrid
---@field AddEmbossedText fun(composer: GuiComposer, text: string, font: CairoFont, bounds: ElementBounds, key: string): GuiComposer
---@field GetEmbossedText fun(composer: GuiComposer, key: string): GuiElementEmbossedText
---@field AddHoverText fun(composer: GuiComposer, text: string, font: CairoFont, width: number, bounds: ElementBounds, key: string): GuiComposer
---@field AddAutoSizeHoverText fun(composer: GuiComposer, text: string, font: CairoFont, width: number, bounds: ElementBounds, key: string): GuiComposer
---@field AddTranspHoverText fun(composer: GuiComposer, text: string, font: CairoFont, width: number, bounds: ElementBounds, key: string): GuiComposer
---@field AddHoverText fun(composer: GuiComposer, text: string, font: CairoFont, width: number, bounds: ElementBounds, background: TextBackground, key: string): GuiComposer
---@field GetHoverText fun(composer: GuiComposer, key: string): GuiElementHoverText
---@field AddRichtext fun(composer: GuiComposer, vtmlCode: string, baseFont: CairoFont, bounds: ElementBounds, key: string): GuiComposer
---@overload fun(composer: GuiComposer, vtmlCode: string, baseFont: CairoFont, bounds: ElementBounds, didClickLink: any`1, key: string): GuiComposer
---@overload fun(composer: GuiComposer, components: RichTextComponentBase[], bounds: ElementBounds, key: string): GuiComposer
---@field GetRichtext fun(composer: GuiComposer, key: string): GuiElementRichtext
---@field AddCustomRender fun(composer: GuiComposer, bounds: ElementBounds, onRender: RenderDelegateWithBounds): GuiComposer
---@field GetCustomRender fun(composer: GuiComposer, key: string): GuiElementCustomRender
---@field AddStaticCustomDraw fun(composer: GuiComposer, bounds: ElementBounds, onDraw: DrawDelegateWithBounds): GuiComposer
---@field AddDynamicCustomDraw fun(composer: GuiComposer, bounds: ElementBounds, onDraw: DrawDelegateWithBounds, key: string): GuiComposer
---@field GetCustomDraw fun(composer: GuiComposer, key: string): GuiElementCustomDraw
---@field AddShadedDialogBG fun(composer: GuiComposer, bounds: ElementBounds, withTitleBar: boolean, strokeWidth: Double, alpha: Single): GuiComposer
---@field AddDialogBG fun(composer: GuiComposer, bounds: ElementBounds, withTitleBar: boolean, alpha: Single): GuiComposer
---@field AddStaticText fun(composer: GuiComposer, text: string, font: CairoFont, bounds: ElementBounds, key: string): GuiComposer
---@overload fun(composer: GuiComposer, text: string, font: CairoFont, orientation: EnumTextOrientation, bounds: ElementBounds, key: string): GuiComposer
---@field AddStaticTextAutoBoxSize fun(composer: GuiComposer, text: string, font: CairoFont, orientation: EnumTextOrientation, bounds: ElementBounds, key: string): GuiComposer
---@field AddStaticTextAutoFontSize fun(composer: GuiComposer, text: string, font: CairoFont, bounds: ElementBounds, key: string): GuiComposer
---@field GetStaticText fun(composer: GuiComposer, key: string): GuiElementStaticText
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
GuiComposerHelpers = {}
