---@meta GuiCompositeMainMenuLeft
---@class GuiCompositeMainMenuLeft: GuiComposite
---@field ctor fun(screenManager: ScreenManager): GuiCompositeMainMenuLeft
---@field get_Width fun(): Double
---@field Compose fun(): nil
---@field UnixTimeNow fun(): Int64
---@field updateButtonActiveFlag fun(key: string): nil
---@field OnSingleplayer fun(): boolean
---@field OnMultiplayer fun(): boolean
---@field OnQuit fun(): boolean
---@field OnMouseDown fun(e: MouseEvent): nil
---@field OnMouseUp fun(e: MouseEvent): nil
---@field RenderBg fun(dt: Single, mainMenuVisible: boolean): nil
---@field Dispose fun(): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field Width Double
GuiCompositeMainMenuLeft = {}
