---@meta TrackStarterDelegate
---@class TrackStarterDelegate: MulticastDelegate
---@field ctor fun(object: table, method: IntPtr): TrackStarterDelegate
---@field Invoke fun(soundLocation: AssetLocation, priority: Single, soundType: EnumSoundany, onLoaded: any`1): MusicTrack
---@field BeginInvoke fun(soundLocation: AssetLocation, priority: Single, soundType: EnumSoundany, onLoaded: any`1, callback: AsyncCallback, object: table): IAsyncResult
---@field EndInvoke fun(result: IAsyncResult): MusicTrack
---@field GetObjectData fun(info: SerializationInfo, context: StreamingContext): nil
---@field Equals fun(obj: table): boolean
---@field GetInvocationList fun(): Delegate[]
---@field GetHashCode fun(): number
---@field get_Target fun(): table
---@field Clone fun(): table
---@field DynamicInvoke fun(args: table[]): table
---@field get_Method fun(): MethodInfo
---@field GetType fun(): any
---@field ToString fun(): string
---@field Target table
---@field Method table
TrackStarterDelegate = {}
