---@meta ArrayExtensions
---@class ArrayExtensions: Object
---@field Nearest fun(array: T[], getDistance: fun(outResult: any): any): T
---@field InRange fun(array: T[], getDistance: fun(outResult: any): any, range: Double): any[]
---@field IndexOf fun(array: T[], predicate: fun(outResult: any): any): number
---@overload fun(array: T[], value: T): number
---@field Contains fun(array: T[], value: T): boolean
---@field Remove fun(array: T[], value: T): T[]
---@field RemoveEntry fun(array: T[], index: number): T[]
---@field Append fun(array: T[], value: T): T[]
---@field InsertAt fun(array: T[], value: T, index: number): T[]
---@field Append fun(array: T[], value: T[]): T[]
---@overload fun(array: T[], values: any[]): T[]
---@field Fill fun(originalArray: T[], with: T): T[]
---@overload fun(originalArray: T[], fillCallback: fillCallback`1): T[]
---@field Shuffle fun(array: T[], rand: Random): T[]
---@overload fun(array: T[], rand: LCGRandom): T[]
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
ArrayExtensions = {}
