---@meta ClientSettings
---@class ClientSettings: SettingsBase
---@field get_FileName fun(): string
---@field get_BkpFileName fun(): string
---@field get_TempFileName fun(): string
---@field get_DialogPositions fun(): table<any, any>
---@field set_DialogPositions fun(value: table<any, any>): nil
---@field SetDialogPosition fun(key: string, pos: Vec2i): nil
---@field GetDialogPosition fun(key: string): Vec2i
---@field get_KeyMapping fun(): table<any, any>
---@field set_KeyMapping fun(value: table<any, any>): nil
---@field SetKeyMapping fun(key: string, value: KeyCombination): nil
---@field GetKeyMapping fun(key: string): KeyCombination
---@field AddKeyCombinationUpdatedWatcher fun(handler: table<any, any>): nil
---@field ClearWatchers fun(): nil
---@field get_SelectedBlockOutline fun(): boolean
---@field set_SelectedBlockOutline fun(value: boolean): nil
---@field get_ShowPasswordProtectedServers fun(): boolean
---@field set_ShowPasswordProtectedServers fun(value: boolean): nil
---@field get_TestGlExtensions fun(): boolean
---@field set_TestGlExtensions fun(value: boolean): nil
---@field get_ScreenshotExifDataMode fun(): number
---@field set_ScreenshotExifDataMode fun(value: number): nil
---@field get_ShowOpenForAllServers fun(): boolean
---@field set_ShowOpenForAllServers fun(value: boolean): nil
---@field get_ShowWhitelistedServers fun(): boolean
---@field set_ShowWhitelistedServers fun(value: boolean): nil
---@field get_ShowModdedServers fun(): boolean
---@field set_ShowModdedServers fun(value: boolean): nil
---@field get_ShowMoreGfxOptions fun(): boolean
---@field set_ShowMoreGfxOptions fun(value: boolean): nil
---@field get_Occlusionculling fun(): boolean
---@field set_Occlusionculling fun(value: boolean): nil
---@field get_GlDebugMode fun(): boolean
---@field set_GlDebugMode fun(value: boolean): nil
---@field get_GlErrorChecking fun(): boolean
---@field set_GlErrorChecking fun(value: boolean): nil
---@field get_MultipleInstances fun(): boolean
---@field set_MultipleInstances fun(value: boolean): nil
---@field get_StartupErrorDialog fun(): boolean
---@field set_StartupErrorDialog fun(value: boolean): nil
---@field get_HighQualityAnimations fun(): boolean
---@field set_HighQualityAnimations fun(value: boolean): nil
---@field get_ToggleSprint fun(): boolean
---@field set_ToggleSprint fun(value: boolean): nil
---@field get_SeparateCtrl fun(): boolean
---@field set_SeparateCtrl fun(value: boolean): nil
---@field get_WebRequestTimeout fun(): number
---@field set_WebRequestTimeout fun(value: number): nil
---@field get_OptimizeRamMode fun(): number
---@field set_OptimizeRamMode fun(value: number): nil
---@field get_LeftDialogMargin fun(): number
---@field set_LeftDialogMargin fun(value: number): nil
---@field get_RightDialogMargin fun(): number
---@field set_RightDialogMargin fun(value: number): nil
---@field get_ShowSurvivalHelpDialog fun(): boolean
---@field set_ShowSurvivalHelpDialog fun(value: boolean): nil
---@field get_ShowCreativeHelpDialog fun(): boolean
---@field set_ShowCreativeHelpDialog fun(value: boolean): nil
---@field get_ViewBobbing fun(): boolean
---@field set_ViewBobbing fun(value: boolean): nil
---@field get_ChatDialogVisible fun(): boolean
---@field set_ChatDialogVisible fun(value: boolean): nil
---@field get_UserEmail fun(): string
---@field set_UserEmail fun(value: string): nil
---@field get_MpToken fun(): string
---@field set_MpToken fun(value: string): nil
---@field get_HasGameServer fun(): boolean
---@field set_HasGameServer fun(value: boolean): nil
---@field get_Sessionkey fun(): string
---@field set_Sessionkey fun(value: string): nil
---@field get_SessionSignature fun(): string
---@field set_SessionSignature fun(value: string): nil
---@field get_MasterserverUrl fun(): string
---@field set_MasterserverUrl fun(value: string): nil
---@field get_ModDbUrl fun(): string
---@field set_ModDbUrl fun(value: string): nil
---@field get_PlayerUID fun(): string
---@field set_PlayerUID fun(value: string): nil
---@field get_PlayerName fun(): string
---@field set_PlayerName fun(value: string): nil
---@field get_Entitlements fun(): string
---@field set_Entitlements fun(value: string): nil
---@field get_SettingsVersion fun(): string
---@field set_SettingsVersion fun(value: string): nil
---@field get_GUIScale fun(): Single
---@field set_GUIScale fun(value: Single): nil
---@field get_FontSize fun(): Single
---@field set_FontSize fun(value: Single): nil
---@field get_LodBias fun(): Single
---@field set_LodBias fun(value: Single): nil
---@field get_LodBiasFar fun(): Single
---@field set_LodBiasFar fun(value: Single): nil
---@field get_SmoothShadows fun(): boolean
---@field set_SmoothShadows fun(value: boolean): nil
---@field get_SSAOQuality fun(): number
---@field set_SSAOQuality fun(value: number): nil
---@field get_FlipScreenshot fun(): boolean
---@field set_FlipScreenshot fun(value: boolean): nil
---@field get_DeveloperMode fun(): boolean
---@field set_DeveloperMode fun(value: boolean): nil
---@field get_ViewDistance fun(): number
---@field set_ViewDistance fun(value: number): nil
---@field get_FXAA fun(): boolean
---@field set_FXAA fun(value: boolean): nil
---@field get_RenderMetaBlocks fun(): boolean
---@field set_RenderMetaBlocks fun(value: boolean): nil
---@field get_ChunkVerticesUploadRateLimiter fun(): number
---@field set_ChunkVerticesUploadRateLimiter fun(value: number): nil
---@field get_SSAA fun(): Single
---@field set_SSAA fun(value: Single): nil
---@field get_MegaScreenshotSizeMul fun(): Single
---@field set_MegaScreenshotSizeMul fun(value: Single): nil
---@field get_WavingFoliage fun(): boolean
---@field set_WavingFoliage fun(value: boolean): nil
---@field get_LiquidFoamAndShinyEffect fun(): boolean
---@field set_LiquidFoamAndShinyEffect fun(value: boolean): nil
---@field get_PauseGameOnLostFocus fun(): boolean
---@field set_PauseGameOnLostFocus fun(value: boolean): nil
---@field get_Bloom fun(): boolean
---@field set_Bloom fun(value: boolean): nil
---@field get_GraphicsPresetId fun(): number
---@field set_GraphicsPresetId fun(value: number): nil
---@field get_GameWindowMode fun(): number
---@field set_GameWindowMode fun(value: number): nil
---@field get_SoundLevel fun(): number
---@field set_SoundLevel fun(value: number): nil
---@field get_EntitySoundLevel fun(): number
---@field set_EntitySoundLevel fun(value: number): nil
---@field get_AmbientSoundLevel fun(): number
---@field set_AmbientSoundLevel fun(value: number): nil
---@field get_WeatherSoundLevel fun(): number
---@field set_WeatherSoundLevel fun(value: number): nil
---@field get_MusicLevel fun(): number
---@field set_MusicLevel fun(value: number): nil
---@field get_MusicFrequency fun(): number
---@field set_MusicFrequency fun(value: number): nil
---@field get_Language fun(): string
---@field set_Language fun(value: string): nil
---@field get_DefaultFontName fun(): string
---@field set_DefaultFontName fun(value: string): nil
---@field get_DecorativeFontName fun(): string
---@field set_DecorativeFontName fun(value: string): nil
---@field get_UseServerTextures fun(): boolean
---@field set_UseServerTextures fun(value: boolean): nil
---@field get_ScreenWidth fun(): number
---@field set_ScreenWidth fun(value: number): nil
---@field get_ScreenHeight fun(): number
---@field set_ScreenHeight fun(value: number): nil
---@field get_WeirdMacOSMouseYOffset fun(): number
---@field set_WeirdMacOSMouseYOffset fun(value: number): nil
---@field get_BlockAtlasSubPixelPadding fun(): Single
---@field set_BlockAtlasSubPixelPadding fun(value: Single): nil
---@field get_ItemAtlasSubPixelPadding fun(): Single
---@field set_ItemAtlasSubPixelPadding fun(value: Single): nil
---@field get_MipMapLevel fun(): number
---@field set_MipMapLevel fun(value: number): nil
---@field get_MaxQuadParticles fun(): number
---@field set_MaxQuadParticles fun(value: number): nil
---@field get_MaxCubeParticles fun(): number
---@field set_MaxCubeParticles fun(value: number): nil
---@field get_MaxAsyncQuadParticles fun(): number
---@field set_MaxAsyncQuadParticles fun(value: number): nil
---@field get_MaxAsyncCubeParticles fun(): number
---@field set_MaxAsyncCubeParticles fun(value: number): nil
---@field get_MouseSensivity fun(): number
---@field set_MouseSensivity fun(value: number): nil
---@field get_MouseSmoothing fun(): number
---@field set_MouseSmoothing fun(value: number): nil
---@field get_VsyncMode fun(): number
---@field set_VsyncMode fun(value: number): nil
---@field get_ModelDataPoolMaxVertexSize fun(): number
---@field set_ModelDataPoolMaxVertexSize fun(value: number): nil
---@field get_ModelDataPoolMaxIndexSize fun(): number
---@field set_ModelDataPoolMaxIndexSize fun(value: number): nil
---@field get_ModelDataPoolMaxParts fun(): number
---@field set_ModelDataPoolMaxParts fun(value: number): nil
---@field get_FieldOfView fun(): number
---@field set_FieldOfView fun(value: number): nil
---@field get_MaxTextureAtlasWidth fun(): number
---@field set_MaxTextureAtlasWidth fun(value: number): nil
---@field get_MaxTextureAtlasHeight fun(): number
---@field set_MaxTextureAtlasHeight fun(value: number): nil
---@field get_SkipNvidiaProfileCheck fun(): boolean
---@field set_SkipNvidiaProfileCheck fun(value: boolean): nil
---@field get_AmbientBloomLevel fun(): number
---@field set_AmbientBloomLevel fun(value: number): nil
---@field get_GodRayQuality fun(): number
---@field set_GodRayQuality fun(value: number): nil
---@field get_Minbrightness fun(): Single
---@field set_Minbrightness fun(value: Single): nil
---@field get_RecordingBufferSize fun(): number
---@field set_RecordingBufferSize fun(value: number): nil
---@field get_UseHRTFAudio fun(): boolean
---@field set_UseHRTFAudio fun(value: boolean): nil
---@field get_AllowSettingHRTFAudio fun(): boolean
---@field set_AllowSettingHRTFAudio fun(value: boolean): nil
---@field get_Force48kHzHRTFAudio fun(): boolean
---@field set_Force48kHzHRTFAudio fun(value: boolean): nil
---@field get_RenderParticles fun(): boolean
---@field set_RenderParticles fun(value: boolean): nil
---@field get_AmbientParticles fun(): boolean
---@field set_AmbientParticles fun(value: boolean): nil
---@field get_RenderClouds fun(): boolean
---@field set_RenderClouds fun(value: boolean): nil
---@field get_TransparentRenderPass fun(): boolean
---@field set_TransparentRenderPass fun(value: boolean): nil
---@field get_GammaLevel fun(): Single
---@field set_GammaLevel fun(value: Single): nil
---@field get_ExtraGammaLevel fun(): Single
---@field set_ExtraGammaLevel fun(value: Single): nil
---@field get_BrightnessLevel fun(): Single
---@field set_BrightnessLevel fun(value: Single): nil
---@field get_SepiaLevel fun(): Single
---@field set_SepiaLevel fun(value: Single): nil
---@field get_CameraShakeStrength fun(): Single
---@field set_CameraShakeStrength fun(value: Single): nil
---@field get_Wireframethickness fun(): Single
---@field set_Wireframethickness fun(value: Single): nil
---@field get_guiColorsPreset fun(): number
---@field set_guiColorsPreset fun(value: number): nil
---@field get_InstabilityWavingStrength fun(): Single
---@field set_InstabilityWavingStrength fun(value: Single): nil
---@field get_ModPaths fun(): any[]
---@field set_ModPaths fun(value: any[]): nil
---@field get_DisabledMods fun(): any[]
---@field set_DisabledMods fun(value: any[]): nil
---@field get_ExtendedDebugInfo fun(): boolean
---@field set_ExtendedDebugInfo fun(value: boolean): nil
---@field get_ScaleScreenshot fun(): boolean
---@field set_ScaleScreenshot fun(value: boolean): nil
---@field get_RecordingFrameRate fun(): Single
---@field set_RecordingFrameRate fun(value: Single): nil
---@field get_GameTickFrameRate fun(): Single
---@field set_GameTickFrameRate fun(value: Single): nil
---@field get_RecordingCodec fun(): string
---@field set_RecordingCodec fun(value: string): nil
---@field get_ChatWindowWidth fun(): number
---@field set_ChatWindowWidth fun(value: number): nil
---@field get_ChatWindowHeight fun(): number
---@field set_ChatWindowHeight fun(value: number): nil
---@field get_MaxFPS fun(): number
---@field set_MaxFPS fun(value: number): nil
---@field get_ShowEntityDebugInfo fun(): boolean
---@field set_ShowEntityDebugInfo fun(value: boolean): nil
---@field get_ShowBlockInfoHud fun(): boolean
---@field set_ShowBlockInfoHud fun(value: boolean): nil
---@field get_ShowBlockInteractionHelp fun(): boolean
---@field set_ShowBlockInteractionHelp fun(value: boolean): nil
---@field get_ShowCoordinateHud fun(): boolean
---@field set_ShowCoordinateHud fun(value: boolean): nil
---@field get_ShadowMapQuality fun(): number
---@field set_ShadowMapQuality fun(value: number): nil
---@field get_ParticleLevel fun(): number
---@field set_ParticleLevel fun(value: number): nil
---@field get_MaxDynamicLights fun(): number
---@field set_MaxDynamicLights fun(value: number): nil
---@field get_MouseWheelSensivity fun(): Single
---@field set_MouseWheelSensivity fun(value: Single): nil
---@field get_VideoFileTarget fun(): string
---@field set_VideoFileTarget fun(value: string): nil
---@field get_GlContextVersion fun(): string
---@field set_GlContextVersion fun(value: string): nil
---@field get_AudioDevice fun(): string
---@field set_AudioDevice fun(value: string): nil
---@field get_DirectMouseMode fun(): boolean
---@field set_DirectMouseMode fun(value: boolean): nil
---@field get_InvertMouseYAxis fun(): boolean
---@field set_InvertMouseYAxis fun(value: boolean): nil
---@field get_ImmersiveMouseMode fun(): boolean
---@field set_ImmersiveMouseMode fun(value: boolean): nil
---@field get_ImmersiveFpMode fun(): boolean
---@field set_ImmersiveFpMode fun(value: boolean): nil
---@field get_AutoChat fun(): boolean
---@field set_AutoChat fun(value: boolean): nil
---@field get_ItemCollectMode fun(): number
---@field set_ItemCollectMode fun(value: number): nil
---@field get_WindowBorder fun(): number
---@field set_WindowBorder fun(value: number): nil
---@field get_OffThreadMipMapCreation fun(): boolean
---@field set_OffThreadMipMapCreation fun(value: boolean): nil
---@field get_FpHandsYOffset fun(): Single
---@field set_FpHandsYOffset fun(value: Single): nil
---@field get_FpHandsFoV fun(): number
---@field set_FpHandsFoV fun(value: number): nil
---@field get_IsNewSettingsFile fun(): boolean
---@field LoadDefaultValues fun(): nil
---@field Save fun(force: boolean): boolean
---@field AddWatcher fun(key: string, handler: OnSettingsChanged): nil
---@field GetStringSetting fun(key: string, defaultValue: string): string
---@field GetStringListSetting fun(key: string, defaultValue: any[]): any[]
---@field GetIntSetting fun(key: string): number
---@field GetFloatSetting fun(key: string): Single
---@field GetBoolSetting fun(key: string): boolean
---@field HasSetting fun(name: string): boolean
---@field GetSettingType fun(name: string): any
---@field Load fun(): nil
---@field get_IsDirty fun(): boolean
---@field set_ShouldTriggerWatchers fun(value: boolean): nil
---@field get_Bool fun(): ISettingsClass
---@field get_Int fun(): ISettingsClass
---@field get_Float fun(): ISettingsClass
---@field get_String fun(): ISettingsClass
---@field get_Strings fun(): ISettingsClass
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field FileName string
---@field BkpFileName string
---@field TempFileName string
---@field DialogPositions string
---@field KeyMapping string
---@field SelectedBlockOutline string
---@field ShowPasswordProtectedServers string
---@field TestGlExtensions string
---@field ScreenshotExifDataMode string
---@field ShowOpenForAllServers string
---@field ShowWhitelistedServers string
---@field ShowModdedServers string
---@field ShowMoreGfxOptions string
---@field Occlusionculling string
---@field GlDebugMode string
---@field GlErrorChecking string
---@field MultipleInstances string
---@field StartupErrorDialog string
---@field HighQualityAnimations string
---@field ToggleSprint string
---@field SeparateCtrl string
---@field WebRequestTimeout string
---@field OptimizeRamMode string
---@field LeftDialogMargin string
---@field RightDialogMargin string
---@field ShowSurvivalHelpDialog string
---@field ShowCreativeHelpDialog string
---@field ViewBobbing string
---@field ChatDialogVisible string
---@field UserEmail string
---@field MpToken string
---@field HasGameServer string
---@field Sessionkey string
---@field SessionSignature string
---@field MasterserverUrl string
---@field ModDbUrl string
---@field PlayerUID string
---@field PlayerName string
---@field Entitlements string
---@field SettingsVersion string
---@field GUIScale string
---@field FontSize string
---@field LodBias string
---@field LodBiasFar string
---@field SmoothShadows string
---@field SSAOQuality string
---@field FlipScreenshot string
---@field DeveloperMode string
---@field ViewDistance string
---@field FXAA string
---@field RenderMetaBlocks string
---@field ChunkVerticesUploadRateLimiter string
---@field SSAA string
---@field MegaScreenshotSizeMul string
---@field WavingFoliage string
---@field LiquidFoamAndShinyEffect string
---@field PauseGameOnLostFocus string
---@field Bloom string
---@field GraphicsPresetId string
---@field GameWindowMode string
---@field SoundLevel string
---@field EntitySoundLevel string
---@field AmbientSoundLevel string
---@field WeatherSoundLevel string
---@field MusicLevel string
---@field MusicFrequency string
---@field Language string
---@field DefaultFontName string
---@field DecorativeFontName string
---@field UseServerTextures string
---@field ScreenWidth string
---@field ScreenHeight string
---@field WeirdMacOSMouseYOffset string
---@field BlockAtlasSubPixelPadding string
---@field ItemAtlasSubPixelPadding string
---@field MipMapLevel string
---@field MaxQuadParticles string
---@field MaxCubeParticles string
---@field MaxAsyncQuadParticles string
---@field MaxAsyncCubeParticles string
---@field MouseSensivity string
---@field MouseSmoothing string
---@field VsyncMode string
---@field ModelDataPoolMaxVertexSize string
---@field ModelDataPoolMaxIndexSize string
---@field ModelDataPoolMaxParts string
---@field FieldOfView string
---@field MaxTextureAtlasWidth string
---@field MaxTextureAtlasHeight string
---@field SkipNvidiaProfileCheck string
---@field AmbientBloomLevel string
---@field GodRayQuality string
---@field Minbrightness string
---@field RecordingBufferSize string
---@field UseHRTFAudio string
---@field AllowSettingHRTFAudio string
---@field Force48kHzHRTFAudio string
---@field RenderParticles string
---@field AmbientParticles string
---@field RenderClouds string
---@field TransparentRenderPass string
---@field GammaLevel string
---@field ExtraGammaLevel string
---@field BrightnessLevel string
---@field SepiaLevel string
---@field CameraShakeStrength string
---@field Wireframethickness string
---@field guiColorsPreset string
---@field InstabilityWavingStrength string
---@field ModPaths string
---@field DisabledMods string
---@field ExtendedDebugInfo string
---@field ScaleScreenshot string
---@field RecordingFrameRate string
---@field GameTickFrameRate string
---@field RecordingCodec string
---@field ChatWindowWidth string
---@field ChatWindowHeight string
---@field MaxFPS string
---@field ShowEntityDebugInfo string
---@field ShowBlockInfoHud string
---@field ShowBlockInteractionHelp string
---@field ShowCoordinateHud string
---@field ShadowMapQuality string
---@field ParticleLevel string
---@field MaxDynamicLights string
---@field MouseWheelSensivity string
---@field VideoFileTarget string
---@field GlContextVersion string
---@field AudioDevice string
---@field DirectMouseMode string
---@field InvertMouseYAxis string
---@field ImmersiveMouseMode string
---@field ImmersiveFpMode string
---@field AutoChat string
---@field ItemCollectMode string
---@field WindowBorder string
---@field OffThreadMipMapCreation string
---@field FpHandsYOffset string
---@field FpHandsFoV string
---@field IsNewSettingsFile string
---@field IsDirty string
---@field ShouldTriggerWatchers string
---@field Bool string
---@field Int string
---@field Float string
---@field String string
---@field Strings string
---@field Inst string
---@field OtherDirty string
ClientSettings = {}
