---@meta MeshDataPoolMasterManager
---@class MeshDataPoolMasterManager: Object
---@field ctor fun(capi: ICoreClientAPI): MeshDataPoolMasterManager
---@field RemoveDataPoolLocations fun(locations: ModelDataPoolLocation[]): nil
---@field OnFrame fun(dt: Single, modelviewMatrix: Single[], shadowMVPMatrix: Single[]): nil
---@field AddModelDataPool fun(pool: MeshDataPool): nil
---@field DisposeAllPools fun(capi: ICoreClientAPI): nil
---@field CalcFragmentation fun(): Single
---@field QuantityModelDataPools fun(): number
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
MeshDataPoolMasterManager = {}
