---@meta Packet_ServerChunkSerializer
---@class Packet_ServerChunkSerializer: Object
---@field ctor fun(): Packet_ServerChunkSerializer
---@field DeserializeLengthDelimitedNew fun(stream: CitoMemoryStream): Packet_ServerChunk
---@field DeserializeBuffer fun(buffer: number[], length: number, instance: Packet_ServerChunk): Packet_ServerChunk
---@field Deserialize fun(stream: CitoMemoryStream, instance: Packet_ServerChunk): Packet_ServerChunk
---@field DeserializeLengthDelimited fun(stream: CitoMemoryStream, instance: Packet_ServerChunk): Packet_ServerChunk
---@field Serialize fun(stream: CitoStream, instance: Packet_ServerChunk): nil
---@field SerializeToBytes fun(instance: Packet_ServerChunk): number[]
---@field SerializeLengthDelimited fun(stream: CitoStream, instance: Packet_ServerChunk): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_ServerChunkSerializer = {}
