---@meta StrongBlockBehavior
---@class StrongBlockBehavior: BlockBehavior
---@field GetDecal fun(world: IWorldAccessor, pos: BlockPos, decalTexSource: ITexPositionSource, decalModelData: MeshData&, blockModelData: MeshData&, handled: EnumHandling&): nil
---@field GetParticleCollisionBoxes fun(blockAccessor: IBlockAccessor, pos: BlockPos, handled: EnumHandling&): Cuboidf[]
---@field GetCollisionBoxes fun(blockAccessor: IBlockAccessor, pos: BlockPos, handled: EnumHandling&): Cuboidf[]
---@field GetSelectionBoxes fun(blockAccessor: IBlockAccessor, pos: BlockPos, handled: EnumHandling&): Cuboidf[]
---@field GetParticleBreakBox fun(blockAccess: IBlockAccessor, pos: BlockPos, facing: BlockFacing, handled: EnumHandling&): Cuboidf
---@field OnDecalTesselation fun(world: IWorldAccessor, decalMesh: MeshData, pos: BlockPos, handled: EnumHandling&): nil
---@field TryPlaceBlockForWorldGen fun(blockAccessor: IBlockAccessor, pos: BlockPos, onBlockFace: BlockFacing, worldgenRandom: LCGRandom, handled: EnumHandling&): boolean
---@field DoParticalSelection fun(world: IWorldAccessor, pos: BlockPos, handled: EnumHandling&): boolean
---@field OnBlockBroken fun(world: IWorldAccessor, pos: BlockPos, byPlayer: IPlayer, handling: EnumHandling&): nil
---@field OnPickBlock fun(world: IWorldAccessor, pos: BlockPos, handling: EnumHandling&): ItemStack
---@field GetDrops fun(world: IWorldAccessor, pos: BlockPos, byPlayer: IPlayer, dropChanceMultiplier: Single&, handling: EnumHandling&): ItemStack[]
---@field OnNeighbourBlockChange fun(world: IWorldAccessor, pos: BlockPos, neibpos: BlockPos, handling: EnumHandling&): nil
---@field CanAttachBlockAt fun(world: IBlockAccessor, block: Block, pos: BlockPos, blockFace: BlockFacing, handling: EnumHandling&, attachmentArea: Cuboidi): boolean
---@field CanCreatureSpawnOn fun(blockAccessor: IBlockAccessor, pos: BlockPos, type: EntityProperties, sc: BaseSpawnConditions, handling: EnumHandling&): boolean
---@field GetRotatedBlockCode fun(angle: number, handling: EnumHandling&): AssetLocation
---@field GetVerticallyFlippedBlockCode fun(handling: EnumHandling&): AssetLocation
---@field GetHorizontallyFlippedBlockCode fun(axis: EnumAxis, handling: EnumHandling&): AssetLocation
---@field IsReplacableBy fun(block: Block, handling: EnumHandling&): boolean
---@field ShouldReceiveClientParticleTicks fun(world: IWorldAccessor, byPlayer: IPlayer, pos: BlockPos, handling: EnumHandling&): boolean
---@field OnAsyncClientParticleTick fun(manager: IAsyncParticleManager, pos: BlockPos, windAffectednessAtPos: Single, secondsTicking: Single): nil
---@field OnBlockRemoved fun(world: IWorldAccessor, pos: BlockPos, handling: EnumHandling&): nil
---@field Activate fun(world: IWorldAccessor, caller: Caller, blockSel: BlockSelection, activationArgs: ITreeAttribute, handled: EnumHandling&): nil
---@field OnBlockInteractStart fun(world: IWorldAccessor, byPlayer: IPlayer, blockSel: BlockSelection, handling: EnumHandling&): boolean
---@field GetPlacedBlockInfo fun(world: IWorldAccessor, pos: BlockPos, forPlayer: IPlayer): string
---@field OnBlockExploded fun(world: IWorldAccessor, pos: BlockPos, explosionCenter: BlockPos, blastType: EnumBlastany, handling: EnumHandling&): nil
---@field GetPlacedBlockInteractionHelp fun(world: IWorldAccessor, selection: BlockSelection, forPlayer: IPlayer, handling: EnumHandling&): WorldInteraction[]
---@field OnBlockInteractStop fun(secondsUsed: Single, world: IWorldAccessor, byPlayer: IPlayer, blockSel: BlockSelection, handling: EnumHandling&): nil
---@field OnBlockInteractStep fun(secondsUsed: Single, world: IWorldAccessor, byPlayer: IPlayer, blockSel: BlockSelection, handling: EnumHandling&): boolean
---@field OnBlockInteractCancel fun(secondsUsed: Single, world: IWorldAccessor, byPlayer: IPlayer, blockSel: BlockSelection, handling: EnumHandling&): boolean
---@field TryPlaceBlock fun(world: IWorldAccessor, byPlayer: IPlayer, itemstack: ItemStack, blockSel: BlockSelection, handling: EnumHandling&, failureCode: string&): boolean
---@field CanPlaceBlock fun(world: IWorldAccessor, byPlayer: IPlayer, blockSel: BlockSelection, handling: EnumHandling&, failureCode: string&): boolean
---@field DoPlaceBlock fun(world: IWorldAccessor, byPlayer: IPlayer, blockSel: BlockSelection, byItemStack: ItemStack, handling: EnumHandling&): boolean
---@field OnBlockPlaced fun(world: IWorldAccessor, blockPos: BlockPos, handling: EnumHandling&): nil
---@field OnCreatedByCrafting fun(allInputslots: ItemSlot[], outputSlot: ItemSlot, byRecipe: GridRecipe, handled: EnumHandling&): nil
---@field GetHeldBlockInfo fun(world: IWorldAccessor, inSlot: ItemSlot): string
---@field GetSnowCoveredBlockCode fun(snowLevel: Single): AssetLocation
---@field GetMiningSpeedModifier fun(world: IWorldAccessor, pos: BlockPos, byPlayer: IPlayer): Single
---@field GetPlacedBlockName fun(sb: stringBuilder, world: IWorldAccessor, pos: BlockPos): nil
---@field GetHeatRetention fun(pos: BlockPos, facing: BlockFacing, handled: EnumHandling&): number
---@field GetRetention fun(pos: BlockPos, facing: BlockFacing, type: EnumRetentionany, handled: EnumHandling&): number
---@field GetLiquidBarrierHeightOnSide fun(face: BlockFacing, pos: BlockPos, handled: EnumHandling&): Single
---@field get_ClientSideOptional fun(): boolean
---@field Initialize fun(properties: Jsontable): nil
---@field OnLoaded fun(api: ICoreAPI): nil
---@field OnUnloaded fun(api: ICoreAPI): nil
---@field GetStorageFlags fun(itemstack: ItemStack, handling: EnumHandling&): EnumItemStorageFlags
---@field OnHeldAttackStart fun(slot: ItemSlot, byEntity: EntityAgent, blockSel: BlockSelection, entitySel: EntitySelection, handHandling: EnumHandHandling&, handling: EnumHandling&): nil
---@field OnHeldAttackCancel fun(secondsPassed: Single, slot: ItemSlot, byEntity: EntityAgent, blockSelection: BlockSelection, entitySel: EntitySelection, cancelReason: EnumItemUseCancelReason, handling: EnumHandling&): boolean
---@field OnHeldAttackStep fun(secondsPassed: Single, slot: ItemSlot, byEntity: EntityAgent, blockSelection: BlockSelection, entitySel: EntitySelection, handling: EnumHandling&): boolean
---@field OnHeldAttackStop fun(secondsPassed: Single, slot: ItemSlot, byEntity: EntityAgent, blockSelection: BlockSelection, entitySel: EntitySelection, handling: EnumHandling&): nil
---@field OnHeldInteractStart fun(slot: ItemSlot, byEntity: EntityAgent, blockSel: BlockSelection, entitySel: EntitySelection, firstEvent: boolean, handHandling: EnumHandHandling&, handling: EnumHandling&): nil
---@field OnHeldInteractStep fun(secondsUsed: Single, slot: ItemSlot, byEntity: EntityAgent, blockSel: BlockSelection, entitySel: EntitySelection, handling: EnumHandling&): boolean
---@field OnHeldInteractStop fun(secondsUsed: Single, slot: ItemSlot, byEntity: EntityAgent, blockSel: BlockSelection, entitySel: EntitySelection, handling: EnumHandling&): nil
---@field OnHeldInteractCancel fun(secondsUsed: Single, slot: ItemSlot, byEntity: EntityAgent, blockSel: BlockSelection, entitySel: EntitySelection, cancelReason: EnumItemUseCancelReason, handled: EnumHandling&): boolean
---@field OnBeforeRender fun(capi: ICoreClientAPI, itemstack: ItemStack, target: EnumItemRenderTarget, renderinfo: ItemRenderInfo&): nil
---@field GetHeldInteractionHelp fun(inSlot: ItemSlot, handling: EnumHandling&): WorldInteraction[]
---@field GetToolModes fun(slot: ItemSlot, forPlayer: IClientPlayer, blockSel: BlockSelection): SkillItem[]
---@field GetToolMode fun(slot: ItemSlot, byPlayer: IPlayer, blockSelection: BlockSelection): number
---@field SetToolMode fun(slot: ItemSlot, byPlayer: IPlayer, blockSelection: BlockSelection, toolMode: number): nil
---@field GetHeldItemInfo fun(inSlot: ItemSlot, dsc: stringBuilder, world: IWorldAccessor, withDebugInfo: boolean): nil
---@field GetHeldItemName fun(sb: stringBuilder, itemStack: ItemStack): nil
---@field OnBlockBrokenWith fun(world: IWorldAccessor, byEntity: Entity, itemslot: ItemSlot, blockSel: BlockSelection, dropQuantityMultiplier: Single, bhHandling: EnumHandling&): boolean
---@field OnBlockBreaking fun(player: IPlayer, blockSel: BlockSelection, itemslot: ItemSlot, remainingResistance: Single, dt: Single, counter: number, handled: EnumHandling&): Single
---@field GetHeldTpHitAnimation fun(slot: ItemSlot, byEntity: Entity, bhHandling: EnumHandling&): string
---@field GetHeldReadyAnimation fun(activeHotbarSlot: ItemSlot, forEntity: Entity, hand: EnumHand, bhHandling: EnumHandling&): string
---@field GetHeldTpIdleAnimation fun(activeHotbarSlot: ItemSlot, forEntity: Entity, hand: EnumHand, bhHandling: EnumHandling&): string
---@field GetHeldTpUseAnimation fun(activeHotbarSlot: ItemSlot, forEntity: Entity, bhHandling: EnumHandling&): string
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field ClientSideOptional boolean
---@field block boolean
---@field collObj boolean
---@field propertiesAtString boolean
StrongBlockBehavior = {}
