---@meta ShaderRegistry
---@class ShaderRegistry: Object
---@field ctor fun(): ShaderRegistry
---@field RegisterShaderProgram fun(name: string, program: ShaderProgram): number
---@overload fun(defaultProgram: EnumShaderProgram, program: ShaderProgram): nil
---@field getProgram fun(renderPass: EnumShaderProgram): ShaderProgram
---@overload fun(renderPass: number): ShaderProgram
---@field getProgramByName fun(shadername: string): ShaderProgram
---@field Load fun(): nil
---@field ReloadShaders fun(): boolean
---@field IsGLSLVersionSupported fun(minVersion: string): boolean
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
ShaderRegistry = {}
