---@meta Packet_BlockEntityPacketSerializer
---@class Packet_BlockEntityPacketSerializer: Object
---@field ctor fun(): Packet_BlockEntityPacketSerializer
---@field DeserializeLengthDelimitedNew fun(stream: CitoMemoryStream): Packet_BlockEntityPacket
---@field DeserializeBuffer fun(buffer: number[], length: number, instance: Packet_BlockEntityPacket): Packet_BlockEntityPacket
---@field Deserialize fun(stream: CitoMemoryStream, instance: Packet_BlockEntityPacket): Packet_BlockEntityPacket
---@field DeserializeLengthDelimited fun(stream: CitoMemoryStream, instance: Packet_BlockEntityPacket): Packet_BlockEntityPacket
---@field Serialize fun(stream: CitoStream, instance: Packet_BlockEntityPacket): nil
---@field SerializeToBytes fun(instance: Packet_BlockEntityPacket): number[]
---@field SerializeLengthDelimited fun(stream: CitoStream, instance: Packet_BlockEntityPacket): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_BlockEntityPacketSerializer = {}
