---@meta ICoreAPICommon
---@class ICoreAPICommon
---@field RegisterRecipeRegistry fun(recipeRegistryCode: string): T
---@field RegisterColorMap fun(map: ColorMap): nil
---@field RegisterEntity fun(className: string, entity: any): nil
---@field RegisterEntityBehaviorClass fun(className: string, entityBehavior: any): nil
---@field RegisterBlockClass fun(className: string, blockType: any): nil
---@field RegisterCropBehavior fun(className: string, type: any): nil
---@field RegisterBlockEntityClass fun(className: string, blockentityType: any): nil
---@field RegisterItemClass fun(className: string, itemType: any): nil
---@field RegisterCollectibleBehaviorClass fun(className: string, blockBehaviorType: any): nil
---@field RegisterBlockBehaviorClass fun(className: string, blockBehaviorType: any): nil
---@field RegisterBlockEntityBehaviorClass fun(className: string, blockEntityBehaviorType: any): nil
---@field RegisterMountable fun(className: string, mountableInstancer: GetMountableDelegate): nil
---@field get_ObjectCache fun(): table<any, any>
---@field get_DataBasePath fun(): string
---@field GetOrCreateDataPath fun(foldername: string): string
---@field StoreModConfig fun(jsonSerializeableData: T, filename: string): nil
---@overload fun(jobj: Jsontable, filename: string): nil
---@field LoadModConfig fun(filename: string): T
---@overload fun(filename: string): Jsontable
---@field ObjectCache table<any, any>
---@field DataBasePath table<any, any>
ICoreAPICommon = {}
