---@meta Packet_ItemTypeSerializer
---@class Packet_ItemTypeSerializer: Object
---@field ctor fun(): Packet_ItemTypeSerializer
---@field DeserializeLengthDelimitedNew fun(stream: CitoMemoryStream): Packet_Itemany
---@field DeserializeBuffer fun(buffer: number[], length: number, instance: Packet_Itemany): Packet_Itemany
---@field Deserialize fun(stream: CitoMemoryStream, instance: Packet_Itemany): Packet_Itemany
---@field DeserializeLengthDelimited fun(stream: CitoMemoryStream, instance: Packet_Itemany): Packet_Itemany
---@field Serialize fun(stream: CitoStream, instance: Packet_Itemany): nil
---@field SerializeToBytes fun(instance: Packet_Itemany): number[]
---@field SerializeLengthDelimited fun(stream: CitoStream, instance: Packet_Itemany): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_ItemTypeSerializer = {}
