---@meta BlockBreakingParticleProps
---@class BlockBreakingParticleProps: CollectibleParticleProperties
---@field ctor fun(): BlockBreakingParticleProps
---@field GetRgbaColor fun(capi: ICoreClientAPI): number
---@field get_Pos fun(): Vec3d
---@field get_Size fun(): Single
---@field get_SizeEvolve fun(): EvolvingNatFloat
---@field get_SwimOnLiquid fun(): boolean
---@field GetVelocity fun(pos: Vec3d): Vec3f
---@field get_ParticleModel fun(): EnumParticleModel
---@field get_Quantity fun(): Single
---@field get_VertexFlags fun(): number
---@field get_LifeLength fun(): Single
---@field ToBytes fun(writer: BinaryWriter): nil
---@field FromBytes fun(reader: BinaryReader, resolver: IWorldAccessor): nil
---@field get_Async fun(): boolean
---@field get_Bounciness fun(): Single
---@field set_Bounciness fun(value: Single): nil
---@field get_DieOnRainHeightmap fun(): boolean
---@field set_DieOnRainHeightmap fun(value: boolean): nil
---@field get_RandomVelocityChange fun(): boolean
---@field set_RandomVelocityChange fun(value: boolean): nil
---@field get_DieInLiquid fun(): boolean
---@field get_DieInAir fun(): boolean
---@field get_SelfPropelled fun(): boolean
---@field get_TerrainCollision fun(): boolean
---@field get_GravityEffect fun(): Single
---@field UseLighting fun(): boolean
---@field RandomBlockPos fun(blockAccess: IBlockAccessor, pos: BlockPos, block: Block, facing: BlockFacing): Vec3d
---@field get_OpacityEvolve fun(): EvolvingNatFloat
---@field get_RedEvolve fun(): EvolvingNatFloat
---@field get_GreenEvolve fun(): EvolvingNatFloat
---@field get_BlueEvolve fun(): EvolvingNatFloat
---@field ColorByBlock fun(): Block
---@field BeginParticle fun(): nil
---@field get_VelocityEvolve fun(): EvolvingNatFloat[]
---@field get_SecondaryParticles fun(): IParticlePropertiesProvider[]
---@field get_DeathParticles fun(): IParticlePropertiesProvider[]
---@field get_SecondarySpawnInterval fun(): Single
---@field PrepareForSecondarySpawn fun(particleInstance: ParticleBase): nil
---@field Init fun(api: ICoreAPI): nil
---@field get_ParentVelocity fun(): Vec3f
---@field set_ParentVelocity fun(value: Vec3f): nil
---@field get_ParentVelocityWeight fun(): Single
---@field set_ParentVelocityWeight fun(value: Single): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field Pos Vec3d
---@field Size Vec3d
---@field SizeEvolve Vec3d
---@field SwimOnLiquid Vec3d
---@field ParticleModel Vec3d
---@field Quantity Vec3d
---@field VertexFlags Vec3d
---@field LifeLength Vec3d
---@field Async Vec3d
---@field Bounciness Vec3d
---@field DieOnRainHeightmap Vec3d
---@field RandomVelocityChange Vec3d
---@field DieInLiquid Vec3d
---@field DieInAir Vec3d
---@field SelfPropelled Vec3d
---@field TerrainCollision Vec3d
---@field GravityEffect Vec3d
---@field OpacityEvolve Vec3d
---@field RedEvolve Vec3d
---@field GreenEvolve Vec3d
---@field BlueEvolve Vec3d
---@field VelocityEvolve Vec3d
---@field SecondaryParticles Vec3d
---@field DeathParticles Vec3d
---@field SecondarySpawnInterval Vec3d
---@field ParentVelocity Vec3d
---@field ParentVelocityWeight Vec3d
---@field boyant Vec3d
---@field rand Vec3d
---@field api Vec3d
BlockBreakingParticleProps = {}
