---@meta ServerSettings
---@class ServerSettings: Object
---@field ctor fun(): ServerSettings
---@field get_WatchModFolder fun(): boolean
---@field Save fun(): nil
---@field Load fun(): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field WatchModFolder boolean
---@field instance boolean
---@field Language boolean
ServerSettings = {}
