---@meta BakedBitmap
---@class BakedBitmap: Object
---@field ctor fun(): BakedBitmap
---@field get_Pixels fun(): number[]
---@field GetPixel fun(x: number, y: number): SKColor
---@field GetPixelArgb fun(x: number, y: number): number
---@field GetPixelRel fun(x: Single, y: Single): SKColor
---@field GetPixelsTransformed fun(rot: number, alpha: number): number[]
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field Pixels number[]
---@field TexturePixels number[]
---@field Width number[]
---@field Height number[]
BakedBitmap = {}
