---@meta Packet_EntityPositionSerializer
---@class Packet_EntityPositionSerializer: Object
---@field ctor fun(): Packet_EntityPositionSerializer
---@field DeserializeLengthDelimitedNew fun(stream: CitoMemoryStream): Packet_EntityPosition
---@field DeserializeBuffer fun(buffer: number[], length: number, instance: Packet_EntityPosition): Packet_EntityPosition
---@field Deserialize fun(stream: CitoMemoryStream, instance: Packet_EntityPosition): Packet_EntityPosition
---@field DeserializeLengthDelimited fun(stream: CitoMemoryStream, instance: Packet_EntityPosition): Packet_EntityPosition
---@field Serialize fun(stream: CitoStream, instance: Packet_EntityPosition): nil
---@field SerializeToBytes fun(instance: Packet_EntityPosition): number[]
---@field SerializeLengthDelimited fun(stream: CitoStream, instance: Packet_EntityPosition): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_EntityPositionSerializer = {}
