---@meta GltfImageSampler
---@class GltfImageSampler: Object
---@field ctor fun(): GltfImageSampler
---@field get_MagFilter fun(): TextureMagFilter
---@field set_MagFilter fun(value: TextureMagFilter): nil
---@field get_MinFilter fun(): TextureMinFilter
---@field set_MinFilter fun(value: TextureMinFilter): nil
---@field get_WrapS fun(): TextureWrapMode
---@field set_WrapS fun(value: TextureWrapMode): nil
---@field get_WrapT fun(): TextureWrapMode
---@field set_WrapT fun(value: TextureWrapMode): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field MagFilter TextureMagFilter
---@field MinFilter TextureMagFilter
---@field WrapS TextureMagFilter
---@field WrapT TextureMagFilter
GltfImageSampler = {}
