---@meta BitmapExternal
---@class BitmapExternal: BitmapRef
---@field ctor fun(): BitmapExternal
---@overload fun(width: number, height: number): BitmapExternal
---@overload fun(ms: MemoryStream, logger: ILogger, loc: AssetLocation): BitmapExternal
---@overload fun(filePath: string): BitmapExternal
---@overload fun(stream: Stream): BitmapExternal
---@overload fun(data: number[], dataLength: number, logger: ILogger): BitmapExternal
---@field get_Height fun(): number
---@field get_Width fun(): number
---@field get_Pixels fun(): number[]
---@field get_PixelsPtrAndLock fun(): IntPtr
---@field Dispose fun(): nil
---@field Save fun(filename: string): nil
---@field GetPixel fun(x: number, y: number): SKColor
---@field GetPixelRel fun(x: Single, y: Single): SKColor
---@field MulAlpha fun(alpha: number): nil
---@field GetPixelsTransformed fun(rot: number, mulAlpha: number): number[]
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field Height number
---@field Width number
---@field Pixels number
---@field PixelsPtrAndLock number
---@field bmp number
BitmapExternal = {}
