---@meta BlockDropItemStack
---@class BlockDropItemStack: Object
---@field ctor fun(): BlockDropItemStack
---@overload fun(stack: ItemStack, chance: Single): BlockDropItemStack
---@field Resolve fun(resolver: IWorldAccessor, sourceForErrorLogging: string, assetLoc: AssetLocation): boolean
---@field GetNextItemStack fun(dropQuantityMultiplier: Single): ItemStack
---@field Clone fun(): BlockDropItemStack
---@field FromBytes fun(reader: BinaryReader, instancer: IClassRegistryAPI): nil
---@field ToBytes fun(writer: BinaryWriter): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
BlockDropItemStack = {}
