---@meta VtmlUtil
---@class VtmlUtil: Object
---@field ctor fun(): VtmlUtil
---@field Richtextify fun(capi: ICoreClientAPI, vtmlCode: string, baseFont: CairoFont, didClickLink: any`1): RichTextComponentBase[]
---@field parseHexColor fun(colorText: string, color: Double[]&): boolean
---@field toHexColor fun(color: Double[]): string
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
VtmlUtil = {}
