---@meta ShapeTesselatorManager
---@class ShapeTesselatorManager: Multithreaded
---@field ctor fun(game: ClientMain): ShapeTesselatorManager
---@overload fun(server: ServerMain): ShapeTesselatorManager
---@field get_Tesselator fun(): ShapeTesselator
---@field GetDefaultBlockMesh fun(block: Block): MeshData
---@field LoadDone fun(): nil
---@field PrepareToLoadShapes fun(): nil
---@field LoadEntityShapesAsync fun(entities: any[], api: ICoreAPI): nil
---@field LoadEntityShapes fun(entities: any[], api: ICoreAPI): nil
---@field TesselateBlocks_Pre fun(): nil
---@field TesselateBlocksForInventory fun(blocks: Iany[], offset: number, maxCount: number): number
---@field TesselateBlocksForInventory_ASync fun(blocks: Iany[]): nil
---@field TesselateBlocks_Async fun(blocks: Iany[]): nil
---@field CreateFastTextureAlternates fun(block: Block): nil
---@field TesselateItems_Pre fun(itemtypes: Iany[]): nil
---@field TesselateItems fun(itemtypes: Iany[], offset: number, maxCount: number): number
---@field GetDefaultBlockMeshRef fun(block: Block): MultiTextureMeshRef
---@field GetDefaultItemMeshRef fun(item: Item): MultiTextureMeshRef
---@field GetCachedShape fun(location: AssetLocation): Shape
---@field ThreadDispose fun(): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field Tesselator ShapeTesselator
---@field shapes ShapeTesselator
---@field objs ShapeTesselator
---@field gltfs ShapeTesselator
---@field blockModelDatas ShapeTesselator
---@field altblockModelDatasLod1 ShapeTesselator
---@field altblockModelDatasLod0 ShapeTesselator
---@field altblockModelDatasLod2 ShapeTesselator
---@field blockModelRefsInventory ShapeTesselator
---@field itemModelRefsInventory ShapeTesselator
---@field altItemModelRefsInventory ShapeTesselator
---@field unknownItemModelData ShapeTesselator
---@field unknownItemModelRef ShapeTesselator
---@field unknownBlockModelData ShapeTesselator
---@field unknownBlockModelRef ShapeTesselator
ShapeTesselatorManager = {}
