---@meta Quaterniond
---@class Quaterniond: Object
---@field ctor fun(): Quaterniond
---@field Create fun(): Double[]
---@field RotationTo fun(output: Double[], a: Double[], b: Double[]): Double[]
---@field SetAxes fun(output: Double[], view: Double[], right: Double[], up: Double[]): Double[]
---@field CloneIt fun(a: Double[]): Double[]
---@field FromValues fun(x: Double, y: Double, z: Double, w: Double): Double[]
---@field Copy fun(output: Double[], a: Double[]): Double[]
---@field Set fun(output: Double[], x: Double, y: Double, z: Double, w: Double): Double[]
---@field Identity_ fun(output: Double[]): Double[]
---@field SetAxisAngle fun(output: Double[], axis: Double[], rad: Double): Double[]
---@field Add fun(output: Double[], a: Double[], b: Double[]): Double[]
---@field Multiply fun(output: Double[], a: Double[], b: Double[]): Double[]
---@field Scale fun(output: Double[], a: Double[], b: Double): Double[]
---@field RotateX fun(output: Double[], a: Double[], rad: Double): Double[]
---@field RotateY fun(output: Double[], a: Double[], rad: Double): Double[]
---@field RotateZ fun(output: Double[], a: Double[], rad: Double): Double[]
---@field CalculateW fun(output: Double[], a: Double[]): Double[]
---@field Dot fun(a: Double[], b: Double[]): Double
---@field ToEulerAngles fun(quat: Double[]): Single[]
---@field Lerp fun(output: Double[], a: Double[], b: Double[], t: Double): Double[]
---@field Slerp fun(output: Double[], a: Double[], b: Double[], t: Double): Double[]
---@field Invert fun(output: Double[], a: Double[]): Double[]
---@field Conjugate fun(output: Double[], a: Double[]): Double[]
---@field Length_ fun(a: Double[]): Double
---@field SquaredLength fun(a: Double[]): Double
---@field Normalize fun(output: Double[], a: Double[]): Double[]
---@field FromMat3 fun(output: Double[], m: Double[]): Double[]
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Quaterniond = {}
