---@meta ParticlePhysics
---@class ParticlePhysics: Object
---@field ctor fun(blockAccess: IBlockAccessor): ParticlePhysics
---@field CollisionStrength fun(velocitybefore: Vec3f, velocitynow: Vec3f, gravityStrength: Single, deltatime: Single): Vec3f
---@field HandleBoyancy fun(pos: Vec3d, velocity: Vec3f, boyant: boolean, gravityStrength: Single, deltatime: Single, height: Single): nil
---@field UpdateMotion fun(pos: Vec3d, motion: Vec3f, size: Single): EnumCollideFlags
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
ParticlePhysics = {}
