---@meta CreativeInventoryTab
---@class CreativeInventoryTab: InventoryGeneric
---@field ctor fun(quantitySlots: number, className: string, instanceId: string, api: ICoreAPI): CreativeInventoryTab
---@overload fun(quantitySlots: number, invId: string, api: ICoreAPI): CreativeInventoryTab
---@field GetTransitionSpeedMul fun(transType: EnumTransitionany, stack: ItemStack): Single
---@field get_TransitionableSpeedMulByType fun(): table<any, any>
---@field set_TransitionableSpeedMulByType fun(value: table<any, any>): nil
---@field get_PerishableFactorByFoodCategory fun(): table<any, any>
---@field set_PerishableFactorByFoodCategory fun(value: table<any, any>): nil
---@field get_BaseWeight fun(): Single
---@field set_BaseWeight fun(value: Single): nil
---@field get_Count fun(): number
---@field get_Item fun(slotId: number): ItemSlot
---@field set_Item fun(slotId: number, value: ItemSlot): nil
---@field GetSuitability fun(sourceSlot: ItemSlot, targetSlot: ItemSlot, isMerge: boolean): Single
---@field FromTreeAttributes fun(treeAttribute: ITreeAttribute): nil
---@field AddSlots fun(amount: number): nil
---@field ToTreeAttributes fun(invtree: ITreeAttribute): nil
---@field GetAutoPullFromSlot fun(atBlockFace: BlockFacing): ItemSlot
---@field GetAutoPushIntoSlot fun(atBlockFace: BlockFacing, fromSlot: ItemSlot): ItemSlot
---@field get_MaxContentDimensions fun(): Size3f
---@field set_MaxContentDimensions fun(value: Size3f): nil
---@field get_InventoryID fun(): string
---@field get_ClassName fun(): string
---@field get_LastChanged fun(): Int64
---@field get_CountForNetworkPacket fun(): number
---@field get_IsDirty fun(): boolean
---@field get_DirtySlots fun(): HashSet`1
---@field get_TakeLocked fun(): boolean
---@field set_TakeLocked fun(value: boolean): nil
---@field get_PutLocked fun(): boolean
---@field set_PutLocked fun(value: boolean): nil
---@field get_RemoveOnClose fun(): boolean
---@field add_SlotModified fun(value: any`1): nil
---@field remove_SlotModified fun(value: any`1): nil
---@field add_SlotNotified fun(value: any`1): nil
---@field remove_SlotNotified fun(value: any`1): nil
---@field add_OnInventoryOpened fun(value: OnInventoryOpenedDelegate): nil
---@field remove_OnInventoryOpened fun(value: OnInventoryOpenedDelegate): nil
---@field add_OnInventoryClosed fun(value: OnInventoryClosedDelegate): nil
---@field remove_OnInventoryClosed fun(value: OnInventoryClosedDelegate): nil
---@field get_Empty fun(): boolean
---@field get_FirstNonEmptySlot fun(): ItemSlot
---@field LateInitialize fun(inventoryID: string, api: ICoreAPI): nil
---@field AfterBlocksLoaded fun(world: IWorldAccessor): nil
---@field ResolveBlocksOrItems fun(): nil
---@field GetSlotId fun(slot: ItemSlot): number
---@field GetBestSuitedSlot fun(sourceSlot: ItemSlot, skipSlots: any[]): WeightedSlot
---@overload fun(sourceSlot: ItemSlot, op: ItemStackMoveOperation, skipSlots: any[]): WeightedSlot
---@field CanContain fun(sinkSlot: ItemSlot, sourceSlot: ItemSlot): boolean
---@field TryFlipItems fun(targetSlotId: number, itemSlot: ItemSlot): table
---@field CanPlayerAccess fun(player: IPlayer, position: EntityPos): boolean
---@field CanPlayerModify fun(player: IPlayer, position: EntityPos): boolean
---@field OnSearchTerm fun(text: string): nil
---@field ActivateSlot fun(slotId: number, sourceSlot: ItemSlot, op: ItemStackMoveOperation&): table
---@field OnItemSlotModified fun(slot: ItemSlot): nil
---@field DidModifyItemSlot fun(slot: ItemSlot, extractedStack: ItemStack): nil
---@field PerformNotifySlot fun(slotId: number): nil
---@field TryFlipItemStack fun(owningPlayer: IPlayer, invIds: string[], slotIds: number[], lastChanged: Int64[]): boolean
---@field TryMoveItemStack fun(player: IPlayer, invIds: string[], slotIds: number[], op: ItemStackMoveOperation&): boolean
---@field GetSlotsIfExists fun(player: IPlayer, invIds: string[], slotIds: number[]): ItemSlot[]
---@field SlotsFromTreeAttributes fun(tree: ITreeAttribute, slots: ItemSlot[], modifiedSlots: any[]): ItemSlot[]
---@field SlotsToTreeAttributes fun(slots: ItemSlot[], tree: ITreeAttribute): nil
---@field GenEmptySlots fun(quantity: number): ItemSlot[]
---@field MarkSlotDirty fun(slotId: number): nil
---@field DiscardAll fun(): nil
---@field DropSlotIfHot fun(slot: ItemSlot, player: IPlayer): nil
---@field DropSlots fun(pos: Vec3d, slotsIds: number[]): nil
---@field DropAll fun(pos: Vec3d, maxStackSize: number): nil
---@field Clear fun(): nil
---@field OnOwningEntityDeath fun(pos: Vec3d): nil
---@field Open fun(player: IPlayer): table
---@field Close fun(player: IPlayer): table
---@field HasOpened fun(player: IPlayer): boolean
---@field GetEnumerator fun(): IEnumerator`1
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field TransitionableSpeedMulByType table<any, any>
---@field PerishableFactorByFoodCategory table<any, any>
---@field BaseWeight table<any, any>
---@field Count table<any, any>
---@field Item table<any, any>
---@field MaxContentDimensions table<any, any>
---@field InventoryID table<any, any>
---@field ClassName table<any, any>
---@field LastChanged table<any, any>
---@field CountForNetworkPacket table<any, any>
---@field IsDirty table<any, any>
---@field DirtySlots table<any, any>
---@field TakeLocked table<any, any>
---@field PutLocked table<any, any>
---@field RemoveOnClose table<any, any>
---@field Empty table<any, any>
---@field FirstNonEmptySlot table<any, any>
---@field SlotModified table<any, any>
---@field SlotNotified table<any, any>
---@field OnInventoryOpened table<any, any>
---@field OnInventoryClosed table<any, any>
---@field TabIndex table<any, any>
---@field OnGetSuitability table<any, any>
---@field OnGetAutoPushIntoSlot table<any, any>
---@field OnGetAutoPullFromSlot table<any, any>
---@field Api table<any, any>
---@field Pos table<any, any>
---@field lastChangedSinceServerStart table<any, any>
---@field openedByPlayerGUIds table<any, any>
---@field InvNetworkUtil table<any, any>
---@field dirtySlots table<any, any>
---@field OnAcquireTransitionSpeed table<any, any>
CreativeInventoryTab = {}
