---@meta Packet_BlockDamageSerializer
---@class Packet_BlockDamageSerializer: Object
---@field ctor fun(): Packet_BlockDamageSerializer
---@field DeserializeLengthDelimitedNew fun(stream: CitoMemoryStream): Packet_BlockDamage
---@field DeserializeBuffer fun(buffer: number[], length: number, instance: Packet_BlockDamage): Packet_BlockDamage
---@field Deserialize fun(stream: CitoMemoryStream, instance: Packet_BlockDamage): Packet_BlockDamage
---@field DeserializeLengthDelimited fun(stream: CitoMemoryStream, instance: Packet_BlockDamage): Packet_BlockDamage
---@field Serialize fun(stream: CitoStream, instance: Packet_BlockDamage): nil
---@field SerializeToBytes fun(instance: Packet_BlockDamage): number[]
---@field SerializeLengthDelimited fun(stream: CitoStream, instance: Packet_BlockDamage): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_BlockDamageSerializer = {}
