---@meta CustomMeshDataPart`1
---@class CustomMeshDataPart`1: Object
---@field ctor fun(): CustomMeshDataPart`1
---@overload fun(arraySize: number): CustomMeshDataPart`1
---@field get_BufferSize fun(): number
---@field get_AllocationSize fun(): number
---@field GrowBuffer fun(growAtLeastBy: number): nil
---@field Add fun(value: Int16): nil
---@field Add4 fun(value: Int16): nil
---@field Add fun(values: Int16[]): nil
---@field SetAllocationSize fun(size: number): nil
---@field AutoAllocationSize fun(): nil
---@field SetFrom fun(meshdatapart: CustomMeshDataPart`1): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field BufferSize number
---@field AllocationSize number
---@field Values number
---@field Count number
---@field InterleaveSizes number
---@field InterleaveStride number
---@field InterleaveOffsets number
---@field Instanced number
---@field StaticDraw number
---@field BaseOffset number
CustomMeshDataPart`1 = {}
