---@meta EntityProperties
---@class EntityProperties: Object
---@field ctor fun(): EntityProperties
---@field get_SpawnCollisionBox fun(): Cuboidf
---@field Clone fun(): EntityProperties
---@field Initialize fun(entity: Entity, api: ICoreAPI): nil
---@field InitSounds fun(assetManager: IAssetManager): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field SpawnCollisionBox Cuboidf
---@field Id Cuboidf
---@field Color Cuboidf
---@field Code Cuboidf
---@field Variant Cuboidf
---@field Class Cuboidf
---@field Habitat Cuboidf
---@field CollisionBoxSize Cuboidf
---@field DeadCollisionBoxSize Cuboidf
---@field SelectionBoxSize Cuboidf
---@field DeadSelectionBoxSize Cuboidf
---@field EyeHeight Cuboidf
---@field SwimmingEyeHeight Cuboidf
---@field Weight Cuboidf
---@field CanClimb Cuboidf
---@field CanClimbAnywhere Cuboidf
---@field FallDamage Cuboidf
---@field FallDamageMultiplier Cuboidf
---@field ClimbTouchDistance Cuboidf
---@field RotateModelOnClimb Cuboidf
---@field KnockbackResistance Cuboidf
---@field Attributes Cuboidf
---@field Client Cuboidf
---@field Server Cuboidf
---@field Sounds Cuboidf
---@field ResolvedSounds Cuboidf
---@field IdleSoundChance Cuboidf
---@field IdleSoundRange Cuboidf
---@field Drops Cuboidf
---@field DropsPacket Cuboidf
EntityProperties = {}
