---@meta UnloadableShape
---@class UnloadableShape: Shape
---@field ctor fun(): UnloadableShape
---@field Unload fun(): nil
---@field Load fun(game: ClientMain, srcandLoc: AssetLocationAndSource): boolean
---@field ResolveTextures fun(shapeTexturesCache: table<any, any>): nil
---@field TrimTextureNamesAndResolveFaces fun(context: StreamingContext): nil
---@field ResolveReferences fun(errorLogger: ILogger, shapeNameForLogging: string): nil
---@field SubclassForStepParenting fun(texturePrefixCode: string, damageEffect: Single): boolean
---@field StepParentShape fun(childShape: Shape, texturePrefixCode: string, childLocationForLogging: string, parentLocationForLogging: string, logger: ILogger, onTexture: Action`2, damageEffect: Single): boolean
---@overload fun(childShape: Shape, childLocationForLogging: string, parentLocationForLogging: string, logger: ILogger, onTexture: Action`2): boolean
---@field CollectElements fun(elements: ShapeElement[], elementsByName: table<any, any>): nil
---@field ResolveAndLoadJoints fun(requireJointsForElements: string[]): nil
---@field ResolveAndFindJoints fun(errorLogger: ILogger, shapeName: string, requireJointsForElements: string[]): nil
---@field WalkElements fun(wildcardpath: string, onElement: any`1): nil
---@field GetElementByName fun(name: string, stringComparison: stringComparison): ShapeElement
---@field RemoveElementByName fun(name: string, stringComparison: stringComparison): boolean
---@field CloneElements fun(): ShapeElement[]
---@field CloneAnimations fun(): Animation[]
---@field Clone fun(): Shape
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
UnloadableShape = {}
