---@meta TcpNetServer
---@class TcpNetServer: NetServer
---@field ctor fun(): TcpNetServer
---@field get_Name fun(): string
---@field get_LocalEndpoint fun(): string
---@field Start fun(): nil
---@field ReadMessage fun(): NetIncomingMessage
---@field SetIpAndPort fun(ip: string, port: number): nil
---@field Dispose fun(): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field Name string
---@field LocalEndpoint string
TcpNetServer = {}
