---@meta Packet_ClientSerializer
---@class Packet_ClientSerializer: Object
---@field ctor fun(): Packet_ClientSerializer
---@field DeserializeLengthDelimitedNew fun(stream: CitoMemoryStream): Packet_Client
---@field DeserializeBuffer fun(buffer: number[], length: number, instance: Packet_Client): Packet_Client
---@field Deserialize fun(stream: CitoMemoryStream, instance: Packet_Client): Packet_Client
---@field DeserializeLengthDelimited fun(stream: CitoMemoryStream, instance: Packet_Client): Packet_Client
---@field Serialize fun(stream: CitoStream, instance: Packet_Client): nil
---@field SerializeToBytes fun(instance: Packet_Client): number[]
---@field SerializeLengthDelimited fun(stream: CitoStream, instance: Packet_Client): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_ClientSerializer = {}
