---@meta GltfAnimationChannelTarget
---@class GltfAnimationChannelTarget: Object
---@field ctor fun(): GltfAnimationChannelTarget
---@field get_Node fun(): Int64
---@field set_Node fun(value: Int64): nil
---@field get_Path fun(): EnumGltfAnimationChannelTargetPath
---@field set_Path fun(value: EnumGltfAnimationChannelTargetPath): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field Node Int64
---@field Path Int64
GltfAnimationChannelTarget = {}
