---@meta ChunkRenderer
---@class ChunkRenderer: Object
---@field ctor fun(textureIds: number[], game: ClientMain): ChunkRenderer
---@field OnSeperateThreadTick fun(dt: Single): nil
---@field PrepareFrame fun(dt: Single): nil
---@field OnBeginFrame fun(dt: Single): nil
---@field RenderShadow fun(dt: Single): nil
---@field RenderOpaque fun(dt: Single): nil
---@field Dispose fun(): nil
---@field AddTesselatedChunk fun(tesschunk: TesselatedChunk, hostChunk: ClientChunk): nil
---@field RemoveDataPoolLocations fun(locations: ModelDataPoolLocation[]): nil
---@field GetStats fun(usedVideoMemory: Int64&, renderedTris: Int64&, allocatedTris: Int64&): nil
---@field CalcFragmentation fun(): Single
---@field QuantityModelDataPools fun(): number
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
ChunkRenderer = {}
