---@meta ExifException
---@class ExifException: Exception
---@field ctor fun(_ErrorCode: ExifErrCode): ExifException
---@field get_Message fun(): string
---@field get_TargetSite fun(): MethodBase
---@field get_Data fun(): IDictionary
---@field GetBaseException fun(): Exception
---@field get_InnerException fun(): Exception
---@field get_HelpLink fun(): string
---@field set_HelpLink fun(value: string): nil
---@field get_Source fun(): string
---@field set_Source fun(value: string): nil
---@field GetObjectData fun(info: SerializationInfo, context: StreamingContext): nil
---@field ToString fun(): string
---@field get_HResult fun(): number
---@field set_HResult fun(value: number): nil
---@field GetType fun(): any
---@field get_StackTrace fun(): string
---@field GetType fun(): any
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field Message string
---@field TargetSite string
---@field Data string
---@field InnerException string
---@field HelpLink string
---@field Source string
---@field HResult string
---@field StackTrace string
---@field ErrorCode string
ExifException = {}
