---@meta SettingsBase
---@class SettingsBase: SettingsBaseNoObf
---@field AddWatcher fun(key: string, handler: OnSettingsChanged`1): nil
---@field ClearWatchers fun(): nil
---@field GetStringSetting fun(key: string, defaultValue: string): string
---@field GetStringListSetting fun(key: string, defaultValue: any[]): any[]
---@field GetIntSetting fun(key: string): number
---@field GetFloatSetting fun(key: string): Single
---@field GetBoolSetting fun(key: string): boolean
---@field HasSetting fun(name: string): boolean
---@field GetSettingType fun(name: string): any
---@field get_FileName fun(): string
---@field get_TempFileName fun(): string
---@field get_BkpFileName fun(): string
---@field Load fun(): nil
---@field get_IsDirty fun(): boolean
---@field Save fun(force: boolean): boolean
---@field LoadDefaultValues fun(): nil
---@field set_ShouldTriggerWatchers fun(value: boolean): nil
---@field get_Bool fun(): ISettingsClass`1
---@field get_Int fun(): ISettingsClass`1
---@field get_Float fun(): ISettingsClass`1
---@field get_String fun(): ISettingsClass`1
---@field get_Strings fun(): ISettingsClass`1
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field FileName string
---@field TempFileName string
---@field BkpFileName string
---@field IsDirty string
---@field ShouldTriggerWatchers string
---@field Bool string
---@field Int string
---@field Float string
---@field String string
---@field Strings string
---@field OtherDirty string
SettingsBase = {}
