---@meta Packet_BulkEntityAttributes
---@class Packet_BulkEntityAttributes: Object
---@field ctor fun(): Packet_BulkEntityAttributes
---@field GetFullUpdates fun(): Packet_EntityAttributes[]
---@field SetFullUpdates fun(value: Packet_EntityAttributes[], count: number, length: number): nil
---@overload fun(value: Packet_EntityAttributes[]): nil
---@field GetFullUpdatesCount fun(): number
---@field FullUpdatesAdd fun(value: Packet_EntityAttributes): nil
---@field GetPartialUpdates fun(): Packet_EntityAttributeUpdate[]
---@field SetPartialUpdates fun(value: Packet_EntityAttributeUpdate[], count: number, length: number): nil
---@overload fun(value: Packet_EntityAttributeUpdate[]): nil
---@field GetPartialUpdatesCount fun(): number
---@field PartialUpdatesAdd fun(value: Packet_EntityAttributeUpdate): nil
---@field GetPosUpdates fun(): Packet_EntityMoved[]
---@field SetPosUpdates fun(value: Packet_EntityMoved[], count: number, length: number): nil
---@overload fun(value: Packet_EntityMoved[]): nil
---@field GetPosUpdatesCount fun(): number
---@field PosUpdatesAdd fun(value: Packet_EntityMoved): nil
---@field GetMinimalPosUpdates fun(): Packet_EntityMovedMinimal[]
---@field SetMinimalPosUpdates fun(value: Packet_EntityMovedMinimal[], count: number, length: number): nil
---@overload fun(value: Packet_EntityMovedMinimal[]): nil
---@field GetMinimalPosUpdatesCount fun(): number
---@field MinimalPosUpdatesAdd fun(value: Packet_EntityMovedMinimal): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_BulkEntityAttributes = {}
