---@meta IClientGameCalendar
---@class IClientGameCalendar
---@field get_SunPositionNormalized fun(): Vec3f
---@field get_SunPosition fun(): Vec3f
---@field get_MoonPosition fun(): Vec3f
---@field get_SunColor fun(): Vec3f
---@field get_ReflectColor fun(): Vec3f
---@field get_SunsetMod fun(): Single
---@field get_DayLightStrength fun(): Single
---@field get_MoonLightStrength fun(): Single
---@field get_SunLightStrength fun(): Single
---@field get_Dusk fun(): boolean
---@field SunPositionNormalized Vec3f
---@field SunPosition Vec3f
---@field MoonPosition Vec3f
---@field SunColor Vec3f
---@field ReflectColor Vec3f
---@field SunsetMod Vec3f
---@field DayLightStrength Vec3f
---@field MoonLightStrength Vec3f
---@field SunLightStrength Vec3f
---@field Dusk Vec3f
IClientGameCalendar = {}
