---@meta BoolAttribute
---@class BoolAttribute: ScalarAttribute`1
---@field ctor fun(): BoolAttribute
---@overload fun(value: boolean): BoolAttribute
---@field FromBytes fun(stream: BinaryReader): nil
---@field ToBytes fun(stream: BinaryWriter): nil
---@field GetAttributeId fun(): number
---@field ToJsonToken fun(): string
---@field Clone fun(): IAttribute
---@field Equals fun(worldForResolve: IWorldAccessor, attr: IAttribute): boolean
---@overload fun(b: table): boolean
---@field GetValue fun(): table
---@field ToString fun(): string
---@field GetHashCode fun(): number
---@field GetType fun(): any
BoolAttribute = {}
