---@meta Packet_PlayerDeathSerializer
---@class Packet_PlayerDeathSerializer: Object
---@field ctor fun(): Packet_PlayerDeathSerializer
---@field DeserializeLengthDelimitedNew fun(stream: CitoMemoryStream): Packet_PlayerDeath
---@field DeserializeBuffer fun(buffer: number[], length: number, instance: Packet_PlayerDeath): Packet_PlayerDeath
---@field Deserialize fun(stream: CitoMemoryStream, instance: Packet_PlayerDeath): Packet_PlayerDeath
---@field DeserializeLengthDelimited fun(stream: CitoMemoryStream, instance: Packet_PlayerDeath): Packet_PlayerDeath
---@field Serialize fun(stream: CitoStream, instance: Packet_PlayerDeath): nil
---@field SerializeToBytes fun(instance: Packet_PlayerDeath): number[]
---@field SerializeLengthDelimited fun(stream: CitoStream, instance: Packet_PlayerDeath): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_PlayerDeathSerializer = {}
