---@meta KeyEvent
---@class KeyEvent: Object
---@field ctor fun(): KeyEvent
---@field get_KeyChar fun(): Char
---@field set_KeyChar fun(value: Char): nil
---@field get_KeyCode fun(): number
---@field set_KeyCode fun(value: number): nil
---@field get_KeyCode2 fun(): Nullable
---@field set_KeyCode2 fun(value: Nullable): nil
---@field get_Handled fun(): boolean
---@field set_Handled fun(value: boolean): nil
---@field get_CtrlPressed fun(): boolean
---@field set_CtrlPressed fun(value: boolean): nil
---@field get_CommandPressed fun(): boolean
---@field set_CommandPressed fun(value: boolean): nil
---@field get_ShiftPressed fun(): boolean
---@field set_ShiftPressed fun(value: boolean): nil
---@field get_AltPressed fun(): boolean
---@field set_AltPressed fun(value: boolean): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field KeyChar Char
---@field KeyCode Char
---@field KeyCode2 Char
---@field Handled Char
---@field CtrlPressed Char
---@field CommandPressed Char
---@field ShiftPressed Char
---@field AltPressed Char
KeyEvent = {}
