---@meta ITextureAtlasAPI
---@class ITextureAtlasAPI
---@field get_Item fun(textureLocation: AssetLocation): TextureAtlasPosition
---@field get_UnknownTexturePosition fun(): TextureAtlasPosition
---@field get_Size fun(): Size2i
---@field get_SubPixelPaddingX fun(): Single
---@field get_SubPixelPaddingY fun(): Single
---@field get_Positions fun(): TextureAtlasPosition[]
---@field get_AtlasTextures fun(): any[]
---@field AllocateTextureSpace fun(width: number, height: number, textureSubId: number&, texPos: TextureAtlasPosition&): boolean
---@field InsertTexture fun(bmp: IBitmap, textureSubId: number&, texPos: TextureAtlasPosition&, alphaTest: Single): boolean
---@overload fun(pngBytes: number[], textureSubId: number&, texPos: TextureAtlasPosition&, alphaTest: Single): boolean
---@field LoadCompositeBitmap fun(path: AssetLocation): IBitmap
---@field GetOrInsertTexture fun(path: AssetLocation, textureSubId: number&, texPos: TextureAtlasPosition&, onCreate: CreateTextureDelegate, alphaTest: Single): boolean
---@field InsertTextureCached fun(path: AssetLocation, bmp: IBitmap, textureSubId: number&, texPos: TextureAtlasPosition&, alphaTest: Single): boolean
---@overload fun(path: AssetLocation, pngBytes: number[], textureSubId: number&, texPos: TextureAtlasPosition&, alphaTest: Single): boolean
---@overload fun(texture: CompositeTexture, textureSubId: number&, texPos: TextureAtlasPosition&, alphaTest: Single): boolean
---@field FreeTextureSpace fun(textureSubId: number): nil
---@field GetRandomColor fun(textureSubId: number): number
---@field RegenMipMaps fun(atlasIndex: number): nil
---@field GetRandomColor fun(textureSubId: number, rndIndex: number): number
---@overload fun(texPos: TextureAtlasPosition, rndIndex: number): number
---@field GetRandomColors fun(texPos: TextureAtlasPosition): number[]
---@field GetAverageColor fun(textureSubId: number): number
---@field RenderTextureIntoAtlas fun(intoAtlasTextureId: number, fromTexture: LoadedTexture, sourceX: Single, sourceY: Single, sourceWidth: Single, sourceHeight: Single, targetX: Single, targetY: Single, alphaTest: Single): nil
---@field Item TextureAtlasPosition
---@field UnknownTexturePosition TextureAtlasPosition
---@field Size TextureAtlasPosition
---@field SubPixelPaddingX TextureAtlasPosition
---@field SubPixelPaddingY TextureAtlasPosition
---@field Positions TextureAtlasPosition
---@field AtlasTextures TextureAtlasPosition
ITextureAtlasAPI = {}
