---@meta Packet_FlipItemstacks
---@class Packet_FlipItemstacks: Object
---@field ctor fun(): Packet_FlipItemstacks
---@field SetSourceInventoryId fun(value: string): nil
---@field SetTargetInventoryId fun(value: string): nil
---@field SetSourceSlot fun(value: number): nil
---@field SetTargetSlot fun(value: number): nil
---@field SetSourceLastChanged fun(value: Int64): nil
---@field SetTargetLastChanged fun(value: Int64): nil
---@field SetSourceTabIndex fun(value: number): nil
---@field SetTargetTabIndex fun(value: number): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_FlipItemstacks = {}
