---@meta Packet_BlockEntitySerializer
---@class Packet_BlockEntitySerializer: Object
---@field ctor fun(): Packet_BlockEntitySerializer
---@field DeserializeLengthDelimitedNew fun(stream: CitoMemoryStream): Packet_BlockEntity
---@field DeserializeBuffer fun(buffer: number[], length: number, instance: Packet_BlockEntity): Packet_BlockEntity
---@field Deserialize fun(stream: CitoMemoryStream, instance: Packet_BlockEntity): Packet_BlockEntity
---@field DeserializeLengthDelimited fun(stream: CitoMemoryStream, instance: Packet_BlockEntity): Packet_BlockEntity
---@field Serialize fun(stream: CitoStream, instance: Packet_BlockEntity): nil
---@field SerializeToBytes fun(instance: Packet_BlockEntity): number[]
---@field SerializeLengthDelimited fun(stream: CitoStream, instance: Packet_BlockEntity): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_BlockEntitySerializer = {}
