---@meta BlockEntityBehavior
---@class BlockEntityBehavior: Object
---@field ctor fun(blockentity: BlockEntity): BlockEntityBehavior
---@field get_Pos fun(): BlockPos
---@field get_Block fun(): Block
---@field Initialize fun(api: ICoreAPI, properties: Jsontable): nil
---@field OnBlockRemoved fun(): nil
---@field OnBlockUnloaded fun(): nil
---@field OnBlockBroken fun(byPlayer: IPlayer): nil
---@field OnBlockPlaced fun(byItemStack: ItemStack): nil
---@field ToTreeAttributes fun(tree: ITreeAttribute): nil
---@field FromTreeAttributes fun(tree: ITreeAttribute, worldAccessForResolve: IWorldAccessor): nil
---@field OnReceivedClientPacket fun(fromPlayer: IPlayer, packetid: number, data: number[]): nil
---@field OnReceivedServerPacket fun(packetid: number, data: number[]): nil
---@field GetBlockInfo fun(forPlayer: IPlayer, dsc: stringBuilder): nil
---@field OnStoreCollectibleMappings fun(blockIdMapping: table<any, any>, itemIdMapping: table<any, any>): nil
---@field OnLoadCollectibleMappings fun(worldForNewMappings: IWorldAccessor, oldBlockIdMapping: table<any, any>, oldItemIdMapping: table<any, any>, schematicSeed: number): nil
---@overload fun(worldForNewMappings: IWorldAccessor, oldBlockIdMapping: table<any, any>, oldItemIdMapping: table<any, any>, schematicSeed: number, resolveImports: boolean): nil
---@field OnTesselation fun(mesher: ITerrainMeshPool, tessThreadTesselator: ITesselatorAPI): boolean
---@field OnPlacementBySchematic fun(api: ICoreServerAPI, blockAccessor: IBlockAccessor, pos: BlockPos, replaceBlocks: table<any, any>, centerrockblockid: number, layerBlock: Block, resolveImports: boolean): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field Pos BlockPos
---@field Block BlockPos
---@field Blockentity BlockPos
---@field properties BlockPos
---@field Api BlockPos
BlockEntityBehavior = {}
