---@meta MatrixToolsd
---@class MatrixToolsd: Object
---@field ctor fun(): MatrixToolsd
---@field Project fun(pos: Vec3d, projection: Double[], view: Double[], viewportWidth: number, viewportHeight: number): Vec3d
---@field MatFollowPlayer fun(m: Double[]): nil
---@field LoadPlayerFacingMatrix fun(m: Double[]): nil
---@field MatFacePlayer fun(m: Double[]): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
MatrixToolsd = {}
