---@meta Packet_WorldMetaDataSerializer
---@class Packet_WorldMetaDataSerializer: Object
---@field ctor fun(): Packet_WorldMetaDataSerializer
---@field DeserializeLengthDelimitedNew fun(stream: CitoMemoryStream): Packet_WorldMetaData
---@field DeserializeBuffer fun(buffer: number[], length: number, instance: Packet_WorldMetaData): Packet_WorldMetaData
---@field Deserialize fun(stream: CitoMemoryStream, instance: Packet_WorldMetaData): Packet_WorldMetaData
---@field DeserializeLengthDelimited fun(stream: CitoMemoryStream, instance: Packet_WorldMetaData): Packet_WorldMetaData
---@field Serialize fun(stream: CitoStream, instance: Packet_WorldMetaData): nil
---@field SerializeToBytes fun(instance: Packet_WorldMetaData): number[]
---@field SerializeLengthDelimited fun(stream: CitoStream, instance: Packet_WorldMetaData): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_WorldMetaDataSerializer = {}
