---@meta GltfAccessor
---@class GltfAccessor: Object
---@field ctor fun(): GltfAccessor
---@field get_BufferView fun(): Int64
---@field set_BufferView fun(value: Int64): nil
---@field get_ComponentType fun(): VertexAttribPointerany
---@field set_ComponentType fun(value: VertexAttribPointerany): nil
---@field get_Count fun(): number
---@field set_Count fun(value: number): nil
---@field get_Max fun(): Double[]
---@field set_Max fun(value: Double[]): nil
---@field get_Min fun(): Double[]
---@field set_Min fun(value: Double[]): nil
---@field get_Type fun(): EnumGltfAccessorany
---@field set_Type fun(value: EnumGltfAccessorany): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field BufferView Int64
---@field ComponentType Int64
---@field Count Int64
---@field Max Int64
---@field Min Int64
---@field Type Int64
GltfAccessor = {}
