---@meta IItemStack
---@class IItemStack
---@field get_Collectible fun(): Collectibletable
---@field get_Class fun(): EnumItemClass
---@field get_Item fun(): Item
---@field get_Block fun(): Block
---@field get_StackSize fun(): number
---@field set_StackSize fun(value: number): nil
---@field get_Id fun(): number
---@field get_Attributes fun(): ITreeAttribute
---@field set_Attributes fun(value: ITreeAttribute): nil
---@field Equals fun(worldForResolve: IWorldAccessor, sourceStack: ItemStack, ignoreAttributeSubTrees: string[]): boolean
---@field ToBytes fun(stream: BinaryWriter): nil
---@field FromBytes fun(stream: BinaryReader): nil
---@field MatchesSearchText fun(world: IWorldAccessor, searchText: string): boolean
---@field GetName fun(): string
---@field GetDescription fun(world: IWorldAccessor, inSlot: ItemSlot, debug: boolean): string
---@field Clone fun(): ItemStack
---@field Collectible Collectibletable
---@field Class Collectibletable
---@field Item Collectibletable
---@field Block Collectibletable
---@field StackSize Collectibletable
---@field Id Collectibletable
---@field Attributes Collectibletable
IItemStack = {}
