---@meta ActiveSlotChangeEventArgs
---@class ActiveSlotChangeEventArgs: Object
---@field ctor fun(from: number, to: number): ActiveSlotChangeEventArgs
---@field get_FromSlot fun(): number
---@field get_ToSlot fun(): number
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field FromSlot number
---@field ToSlot number
ActiveSlotChangeEventArgs = {}
