---@meta Mat3d
---@class Mat3d: Object
---@field ctor fun(): Mat3d
---@field Create fun(): Double[]
---@field FromMat4 fun(output: Double[], a: Double[]): Double[]
---@field CloneIt fun(a: Double[]): Double[]
---@field Copy fun(output: Double[], a: Double[]): Double[]
---@field Identity_ fun(output: Double[]): Double[]
---@field Transpose fun(output: Double[], a: Double[]): Double[]
---@field Invert fun(output: Double[], a: Double[]): Double[]
---@field Adjoint fun(output: Double[], a: Double[]): Double[]
---@field Determinant fun(a: Double[]): Double
---@field Multiply fun(output: Double[], a: Double[], b: Double[]): Double[]
---@field Mul fun(output: Double[], a: Double[], b: Double[]): Double[]
---@field Translate fun(output: Double[], a: Double[], v: Double[]): Double[]
---@field Rotate fun(output: Double[], a: Double[], rad: Double): Double[]
---@field Scale fun(output: Double[], a: Double[], v: Double[]): Double[]
---@field FromMat2d fun(output: Double[], a: Double[]): Double[]
---@field FromQuat fun(output: Double[], q: Double[]): Double[]
---@field NormalFromMat4 fun(output: Double[], a: Double[]): Double[]
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Mat3d = {}
