---@meta LimitedList`1
---@class LimitedList`1: Object
---@field ctor fun(maxCapacity: number): LimitedList`1
---@overload fun(maxCapacity: number, initialElements: any[]): LimitedList`1
---@field Add fun(key: TElem): nil
---@field get_Item fun(index: number): TElem
---@field SetCapacity fun(maxCapacity: number): nil
---@field Clear fun(): nil
---@field get_Count fun(): number
---@field RemoveAt fun(i: number): nil
---@field LastElement fun(): TElem
---@field IsFull fun(): boolean
---@field GetEnumerator fun(): IEnumerator
---@field ToArray fun(): TElem[]
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field Item TElem
---@field Count TElem
LimitedList`1 = {}
