---@meta ParticleRenderer2D
---@class ParticleRenderer2D: Object
---@field ctor fun(screenManager: ScreenManager, api: ICoreClientAPI, poolSize: number): ParticleRenderer2D
---@field Compose fun(texture: string): nil
---@field Spawn fun(prop: IParticlePropertiesProvider): nil
---@field Render fun(dt: Single): nil
---@field Dispose fun(): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
ParticleRenderer2D = {}
