---@meta BlockFacing
---@class BlockFacing: Object
---@field get_Flag fun(): number
---@field get_Index fun(): number
---@field get_MeshDataIndex fun(): number
---@field get_HorizontalAngleIndex fun(): number
---@field get_Normali fun(): Vec3i
---@field get_Normalf fun(): Vec3f
---@field get_Normald fun(): Vec3d
---@field get_Plane fun(): Cuboidf
---@field get_NormalByte fun(): number
---@field get_NormalPacked fun(): number
---@field get_NormalPackedFlags fun(): number
---@field get_PlaneCenter fun(): Vec3f
---@field get_Code fun(): string
---@field get_IsHorizontal fun(): boolean
---@field get_IsVertical fun(): boolean
---@field get_IsAxisNS fun(): boolean
---@field get_IsAxisWE fun(): boolean
---@field get_Axis fun(): EnumAxis
---@field get_Opposite fun(): BlockFacing
---@field GetOpposite fun(): BlockFacing
---@field GetCCW fun(): BlockFacing
---@field GetCW fun(): BlockFacing
---@field GetHorizontalRotated fun(angle: number): BlockFacing
---@field FaceWhenRotatedBy fun(radX: Single, radY: Single, radZ: Single): BlockFacing
---@field GetFaceBrightness fun(radX: Single, radY: Single, radZ: Single, BlockSideBrightnessByFacing: Single[]): Single
---@field IterateThruFacingOffsets fun(pos: BlockPos): nil
---@field FinishIteratingAllFaces fun(pos: BlockPos): nil
---@field GetFaceBrightness fun(matrix: Double[], BlockSideBrightnessByFacing: Single[]): Single
---@field IsAdjacent fun(facing: BlockFacing): boolean
---@field ToString fun(): string
---@field FromCode fun(code: string): BlockFacing
---@field FromFirstLetter fun(code: Char): BlockFacing
---@overload fun(code: string): BlockFacing
---@field FromNormal fun(vec: Vec3f): BlockFacing
---@overload fun(vec: Vec3i): BlockFacing
---@field FromVector fun(x: Double, y: Double, z: Double): BlockFacing
---@field FromFlag fun(flag: number): BlockFacing
---@field HorizontalFromAngle fun(radiant: Single): BlockFacing
---@field FlagContains fun(flag: number, facing: BlockFacing): boolean
---@field FlagContainsHorizontals fun(flag: number): boolean
---@field GetType fun(): any
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field Flag number
---@field Index number
---@field MeshDataIndex number
---@field HorizontalAngleIndex number
---@field Normali number
---@field Normalf number
---@field Normald number
---@field Plane number
---@field NormalByte number
---@field NormalPacked number
---@field NormalPackedFlags number
---@field PlaneCenter number
---@field Code number
---@field IsHorizontal number
---@field IsVertical number
---@field IsAxisNS number
---@field IsAxisWE number
---@field Axis number
---@field Opposite number
---@field HorizontalFlags number
---@field VerticalFlags number
---@field NORTH number
---@field EAST number
---@field SOUTH number
---@field WEST number
---@field UP number
---@field DOWN number
---@field ALLFACES number
---@field ALLNORMALI number
---@field AllVertexFlagsNormals number
---@field HORIZONTALS number
---@field HORIZONTAL_NORMALI number
---@field VERTICALS number
---@field HORIZONTALS_ANGLEORDER number
---@field NumberOfFaces number
---@field indexNORTH number
---@field indexEAST number
---@field indexSOUTH number
---@field indexWEST number
---@field indexUP number
---@field indexDOWN number
BlockFacing = {}
