---@meta Asset
---@class Asset: Object
---@field ctor fun(bytes: number[], Location: AssetLocation, origin: IAssetOrigin): Asset
---@overload fun(Location: AssetLocation): Asset
---@field get_Origin fun(): IAssetOrigin
---@field set_Origin fun(value: IAssetOrigin): nil
---@field get_Name fun(): string
---@field ToObject fun(settings: JsonSerializerSettings): T
---@field ToText fun(): string
---@field ToBitmap fun(api: ICoreClientAPI): BitmapRef
---@field IsLoaded fun(): boolean
---@field ToString fun(): string
---@field GetHashCode fun(): number
---@field Equals fun(obj: table): boolean
---@field BytesToString fun(data: number[]): string
---@field GetType fun(): any
---@field Origin IAssetOrigin
---@field Name IAssetOrigin
---@field Data IAssetOrigin
---@field Location IAssetOrigin
---@field FilePath IAssetOrigin
Asset = {}
