---@meta GltfTextureElement
---@class GltfTextureElement: Object
---@field ctor fun(): GltfTextureElement
---@field get_Source fun(): Int64
---@field set_Source fun(value: Int64): nil
---@field get_Sampler fun(): Int64
---@field set_Sampler fun(value: Int64): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field Source Int64
---@field Sampler Int64
GltfTextureElement = {}
