---@meta ChatCommandComparer
---@class ChatCommandComparer: Object
---@field ctor fun(): ChatCommandComparer
---@field get_Comparer fun(): ChatCommandComparer
---@field Equals fun(x: IChatCommand, y: IChatCommand): boolean
---@field GetHashCode fun(obj: IChatCommand): number
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@overload fun(): number
---@field Comparer ChatCommandComparer
ChatCommandComparer = {}
