---@meta FloatingSedimentParticles
---@class FloatingSedimentParticles: ParticlesProviderBase
---@field ctor fun(): FloatingSedimentParticles
---@field get_ParticleModel fun(): EnumParticleModel
---@field get_DieInLiquid fun(): boolean
---@field get_DieInAir fun(): boolean
---@field get_GravityEffect fun(): Single
---@field get_LifeLength fun(): Single
---@field get_SwimOnLiquid fun(): boolean
---@field get_Pos fun(): Vec3d
---@field get_Quantity fun(): Single
---@field get_Size fun(): Single
---@field get_VertexFlags fun(): number
---@field get_SizeEvolve fun(): EvolvingNatFloat
---@field get_OpacityEvolve fun(): EvolvingNatFloat
---@field GetVelocity fun(pos: Vec3d): Vec3f
---@field GetRgbaColor fun(capi: ICoreClientAPI): number
---@field get_Async fun(): boolean
---@field get_Bounciness fun(): Single
---@field set_Bounciness fun(value: Single): nil
---@field get_RandomVelocityChange fun(): boolean
---@field set_RandomVelocityChange fun(value: boolean): nil
---@field get_DieOnRainHeightmap fun(): boolean
---@field set_DieOnRainHeightmap fun(value: boolean): nil
---@field get_RedEvolve fun(): EvolvingNatFloat
---@field get_GreenEvolve fun(): EvolvingNatFloat
---@field get_BlueEvolve fun(): EvolvingNatFloat
---@field get_VelocityEvolve fun(): EvolvingNatFloat[]
---@field get_SelfPropelled fun(): boolean
---@field get_TerrainCollision fun(): boolean
---@field ToBytes fun(writer: BinaryWriter): nil
---@field FromBytes fun(reader: BinaryReader, resolver: IWorldAccessor): nil
---@field get_SecondarySpawnInterval fun(): Single
---@field get_SecondaryParticles fun(): IParticlePropertiesProvider[]
---@field get_DeathParticles fun(): IParticlePropertiesProvider[]
---@field BeginParticle fun(): nil
---@field PrepareForSecondarySpawn fun(particleInstance: ParticleBase): nil
---@field Init fun(api: ICoreAPI): nil
---@field get_ParentVelocity fun(): Vec3f
---@field set_ParentVelocity fun(value: Vec3f): nil
---@field get_WindAffected fun(): boolean
---@field set_WindAffected fun(value: boolean): nil
---@field get_ParentVelocityWeight fun(): Single
---@field set_ParentVelocityWeight fun(value: Single): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field ParticleModel EnumParticleModel
---@field DieInLiquid EnumParticleModel
---@field DieInAir EnumParticleModel
---@field GravityEffect EnumParticleModel
---@field LifeLength EnumParticleModel
---@field SwimOnLiquid EnumParticleModel
---@field Pos EnumParticleModel
---@field Quantity EnumParticleModel
---@field Size EnumParticleModel
---@field VertexFlags EnumParticleModel
---@field SizeEvolve EnumParticleModel
---@field OpacityEvolve EnumParticleModel
---@field Async EnumParticleModel
---@field Bounciness EnumParticleModel
---@field RandomVelocityChange EnumParticleModel
---@field DieOnRainHeightmap EnumParticleModel
---@field RedEvolve EnumParticleModel
---@field GreenEvolve EnumParticleModel
---@field BlueEvolve EnumParticleModel
---@field VelocityEvolve EnumParticleModel
---@field SelfPropelled EnumParticleModel
---@field TerrainCollision EnumParticleModel
---@field SecondarySpawnInterval EnumParticleModel
---@field SecondaryParticles EnumParticleModel
---@field DeathParticles EnumParticleModel
---@field ParentVelocity EnumParticleModel
---@field WindAffected EnumParticleModel
---@field ParentVelocityWeight EnumParticleModel
---@field BasePos EnumParticleModel
---@field AddPos EnumParticleModel
---@field AddVelocity EnumParticleModel
---@field SedimentBlock EnumParticleModel
---@field SedimentPos EnumParticleModel
---@field quantity EnumParticleModel
---@field waterColor EnumParticleModel
FloatingSedimentParticles = {}
