---@meta ClientGameCalendar
---@class ClientGameCalendar: GameCalendar
---@field get_DayLightStrength fun(): Single
---@field set_DayLightStrength fun(value: Single): nil
---@field get_MoonLightStrength fun(): Single
---@field set_MoonLightStrength fun(value: Single): nil
---@field get_SunLightStrength fun(): Single
---@field set_SunLightStrength fun(value: Single): nil
---@field get_SunColor fun(): Vec3f
---@field get_ReflectColor fun(): Vec3f
---@field get_SunLightColor fun(): Color
---@field Update fun(): nil
---@field get_TimeSpeedModifiers fun(): table<any, any>
---@field set_TimeSpeedModifiers fun(value: table<any, any>): nil
---@field get_SpeedOfTime fun(): Single
---@field get_CalendarSpeedMul fun(): Single
---@field set_CalendarSpeedMul fun(value: Single): nil
---@field get_Timelapse fun(): Single
---@field set_Timelapse fun(value: Single): nil
---@field get_DaysPerMonth fun(): number
---@field set_DaysPerMonth fun(value: number): nil
---@field get_DaysPerYear fun(): number
---@field get_DayOfMonth fun(): number
---@field get_MonthsPerYear fun(): number
---@field get_FullHourOfDay fun(): number
---@field get_HourOfDay fun(): Single
---@field get_ElapsedSeconds fun(): Int64
---@field get_ElapsedHours fun(): Double
---@field get_ElapsedDays fun(): Double
---@field get_TotalSeconds fun(): Int64
---@field get_TotalHours fun(): Double
---@field get_TotalDays fun(): Double
---@field get_DayOfYear fun(): number
---@field get_DayOfYearf fun(): Single
---@field get_Year fun(): number
---@field get_Month fun(): number
---@field get_Monthf fun(): Single
---@field get_MonthName fun(): EnumMonth
---@field get_YearRel fun(): Single
---@field get_MoonPhase fun(): EnumMoonPhase
---@field get_MoonPhaseExact fun(): Double
---@field get_Dusk fun(): boolean
---@field get_MoonPhaseBrightness fun(): Single
---@field get_MoonSize fun(): Single
---@field get_SunsetMod fun(): Single
---@field get_IsRunning fun(): boolean
---@field get_OnGetSolarSphericalCoords fun(): SolarSphericalCoordsDelegate
---@field set_OnGetSolarSphericalCoords fun(value: SolarSphericalCoordsDelegate): nil
---@field get_OnGetHemisphere fun(): HemisphereDelegate
---@field set_OnGetHemisphere fun(value: HemisphereDelegate): nil
---@field get_OnGetLatitude fun(): GetLatitudeDelegate
---@field set_OnGetLatitude fun(value: GetLatitudeDelegate): nil
---@field get_SeasonOverride fun(): Nullable`1
---@field set_SeasonOverride fun(value: Nullable`1): nil
---@field RealSecondsToGameSeconds fun(seconds: Single): Single
---@field SetSeasonOverride fun(seasonRel: Nullable`1): nil
---@field SetTimeSpeedModifier fun(name: string, speed: Single): nil
---@field RemoveTimeSpeedModifier fun(name: string): nil
---@field SetTotalSeconds fun(totalSecondsNow: Int64, totalSecondsStart: Int64): nil
---@field Start fun(): nil
---@field Stop fun(): nil
---@field Tick fun(): nil
---@field SetDayTime fun(wantHourOfDay: Single): nil
---@field SetMonth fun(month: Single): nil
---@field Add fun(hours: Single): nil
---@field GetDayLightStrength fun(x: Double, z: Double): Single
---@overload fun(pos: BlockPos): Single
---@field GetSeason fun(pos: BlockPos): EnumSeason
---@field GetSeasonRel fun(pos: BlockPos): Single
---@field GetHemisphere fun(pos: BlockPos): EnumHemisphere
---@field getSunlightPixelRel fun(relx: Single, rely: Single): Color
---@field ToPacket fun(): Packet_Server
---@field PrettyDate fun(): string
---@field UpdateFromPacket fun(packet: Packet_Server): nil
---@field BitmapCreateFromPng fun(asset: IAsset): BitmapRef
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field DayLightStrength Single
---@field MoonLightStrength Single
---@field SunLightStrength Single
---@field SunColor Single
---@field ReflectColor Single
---@field SunLightColor Single
---@field TimeSpeedModifiers Single
---@field SpeedOfTime Single
---@field CalendarSpeedMul Single
---@field Timelapse Single
---@field DaysPerMonth Single
---@field DaysPerYear Single
---@field DayOfMonth Single
---@field MonthsPerYear Single
---@field FullHourOfDay Single
---@field HourOfDay Single
---@field ElapsedSeconds Single
---@field ElapsedHours Single
---@field ElapsedDays Single
---@field TotalSeconds Single
---@field TotalHours Single
---@field TotalDays Single
---@field DayOfYear Single
---@field DayOfYearf Single
---@field Year Single
---@field Month Single
---@field Monthf Single
---@field MonthName Single
---@field YearRel Single
---@field MoonPhase Single
---@field MoonPhaseExact Single
---@field Dusk Single
---@field MoonPhaseBrightness Single
---@field MoonSize Single
---@field SunsetMod Single
---@field IsRunning Single
---@field OnGetSolarSphericalCoords Single
---@field OnGetHemisphere Single
---@field OnGetLatitude Single
---@field SeasonOverride Single
---@field SunPosition Single
---@field MoonPosition Single
---@field SunPositionNormalized Single
---@field ClientCalendarStartingSeconds Single
---@field HoursPerDay Single
---@field MoonOrbitDays Single
---@field DayLengthInRealLifeSeconds Single
---@field LastIngameSecond Single
---@field sunLightTextureSize Single
---@field sunLightTexture Single
ClientGameCalendar = {}
