---@meta ServerMapRegion
---@class ServerMapRegion: Object
---@field ctor fun(): ServerMapRegion
---@field get_OreMapVerticalDistortTop fun(): IntDataMap2D
---@field set_OreMapVerticalDistortTop fun(value: IntDataMap2D): nil
---@field get_OreMapVerticalDistortBottom fun(): IntDataMap2D
---@field set_OreMapVerticalDistortBottom fun(value: IntDataMap2D): nil
---@field get_BlockPatchMaps fun(): table<any, any>
---@field set_BlockPatchMaps fun(value: table<any, any>): nil
---@field CreateNew fun(): ServerMapRegion
---@field AddGeneratedStructure fun(newStructure: GeneratedStructure): nil
---@field FromBytes fun(serializedMapRegion: number[]): ServerMapRegion
---@field ToBytes fun(): number[]
---@field ToPacket fun(regionX: number, regionZ: number): Packet_Server
---@overload fun(map: IntDataMap2D): Packet_IntMap
---@field SetModdata fun(key: string, data: number[]): nil
---@field RemoveModdata fun(key: string): nil
---@field GetModdata fun(key: string): number[]
---@overload fun(key: string, data: T): nil
---@overload fun(key: string): T
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field OreMapVerticalDistortTop IntDataMap2D
---@field OreMapVerticalDistortBottom IntDataMap2D
---@field BlockPatchMaps IntDataMap2D
---@field LandformMap IntDataMap2D
---@field ForestMap IntDataMap2D
---@field ClimateMap IntDataMap2D
---@field GeologicProvinceMap IntDataMap2D
---@field BushMap IntDataMap2D
---@field FlowerMap IntDataMap2D
---@field OreMaps IntDataMap2D
---@field ModData IntDataMap2D
---@field ModMaps IntDataMap2D
---@field GeneratedStructures IntDataMap2D
---@field RockStrata IntDataMap2D
---@field BeachMap IntDataMap2D
---@field UpheavelMap IntDataMap2D
---@field OceanMap IntDataMap2D
---@field DirtyForSaving IntDataMap2D
---@field NeighbourRegionsChecked IntDataMap2D
---@field loadedTotalMs IntDataMap2D
ServerMapRegion = {}
