---@meta BoolArrayAttribute
---@class BoolArrayAttribute: ArrayAttribute`1
---@field ctor fun(): BoolArrayAttribute
---@overload fun(value: boolean[]): BoolArrayAttribute
---@field ToBytes fun(stream: BinaryWriter): nil
---@field FromBytes fun(stream: BinaryReader): nil
---@field GetAttributeId fun(): number
---@field Clone fun(): IAttribute
---@field Equals fun(worldForResolve: IWorldAccessor, attr: IAttribute): boolean
---@field GetValue fun(): table
---@field ToJsonToken fun(): string
---@field ToString fun(): string
---@field GetHashCode fun(): number
---@field GetType fun(): any
---@field Equals fun(obj: table): boolean
BoolArrayAttribute = {}
