---@meta BlockSounds
---@class BlockSounds: Object
---@field ctor fun(): BlockSounds
---@field get_Walk fun(): AssetLocation
---@field set_Walk fun(value: AssetLocation): nil
---@field get_Inside fun(): AssetLocation
---@field set_Inside fun(value: AssetLocation): nil
---@field get_Break fun(): AssetLocation
---@field set_Break fun(value: AssetLocation): nil
---@field get_Place fun(): AssetLocation
---@field set_Place fun(value: AssetLocation): nil
---@field get_Hit fun(): AssetLocation
---@field set_Hit fun(value: AssetLocation): nil
---@field get_ByTool fun(): table<any, any>
---@field set_ByTool fun(value: table<any, any>): nil
---@field Clone fun(): BlockSounds
---@field GetBreakSound fun(byPlayer: IPlayer): AssetLocation
---@field GetHitSound fun(byPlayer: IPlayer): AssetLocation
---@overload fun(tool: EnumTool): AssetLocation
---@overload fun(tool: EnumTool): AssetLocation
---@field OnDeserializedMethod fun(context: StreamingContext): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field Walk AssetLocation
---@field Inside AssetLocation
---@field Break AssetLocation
---@field Place AssetLocation
---@field Hit AssetLocation
---@field ByTool AssetLocation
---@field Ambient AssetLocation
---@field AmbientBlockCount AssetLocation
BlockSounds = {}
