---@meta Page
---@class Page: Object
---@field ctor fun(): Page
---@field bos fun(): number
---@field eos fun(): number
---@field granulepos fun(): Int64
---@field serialno fun(): number
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Page = {}
