---@meta SettingsBaseNoObf
---@class SettingsBaseNoObf: Object
---@field set_ShouldTriggerWatchers fun(value: boolean): nil
---@field get_Bool fun(): ISettingsClass`1
---@field get_Int fun(): ISettingsClass`1
---@field get_Float fun(): ISettingsClass`1
---@field get_String fun(): ISettingsClass`1
---@field get_Strings fun(): ISettingsClass`1
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field ShouldTriggerWatchers boolean
---@field Bool boolean
---@field Int boolean
---@field Float boolean
---@field String boolean
---@field Strings boolean
---@field OtherDirty boolean
SettingsBaseNoObf = {}
