---@meta ClientEventManager
---@class ClientEventManager: EventManager
---@field ctor fun(game: ClientMain): ClientEventManager
---@field get_Logger fun(): ILogger
---@field get_CommandPrefix fun(): string
---@field get_InWorldEllapsedMs fun(): Int64
---@field add_OnHighlightBlocks fun(value: HighlightBlocksDelegate): nil
---@field remove_OnHighlightBlocks fun(value: HighlightBlocksDelegate): nil
---@field add_OnUpdateLighting fun(value: UpdateLightingDelegate): nil
---@field remove_OnUpdateLighting fun(value: UpdateLightingDelegate): nil
---@field add_OnChunkLoaded fun(value: ChunkLoadedDelegate): nil
---@field remove_OnChunkLoaded fun(value: ChunkLoadedDelegate): nil
---@field add_OnReloadShapes fun(value: Action): nil
---@field remove_OnReloadShapes fun(value: Action): nil
---@field add_OnReloadTextures fun(value: Action): nil
---@field remove_OnReloadTextures fun(value: Action): nil
---@field add_InGameError fun(value: IngameErrorDelegate): nil
---@field remove_InGameError fun(value: IngameErrorDelegate): nil
---@field add_InGameDiscovery fun(value: IngameDiscoveryDelegate): nil
---@field remove_InGameDiscovery fun(value: IngameDiscoveryDelegate): nil
---@field add_ColorPresetChanged fun(value: Action): nil
---@field remove_ColorPresetChanged fun(value: Action): nil
---@field RegisterRenderer fun(handler: any`1, stage: EnumRenderStage, profilingName: string, renderOrder: Double): nil
---@overload fun(handler: IRenderer, stage: EnumRenderStage, profilingName: string): nil
---@field UnregisterRenderer fun(handler: IRenderer, stage: EnumRenderStage): nil
---@field TriggerHighlightBlocks fun(player: IPlayer, slotId: number, blocks: any[], colors: any[], mode: EnumHighlightBlocksMode, shape: EnumHighlightShape, scale: Single): nil
---@field TriggerRenderStage fun(stage: EnumRenderStage, dt: Single): nil
---@field TriggerLightingUpdate fun(oldBlockId: number, newBlockId: number, pos: BlockPos, blockUpdatesBulk: table<any, any>): nil
---@field TriggerChunkLoaded fun(chunkpos: Vec3i): nil
---@field RegisterReloadShaders fun(handler: ActionBoolReturn): nil
---@field UnregisterReloadShaders fun(handler: ActionBoolReturn): nil
---@field RegisterOnChunkRetesselated fun(chunkPos: Vec3i, atQuantityDrawn: number, listener: Action): nil
---@field TriggerChunkRetesselated fun(chunkPos: Vec3i, chunk: ClientChunk): nil
---@field TriggerDialogOpened fun(dialog: GuiDialog): nil
---@field TriggerDialogClosed fun(dialog: GuiDialog): nil
---@field TriggerGameWindowFocus fun(focus: boolean): nil
---@field TriggerNewModChatLine fun(groupid: number, message: string, chattype: EnumChatany, data: string): nil
---@field TriggerNewClientChatLine fun(groupid: number, message: string, chattype: EnumChatany, data: string): nil
---@field TriggerIngameError fun(sender: table, errorCode: string, text: string): nil
---@field TriggerIngameDiscovery fun(sender: table, errorCode: string, text: string): nil
---@field TriggerColorPresetChanged fun(): nil
---@field TriggerNewServerChatLine fun(groupid: number, message: string, chattype: EnumChatany, data: string): nil
---@field TriggerBeforeActiveSlotChanged fun(game: ClientMain, fromSlot: number, toSlot: number): boolean
---@field TriggerAfterActiveSlotChanged fun(game: ClientMain, fromSlot: number, toSlot: number): nil
---@field TriggerBlockBreaking fun(blockDamage: BlockDamage): nil
---@field TriggerBlockBroken fun(blockDamage: BlockDamage): nil
---@field TriggerPlayerModeChange fun(): nil
---@field TriggerReloadShapes fun(): nil
---@field TriggerReloadTextures fun(): nil
---@field TriggerReloadShaders fun(): boolean
---@field TriggerEntitySpawn fun(entity: Entity): nil
---@field TriggerEntityLoaded fun(entity: Entity): nil
---@field TriggerEntityDespawn fun(entity: Entity, despawnReason: EntityDespawnData): nil
---@field RegisterPlayerPropertyChangedWatcher fun(property: EnumProperty, handler: OnPlayerPropertyChanged): nil
---@field HasPrivilege fun(playerUid: string, privilegecode: string): boolean
---@field TriggerOnMouseEnterSlot fun(game: ClientMain, slot: ItemSlot): nil
---@field TriggerOnMouseLeaveSlot fun(game: ClientMain, itemSlot: ItemSlot): nil
---@field add_OnGetClimate fun(value: OnGetClimateDelegate): nil
---@field remove_OnGetClimate fun(value: OnGetClimateDelegate): nil
---@field add_OnGetWindSpeed fun(value: OnGetWindSpeedDelegate): nil
---@field remove_OnGetWindSpeed fun(value: OnGetWindSpeedDelegate): nil
---@field TriggerOnGetClimate fun(climate: ClimateCondition&, pos: BlockPos, mode: EnumGetClimateMode, totalDays: Double): nil
---@field TriggerOnGetWindSpeed fun(pos: Vec3d, windSpeed: Vec3d&): nil
---@field TriggerGameTick fun(ellapsedMilliseconds: Int64, world: IWorldAccessor): nil
---@field TriggerGameTickDebug fun(ellapsedMilliseconds: Int64, world: IWorldAccessor): nil
---@field AddGameTickListener fun(handler: any`1, millisecondInterval: number, initialDelayOffsetMs: number): Int64
---@overload fun(handler: any`1, errorHandler: any`1, millisecondInterval: number, initialDelayOffsetMs: number): Int64
---@overload fun(handler: Action`3, pos: BlockPos, millisecondInterval: number, initialDelayOffsetMs: number): Int64
---@field AddDelayedCallback fun(handler: any`1, callAfterEllapsedMS: Int64): Int64
---@overload fun(handler: Action`3, pos: BlockPos, callAfterEllapsedMS: Int64): Int64
---@field RemoveDelayedCallback fun(listenerId: Int64): nil
---@field RemoveGameTickListener fun(listenerId: Int64): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field Logger ILogger
---@field CommandPrefix ILogger
---@field InWorldEllapsedMs ILogger
---@field OnHighlightBlocks ILogger
---@field OnUpdateLighting ILogger
---@field OnChunkLoaded ILogger
---@field OnReloadShapes ILogger
---@field OnReloadTextures ILogger
---@field InGameError ILogger
---@field InGameDiscovery ILogger
---@field ColorPresetChanged ILogger
---@field OnGetClimate ILogger
---@field OnGetWindSpeed ILogger
---@field OnAmbientSoundsScanComplete ILogger
---@field CurrentTrackSupplier ILogger
---@field TrackStarter ILogger
---@field OnChunkRetesselated ILogger
---@field OnGameWindowFocus ILogger
---@field OnDialogOpened ILogger
---@field OnDialogClosed ILogger
---@field OnUnBreakingBlock ILogger
---@field OnPlayerBreakingBlock ILogger
---@field OnPlayerBrokenBlock ILogger
---@field OnBlockChanged ILogger
---@field OnPlayerModeChange ILogger
---@field OnReloadShaders ILogger
---@field OnEntitySpawn ILogger
---@field OnEntityLoaded ILogger
---@field OnEntityDespawn ILogger
---@field OnPlayerDeath ILogger
---@field OnPlayerPropertyChanged ILogger
---@field OnActiveSlotChanged ILogger
---@field OnNewServerToClientChatLine ILogger
---@field OnNewClientToServerChatLine ILogger
---@field OnNewClientOnlyChatLine ILogger
---@field EventBusListeners ILogger
---@field renderersByStage ILogger
ClientEventManager = {}
