---@meta Packet_ServerIdentification
---@class Packet_ServerIdentification: Object
---@field ctor fun(): Packet_ServerIdentification
---@field SetNetworkVersion fun(value: string): nil
---@field SetGameVersion fun(value: string): nil
---@field SetServerName fun(value: string): nil
---@field SetMapSizeX fun(value: number): nil
---@field SetMapSizeY fun(value: number): nil
---@field SetMapSizeZ fun(value: number): nil
---@field SetRegionMapSizeX fun(value: number): nil
---@field SetRegionMapSizeY fun(value: number): nil
---@field SetRegionMapSizeZ fun(value: number): nil
---@field SetDisableShadows fun(value: number): nil
---@field SetPlayerAreaSize fun(value: number): nil
---@field SetSeed fun(value: number): nil
---@field SetPlayStyle fun(value: string): nil
---@field SetRequireRemapping fun(value: number): nil
---@field GetMods fun(): Packet_ModId[]
---@field SetMods fun(value: Packet_ModId[], count: number, length: number): nil
---@overload fun(value: Packet_ModId[]): nil
---@field GetModsCount fun(): number
---@field ModsAdd fun(value: Packet_ModId): nil
---@field SetWorldConfiguration fun(value: number[]): nil
---@field SetSavegameIdentifier fun(value: string): nil
---@field SetPlayListCode fun(value: string): nil
---@field GetServerModIdBlackList fun(): string[]
---@field SetServerModIdBlackList fun(value: string[], count: number, length: number): nil
---@overload fun(value: string[]): nil
---@field GetServerModIdBlackListCount fun(): number
---@field ServerModIdBlackListAdd fun(value: string): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_ServerIdentification = {}
