---@meta WorldConfig
---@class WorldConfig: Object
---@field ctor fun(mods: any[]): WorldConfig
---@field get_PlayStyles fun(): any[]
---@field get_CurrentPlayStyle fun(): PlayStyle
---@field get_CurrentPlayStyleIndex fun(): number
---@field get_WorldConfigsPlaystyle fun(): table<any, any>
---@field get_WorldConfigsCustom fun(): table<any, any>
---@field get_Jworldconfig fun(): Jsontable
---@field get_Item fun(code: string): WorldConfigurationValue
---@field LoadPlayStyles fun(): nil
---@field selectPlayStyle fun(index: number): nil
---@overload fun(playstylecode: string): nil
---@field updateJWorldConfig fun(): nil
---@field allDefaultValues fun(mods: any[]): Jsontable
---@field ApplyConfigs fun(inputElements: any[]): nil
---@field ToRichText fun(withCustomConfigs: boolean): string
---@overload fun(playstyle: PlayStyle, withCustomConfigs: boolean): string
---@field ToJson fun(): string
---@field FromJson fun(json: string): nil
---@field Clone fun(): WorldConfig
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field PlayStyles any[]
---@field CurrentPlayStyle any[]
---@field CurrentPlayStyleIndex any[]
---@field WorldConfigsPlaystyle any[]
---@field WorldConfigsCustom any[]
---@field Jworldconfig any[]
---@field Item any[]
---@field MapsizeY any[]
---@field Seed any[]
---@field IsNewWorld any[]
WorldConfig = {}
