---@meta ShaderProgramSky
---@class ShaderProgramSky: ShaderProgram
---@field ctor fun(): ShaderProgramSky
---@field set_FogDensityIn fun(value: Single): nil
---@field set_FogMinIn fun(value: Single): nil
---@field set_DayLight fun(value: Single): nil
---@field set_HorizonFog fun(value: Single): nil
---@field set_PlayerPos fun(value: Vec3f): nil
---@field set_SunPosition fun(value: Vec3f): nil
---@field set_FlatFogDensity fun(value: Single): nil
---@field set_FlatFogStart fun(value: Single): nil
---@field set_ViewDistance fun(value: Single): nil
---@field set_ViewDistanceLod0 fun(value: Single): nil
---@field set_ZNear fun(value: Single): nil
---@field set_ZFar fun(value: Single): nil
---@field set_LightPosition fun(value: Vec3f): nil
---@field set_ShadowIntensity fun(value: Single): nil
---@field set_ShadowMapFar2D fun(value: number): nil
---@field set_ShadowMapWidthInv fun(value: Single): nil
---@field set_ShadowMapHeightInv fun(value: Single): nil
---@field set_ShadowMapNear2D fun(value: number): nil
---@field set_WindWaveCounter fun(value: Single): nil
---@field set_GlitchStrength fun(value: Single): nil
---@field set_PlayerToSealevelOffset fun(value: Single): nil
---@field set_DitherSeed fun(value: number): nil
---@field set_HorizontalResolution fun(value: number): nil
---@field set_FogWaveCounter fun(value: Single): nil
---@field set_Glow2D fun(value: number): nil
---@field set_Sky2D fun(value: number): nil
---@field set_SunsetMod fun(value: Single): nil
---@field set_RgbaFogIn fun(value: Vec4f): nil
---@field set_RgbaAmbientIn fun(value: Vec3f): nil
---@field set_ProjectionMatrix fun(value: Single[]): nil
---@field set_ModelViewMatrix fun(value: Single[]): nil
---@field set_ShadowRangeFar fun(value: Single): nil
---@field set_ToShadowMapSpaceMatrixFar fun(value: Single[]): nil
---@field set_ShadowRangeNear fun(value: Single): nil
---@field set_ToShadowMapSpaceMatrixNear fun(value: Single[]): nil
---@field set_GlitchStrengthFL fun(value: Single): nil
---@field set_NightVisionStrength fun(value: Single): nil
---@field PointLightsArray fun(count: number, values: Single[]): nil
---@field PointLightColorsArray fun(count: number, values: Single[]): nil
---@field set_PointLightQuantity fun(value: number): nil
---@field Compile fun(): boolean
---@field get_Disposed fun(): boolean
---@field get_ClampTexturesToEdge fun(): boolean
---@field set_ClampTexturesToEdge fun(value: boolean): nil
---@field get_LoadError fun(): boolean
---@field set_LoadError fun(value: boolean): nil
---@field SetCustomSampler fun(uniformName: string, isLinear: boolean): nil
---@field Uniform fun(uniformName: string, value: Single): nil
---@overload fun(uniformName: string, value: number): nil
---@overload fun(uniformName: string, value: Vec2f): nil
---@overload fun(uniformName: string, value: Vec3f): nil
---@overload fun(uniformName: string, value: Vec3i): nil
---@field Uniforms2 fun(uniformName: string, count: number, values: Single[]): nil
---@field Uniforms3 fun(uniformName: string, count: number, values: Single[]): nil
---@field Uniform fun(uniformName: string, value: Vec4f): nil
---@field Uniforms4 fun(uniformName: string, count: number, values: Single[]): nil
---@field UniformMatrix fun(uniformName: string, matrix: Single[]): nil
---@overload fun(uniformName: string, matrix: Matrix4&): nil
---@field HasUniform fun(uniformName: string): boolean
---@field BindTexture2D fun(samplerName: string, textureId: number, textureNumber: number): nil
---@overload fun(samplerName: string, textureId: number): nil
---@field BindTextureCube fun(samplerName: string, textureId: number, textureNumber: number): nil
---@field UniformMatrices4x3 fun(uniformName: string, count: number, matrix: Single[]): nil
---@field UniformMatrices fun(uniformName: string, count: number, matrix: Single[]): nil
---@field Use fun(): nil
---@field Stop fun(): nil
---@field Dispose fun(): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field FogDensityIn Single
---@field FogMinIn Single
---@field DayLight Single
---@field HorizonFog Single
---@field PlayerPos Single
---@field SunPosition Single
---@field FlatFogDensity Single
---@field FlatFogStart Single
---@field ViewDistance Single
---@field ViewDistanceLod0 Single
---@field ZNear Single
---@field ZFar Single
---@field LightPosition Single
---@field ShadowIntensity Single
---@field ShadowMapFar2D Single
---@field ShadowMapWidthInv Single
---@field ShadowMapHeightInv Single
---@field ShadowMapNear2D Single
---@field WindWaveCounter Single
---@field GlitchStrength Single
---@field PlayerToSealevelOffset Single
---@field DitherSeed Single
---@field HorizontalResolution Single
---@field FogWaveCounter Single
---@field Glow2D Single
---@field Sky2D Single
---@field SunsetMod Single
---@field RgbaFogIn Single
---@field RgbaAmbientIn Single
---@field ProjectionMatrix Single
---@field ModelViewMatrix Single
---@field ShadowRangeFar Single
---@field ToShadowMapSpaceMatrixFar Single
---@field ShadowRangeNear Single
---@field ToShadowMapSpaceMatrixNear Single
---@field GlitchStrengthFL Single
---@field NightVisionStrength Single
---@field PointLightQuantity Single
---@field Disposed Single
---@field ClampTexturesToEdge Single
---@field LoadError Single
---@field attributes Single
---@field LoadFromFile Single
---@field AssetDomain Single
---@field PassId Single
---@field ProgramId Single
---@field PassName Single
---@field VertexShader Single
---@field GeometryShader Single
---@field FragmentShader Single
---@field uniformLocations Single
---@field textureLocations Single
---@field clampTToEdge Single
---@field includes Single
---@field customSamplers Single
ShaderProgramSky = {}
