---@meta MusicTrack
---@class MusicTrack: Object
---@field ctor fun(): MusicTrack
---@field get_IsActive fun(): boolean
---@field get_Priority fun(): Single
---@field set_Priority fun(value: Single): nil
---@field get_Name fun(): string
---@field Stop fun(): nil
---@field Initialize fun(assetManager: IAssetManager, capi: ICoreClientAPI, musicEngine: IMusicEngine): nil
---@field ShouldPlay fun(props: TrackedPlayerProperties, conds: ClimateCondition, pos: BlockPos): boolean
---@field BeginPlay fun(props: TrackedPlayerProperties): nil
---@field ContinuePlay fun(dt: Single, props: TrackedPlayerProperties): boolean
---@field FadeOut fun(seconds: Single, onFadedOut: Action): nil
---@field UpdateVolume fun(): nil
---@field FastForward fun(seconds: Single): nil
---@field BeginSort fun(): nil
---@field get_PositionString fun(): string
---@field get_StartPriority fun(): Single
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field IsActive boolean
---@field Priority boolean
---@field Name boolean
---@field PositionString boolean
---@field StartPriority boolean
---@field Location boolean
---@field loading boolean
---@field ManualDispose boolean
---@field Sound boolean
MusicTrack = {}
