---@meta TextBackground
---@class TextBackground: Object
---@field ctor fun(): TextBackground
---@field set_Padding fun(value: number): nil
---@field Clone fun(): TextBackground
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field Padding number
---@field HorPadding number
---@field VerPadding number
---@field Radius number
---@field FillColor number
---@field BorderColor number
---@field BorderWidth number
---@field Shade number
---@field ShadeColor number
TextBackground = {}
