---@meta Packet_TransitionableProperties
---@class Packet_TransitionableProperties: Object
---@field ctor fun(): Packet_TransitionableProperties
---@field SetFreshHours fun(value: Packet_NatFloat): nil
---@field SetTransitionHours fun(value: Packet_NatFloat): nil
---@field SetTransitionedStack fun(value: number[]): nil
---@field SetTransitionRatio fun(value: number): nil
---@field SetType fun(value: number): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_TransitionableProperties = {}
