---@meta GltfTesselator
---@class GltfTesselator: Object
---@field ctor fun(): GltfTesselator
---@field Load fun(asset: Gltfany, mesh: MeshData&, pos: TextureAtlasPosition, generalGlowLevel: number, climateColorMapIndex: number, seasonColorMapIndex: number, renderPass: Int16, bakedTextures: number[][][]&): nil
---@field ParseGltf fun(gltf: Gltfany, pos: TextureAtlasPosition, generalGlowLevel: number, climateColorMapIndex: number, seasonColorMapIndex: number, renderPass: Int16, bakedTextures: number[][][]&): nil
---@field BuildMeshDataPart fun(node: GltfNode, pos: TextureAtlasPosition, climateColorMapIndex: number, seasonColorMapIndex: number, renderPass: Int16, colorFactor: Single[], pbrFactor: Single[]): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
GltfTesselator = {}
