---@meta FrustumCulling
---@class FrustumCulling: Object
---@field ctor fun(): FrustumCulling
---@field UpdateViewDistance fun(newValue: number): nil
---@field SphereInFrustum fun(x: Double, y: Double, z: Double, radius: Double): boolean
---@field InFrustum fun(sphere: Sphere): boolean
---@field InFrustumShadowPass fun(sphere: Sphere): boolean
---@field InFrustumAndRange fun(sphere: Sphere, nowVisible: boolean, lodLevel: number): boolean
---@field CalcFrustumEquations fun(playerPos: BlockPos, projectionMatrix: Double[], cameraMatrix: Double[]): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
FrustumCulling = {}
