---@meta IAnimator
---@class IAnimator
---@field get_Matrices4x3 fun(): Single[]
---@field get_ActiveAnimationCount fun(): number
---@field get_RunningAnimations fun(): RunningAnimation[]
---@field GetAnimationState fun(code: string): RunningAnimation
---@field get_CalculateMatrices fun(): boolean
---@field set_CalculateMatrices fun(value: boolean): nil
---@field GetAttachmentPointPose fun(code: string): AttachmentPointAndPose
---@field GetPosebyName fun(name: string, stringComparison: stringComparison): ElementPose
---@field OnFrame fun(activeAnimationsByAnimCode: table<any, any>, dt: Single): nil
---@field DumpCurrentState fun(): string
---@field Matrices4x3 Single[]
---@field ActiveAnimationCount Single[]
---@field RunningAnimations Single[]
---@field CalculateMatrices Single[]
IAnimator = {}
