---@meta Packet_ItemType
---@class Packet_ItemType: Object
---@field ctor fun(): Packet_ItemType
---@field SetItemId fun(value: number): nil
---@field SetMaxStackSize fun(value: number): nil
---@field SetCode fun(value: string): nil
---@field GetBehaviors fun(): Packet_Behavior[]
---@field SetBehaviors fun(value: Packet_Behavior[], count: number, length: number): nil
---@overload fun(value: Packet_Behavior[]): nil
---@field GetBehaviorsCount fun(): number
---@field BehaviorsAdd fun(value: Packet_Behavior): nil
---@field GetCompositeTextures fun(): Packet_CompositeTexture[]
---@field SetCompositeTextures fun(value: Packet_CompositeTexture[], count: number, length: number): nil
---@overload fun(value: Packet_CompositeTexture[]): nil
---@field GetCompositeTexturesCount fun(): number
---@field CompositeTexturesAdd fun(value: Packet_CompositeTexture): nil
---@field SetDurability fun(value: number): nil
---@field GetMiningmaterial fun(): number[]
---@field SetMiningmaterial fun(value: number[], count: number, length: number): nil
---@overload fun(value: number[]): nil
---@field GetMiningmaterialCount fun(): number
---@field MiningmaterialAdd fun(value: number): nil
---@field GetMiningmaterialspeed fun(): number[]
---@field SetMiningmaterialspeed fun(value: number[], count: number, length: number): nil
---@overload fun(value: number[]): nil
---@field GetMiningmaterialspeedCount fun(): number
---@field MiningmaterialspeedAdd fun(value: number): nil
---@field GetDamagedby fun(): number[]
---@field SetDamagedby fun(value: number[], count: number, length: number): nil
---@overload fun(value: number[]): nil
---@field GetDamagedbyCount fun(): number
---@field DamagedbyAdd fun(value: number): nil
---@field SetCreativeInventoryStacks fun(value: number[]): nil
---@field GetCreativeInventoryTabs fun(): string[]
---@field SetCreativeInventoryTabs fun(value: string[], count: number, length: number): nil
---@overload fun(value: string[]): nil
---@field GetCreativeInventoryTabsCount fun(): number
---@field CreativeInventoryTabsAdd fun(value: string): nil
---@field SetGuiTransform fun(value: Packet_ModelTransform): nil
---@field SetFpHandTransform fun(value: Packet_ModelTransform): nil
---@field SetTpHandTransform fun(value: Packet_ModelTransform): nil
---@field SetTpOffHandTransform fun(value: Packet_ModelTransform): nil
---@field SetGroundTransform fun(value: Packet_ModelTransform): nil
---@field SetAttributes fun(value: string): nil
---@field SetCombustibleProps fun(value: Packet_CombustibleProperties): nil
---@field SetNutritionProps fun(value: Packet_NutritionProperties): nil
---@field SetGrindingProps fun(value: Packet_GrindingProperties): nil
---@field SetCrushingProps fun(value: Packet_CrushingProperties): nil
---@field GetTransitionableProps fun(): Packet_TransitionableProperties[]
---@field SetTransitionableProps fun(value: Packet_TransitionableProperties[], count: number, length: number): nil
---@overload fun(value: Packet_TransitionableProperties[]): nil
---@field GetTransitionablePropsCount fun(): number
---@field TransitionablePropsAdd fun(value: Packet_TransitionableProperties): nil
---@field SetShape fun(value: Packet_CompositeShape): nil
---@field GetTextureCodes fun(): string[]
---@field SetTextureCodes fun(value: string[], count: number, length: number): nil
---@overload fun(value: string[]): nil
---@field GetTextureCodesCount fun(): number
---@field TextureCodesAdd fun(value: string): nil
---@field SetItemClass fun(value: string): nil
---@field SetTool fun(value: number): nil
---@field SetMaterialDensity fun(value: number): nil
---@field SetAttackPower fun(value: number): nil
---@field SetAttackRange fun(value: number): nil
---@field SetLiquidSelectable fun(value: number): nil
---@field SetMiningTier fun(value: number): nil
---@field SetStorageFlags fun(value: number): nil
---@field SetRenderAlphaTest fun(value: number): nil
---@field SetHeldTpHitAnimation fun(value: string): nil
---@field SetHeldRightTpIdleAnimation fun(value: string): nil
---@field SetHeldLeftTpIdleAnimation fun(value: string): nil
---@field SetHeldTpUseAnimation fun(value: string): nil
---@field SetMatterState fun(value: number): nil
---@field GetVariant fun(): Packet_VariantPart[]
---@field SetVariant fun(value: Packet_VariantPart[], count: number, length: number): nil
---@overload fun(value: Packet_VariantPart[]): nil
---@field GetVariantCount fun(): number
---@field VariantAdd fun(value: Packet_VariantPart): nil
---@field SetHeldSounds fun(value: Packet_HeldSoundSet): nil
---@field SetWidth fun(value: number): nil
---@field SetHeight fun(value: number): nil
---@field SetLength fun(value: number): nil
---@field GetLightHsv fun(): number[]
---@field SetLightHsv fun(value: number[], count: number, length: number): nil
---@overload fun(value: number[]): nil
---@field GetLightHsvCount fun(): number
---@field LightHsvAdd fun(value: number): nil
---@field SetIsMissing fun(value: number): nil
---@field SetHeldLeftReadyAnimation fun(value: string): nil
---@field SetHeldRightReadyAnimation fun(value: string): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_ItemType = {}
