---@meta HudElement
---@class HudElement: GuiDialog
---@field ctor fun(capi: ICoreClientAPI): HudElement
---@field get_DialogType fun(): EnumDialogany
---@field get_ToggleKeyCombinationCode fun(): string
---@field get_PrefersUngrabbedMouse fun(): boolean
---@field OnRenderGUI fun(deltaTime: Single): nil
---@field get_SingleComposer fun(): GuiComposer
---@field set_SingleComposer fun(value: GuiComposer): nil
---@field get_DebugName fun(): string
---@field get_ZSize fun(): Single
---@field get_Focused fun(): boolean
---@field get_Focusable fun(): boolean
---@field add_OnOpened fun(value: Action): nil
---@field remove_OnOpened fun(value: Action): nil
---@field add_OnClosed fun(value: Action): nil
---@field remove_OnClosed fun(value: Action): nil
---@field OnBlockTexturesLoaded fun(): nil
---@field OnLevelFinalize fun(): nil
---@field OnOwnPlayerDataReceived fun(): nil
---@field get_DrawOrder fun(): Double
---@field get_InputOrder fun(): Double
---@field get_UnregisterOnClose fun(): boolean
---@field OnGuiOpened fun(): nil
---@field OnGuiClosed fun(): nil
---@field TryOpen fun(): boolean
---@overload fun(withFocus: boolean): boolean
---@field TryClose fun(): boolean
---@field UnFocus fun(): nil
---@field Focus fun(): nil
---@field Toggle fun(): nil
---@field IsOpened fun(): boolean
---@overload fun(dialogComposerName: string): boolean
---@field OnBeforeRenderFrame3D fun(deltaTime: Single): nil
---@field OnFinalizeFrame fun(dt: Single): nil
---@field OnKeyDown fun(args: KeyEvent): nil
---@field OnKeyPress fun(args: KeyEvent): nil
---@field OnKeyUp fun(args: KeyEvent): nil
---@field OnEscapePressed fun(): boolean
---@field OnMouseEnterSlot fun(slot: ItemSlot): boolean
---@field OnMouseLeaveSlot fun(itemSlot: ItemSlot): boolean
---@field OnMouseClickSlot fun(itemSlot: ItemSlot): boolean
---@field OnMouseDown fun(args: MouseEvent): nil
---@field OnMouseUp fun(args: MouseEvent): nil
---@field OnMouseMove fun(args: MouseEvent): nil
---@field OnMouseWheel fun(args: MouseWheelEventArgs): nil
---@field ShouldReceiveRenderEvents fun(): boolean
---@field ShouldReceiveKeyboardEvents fun(): boolean
---@field ShouldReceiveMouseEvents fun(): boolean
---@field RequiresUngrabbedMouse fun(): boolean
---@field get_DisableMouseGrab fun(): boolean
---@field CaptureAllInputs fun(): boolean
---@field CaptureRawMouse fun(): boolean
---@field Dispose fun(): nil
---@field ClearComposers fun(): nil
---@field IsInRangeOf fun(pos: Vec3d): boolean
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field DialogType EnumDialogany
---@field ToggleKeyCombinationCode EnumDialogany
---@field PrefersUngrabbedMouse EnumDialogany
---@field SingleComposer EnumDialogany
---@field DebugName EnumDialogany
---@field ZSize EnumDialogany
---@field Focused EnumDialogany
---@field Focusable EnumDialogany
---@field DrawOrder EnumDialogany
---@field InputOrder EnumDialogany
---@field UnregisterOnClose EnumDialogany
---@field DisableMouseGrab EnumDialogany
---@field OnOpened EnumDialogany
---@field OnClosed EnumDialogany
---@field Composers EnumDialogany
---@field ignoreNextKeyPress EnumDialogany
---@field MouseOverCursor EnumDialogany
HudElement = {}
