---@meta Packet_Cube
---@class Packet_Cube: Object
---@field ctor fun(): Packet_Cube
---@field SetMinx fun(value: number): nil
---@field SetMiny fun(value: number): nil
---@field SetMinz fun(value: number): nil
---@field SetMaxx fun(value: number): nil
---@field SetMaxy fun(value: number): nil
---@field SetMaxz fun(value: number): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_Cube = {}
