---@meta Size3f
---@class Size3f: Object
---@field ctor fun(): Size3f
---@overload fun(width: Single, height: Single, length: Single): Size3f
---@field Clone fun(): Size3f
---@field CanContain fun(obj: Size3f): boolean
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Size3f = {}
