---@meta ColorBlend
---@class ColorBlend: Object
---@field Blend fun(blendMode: EnumColorBlendMode, colorBase: number, colorOver: number): number
---@field Normal fun(rgb1: number, rgb2: number): number
---@field Overlay fun(rgb1: number, rgb2: number): number
---@field Darken fun(rgb1: number, rgb2: number): number
---@field Lighten fun(rgb1: number, rgb2: number): number
---@field Multiply fun(rgb1: number, rgb2: number): number
---@field Screen fun(rgb1: number, rgb2: number): number
---@field ColorDodge fun(rgb1: number, rgb2: number): number
---@field ColorBurn fun(rgb1: number, rgb2: number): number
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
ColorBlend = {}
