---@meta IInputAPI
---@class IInputAPI
---@field get_ClipboardText fun(): string
---@field set_ClipboardText fun(value: string): nil
---@field add_InWorldAction fun(value: OnEntityAction): nil
---@field remove_InWorldAction fun(value: OnEntityAction): nil
---@field get_KeyboardKeyStateRaw fun(): boolean[]
---@field get_KeyboardKeyState fun(): boolean[]
---@field get_MouseButton fun(): MouseButtonState
---@field get_InWorldMouseButton fun(): MouseButtonState
---@field get_MouseX fun(): number
---@field get_MouseY fun(): number
---@field get_MouseYaw fun(): Single
---@field set_MouseYaw fun(value: Single): nil
---@field get_MousePitch fun(): Single
---@field set_MousePitch fun(value: Single): nil
---@field TriggerOnMouseEnterSlot fun(slot: ItemSlot): nil
---@field TriggerOnMouseLeaveSlot fun(itemSlot: ItemSlot): nil
---@field TriggerOnMouseClickSlot fun(itemSlot: ItemSlot): nil
---@field get_MouseWorldInteractAnyway fun(): boolean
---@field set_MouseWorldInteractAnyway fun(value: boolean): nil
---@field get_MouseGrabbed fun(): boolean
---@field RegisterHotKey fun(hotkeyCode: string, name: string, key: GlKeys, type: Hotkeyany, altPressed: boolean, ctrlPressed: boolean, shiftPressed: boolean): nil
---@field RegisterHotKeyFirst fun(hotkeyCode: string, name: string, key: GlKeys, type: Hotkeyany, altPressed: boolean, ctrlPressed: boolean, shiftPressed: boolean): nil
---@field SetHotKeyHandler fun(hotkeyCode: string, handler: ActionConsumable`1): nil
---@field AddHotkeyListener fun(handler: OnHotKeyDelegate): nil
---@field get_HotKeys fun(): Orderedtable<any, any>
---@field GetHotKeyByCode fun(toggleKeyCombinationCode: string): HotKey
---@field ClipboardText string
---@field KeyboardKeyStateRaw string
---@field KeyboardKeyState string
---@field MouseButton string
---@field InWorldMouseButton string
---@field MouseX string
---@field MouseY string
---@field MouseYaw string
---@field MousePitch string
---@field MouseWorldInteractAnyway string
---@field MouseGrabbed string
---@field HotKeys string
---@field InWorldAction string
IInputAPI = {}
