---@meta Packet_ServerCalendar
---@class Packet_ServerCalendar: Object
---@field ctor fun(): Packet_ServerCalendar
---@field SetTotalSeconds fun(value: Int64): nil
---@field GetTimeSpeedModifierNames fun(): string[]
---@field SetTimeSpeedModifierNames fun(value: string[], count: number, length: number): nil
---@overload fun(value: string[]): nil
---@field GetTimeSpeedModifierNamesCount fun(): number
---@field TimeSpeedModifierNamesAdd fun(value: string): nil
---@field GetTimeSpeedModifierSpeeds fun(): number[]
---@field SetTimeSpeedModifierSpeeds fun(value: number[], count: number, length: number): nil
---@overload fun(value: number[]): nil
---@field GetTimeSpeedModifierSpeedsCount fun(): number
---@field TimeSpeedModifierSpeedsAdd fun(value: number): nil
---@field SetMoonOrbitDays fun(value: number): nil
---@field SetHoursPerDay fun(value: number): nil
---@field SetRunning fun(value: number): nil
---@field SetCalendarSpeedMul fun(value: number): nil
---@field SetDaysPerMonth fun(value: number): nil
---@field SetTotalSecondsStart fun(value: Int64): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_ServerCalendar = {}
