---@meta Packet_ServerSerializer
---@class Packet_ServerSerializer: Object
---@field ctor fun(): Packet_ServerSerializer
---@field DeserializeLengthDelimitedNew fun(stream: CitoMemoryStream): Packet_Server
---@field DeserializeBuffer fun(buffer: number[], length: number, instance: Packet_Server): Packet_Server
---@field Deserialize fun(stream: CitoMemoryStream, instance: Packet_Server): Packet_Server
---@field DeserializeLengthDelimited fun(stream: CitoMemoryStream, instance: Packet_Server): Packet_Server
---@field Serialize fun(stream: CitoStream, instance: Packet_Server): nil
---@field SerializeToBytes fun(instance: Packet_Server): number[]
---@field SerializeLengthDelimited fun(stream: CitoStream, instance: Packet_Server): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_ServerSerializer = {}
