---@meta TagItem
---@class TagItem: Object
---@field ctor fun(TagSpec: ExifTag, _TagType: ExifTagany, _ValueCount: number): TagItem
---@overload fun(_TagId: ExifTagId, _TagType: ExifTagany, _ValueCount: number): TagItem
---@overload fun(_TagId: ExifTagId, _TagType: ExifTagany, _ValueCount: number, _ValueArray: number[], _ValueIndex: number, _AllocatedByteCount: number, _OriginalDataOffset: number): TagItem
---@field get_ByteCount fun(): number
---@field AllocTagMemory fun(RequiredByteCount: number): number[]
---@field SetTagTypeAndValueCount fun(_TagType: ExifTagany, _ValueCount: number, KeepExistingData: boolean): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field ByteCount number
---@field TagId number
---@field TagType number
---@field ValueCount number
---@field ValueData number
---@field ValueIndex number
---@field AllocatedByteCount number
---@field OriginalDataOffset number
TagItem = {}
