---@meta IGameSettingsHandler
---@class IGameSettingsHandler
---@field LeaveSettingsMenu fun(): boolean
---@field get_MaxViewDistanceAlarmValue fun(): Nullable`1
---@field ReloadShaders fun(): nil
---@field get_IsIngame fun(): boolean
---@field dialogBase fun(name: string, width: Double, height: Double): GuiComposer
---@field OnMacroEditor fun(): nil
---@field MaxViewDistanceAlarmValue Nullable`1
---@field IsIngame Nullable`1
IGameSettingsHandler = {}
