---@meta CollisionTester
---@class CollisionTester: Object
---@field ctor fun(): CollisionTester
---@field ApplyTerrainCollision fun(entity: Entity, entitypos: EntityPos, dtFac: Single, outposition: Vec3d&, stepHeight: Single, YExtra: Single): nil
---@field IsColliding fun(blockAccessor: IBlockAccessor, entityBoxRel: Cuboidf, pos: Vec3d, alsoCheckTouch: boolean): boolean
---@field GetCollidingBlock fun(blockAccessor: IBlockAccessor, entityBoxRel: Cuboidf, pos: Vec3d, alsoCheckTouch: boolean): Block
---@field GetCollidingCollisionBox fun(blockAccessor: IBlockAccessor, entityBoxRel: Cuboidf, pos: Vec3d, alsoCheckTouch: boolean): Cuboidd
---@overload fun(blockAccessor: IBlockAccessor, entityBoxRel: Cuboidf, pos: Vec3d, intoCubuid: Cuboidd&, alsoCheckTouch: boolean): boolean
---@field AabbIntersect fun(aabb: Cuboidf, x: Double, y: Double, z: Double, aabb2: Cuboidf, pos: Vec3d): boolean
---@overload fun(aabb: Cuboidd, aabb2: Cuboidd, motion: Vec3d): EnumIntersect
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
CollisionTester = {}
