---@meta JsonTesselator
---@class JsonTesselator: Object
---@field ctor fun(): JsonTesselator
---@field SetUpLightRGBs fun(vars: TCTCache): Int64
---@field Tesselate fun(vars: TCTCache): nil
---@field NotSurrounded fun(vars: TCTCache, extIndex3d: number): boolean
---@field doMesh fun(vars: TCTCache, sourceMesh: MeshData, lodLevel: number): nil
---@field AddJsonModelDataToMesh fun(sourceMesh: MeshData, lodlevel: number, vars: TCTCache, poolSupplier: IMeshPoolSupplier, tfMatrix: Single[]): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
JsonTesselator = {}
