---@meta IInventory
---@class IInventory
---@field get_Empty fun(): boolean
---@field get_RemoveOnClose fun(): boolean
---@field get_TakeLocked fun(): boolean
---@field get_PutLocked fun(): boolean
---@field get_LastChanged fun(): Int64
---@field get_Item fun(slotId: number): ItemSlot
---@field set_Item fun(slotId: number, value: ItemSlot): nil
---@field get_ClassName fun(): string
---@field get_InventoryID fun(): string
---@field get_DirtySlots fun(): HashSet`1
---@field Open fun(player: IPlayer): table
---@field Close fun(player: IPlayer): table
---@field HasOpened fun(player: IPlayer): boolean
---@field GetBestSuitedSlot fun(sourceSlot: ItemSlot, op: ItemStackMoveOperation, skipSlots: any[]): WeightedSlot
---@overload fun(sourceSlot: ItemSlot, skipSlots: any[]): WeightedSlot
---@field ActivateSlot fun(slotId: number, sourceSlot: ItemSlot, op: ItemStackMoveOperation&): table
---@field TryFlipItems fun(targetSlotId: number, sourceSlot: ItemSlot): table
---@field GetSlotId fun(slot: ItemSlot): number
---@field MarkSlotDirty fun(slotId: number): nil
---@field add_SlotModified fun(value: any`1): nil
---@field remove_SlotModified fun(value: any`1): nil
---@field add_SlotNotified fun(value: any`1): nil
---@field remove_SlotNotified fun(value: any`1): nil
---@field Empty boolean
---@field RemoveOnClose boolean
---@field TakeLocked boolean
---@field PutLocked boolean
---@field LastChanged boolean
---@field Item boolean
---@field ClassName boolean
---@field InventoryID boolean
---@field DirtySlots boolean
---@field SlotModified boolean
---@field SlotNotified boolean
IInventory = {}
