---@meta Vec3i
---@class Vec3i: Object
---@field ctor fun(): Vec3i
---@overload fun(x: number, y: number, z: number): Vec3i
---@overload fun(pos: BlockPos): Vec3i
---@field get_IsZero fun(): boolean
---@field get_Item fun(index: number): number
---@field set_Item fun(index: number, value: number): nil
---@field get_AsBlockPos fun(): BlockPos
---@field Add fun(x: number, y: number, z: number): Vec3i
---@field AddCopy fun(x: number, y: number, z: number): Vec3i
---@overload fun(x: number, y: number, z: number, intoVec: Vec3i): Vec3i
---@overload fun(towardsFace: BlockFacing, length: number): Vec3i
---@field ManhattenDistanceTo fun(vec: Vec3i): number
---@field SquareDistanceTo fun(vec: Vec3i): Int64
---@overload fun(x: number, y: number, z: number): Int64
---@field DistanceTo fun(vec: Vec3i): Double
---@field Reduce fun(val: number): nil
---@field ReduceX fun(val: number): nil
---@field ReduceY fun(val: number): nil
---@field ReduceZ fun(val: number): nil
---@field Set fun(positionX: number, positionY: number, positionZ: number): Vec3i
---@overload fun(fromPos: Vec3i): Vec3i
---@field Clone fun(): Vec3i
---@field Equals fun(obj: table): boolean
---@overload fun(other: Vec3i): boolean
---@field GetHashCode fun(): number
---@field ToString fun(): string
---@field get_Zero fun(): Vec3i
---@field get_XZ fun(): Vec2i
---@field AddCopy fun(facing: BlockFacing): Vec3i
---@field ToBlockPos fun(): BlockPos
---@field Equals fun(x: number, y: number, z: number): boolean
---@field op_Multiply fun(left: Vec3i, right: number): Vec3i
---@overload fun(left: number, right: Vec3i): Vec3i
---@field op_Division fun(left: Vec3i, right: number): Vec3i
---@field op_Addition fun(left: Vec3i, right: Vec3i): Vec3i
---@field op_Subtraction fun(left: Vec3i, right: Vec3i): Vec3i
---@field op_UnaryNegation fun(vec: Vec3i): Vec3i
---@field op_Equality fun(left: Vec3i, right: Vec3i): boolean
---@field op_Inequality fun(left: Vec3i, right: Vec3i): boolean
---@field get_AsVec3i fun(): Vec3i
---@field GetType fun(): any
---@field IsZero boolean
---@field Item boolean
---@field AsBlockPos boolean
---@field Zero boolean
---@field XZ boolean
---@field AsVec3i boolean
---@field X boolean
---@field Y boolean
---@field Z boolean
---@field DirectAndIndirectNeighbours boolean
Vec3i = {}
