---@meta GrindingProperties
---@class GrindingProperties: Object
---@field ctor fun(): GrindingProperties
---@field get_GrindedStack fun(): JsonItemStack
---@field set_GrindedStack fun(value: JsonItemStack): nil
---@field Clone fun(): GrindingProperties
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field GrindedStack JsonItemStack
---@field usedObsoleteNotation JsonItemStack
---@field GroundStack JsonItemStack
GrindingProperties = {}
