---@meta Particle2D
---@class Particle2D: ParticleBase
---@field ctor fun(): Particle2D
---@field TickFixedStep fun(dt: Single, api: ICoreClientAPI, physicsSim: ParticlePhysics): nil
---@field TickNow fun(lifedt: Single, pdt: Single, api: ICoreClientAPI, physicsSim: ParticlePhysics): nil
---@field UpdateBuffers fun(buffer: MeshData, cameraPos: Vec3d, posPosition: number&, rgbaPosition: number&, flagPosition: number&): nil
---@field SetAlive fun(GravityEffect: Single): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Particle2D = {}
