---@meta ServerPackets
---@class ServerPackets: Object
---@field ctor fun(): ServerPackets
---@field IngameError fun(code: string, text: string, langargs: table[]): Packet_Server
---@field IngameDiscovery fun(code: string, text: string, langargs: table[]): Packet_Server
---@field ChatLine fun(groupid: number, text: string, chatType: EnumChatany, data: string): Packet_Server
---@field LevelInitialize fun(maxViewDistance: number): Packet_Server
---@field LevelFinalize fun(): Packet_Server
---@field Serialize fun(packet: Packet_Server, retLength: IntRef): number[]
---@field GetSendableEntityMovedPacket fun(entity: Entity, isTeleport: boolean): Packet_Server
---@field GetBulkEntityAttributesPacket fun(entitiesFull: any[], entitiesPartial: any[], entitiesPositionUpdate: any[], entitiesPositionMinimalUpdate: any[]): Packet_Server
---@field GetBulkEntityDebugAttributesPacket fun(entitiesFull: any[], entitiesPartial: any[]): Packet_Server
---@field GetEntityAttributesPacket fun(entity: Entity): Packet_Server
---@field GetEntityAttributesUpdatePacket fun(entity: Entity): Packet_Server
---@field GetFullEntityPacket fun(entity: Entity, ms: MemoryStream, writer: BinaryWriter): Packet_Server
---@field GetEntityDespawnPacket fun(despawns: any[]): Packet_Server
---@field GetEntitySpawnPacket fun(spawns: any[]): Packet_Server
---@field GetEntityPacket fun(entity: Entity): Packet_Entity
---@overload fun(entity: Entity, ms: MemoryStream, writer: BinaryWriter): Packet_Entity
---@field getEntityPositionPacket fun(pos: EntityPos, eagent: EntityAgent): Packet_EntityPosition
---@field getEntityDataForClient fun(entity: Entity, ms: MemoryStream, writer: BinaryWriter): number[]
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
ServerPackets = {}
