---@meta Packet_HighlightBlocks
---@class Packet_HighlightBlocks: Object
---@field ctor fun(): Packet_HighlightBlocks
---@field SetMode fun(value: number): nil
---@field SetShape fun(value: number): nil
---@field SetBlocks fun(value: number[]): nil
---@field GetColors fun(): number[]
---@field SetColors fun(value: number[], count: number, length: number): nil
---@overload fun(value: number[]): nil
---@field GetColorsCount fun(): number
---@field ColorsAdd fun(value: number): nil
---@field SetSlotid fun(value: number): nil
---@field SetScale fun(value: number): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_HighlightBlocks = {}
