---@meta Packet_InventoryDoubleUpdateSerializer
---@class Packet_InventoryDoubleUpdateSerializer: Object
---@field ctor fun(): Packet_InventoryDoubleUpdateSerializer
---@field DeserializeLengthDelimitedNew fun(stream: CitoMemoryStream): Packet_InventoryDoubleUpdate
---@field DeserializeBuffer fun(buffer: number[], length: number, instance: Packet_InventoryDoubleUpdate): Packet_InventoryDoubleUpdate
---@field Deserialize fun(stream: CitoMemoryStream, instance: Packet_InventoryDoubleUpdate): Packet_InventoryDoubleUpdate
---@field DeserializeLengthDelimited fun(stream: CitoMemoryStream, instance: Packet_InventoryDoubleUpdate): Packet_InventoryDoubleUpdate
---@field Serialize fun(stream: CitoStream, instance: Packet_InventoryDoubleUpdate): nil
---@field SerializeToBytes fun(instance: Packet_InventoryDoubleUpdate): number[]
---@field SerializeLengthDelimited fun(stream: CitoStream, instance: Packet_InventoryDoubleUpdate): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_InventoryDoubleUpdateSerializer = {}
