---@meta FoodNutritionProperties
---@class FoodNutritionProperties: Object
---@field ctor fun(): FoodNutritionProperties
---@field get_Saturation fun(): Single
---@field set_Saturation fun(value: Single): nil
---@field get_Intoxication fun(): Single
---@field set_Intoxication fun(value: Single): nil
---@field Clone fun(): FoodNutritionProperties
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field Saturation Single
---@field Intoxication Single
---@field FoodCategory Single
---@field Satiety Single
---@field SaturationLossDelay Single
---@field Health Single
---@field EatenStack Single
FoodNutritionProperties = {}
