---@meta CmdArgs
---@class CmdArgs: Object
---@field ctor fun(): CmdArgs
---@overload fun(joinedargs: string): CmdArgs
---@overload fun(args: string[]): CmdArgs
---@field Push fun(joinedargs: string): nil
---@field get_Item fun(index: number): string
---@field set_Item fun(index: number, value: string): nil
---@field get_Length fun(): number
---@field PopAll fun(): string
---@field PeekChar fun(defaultValue: Nullable`1): Nullable`1
---@field PopChar fun(defaultValue: Nullable`1): Nullable`1
---@field PopWord fun(defaultValue: string): string
---@field PeekWord fun(defaultValue: string): string
---@field PopUntil fun(endChar: Char): string
---@field PopCodeBlock fun(blockOpenChar: Char, blockCloseChar: Char, parseErrorMsg: string&): string
---@field PushSingle fun(arg: string): nil
---@field AppendSingle fun(arg: string): nil
---@field PopEnum fun(defaultValue: T): T
---@field PopInt fun(defaultValue: Nullable`1): Nullable`1
---@field PopLong fun(defaultValue: Nullable`1): Nullable`1
---@field PopBool fun(defaultValue: Nullable`1, trueAlias: string): Nullable`1
---@field PopDouble fun(defaultValue: Nullable`1): Nullable`1
---@field PopFloat fun(defaultValue: Nullable`1): Nullable`1
---@field PopVec3i fun(defaultValue: Vec3i): Vec3i
---@field PopVec3d fun(defaultValue: Vec3d): Vec3d
---@field PopFlexiblePos fun(playerPos: Vec3d, mapMiddle: Vec3d): Vec3d
---@field PopFlexiblePos2D fun(playerPos: Vec3d, mapMiddle: Vec3d): Vec2i
---@field Clone fun(): CmdArgs
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field Item string
---@field Length string
CmdArgs = {}
