---@meta GltfAnimationSampler
---@class GltfAnimationSampler: Object
---@field ctor fun(): GltfAnimationSampler
---@field get_Input fun(): Int64
---@field set_Input fun(value: Int64): nil
---@field get_Interpolation fun(): EnumGltfAnimationSamplerInterpolation
---@field set_Interpolation fun(value: EnumGltfAnimationSamplerInterpolation): nil
---@field get_Output fun(): Int64
---@field set_Output fun(value: Int64): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field Input Int64
---@field Interpolation Int64
---@field Output Int64
GltfAnimationSampler = {}
