---@meta LayeredVoxelRecipe`1
---@class LayeredVoxelRecipe`1: RecipeBase`1
---@field ctor fun(): LayeredVoxelRecipe`1
---@field get_QuantityLayers fun(): number
---@field get_RecipeCategoryCode fun(): string
---@field Resolve fun(world: IWorldAccessor, sourceForErrorLogging: string): boolean
---@field GenVoxels fun(): nil
---@field ToBytes fun(writer: BinaryWriter): nil
---@field FromBytes fun(reader: BinaryReader, resolver: IWorldAccessor): nil
---@field GetNameToCodeMapping fun(world: IWorldAccessor): table<any, any>
---@field WildCardMatch fun(wildCard: AssetLocation, blockCode: AssetLocation): boolean
---@field get_Ingredient fun(): CraftingRecipeIngredient
---@field set_Ingredient fun(value: CraftingRecipeIngredient): nil
---@field get_Name fun(): AssetLocation
---@field set_Name fun(value: AssetLocation): nil
---@field get_Enabled fun(): boolean
---@field set_Enabled fun(value: boolean): nil
---@field Clone fun(): T
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field QuantityLayers number
---@field RecipeCategoryCode number
---@field Ingredient number
---@field Name number
---@field Enabled number
---@field Pattern number
---@field Voxels number
---@field RecipeId number
---@field Ingredients number
---@field Output number
LayeredVoxelRecipe`1 = {}
