---@meta TyronThreadPool
---@class TyronThreadPool: Object
---@field ctor fun(): TyronThreadPool
---@field ListAllRunningTasks fun(): string
---@field ListAllThreads fun(): string
---@field QueueTask fun(callback: Action, caller: string): nil
---@field QueueLongDurationTask fun(callback: Action, caller: string): nil
---@overload fun(callback: Action): nil
---@overload fun(callback: Action): nil
---@field CreateDedicatedThread fun(starter: ThreadStart, name: string): Thread
---@field Dispose fun(): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
TyronThreadPool = {}
