---@meta Packet_BlockDrop
---@class Packet_BlockDrop: Object
---@field ctor fun(): Packet_BlockDrop
---@field SetQuantityAvg fun(value: number): nil
---@field SetQuantityVar fun(value: number): nil
---@field SetQuantityDist fun(value: number): nil
---@field SetDroppedStack fun(value: number[]): nil
---@field SetTool fun(value: number): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_BlockDrop = {}
