---@meta GuiElementListMenu
---@class GuiElementListMenu: GuiElementTextBase
---@field ctor fun(capi: ICoreClientAPI, values: string[], names: string[], selectedIndex: number, onSelectionChanged: SelectionChangedDelegate, bounds: ElementBounds, font: CairoFont, multiSelect: boolean): GuiElementListMenu
---@field get_Values fun(): string[]
---@field set_Values fun(value: string[]): nil
---@field get_Names fun(): string[]
---@field set_Names fun(value: string[]): nil
---@field get_SelectedIndex fun(): number
---@field set_SelectedIndex fun(value: number): nil
---@field get_HoveredIndex fun(): number
---@field set_HoveredIndex fun(value: number): nil
---@field get_SelectedIndices fun(): number[]
---@field set_SelectedIndices fun(value: number[]): nil
---@field get_IsOpened fun(): boolean
---@field get_DrawOrder fun(): Double
---@field get_Focusable fun(): boolean
---@field ComposeElements fun(ctx: Context, surface: ImageSurface): nil
---@field ComposeDynamicElements fun(): nil
---@field IsPositionInside fun(posX: number, posY: number): boolean
---@field RenderInteractiveElements fun(deltaTime: Single): nil
---@field OnKeyDown fun(api: ICoreClientAPI, args: KeyEvent): nil
---@field OnMouseMove fun(api: ICoreClientAPI, args: MouseEvent): nil
---@field OnMouseUp fun(api: ICoreClientAPI, args: MouseEvent): nil
---@field Open fun(): nil
---@field OnMouseDown fun(api: ICoreClientAPI, args: MouseEvent): nil
---@field OnMouseWheel fun(api: ICoreClientAPI, args: MouseWheelEventArgs): nil
---@field OnFocusLost fun(): nil
---@field SetSelectedIndex fun(selectedIndex: number): nil
---@field SetSelectedValue fun(value: string[]): nil
---@field SetList fun(values: string[], names: string[]): nil
---@field Dispose fun(): nil
---@field get_Text fun(): string
---@field set_Text fun(value: string): nil
---@field ComposeTextElements fun(ctx: Context, surface: ImageSurface): nil
---@field GetMultilineTextHeight fun(): Double
---@field DrawMultilineTextAt fun(ctx: Context, posX: Double, posY: Double, orientation: EnumTextOrientation): Double
---@field DrawTextLineAt fun(ctx: Context, text: string, posX: Double, posY: Double, textPathMode: boolean): nil
---@field GetText fun(): string
---@field get_Enabled fun(): boolean
---@field set_Enabled fun(value: boolean): nil
---@field get_InsideClipBounds fun(): ElementBounds
---@field set_InsideClipBounds fun(value: ElementBounds): nil
---@field get_RenderAsPremultipliedAlpha fun(): boolean
---@field set_RenderAsPremultipliedAlpha fun(value: boolean): nil
---@field get_HasFocus fun(): boolean
---@field get_Scale fun(): Double
---@field set_Scale fun(value: Double): nil
---@field OnFocusGained fun(): nil
---@field PostRenderInteractiveElements fun(deltaTime: Single): nil
---@field RenderFocusOverlay fun(deltaTime: Single): nil
---@field BeforeCalcBounds fun(): nil
---@field DialogRoundRectangle fun(ctx: Context, bounds: ElementBounds): nil
---@field ElementRoundRectangle fun(ctx: Context, bounds: ElementBounds, isBackground: boolean, radius: Double): nil
---@field ShadePath fun(ctx: Context, thickness: Double): nil
---@field EmbossRoundRectangleDialog fun(ctx: Context, x: Double, y: Double, width: Double, height: Double, inverse: boolean): nil
---@field EmbossRoundRectangleElement fun(ctx: Context, x: Double, y: Double, width: Double, height: Double, inverse: boolean, depth: number, radius: number): nil
---@overload fun(ctx: Context, bounds: ElementBounds, inverse: boolean, depth: number, radius: number): nil
---@field RenderBoundsDebug fun(): nil
---@field OnMouseDownOnElement fun(api: ICoreClientAPI, args: MouseEvent): nil
---@field OnMouseUpOnElement fun(api: ICoreClientAPI, args: MouseEvent): nil
---@field OnMouseEnterSlot fun(api: ICoreClientAPI, slot: ItemSlot): boolean
---@field OnMouseLeaveSlot fun(api: ICoreClientAPI, slot: ItemSlot): boolean
---@field OnKeyUp fun(api: ICoreClientAPI, args: KeyEvent): nil
---@field OnKeyPress fun(api: ICoreClientAPI, args: KeyEvent): nil
---@field get_MouseOverCursor fun(): string
---@field OutlineColor fun(): number
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field Values string[]
---@field Names string[]
---@field SelectedIndex string[]
---@field HoveredIndex string[]
---@field SelectedIndices string[]
---@field IsOpened string[]
---@field DrawOrder string[]
---@field Focusable string[]
---@field Text string[]
---@field Enabled string[]
---@field InsideClipBounds string[]
---@field RenderAsPremultipliedAlpha string[]
---@field HasFocus string[]
---@field Scale string[]
---@field MouseOverCursor string[]
---@field MaxHeight string[]
---@field textUtil string[]
---@field textPathMode string[]
---@field Font string[]
---@field Bounds string[]
---@field TabIndex string[]
GuiElementListMenu = {}
