---@meta ElementStdBounds
---@class ElementStdBounds: Object
---@field Statbar fun(alignment: EnumDialogArea, width: Double): ElementBounds
---@field get_AutosizedMainDialog fun(): ElementBounds
---@field MainScreenRightPart fun(): ElementBounds
---@field AutosizedMainDialogAtPos fun(fixedY: Double): ElementBounds
---@field DialogBackground fun(): ElementBounds
---@overload fun(horPadding: Double, verPadding: Double): ElementBounds
---@field MenuButton fun(rowIndex: Single, alignment: EnumDialogArea): ElementBounds
---@field Rowed fun(rowIndex: Single, padding: Double, alignment: EnumDialogArea): ElementBounds
---@field Sign fun(fixedX: Double, fixedY: Double, fixedWith: Double, fixedHeight: Double): ElementBounds
---@field Slider fun(x: Double, y: Double, width: Double): ElementBounds
---@field VerticalScrollbar fun(leftElement: ElementBounds): ElementBounds
---@field Slot fun(x: Double, y: Double): ElementBounds
---@field SlotGrid fun(alignment: EnumDialogArea, x: Double, y: Double, cols: number, rows: number): ElementBounds
---@field ToggleButton fun(fixedX: Double, fixedY: Double, width: Double, height: Double): ElementBounds
---@field TitleBar fun(): ElementBounds
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field AutosizedMainDialog ElementBounds
---@field mainMenuUnscaledLogoSize ElementBounds
---@field mainMenuUnscaledLogoHorPadding ElementBounds
---@field mainMenuUnscaledLogoVerPadding ElementBounds
---@field mainMenuUnscaledWoodPlankWidth ElementBounds
ElementStdBounds = {}
