---@meta MouseEvent
---@class MouseEvent: Object
---@field ctor fun(x: number, y: number, deltaX: number, deltaY: number, button: EnumMouseButton, modifiers: number): MouseEvent
---@overload fun(x: number, y: number, deltaX: number, deltaY: number, button: EnumMouseButton): MouseEvent
---@overload fun(x: number, y: number, deltaX: number, deltaY: number): MouseEvent
---@overload fun(x: number, y: number, button: EnumMouseButton, modifiers: number): MouseEvent
---@overload fun(x: number, y: number, button: EnumMouseButton): MouseEvent
---@overload fun(x: number, y: number): MouseEvent
---@field get_X fun(): number
---@field get_Y fun(): number
---@field get_DeltaX fun(): number
---@field get_DeltaY fun(): number
---@field get_Button fun(): EnumMouseButton
---@field get_Modifiers fun(): number
---@field get_Handled fun(): boolean
---@field set_Handled fun(value: boolean): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field X number
---@field Y number
---@field DeltaX number
---@field DeltaY number
---@field Button number
---@field Modifiers number
---@field Handled number
MouseEvent = {}
