---@meta Packet_ServerPlayerPingSerializer
---@class Packet_ServerPlayerPingSerializer: Object
---@field ctor fun(): Packet_ServerPlayerPingSerializer
---@field DeserializeLengthDelimitedNew fun(stream: CitoMemoryStream): Packet_ServerPlayerPing
---@field DeserializeBuffer fun(buffer: number[], length: number, instance: Packet_ServerPlayerPing): Packet_ServerPlayerPing
---@field Deserialize fun(stream: CitoMemoryStream, instance: Packet_ServerPlayerPing): Packet_ServerPlayerPing
---@field DeserializeLengthDelimited fun(stream: CitoMemoryStream, instance: Packet_ServerPlayerPing): Packet_ServerPlayerPing
---@field Serialize fun(stream: CitoStream, instance: Packet_ServerPlayerPing): nil
---@field SerializeToBytes fun(instance: Packet_ServerPlayerPing): number[]
---@field SerializeLengthDelimited fun(stream: CitoStream, instance: Packet_ServerPlayerPing): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_ServerPlayerPingSerializer = {}
