---@meta Packet_ServerEntityDrawBlockSerializer
---@class Packet_ServerEntityDrawBlockSerializer: Object
---@field ctor fun(): Packet_ServerEntityDrawBlockSerializer
---@field DeserializeLengthDelimitedNew fun(stream: CitoMemoryStream): Packet_ServerEntityDrawBlock
---@field DeserializeBuffer fun(buffer: number[], length: number, instance: Packet_ServerEntityDrawBlock): Packet_ServerEntityDrawBlock
---@field Deserialize fun(stream: CitoMemoryStream, instance: Packet_ServerEntityDrawBlock): Packet_ServerEntityDrawBlock
---@field DeserializeLengthDelimited fun(stream: CitoMemoryStream, instance: Packet_ServerEntityDrawBlock): Packet_ServerEntityDrawBlock
---@field Serialize fun(stream: CitoStream, instance: Packet_ServerEntityDrawBlock): nil
---@field SerializeToBytes fun(instance: Packet_ServerEntityDrawBlock): number[]
---@field SerializeLengthDelimited fun(stream: CitoStream, instance: Packet_ServerEntityDrawBlock): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_ServerEntityDrawBlockSerializer = {}
