---@meta IVertexShaderProgramFogandlight
---@class IVertexShaderProgramFogandlight
---@field set_FlatFogDensity fun(value: Single): nil
---@field set_FlatFogStart fun(value: Single): nil
---@field set_ViewDistance fun(value: Single): nil
---@field set_ViewDistanceLod0 fun(value: Single): nil
---@field set_GlitchStrengthFL fun(value: Single): nil
---@field set_NightVisionStrength fun(value: Single): nil
---@field set_PointLights fun(value: Vec3f): nil
---@field set_PointLightColors fun(value: Vec3f): nil
---@field set_PointLightQuantity fun(value: number): nil
---@field FlatFogDensity Single
---@field FlatFogStart Single
---@field ViewDistance Single
---@field ViewDistanceLod0 Single
---@field GlitchStrengthFL Single
---@field NightVisionStrength Single
---@field PointLights Single
---@field PointLightColors Single
---@field PointLightQuantity Single
IVertexShaderProgramFogandlight = {}
