---@meta Packet_ServerPingSerializer
---@class Packet_ServerPingSerializer: Object
---@field ctor fun(): Packet_ServerPingSerializer
---@field DeserializeLengthDelimitedNew fun(stream: CitoMemoryStream): Packet_ServerPing
---@field DeserializeBuffer fun(buffer: number[], length: number, instance: Packet_ServerPing): Packet_ServerPing
---@field Deserialize fun(stream: CitoMemoryStream, instance: Packet_ServerPing): Packet_ServerPing
---@field DeserializeLengthDelimited fun(stream: CitoMemoryStream, instance: Packet_ServerPing): Packet_ServerPing
---@field Serialize fun(stream: CitoStream, instance: Packet_ServerPing): nil
---@field SerializeToBytes fun(instance: Packet_ServerPing): number[]
---@field SerializeLengthDelimited fun(stream: CitoStream, instance: Packet_ServerPing): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_ServerPingSerializer = {}
