---@meta MeshDataRecycler
---@class MeshDataRecycler: Object
---@field ctor fun(clientMain: IClientWorldAccessor): MeshDataRecycler
---@field GetOrCreateMesh fun(minimumVertices: number): MeshData
---@field DoRecycling fun(): nil
---@field Recycle fun(meshData: MeshData): nil
---@field Dispose fun(): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
MeshDataRecycler = {}
