---@meta ModelTransformNoDefaults
---@class ModelTransformNoDefaults: Object
---@field ctor fun(): ModelTransformNoDefaults
---@field set_Scale fun(value: Single): nil
---@field get_AsMatrix fun(): Single[]
---@field Clear fun(): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field Scale Single
---@field AsMatrix Single
---@field Translation Single
---@field Rotation Single
---@field Origin Single
---@field Rotate Single
---@field ScaleXYZ Single
ModelTransformNoDefaults = {}
