---@meta IAsset
---@class IAsset
---@field get_Name fun(): string
---@field get_Location fun(): AssetLocation
---@field get_Origin fun(): IAssetOrigin
---@field set_Origin fun(value: IAssetOrigin): nil
---@field get_Data fun(): number[]
---@field set_Data fun(value: number[]): nil
---@field ToObject fun(settings: JsonSerializerSettings): T
---@field ToText fun(): string
---@field ToBitmap fun(capi: ICoreClientAPI): BitmapRef
---@field IsLoaded fun(): boolean
---@field Name string
---@field Location string
---@field Origin string
---@field Data string
IAsset = {}
