---@meta CairoFont
---@class CairoFont: FontConfig
---@field ctor fun(): CairoFont
---@overload fun(config: FontConfig): CairoFont
---@overload fun(unscaledFontSize: Double, fontName: string): CairoFont
---@overload fun(unscaledFontSize: Double, fontName: string, color: Double[], strokeColor: Double[]): CairoFont
---@field WithLineHeightMultiplier fun(lineHeightMul: Double): CairoFont
---@field WithStroke fun(color: Double[], width: Double): CairoFont
---@field AutoFontSize fun(text: string, bounds: ElementBounds, onlyShrink: boolean): nil
---@field AutoBoxSize fun(text: string, bounds: ElementBounds, onlyGrow: boolean): nil
---@field WithColor fun(color: Double[]): CairoFont
---@field WithWeight fun(weight: FontWeight): CairoFont
---@field WithRenderTwice fun(): CairoFont
---@field WithSlant fun(slant: FontSlant): CairoFont
---@field WithFont fun(fontname: string): CairoFont
---@field SetupContext fun(ctx: Context): nil
---@field GetFontExtents fun(): FontExtents
---@field GetTextExtents fun(text: string): TextExtents
---@field Clone fun(): CairoFont
---@field WithFontSize fun(fontSize: Single): CairoFont
---@field ButtonText fun(): CairoFont
---@field ButtonPressedText fun(): CairoFont
---@field WithOrientation fun(orientation: EnumTextOrientation): CairoFont
---@field TextInput fun(): CairoFont
---@field SmallTextInput fun(): CairoFont
---@field WhiteMediumText fun(): CairoFont
---@field WhiteSmallishText fun(): CairoFont
---@overload fun(baseFont: string): CairoFont
---@field WhiteSmallText fun(): CairoFont
---@field WhiteDetailText fun(): CairoFont
---@field Dispose fun(): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
CairoFont = {}
