---@meta Packet_EntityDespawn
---@class Packet_EntityDespawn: Object
---@field ctor fun(): Packet_EntityDespawn
---@field GetEntityId fun(): Int64[]
---@field SetEntityId fun(value: Int64[], count: number, length: number): nil
---@overload fun(value: Int64[]): nil
---@field GetEntityIdCount fun(): number
---@field EntityIdAdd fun(value: Int64): nil
---@field GetDespawnReason fun(): number[]
---@field SetDespawnReason fun(value: number[], count: number, length: number): nil
---@overload fun(value: number[]): nil
---@field GetDespawnReasonCount fun(): number
---@field DespawnReasonAdd fun(value: number): nil
---@field GetDeathDamageSource fun(): number[]
---@field SetDeathDamageSource fun(value: number[], count: number, length: number): nil
---@overload fun(value: number[]): nil
---@field GetDeathDamageSourceCount fun(): number
---@field DeathDamageSourceAdd fun(value: number): nil
---@field GetByEntityId fun(): Int64[]
---@field SetByEntityId fun(value: Int64[], count: number, length: number): nil
---@overload fun(value: Int64[]): nil
---@field GetByEntityIdCount fun(): number
---@field ByEntityIdAdd fun(value: Int64): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_EntityDespawn = {}
