---@meta Vec3Utilsd
---@class Vec3Utilsd: Object
---@field ctor fun(): Vec3Utilsd
---@field Create fun(): Double[]
---@field CloneIt fun(a: Double[]): Double[]
---@field FromValues fun(x: Double, y: Double, z: Double): Double[]
---@field Copy fun(output: Double[], a: Double[]): Double[]
---@field Set fun(output: Double[], x: Double, y: Double, z: Double): Double[]
---@field Add fun(output: Double[], a: Double[], b: Double[]): Double[]
---@field Substract fun(output: Double[], a: Double[], b: Double[]): Double[]
---@field Multiply fun(output: Double[], a: Double[], b: Double[]): Double[]
---@field Divide fun(output: Double[], a: Double[], b: Double[]): Double[]
---@field Min fun(output: Double[], a: Double[], b: Double[]): Double[]
---@field Max fun(output: Double[], a: Double[], b: Double[]): Double[]
---@field Scale fun(output: Double[], a: Double[], b: Double): Double[]
---@field ScaleAndAdd fun(output: Double[], a: Double[], b: Double[], scale: Double): Double[]
---@field Distance fun(a: Double[], b: Double[]): Double
---@field SquaredDistance fun(a: Double[], b: Double[]): Double
---@field Length_ fun(a: Double[]): Double
---@field SquaredLength fun(a: Double[]): Double
---@field SqrLen fun(a: Double[]): Double
---@field Negate fun(output: Double[], a: Double[]): Double[]
---@field Normalize fun(output: Double[], a: Double[]): Double[]
---@field Dot fun(a: Double[], b: Double[]): Double
---@field Cross fun(output: Double[], a: Double[], b: Double[]): Double[]
---@field Lerp fun(output: Double[], a: Double[], b: Double[], t: Double): Double[]
---@field TransformMat4 fun(output: Double[], a: Double[], m: Double[]): Double[]
---@field TransformMat3 fun(output: Double[], a: Double[], m: Double[]): Double[]
---@field TransformQuat fun(output: Double[], a: Double[], q: Double[]): Double[]
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Vec3Utilsd = {}
