---@meta Packet_ModelTransformSerializer
---@class Packet_ModelTransformSerializer: Object
---@field ctor fun(): Packet_ModelTransformSerializer
---@field DeserializeLengthDelimitedNew fun(stream: CitoMemoryStream): Packet_ModelTransform
---@field DeserializeBuffer fun(buffer: number[], length: number, instance: Packet_ModelTransform): Packet_ModelTransform
---@field Deserialize fun(stream: CitoMemoryStream, instance: Packet_ModelTransform): Packet_ModelTransform
---@field DeserializeLengthDelimited fun(stream: CitoMemoryStream, instance: Packet_ModelTransform): Packet_ModelTransform
---@field Serialize fun(stream: CitoStream, instance: Packet_ModelTransform): nil
---@field SerializeToBytes fun(instance: Packet_ModelTransform): number[]
---@field SerializeLengthDelimited fun(stream: CitoStream, instance: Packet_ModelTransform): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_ModelTransformSerializer = {}
