---@meta ProtoPlatform
---@class ProtoPlatform: Object
---@field ctor fun(): ProtoPlatform
---@field StringToBytes fun(s: string): number[]
---@field BytesToString fun(bytes: number[], length: number): string
---@field ArrayLength fun(a: number[]): number
---@field IntToByte fun(a: number): number
---@field logical_right_shift fun(x: number, n: number): number
---@overload fun(x: Int64, n: number): Int64
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
ProtoPlatform = {}
