---@meta BaseServerChatCommandDelegateProvider
---@class BaseServerChatCommandDelegateProvider: Object
---@field ctor fun(server: ServerMain): BaseServerChatCommandDelegateProvider
---@field get_syntax fun(): string
---@field set_syntax fun(value: string): nil
---@field GetDelegate fun(): ServerChatCommandDelegate
---@field GetClient fun(player: IServerPlayer): ConnectedClient
---@field Handle fun(player: IServerPlayer, groupId: number, args: CmdArgs): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field syntax string
BaseServerChatCommandDelegateProvider = {}
