---@meta Packet_FlipItemstacksSerializer
---@class Packet_FlipItemstacksSerializer: Object
---@field ctor fun(): Packet_FlipItemstacksSerializer
---@field DeserializeLengthDelimitedNew fun(stream: CitoMemoryStream): Packet_FlipItemstacks
---@field DeserializeBuffer fun(buffer: number[], length: number, instance: Packet_FlipItemstacks): Packet_FlipItemstacks
---@field Deserialize fun(stream: CitoMemoryStream, instance: Packet_FlipItemstacks): Packet_FlipItemstacks
---@field DeserializeLengthDelimited fun(stream: CitoMemoryStream, instance: Packet_FlipItemstacks): Packet_FlipItemstacks
---@field Serialize fun(stream: CitoStream, instance: Packet_FlipItemstacks): nil
---@field SerializeToBytes fun(instance: Packet_FlipItemstacks): number[]
---@field SerializeLengthDelimited fun(stream: CitoStream, instance: Packet_FlipItemstacks): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_FlipItemstacksSerializer = {}
