---@meta Packet_InventoryUpdateSerializer
---@class Packet_InventoryUpdateSerializer: Object
---@field ctor fun(): Packet_InventoryUpdateSerializer
---@field DeserializeLengthDelimitedNew fun(stream: CitoMemoryStream): Packet_InventoryUpdate
---@field DeserializeBuffer fun(buffer: number[], length: number, instance: Packet_InventoryUpdate): Packet_InventoryUpdate
---@field Deserialize fun(stream: CitoMemoryStream, instance: Packet_InventoryUpdate): Packet_InventoryUpdate
---@field DeserializeLengthDelimited fun(stream: CitoMemoryStream, instance: Packet_InventoryUpdate): Packet_InventoryUpdate
---@field Serialize fun(stream: CitoStream, instance: Packet_InventoryUpdate): nil
---@field SerializeToBytes fun(instance: Packet_InventoryUpdate): number[]
---@field SerializeLengthDelimited fun(stream: CitoStream, instance: Packet_InventoryUpdate): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_InventoryUpdateSerializer = {}
