---@meta Packet_ServerPlayerPing
---@class Packet_ServerPlayerPing: Object
---@field ctor fun(): Packet_ServerPlayerPing
---@field GetClientIds fun(): number[]
---@field SetClientIds fun(value: number[], count: number, length: number): nil
---@overload fun(value: number[]): nil
---@field GetClientIdsCount fun(): number
---@field ClientIdsAdd fun(value: number): nil
---@field GetPings fun(): number[]
---@field SetPings fun(value: number[], count: number, length: number): nil
---@overload fun(value: number[]): nil
---@field GetPingsCount fun(): number
---@field PingsAdd fun(value: number): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_ServerPlayerPing = {}
