---@meta Packet_EntitiesSerializer
---@class Packet_EntitiesSerializer: Object
---@field ctor fun(): Packet_EntitiesSerializer
---@field DeserializeLengthDelimitedNew fun(stream: CitoMemoryStream): Packet_Entities
---@field DeserializeBuffer fun(buffer: number[], length: number, instance: Packet_Entities): Packet_Entities
---@field Deserialize fun(stream: CitoMemoryStream, instance: Packet_Entities): Packet_Entities
---@field DeserializeLengthDelimited fun(stream: CitoMemoryStream, instance: Packet_Entities): Packet_Entities
---@field Serialize fun(stream: CitoStream, instance: Packet_Entities): nil
---@field SerializeToBytes fun(instance: Packet_Entities): number[]
---@field SerializeLengthDelimited fun(stream: CitoStream, instance: Packet_Entities): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_EntitiesSerializer = {}
