---@meta Tag2RichTextDelegate
---@class Tag2RichTextDelegate: MulticastDelegate
---@field ctor fun(object: table, method: IntPtr): Tag2RichTextDelegate
---@field Invoke fun(capi: ICoreClientAPI, token: VtmlTagToken, fontStack: Stack`1, didClickLink: any`1): RichTextComponentBase
---@field BeginInvoke fun(capi: ICoreClientAPI, token: VtmlTagToken, fontStack: Stack`1, didClickLink: any`1, callback: AsyncCallback, object: table): IAsyncResult
---@field EndInvoke fun(result: IAsyncResult): RichTextComponentBase
---@field GetObjectData fun(info: SerializationInfo, context: StreamingContext): nil
---@field Equals fun(obj: table): boolean
---@field GetInvocationList fun(): Delegate[]
---@field GetHashCode fun(): number
---@field get_Target fun(): table
---@field Clone fun(): table
---@field DynamicInvoke fun(args: table[]): table
---@field get_Method fun(): MethodInfo
---@field GetType fun(): any
---@field ToString fun(): string
---@field Target table
---@field Method table
Tag2RichTextDelegate = {}
