---@meta UniqueQueue`1
---@class UniqueQueue`1: Object
---@field ctor fun(): UniqueQueue`1
---@field get_Count fun(): number
---@field Clear fun(): nil
---@field Contains fun(item: T): boolean
---@field Enqueue fun(item: T): nil
---@field Dequeue fun(): T
---@field Peek fun(): T
---@field GetEnumerator fun(): IEnumerator`1
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field Count number
UniqueQueue`1 = {}
