---@meta IVertexShaderProgramColormap
---@class IVertexShaderProgramColormap
---@field set_ColorMapRects fun(value: Vec4f): nil
---@field set_SeasonRel fun(value: Single): nil
---@field set_SeaLevel fun(value: Single): nil
---@field set_AtlasHeight fun(value: Single): nil
---@field set_SeasonTemperature fun(value: Single): nil
---@field ColorMapRects Vec4f
---@field SeasonRel Vec4f
---@field SeaLevel Vec4f
---@field AtlasHeight Vec4f
---@field SeasonTemperature Vec4f
IVertexShaderProgramColormap = {}
