---@meta IGameDbConnection
---@class IGameDbConnection
---@field get_IsReadOnly fun(): boolean
---@field OpenOrCreate fun(filename: string, errorMessage: string&, requireWriteAccess: boolean, corruptionProtection: boolean, doIntegrityCheck: boolean): boolean
---@field CreateBackup fun(backupFilename: string): nil
---@field Vacuum fun(): nil
---@field GetAllChunks fun(): any[]
---@field GetAllMapChunks fun(): any[]
---@field GetAllMapRegions fun(): any[]
---@field GetPlayerData fun(playeruid: string): number[]
---@field SetPlayerData fun(playeruid: string, data: number[]): nil
---@field ChunkExists fun(position: UInt64): boolean
---@field MapChunkExists fun(position: UInt64): boolean
---@field MapRegionExists fun(position: UInt64): boolean
---@field GetChunk fun(coord: UInt64): number[]
---@field GetMapChunk fun(coord: UInt64): number[]
---@field GetMapRegion fun(coord: UInt64): number[]
---@field SetChunks fun(chunks: any[]): nil
---@field SetMapChunks fun(mapchunks: any[]): nil
---@field SetMapRegions fun(mapregions: any[]): nil
---@field DeleteChunks fun(chunkpositions: any[]): nil
---@field DeleteMapChunks fun(chunkpositions: any[]): nil
---@field DeleteMapRegions fun(chunkpositions: any[]): nil
---@field GetGameData fun(): number[]
---@field StoreGameData fun(data: number[]): nil
---@field QuickCorrectSaveGameVersionTest fun(): boolean
---@field UpgradeToWriteAccess fun(): nil
---@field IntegrityCheck fun(): boolean
---@field IsReadOnly boolean
IGameDbConnection = {}
