---@meta Packet_BulkEntityDebugAttributes
---@class Packet_BulkEntityDebugAttributes: Object
---@field ctor fun(): Packet_BulkEntityDebugAttributes
---@field GetFullUpdates fun(): Packet_EntityAttributes[]
---@field SetFullUpdates fun(value: Packet_EntityAttributes[], count: number, length: number): nil
---@overload fun(value: Packet_EntityAttributes[]): nil
---@field GetFullUpdatesCount fun(): number
---@field FullUpdatesAdd fun(value: Packet_EntityAttributes): nil
---@field GetPartialUpdates fun(): Packet_EntityAttributeUpdate[]
---@field SetPartialUpdates fun(value: Packet_EntityAttributeUpdate[], count: number, length: number): nil
---@overload fun(value: Packet_EntityAttributeUpdate[]): nil
---@field GetPartialUpdatesCount fun(): number
---@field PartialUpdatesAdd fun(value: Packet_EntityAttributeUpdate): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_BulkEntityDebugAttributes = {}
