---@meta LandClaim
---@class LandClaim: Object
---@field ctor fun(): LandClaim
---@field get_Center fun(): BlockPos
---@field get_SizeXZ fun(): number
---@field get_SizeXYZ fun(): number
---@field CreateClaim fun(player: IPlayer, protectionLevel: number): LandClaim
---@overload fun(entity: EntityAgent, protectionLevel: number): LandClaim
---@overload fun(ownerName: string, protectionLevel: number): LandClaim
---@field TestPlayerAccess fun(player: IPlayer, claimFlag: EnumBlockAccessFlags): EnumPlayerAccessResult
---@field PositionInside fun(position: Vec3d): boolean
---@overload fun(position: BlockPos): boolean
---@field AddArea fun(cuboidi: Cuboidi): EnumClaimError
---@field Intersects fun(cuboidi: Cuboidi): boolean
---@field Intersects2d fun(rec: HorRectanglei): boolean
---@field Clone fun(): LandClaim
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field Center BlockPos
---@field SizeXZ BlockPos
---@field SizeXYZ BlockPos
---@field Areas BlockPos
---@field ProtectionLevel BlockPos
---@field OwnedByEntityId BlockPos
---@field OwnedByPlayerUid BlockPos
---@field OwnedByPlayerGroupUid BlockPos
---@field LastKnownOwnerName BlockPos
---@field Description BlockPos
---@field PermittedPlayerGroupIds BlockPos
---@field PermittedPlayerUids BlockPos
---@field PermittedPlayerLastKnownPlayerName BlockPos
---@field AllowUseEveryone BlockPos
LandClaim = {}
