---@meta Packet_HeldSoundSet
---@class Packet_HeldSoundSet: Object
---@field ctor fun(): Packet_HeldSoundSet
---@field SetIdle fun(value: string): nil
---@field SetEquip fun(value: string): nil
---@field SetUnequip fun(value: string): nil
---@field SetAttack fun(value: string): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_HeldSoundSet = {}
