---@meta Caller
---@class Caller: Object
---@field ctor fun(): Caller
---@field get_Player fun(): IPlayer
---@field set_Player fun(value: IPlayer): nil
---@field get_Entity fun(): Entity
---@field set_Entity fun(value: Entity): nil
---@field HasPrivilege fun(privilege: string): boolean
---@field GetRole fun(sapi: ICoreServerAPI): IPlayerRole
---@field GetName fun(): string
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field Player IPlayer
---@field Entity IPlayer
---@field Type IPlayer
---@field CallerPrivileges IPlayer
---@field CallerRole IPlayer
---@field FromChatGroupId IPlayer
---@field Pos IPlayer
Caller = {}
