---@meta Compression
---@class Compression: Object
---@field ctor fun(): Compression
---@field Reset fun(): nil
---@field Compress fun(data: number[]): number[]
---@field CompressOffset4 fun(data: number[], len: number): number[]
---@field Compress fun(data: number[], version: number): number[]
---@overload fun(data: UInt16[], version: number): number[]
---@overload fun(data: number[], length: number, version: number): number[]
---@overload fun(data: Unumber[], length: number, version: number): number[]
---@field CompressAndCombine fun(data: number[], intdata: number[], intLength: number): number[]
---@field Decompress fun(data: number[]): number[]
---@overload fun(data: number[], offset: number, length: number): number[]
---@overload fun(data: number[], dest: number[], version: number): nil
---@field DecompressToUshort fun(data: number[], container: UInt16[], reusableBytes: number[], version: number): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Compression = {}
