---@meta IServerConfig
---@class IServerConfig
---@field get_Port fun(): number
---@field get_ServerName fun(): string
---@field set_ServerName fun(value: string): nil
---@field get_WelcomeMessage fun(): string
---@field set_WelcomeMessage fun(value: string): nil
---@field get_MaxClients fun(): number
---@field set_MaxClients fun(value: number): nil
---@field get_Password fun(): string
---@field set_Password fun(value: string): nil
---@field get_MaxChunkRadius fun(): number
---@field set_MaxChunkRadius fun(value: number): nil
---@field get_TickTime fun(): Single
---@field set_TickTime fun(value: Single): nil
---@field get_BlockTickChunkRange fun(): number
---@field set_BlockTickChunkRange fun(value: number): nil
---@field get_MaxMainThreadBlockTicks fun(): number
---@field set_MaxMainThreadBlockTicks fun(value: number): nil
---@field get_RandomBlockTicksPerChunk fun(): number
---@field set_RandomBlockTicksPerChunk fun(value: number): nil
---@field get_BlockTickInterval fun(): number
---@field set_BlockTickInterval fun(value: number): nil
---@field get_Roles fun(): any[]
---@field get_DefaultRoleCode fun(): string
---@field set_DefaultRoleCode fun(value: string): nil
---@field get_AntiAbuse fun(): EnumProtectionLevel
---@field set_AntiAbuse fun(value: EnumProtectionLevel): nil
---@field get_OnlyWhitelisted fun(): boolean
---@field set_OnlyWhitelisted fun(value: boolean): nil
---@field get_DefaultSpawn fun(): PlayerSpawnPos
---@field set_DefaultSpawn fun(value: PlayerSpawnPos): nil
---@field get_AllowPvP fun(): boolean
---@field set_AllowPvP fun(value: boolean): nil
---@field get_AllowFireSpread fun(): boolean
---@field set_AllowFireSpread fun(value: boolean): nil
---@field get_AllowFallingBlocks fun(): boolean
---@field set_AllowFallingBlocks fun(value: boolean): nil
---@field get_HostedMode fun(): boolean
---@field set_HostedMode fun(value: boolean): nil
---@field get_HostedModeAllowMods fun(): boolean
---@field set_HostedModeAllowMods fun(value: boolean): nil
---@field get_SpawnCapPlayerScaling fun(): Single
---@field set_SpawnCapPlayerScaling fun(value: Single): nil
---@field Port number
---@field ServerName number
---@field WelcomeMessage number
---@field MaxClients number
---@field Password number
---@field MaxChunkRadius number
---@field TickTime number
---@field BlockTickChunkRange number
---@field MaxMainThreadBlockTicks number
---@field RandomBlockTicksPerChunk number
---@field BlockTickInterval number
---@field Roles number
---@field DefaultRoleCode number
---@field AntiAbuse number
---@field OnlyWhitelisted number
---@field DefaultSpawn number
---@field AllowPvP number
---@field AllowFireSpread number
---@field AllowFallingBlocks number
---@field HostedMode number
---@field HostedModeAllowMods number
---@field SpawnCapPlayerScaling number
IServerConfig = {}
