---@meta Packet_BlockEntitiesSerializer
---@class Packet_BlockEntitiesSerializer: Object
---@field ctor fun(): Packet_BlockEntitiesSerializer
---@field DeserializeLengthDelimitedNew fun(stream: CitoMemoryStream): Packet_BlockEntities
---@field DeserializeBuffer fun(buffer: number[], length: number, instance: Packet_BlockEntities): Packet_BlockEntities
---@field Deserialize fun(stream: CitoMemoryStream, instance: Packet_BlockEntities): Packet_BlockEntities
---@field DeserializeLengthDelimited fun(stream: CitoMemoryStream, instance: Packet_BlockEntities): Packet_BlockEntities
---@field Serialize fun(stream: CitoStream, instance: Packet_BlockEntities): nil
---@field SerializeToBytes fun(instance: Packet_BlockEntities): number[]
---@field SerializeLengthDelimited fun(stream: CitoStream, instance: Packet_BlockEntities): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_BlockEntitiesSerializer = {}
