---@meta Packet_ServerSetBlock
---@class Packet_ServerSetBlock: Object
---@field ctor fun(): Packet_ServerSetBlock
---@field SetX fun(value: number): nil
---@field SetY fun(value: number): nil
---@field SetZ fun(value: number): nil
---@field SetBlockType fun(value: number): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_ServerSetBlock = {}
