---@meta ClientChatLineDelegate
---@class ClientChatLineDelegate: MulticastDelegate
---@field ctor fun(object: table, method: IntPtr): ClientChatLineDelegate
---@field Invoke fun(groupId: number, message: string&, handled: EnumHandling&): nil
---@field BeginInvoke fun(groupId: number, message: string&, handled: EnumHandling&, callback: AsyncCallback, object: table): IAsyncResult
---@field EndInvoke fun(message: string&, handled: EnumHandling&, result: IAsyncResult): nil
---@field GetObjectData fun(info: SerializationInfo, context: StreamingContext): nil
---@field Equals fun(obj: table): boolean
---@field GetInvocationList fun(): Delegate[]
---@field GetHashCode fun(): number
---@field get_Target fun(): table
---@field Clone fun(): table
---@field DynamicInvoke fun(args: table[]): table
---@field get_Method fun(): MethodInfo
---@field GetType fun(): any
---@field ToString fun(): string
---@field Target table
---@field Method table
ClientChatLineDelegate = {}
