---@meta Packet_ServerExchangeBlockSerializer
---@class Packet_ServerExchangeBlockSerializer: Object
---@field ctor fun(): Packet_ServerExchangeBlockSerializer
---@field DeserializeLengthDelimitedNew fun(stream: CitoMemoryStream): Packet_ServerExchangeBlock
---@field DeserializeBuffer fun(buffer: number[], length: number, instance: Packet_ServerExchangeBlock): Packet_ServerExchangeBlock
---@field Deserialize fun(stream: CitoMemoryStream, instance: Packet_ServerExchangeBlock): Packet_ServerExchangeBlock
---@field DeserializeLengthDelimited fun(stream: CitoMemoryStream, instance: Packet_ServerExchangeBlock): Packet_ServerExchangeBlock
---@field Serialize fun(stream: CitoStream, instance: Packet_ServerExchangeBlock): nil
---@field SerializeToBytes fun(instance: Packet_ServerExchangeBlock): number[]
---@field SerializeLengthDelimited fun(stream: CitoStream, instance: Packet_ServerExchangeBlock): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_ServerExchangeBlockSerializer = {}
