---@meta Packet_ServerLevelProgress
---@class Packet_ServerLevelProgress: Object
---@field ctor fun(): Packet_ServerLevelProgress
---@field SetPercentComplete fun(value: number): nil
---@field SetStatus fun(value: string): nil
---@field SetPercentCompleteSubitem fun(value: number): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_ServerLevelProgress = {}
