---@meta Packet_BlockDamage
---@class Packet_BlockDamage: Object
---@field ctor fun(): Packet_BlockDamage
---@field SetPosX fun(value: number): nil
---@field SetPosY fun(value: number): nil
---@field SetPosZ fun(value: number): nil
---@field SetFacing fun(value: number): nil
---@field SetDamage fun(value: number): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_BlockDamage = {}
