---@meta Packet_ClientHandInteractionSerializer
---@class Packet_ClientHandInteractionSerializer: Object
---@field ctor fun(): Packet_ClientHandInteractionSerializer
---@field DeserializeLengthDelimitedNew fun(stream: CitoMemoryStream): Packet_ClientHandInteraction
---@field DeserializeBuffer fun(buffer: number[], length: number, instance: Packet_ClientHandInteraction): Packet_ClientHandInteraction
---@field Deserialize fun(stream: CitoMemoryStream, instance: Packet_ClientHandInteraction): Packet_ClientHandInteraction
---@field DeserializeLengthDelimited fun(stream: CitoMemoryStream, instance: Packet_ClientHandInteraction): Packet_ClientHandInteraction
---@field Serialize fun(stream: CitoStream, instance: Packet_ClientHandInteraction): nil
---@field SerializeToBytes fun(instance: Packet_ClientHandInteraction): number[]
---@field SerializeLengthDelimited fun(stream: CitoStream, instance: Packet_ClientHandInteraction): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_ClientHandInteractionSerializer = {}
