---@meta CompositeShape
---@class CompositeShape: Object
---@field ctor fun(): CompositeShape
---@field get_RotateXYZCopy fun(): Vec3f
---@field get_OffsetXYZCopy fun(): Vec3f
---@field GetHashCode fun(): number
---@field Clone fun(): CompositeShape
---@field CloneWithoutAlternates fun(): CompositeShape
---@field LoadAlternates fun(assetManager: IAssetManager, logger: ILogger): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field RotateXYZCopy Vec3f
---@field OffsetXYZCopy Vec3f
---@field Base Vec3f
---@field Format Vec3f
---@field InsertBakedTextures Vec3f
---@field rotateX Vec3f
---@field rotateY Vec3f
---@field rotateZ Vec3f
---@field offsetX Vec3f
---@field offsetY Vec3f
---@field offsetZ Vec3f
---@field Scale Vec3f
---@field Alternates Vec3f
---@field BakedAlternates Vec3f
---@field Overlays Vec3f
---@field VoxelizeTexture Vec3f
---@field QuantityElements Vec3f
---@field SelectiveElements Vec3f
CompositeShape = {}
