---@meta IServerNetworkAPI
---@class IServerNetworkAPI
---@field RegisterChannel fun(channelName: string): IServerNetworkChannel
---@field GetChannel fun(channelName: string): IServerNetworkChannel
---@field SendBlockEntityPacket fun(player: IServerPlayer, x: number, y: number, z: number, packetId: number, data: number[]): nil
---@field SendEntityPacket fun(player: IServerPlayer, entityid: Int64, packetId: number, data: number[]): nil
---@field BroadcastEntityPacket fun(entityid: Int64, packetId: number, data: number[]): nil
---@field BroadcastBlockEntityPacket fun(x: number, y: number, z: number, packetId: number, data: number[]): nil
---@field SendArbitraryPacket fun(data: number[], players: IServerPlayer[]): nil
---@field BroadcastArbitraryPacket fun(data: number[], exceptPlayers: IServerPlayer[]): nil
---@field SendBlockEntityPacket fun(player: IServerPlayer, pos: BlockPos, packetId: number, data: T): nil
---@overload fun(pos: BlockPos, packetId: number, data: T): nil
IServerNetworkAPI = {}
