---@meta Size3i
---@class Size3i: Object
---@field ctor fun(): Size3i
---@overload fun(width: number, height: number, length: number): Size3i
---@field Clone fun(): Size3i
---@field CanContain fun(obj: Size3i): boolean
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Size3i = {}
