---@meta Packet_EntityInteraction
---@class Packet_EntityInteraction: Object
---@field ctor fun(): Packet_EntityInteraction
---@field SetMouseButton fun(value: number): nil
---@field SetEntityId fun(value: Int64): nil
---@field SetOnBlockFace fun(value: number): nil
---@field SetHitX fun(value: Int64): nil
---@field SetHitY fun(value: Int64): nil
---@field SetHitZ fun(value: Int64): nil
---@field SetSelectionBoxIndex fun(value: number): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_EntityInteraction = {}
