---@meta VtmlTextToken
---@class VtmlTextToken: VtmlToken
---@field ctor fun(): VtmlTextToken
---@field get_StartPosition fun(): number
---@field set_StartPosition fun(value: number): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field StartPosition number
---@field Text number
VtmlTextToken = {}
