---@meta IntAttribute
---@class IntAttribute: ScalarAttribute`1
---@field ctor fun(): IntAttribute
---@overload fun(value: number): IntAttribute
---@field FromBytes fun(stream: BinaryReader): nil
---@field ToBytes fun(stream: BinaryWriter): nil
---@field GetAttributeId fun(): number
---@field Clone fun(): IAttribute
---@field Equals fun(worldForResolve: IWorldAccessor, attr: IAttribute): boolean
---@overload fun(b: table): boolean
---@field GetValue fun(): table
---@field ToString fun(): string
---@field ToJsonToken fun(): string
---@field GetHashCode fun(): number
---@field GetType fun(): any
IntAttribute = {}
