---@meta BlockTypeNet
---@class BlockTypeNet: CollectibleNet
---@field ctor fun(): BlockTypeNet
---@field ReadBlockTypePacket fun(packet: Packet_Blockany, world: IWorldAccessor, registry: ClassRegistry): Block
---@field GetBlockTypePacket fun(block: Block, registry: IClassRegistryAPI): Packet_Blockany
---@field PackSetBlocksList fun(positions: any[], blockAccessor: IBlockAccessor): number[]
---@field PackSetDecorsList fun(chunk: WorldChunk, chunkIndex: Int64, blockAccessor: IBlockAccessor): number[]
---@field UnpackSetDecors fun(data: number[], worldAccessor: IWorldAccessor, chunkIndex: Int64&): table<any, any>
---@field UnpackSetBlocks fun(setBlocks: number[], liquidsLayer: number[]&): KeyValuePair`2
---@field PackBlocksPositions fun(positions: any[]): number[]
---@field UnpackBlockPositions fun(setBlocks: number[]): BlockPos[]
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
BlockTypeNet = {}
