---@meta ModDependency
---@class ModDependency: Object
---@field ctor fun(modID: string, version: string): ModDependency
---@field get_ModID fun(): string
---@field get_Version fun(): string
---@field ToString fun(): string
---@field GetType fun(): any
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field ModID string
---@field Version string
ModDependency = {}
