---@meta Packet_BlockEntityPacket
---@class Packet_BlockEntityPacket: Object
---@field ctor fun(): Packet_BlockEntityPacket
---@field SetX fun(value: number): nil
---@field SetY fun(value: number): nil
---@field SetZ fun(value: number): nil
---@field SetPacketid fun(value: number): nil
---@field SetData fun(value: number[]): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_BlockEntityPacket = {}
