---@meta AssetManager
---@class AssetManager: Object
---@field ctor fun(assetsPath: string, side: EnumAppSide): AssetManager
---@field get_AllAssets fun(): table<any, any>
---@field Add fun(path: AssetLocation, asset: IAsset): nil
---@field InitAndLoadBaseAssets fun(Logger: ILogger): number
---@field AddExternalAssets fun(Logger: ILogger, modloader: ModLoader): number
---@field UnloadExternalAssets fun(logger: ILogger): nil
---@field UnloadAssets fun(category: AssetCategory): nil
---@overload fun(): nil
---@field GetLocations fun(fullPathBeginsWith: string, domain: string): any[]
---@field Exists fun(location: AssetLocation): boolean
---@field TryGet fun(Path: string, loadAsset: boolean): IAsset
---@overload fun(Location: AssetLocation, loadAsset: boolean): IAsset
---@field TryGet_BaseAssets fun(Path: string, loadAsset: boolean): IAsset
---@overload fun(Location: AssetLocation, loadAsset: boolean): IAsset
---@field Get fun(Path: string): IAsset
---@overload fun(Location: AssetLocation): IAsset
---@overload fun(Location: AssetLocation): T
---@field GetMany fun(category: AssetCategory, loadAsset: boolean): any[]
---@field GetManyInCategory fun(categoryCode: string, pathBegins: string, domain: string, loadAsset: boolean): any[]
---@field GetMany fun(partialPath: string, domain: string, loadAsset: boolean): any[]
---@overload fun(logger: ILogger, fullPath: string, domain: string): table<any, any>
---@field Reload fun(location: AssetLocation): number
---@overload fun(category: AssetCategory): number
---@field GetCategoryFromFullPath fun(fullpath: string): AssetCategory
---@field AddPathOrigin fun(domain: string, fullPath: string): nil
---@field AddModOrigin fun(domain: string, fullPath: string): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field AllAssets table<any, any>
---@field allAssetsLoaded table<any, any>
---@field Assets table<any, any>
---@field RuntimeAssets table<any, any>
---@field Origins table<any, any>
---@field CustomAppOrigins table<any, any>
---@field CustomModOrigins table<any, any>
AssetManager = {}
