---@meta TransitionableProperties
---@class TransitionableProperties: Object
---@field ctor fun(): TransitionableProperties
---@field Clone fun(): TransitionableProperties
---@field ToBytes fun(writer: BinaryWriter): nil
---@field FromBytes fun(reader: BinaryReader, instancer: IClassRegistryAPI): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
TransitionableProperties = {}
