---@meta MacroManager
---@class MacroManager: Object
---@field ctor fun(game: ClientMain): MacroManager
---@field get_MacrosByIndex fun(): Sortedtable<any, any>
---@field set_MacrosByIndex fun(value: Sortedtable<any, any>): nil
---@field LoadMacros fun(): nil
---@field DeleteMacro fun(macroIndex: number): nil
---@field SetMacro fun(macroIndex: number, macro: IMacroBase): nil
---@field SaveMacro fun(macroIndex: number): boolean
---@field RunMacro fun(macroIndex: number, world: IClientWorldAccessor): boolean
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field MacrosByIndex Sortedtable<any, any>
MacroManager = {}
