---@meta Packet_ActivateInventorySlot
---@class Packet_ActivateInventorySlot: Object
---@field ctor fun(): Packet_ActivateInventorySlot
---@field SetMouseButton fun(value: number): nil
---@field SetModifiers fun(value: number): nil
---@field SetTargetInventoryId fun(value: string): nil
---@field SetTargetSlot fun(value: number): nil
---@field SetTargetLastChanged fun(value: Int64): nil
---@field SetTabIndex fun(value: number): nil
---@field SetPriority fun(value: number): nil
---@field SetDir fun(value: number): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_ActivateInventorySlot = {}
