---@meta IPlayer
---@class IPlayer
---@field get_Role fun(): IPlayerRole
---@field set_Role fun(value: IPlayerRole): nil
---@field get_Groups fun(): PlayerGroupMembership[]
---@field GetGroups fun(): PlayerGroupMembership[]
---@field GetGroup fun(groupId: number): PlayerGroupMembership
---@field get_Entitlements fun(): any[]
---@field get_CurrentBlockSelection fun(): BlockSelection
---@field get_CurrentEntitySelection fun(): EntitySelection
---@field get_PlayerName fun(): string
---@field get_PlayerUID fun(): string
---@field get_ClientId fun(): number
---@field get_Entity fun(): EntityPlayer
---@field get_WorldData fun(): IWorldPlayerData
---@field get_InventoryManager fun(): IPlayerInventoryManager
---@field get_Privileges fun(): string[]
---@field get_ImmersiveFpMode fun(): boolean
---@field HasPrivilege fun(privilegeCode: string): boolean
---@field Role IPlayerRole
---@field Groups IPlayerRole
---@field Entitlements IPlayerRole
---@field CurrentBlockSelection IPlayerRole
---@field CurrentEntitySelection IPlayerRole
---@field PlayerName IPlayerRole
---@field PlayerUID IPlayerRole
---@field ClientId IPlayerRole
---@field Entity IPlayerRole
---@field WorldData IPlayerRole
---@field InventoryManager IPlayerRole
---@field Privileges IPlayerRole
---@field ImmersiveFpMode IPlayerRole
IPlayer = {}
