---@meta GuiJsonDialog
---@class GuiJsonDialog: GuiDialogGeneric
---@field ctor fun(settings: JsonDialogSettings, capi: ICoreClientAPI): GuiJsonDialog
---@overload fun(settings: JsonDialogSettings, capi: ICoreClientAPI, focusFirstElement: boolean): GuiJsonDialog
---@field get_DebugName fun(): string
---@field get_ToggleKeyCombinationCode fun(): string
---@field Recompose fun(): nil
---@field get_PrefersUngrabbedMouse fun(): boolean
---@field ComposeDialog fun(focusFirstElement: boolean): nil
---@field OnMouseDown fun(args: MouseEvent): nil
---@field OnMouseUp fun(args: MouseEvent): nil
---@field ReloadValues fun(): nil
---@field get_UnregisterOnClose fun(): boolean
---@field get_Attributes fun(): ITreeAttribute
---@field UnfocusElements fun(): nil
---@field FocusElement fun(index: number): nil
---@field IsInRangeOfBlock fun(blockEntityPos: BlockPos): boolean
---@field get_SingleComposer fun(): GuiComposer
---@field set_SingleComposer fun(value: GuiComposer): nil
---@field get_ZSize fun(): Single
---@field get_Focused fun(): boolean
---@field get_Focusable fun(): boolean
---@field get_DialogType fun(): EnumDialogany
---@field add_OnOpened fun(value: Action): nil
---@field remove_OnOpened fun(value: Action): nil
---@field add_OnClosed fun(value: Action): nil
---@field remove_OnClosed fun(value: Action): nil
---@field OnBlockTexturesLoaded fun(): nil
---@field OnLevelFinalize fun(): nil
---@field OnOwnPlayerDataReceived fun(): nil
---@field get_DrawOrder fun(): Double
---@field get_InputOrder fun(): Double
---@field OnGuiOpened fun(): nil
---@field OnGuiClosed fun(): nil
---@field TryOpen fun(): boolean
---@overload fun(withFocus: boolean): boolean
---@field TryClose fun(): boolean
---@field UnFocus fun(): nil
---@field Focus fun(): nil
---@field Toggle fun(): nil
---@field IsOpened fun(): boolean
---@overload fun(dialogComposerName: string): boolean
---@field OnBeforeRenderFrame3D fun(deltaTime: Single): nil
---@field OnRenderGUI fun(deltaTime: Single): nil
---@field OnFinalizeFrame fun(dt: Single): nil
---@field OnKeyDown fun(args: KeyEvent): nil
---@field OnKeyPress fun(args: KeyEvent): nil
---@field OnKeyUp fun(args: KeyEvent): nil
---@field OnEscapePressed fun(): boolean
---@field OnMouseEnterSlot fun(slot: ItemSlot): boolean
---@field OnMouseLeaveSlot fun(itemSlot: ItemSlot): boolean
---@field OnMouseClickSlot fun(itemSlot: ItemSlot): boolean
---@field OnMouseMove fun(args: MouseEvent): nil
---@field OnMouseWheel fun(args: MouseWheelEventArgs): nil
---@field ShouldReceiveRenderEvents fun(): boolean
---@field ShouldReceiveKeyboardEvents fun(): boolean
---@field ShouldReceiveMouseEvents fun(): boolean
---@field RequiresUngrabbedMouse fun(): boolean
---@field get_DisableMouseGrab fun(): boolean
---@field CaptureAllInputs fun(): boolean
---@field CaptureRawMouse fun(): boolean
---@field Dispose fun(): nil
---@field ClearComposers fun(): nil
---@field IsInRangeOf fun(pos: Vec3d): boolean
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field DebugName string
---@field ToggleKeyCombinationCode string
---@field PrefersUngrabbedMouse string
---@field UnregisterOnClose string
---@field Attributes string
---@field SingleComposer string
---@field ZSize string
---@field Focused string
---@field Focusable string
---@field DialogType string
---@field DrawOrder string
---@field InputOrder string
---@field DisableMouseGrab string
---@field OnOpened string
---@field OnClosed string
---@field DialogTitle string
---@field Composers string
---@field ignoreNextKeyPress string
---@field MouseOverCursor string
GuiJsonDialog = {}
