---@meta GuiScreenRunningGame
---@class GuiScreenRunningGame: GuiScreen
---@field ctor fun(screenManager: ScreenManager, parent: GuiScreen): GuiScreenRunningGame
---@field OnEvent fun(eventCode: string, arg: table): boolean
---@field Start fun(singleplayer: boolean, serverargs: StartServerArgs, connectData: ServerConnectData): nil
---@field RenderToPrimary fun(dt: Single): nil
---@field RenderAfterPostProcessing fun(dt: Single): nil
---@field RenderAfterFinalComposition fun(dt: Single): nil
---@field RenderAfterBlit fun(dt: Single): nil
---@field RenderToDefaultFramebuffer fun(dt: Single): nil
---@field OnWindowClosed fun(): nil
---@field ReloadWorld fun(reason: string): nil
---@field ExitOrRedirect fun(isDisconnect: boolean, reason: string): nil
---@field OnKeyDown fun(args: KeyEvent): nil
---@field OnKeyUp fun(args: KeyEvent): nil
---@field OnKeyPress fun(args: KeyEvent): nil
---@field OnMouseDown fun(args: MouseEvent): nil
---@field OnMouseMove fun(args: MouseEvent): nil
---@field OnMouseUp fun(args: MouseEvent): nil
---@field OnMouseWheel fun(args: MouseWheelEventArgs): nil
---@field OnFileDrop fun(filename: string): boolean
---@field OnFocusChanged fun(focus: boolean): nil
---@field get_ShouldDisposePreviousScreen fun(): boolean
---@field get_IsOpened fun(): boolean
---@field get_RenderBg fun(): boolean
---@field set_RenderBg fun(value: boolean): nil
---@field BubbleUpEvent fun(eventCode: string): nil
---@field Refresh fun(): nil
---@field BubbleUpEvent fun(eventCode: string, arg: table): nil
---@field OnBackPressed fun(): boolean
---@field OnScreenUnload fun(): nil
---@field OnScreenLoaded fun(): nil
---@field Dispose fun(): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field ShouldDisposePreviousScreen boolean
---@field IsOpened boolean
---@field RenderBg boolean
---@field serverargs boolean
---@field ElementComposer boolean
---@field ScreenManager boolean
---@field ParentScreen boolean
---@field ShowMainMenu boolean
---@field UnfocusedMouseCursor boolean
---@field FocusedMouseCursor boolean
GuiScreenRunningGame = {}
