---@meta ItemSlotCreative
---@class ItemSlotCreative: ItemSlot
---@field ctor fun(inventory: InventoryBase): ItemSlotCreative
---@field TakeOutWhole fun(): ItemStack
---@field TakeOut fun(quantity: number): ItemStack
---@field TryPutInto fun(sinkSlot: ItemSlot, op: ItemStackMoveOperation&): number
---@field TryFlipWith fun(itemSlot: ItemSlot): boolean
---@field OnItemSlotModified fun(sinkStack: ItemStack): nil
---@field add_MarkedDirty fun(value: ActionConsumable): nil
---@field remove_MarkedDirty fun(value: ActionConsumable): nil
---@field get_MaxSlotStackSize fun(): number
---@field set_MaxSlotStackSize fun(value: number): nil
---@field get_Inventory fun(): InventoryBase
---@field get_DrawUnavailable fun(): boolean
---@field set_DrawUnavailable fun(value: boolean): nil
---@field get_Itemstack fun(): ItemStack
---@field set_Itemstack fun(value: ItemStack): nil
---@field get_StackSize fun(): number
---@field get_Empty fun(): boolean
---@field get_StorageType fun(): EnumItemStorageFlags
---@field set_StorageType fun(value: EnumItemStorageFlags): nil
---@field GetRemainingSlotSpace fun(forItemstack: ItemStack): number
---@field CanTakeFrom fun(sourceSlot: ItemSlot, priority: EnumMergePriority): boolean
---@field CanHold fun(sourceSlot: ItemSlot): boolean
---@field CanTake fun(): boolean
---@field TryPutInto fun(world: IWorldAccessor, sinkSlot: ItemSlot, quantity: number): number
---@field ActivateSlot fun(sourceSlot: ItemSlot, op: ItemStackMoveOperation&): nil
---@field MarkDirty fun(): nil
---@field GetStackName fun(): string
---@field GetStackDescription fun(world: IClientWorldAccessor, extendedDebugInfo: boolean): string
---@field ToString fun(): string
---@field GetType fun(): any
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field MaxSlotStackSize number
---@field Inventory number
---@field DrawUnavailable number
---@field Itemstack number
---@field StackSize number
---@field Empty number
---@field StorageType number
---@field MarkedDirty number
---@field BackgroundIcon number
---@field HexBackgroundColor number
ItemSlotCreative = {}
