---@meta Packet_CubeSerializer
---@class Packet_CubeSerializer: Object
---@field ctor fun(): Packet_CubeSerializer
---@field DeserializeLengthDelimitedNew fun(stream: CitoMemoryStream): Packet_Cube
---@field DeserializeBuffer fun(buffer: number[], length: number, instance: Packet_Cube): Packet_Cube
---@field Deserialize fun(stream: CitoMemoryStream, instance: Packet_Cube): Packet_Cube
---@field DeserializeLengthDelimited fun(stream: CitoMemoryStream, instance: Packet_Cube): Packet_Cube
---@field Serialize fun(stream: CitoStream, instance: Packet_Cube): nil
---@field SerializeToBytes fun(instance: Packet_Cube): number[]
---@field SerializeLengthDelimited fun(stream: CitoStream, instance: Packet_Cube): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_CubeSerializer = {}
