---@meta Packet_ActivateInventorySlotSerializer
---@class Packet_ActivateInventorySlotSerializer: Object
---@field ctor fun(): Packet_ActivateInventorySlotSerializer
---@field DeserializeLengthDelimitedNew fun(stream: CitoMemoryStream): Packet_ActivateInventorySlot
---@field DeserializeBuffer fun(buffer: number[], length: number, instance: Packet_ActivateInventorySlot): Packet_ActivateInventorySlot
---@field Deserialize fun(stream: CitoMemoryStream, instance: Packet_ActivateInventorySlot): Packet_ActivateInventorySlot
---@field DeserializeLengthDelimited fun(stream: CitoMemoryStream, instance: Packet_ActivateInventorySlot): Packet_ActivateInventorySlot
---@field Serialize fun(stream: CitoStream, instance: Packet_ActivateInventorySlot): nil
---@field SerializeToBytes fun(instance: Packet_ActivateInventorySlot): number[]
---@field SerializeLengthDelimited fun(stream: CitoStream, instance: Packet_ActivateInventorySlot): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_ActivateInventorySlotSerializer = {}
