---@meta TcpConnection
---@class TcpConnection: Object
---@field ctor fun(s: Socket): TcpConnection
---@field add_ReceivedMessage fun(value: EventHandler`1): nil
---@field remove_ReceivedMessage fun(value: EventHandler`1): nil
---@field add_Disconnected fun(value: EventHandler`1): nil
---@field remove_Disconnected fun(value: EventHandler`1): nil
---@field BeginReceive fun(): nil
---@field Send fun(data: number[], compressedFlag: boolean): EnumSendResult
---@field SendPreparedBytes fun(dataWithLength: number[], length: number, compressedFlag: boolean): EnumSendResult
---@field ToString fun(): string
---@field GetType fun(): any
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
TcpConnection = {}
