---@meta IGuiAPI
---@class IGuiAPI
---@field get_QuadMeshRef fun(): MeshRef
---@field get_LoadedGuis fun(): any[]
---@field get_OpenedGuis fun(): any[]
---@field get_TextTexture fun(): TextTextureUtil
---@field get_Text fun(): TextDrawUtil
---@field get_Icons fun(): IconUtil
---@field get_WindowBounds fun(): ElementBounds
---@field GetDialogBoundsInArea fun(area: EnumDialogArea): any[]
---@field CreateCompo fun(dialogName: string, bounds: ElementBounds): GuiComposer
---@field RegisterDialog fun(dialogs: GuiDialog[]): nil
---@field DeleteTexture fun(textureid: number): nil
---@field LoadSvg fun(loc: AssetLocation, textureWidth: number, textureHeight: number, width: number, height: number, color: Nullable`1): LoadedTexture
---@field DrawSvg fun(svgAsset: IAsset, intoSurface: ImageSurface, posx: number, posy: number, width: number, height: number, color: Nullable`1): nil
---@overload fun(svgAsset: IAsset, intoSurface: ImageSurface, transform: Matrix, posx: number, posy: number, width: number, height: number, color: Nullable`1): nil
---@field LoadSvgWithPadding fun(loc: AssetLocation, textureWidth: number, textureHeight: number, padding: number, color: Nullable`1): LoadedTexture
---@field LoadCairoTexture fun(surface: ImageSurface, linearMag: boolean): number
---@field LoadOrUpdateCairoTexture fun(surface: ImageSurface, linearMag: boolean, intoTexture: LoadedTexture&): nil
---@field GetDialogPosition fun(key: string): Vec2i
---@field SetDialogPosition fun(key: string, pos: Vec2i): nil
---@field PlaySound fun(soundname: string, randomizePitch: boolean, volume: Single): nil
---@overload fun(soundname: AssetLocation, randomizePitch: boolean, volume: Single): nil
---@field RequestFocus fun(guiDialog: GuiDialog): nil
---@field TriggerDialogOpened fun(guiDialog: GuiDialog): nil
---@field TriggerDialogClosed fun(guiDialog: GuiDialog): nil
---@field OpenLink fun(href: string): nil
---@field QuadMeshRef MeshRef
---@field LoadedGuis MeshRef
---@field OpenedGuis MeshRef
---@field TextTexture MeshRef
---@field Text MeshRef
---@field Icons MeshRef
---@field WindowBounds MeshRef
IGuiAPI = {}
