---@meta QuadMeshUtil
---@class QuadMeshUtil: Object
---@field ctor fun(): QuadMeshUtil
---@field GetQuad fun(): MeshData
---@field GetCustomQuadModelData fun(x: Single, y: Single, z: Single, dw: Single, dh: Single): MeshData
---@field GetCustomQuad fun(x: Single, y: Single, z: Single, width: Single, height: Single, r: number, g: number, b: number, a: number): MeshData
---@field GetCustomQuadHorizontal fun(x: Single, y: Single, z: Single, width: Single, length: Single, r: number, g: number, b: number, a: number): MeshData
---@field GetCustomQuadModelData fun(u: Single, v: Single, u2: Single, v2: Single, dx: Single, dy: Single, dw: Single, dh: Single, r: number, g: number, b: number, a: number): MeshData
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
QuadMeshUtil = {}
