---@meta IServerEventAPI
---@class IServerEventAPI
---@field GetRegisteredWorldGenHandlers fun(worldType: string): IWorldGenHandler
---@field TriggerTrySpawnEntity fun(blockAccessor: IBlockAccessor, properties: EntityProperties&, position: Vec3d, herdId: Int64): boolean
---@field GetWorldgenBlockAccessor fun(handler: WorldGenThreadDelegate): nil
---@field InitWorldGenerator fun(handler: Action, forWorldType: string): nil
---@field MapChunkGeneration fun(handler: MapChunkGeneratorDelegate, forWorldType: string): nil
---@field MapRegionGeneration fun(handler: MapRegionGeneratorDelegate, forWorldType: string): nil
---@field ChunkColumnGeneration fun(handler: ChunkColumnGenerationDelegate, pass: EnumWorldGenPass, forWorldType: string): nil
---@field WorldgenHook fun(handler: WorldGenHookDelegate, forWorldType: string, hook: string): nil
---@field TriggerWorldgenHook fun(hook: string, blockAccessor: IBlockAccessor, pos: BlockPos, loc: AssetLocation): nil
---@field add_BeginChunkColumnLoadChunkThread fun(value: ChunkColumnBeginLoadChunkThread): nil
---@field remove_BeginChunkColumnLoadChunkThread fun(value: ChunkColumnBeginLoadChunkThread): nil
---@field add_ChunkColumnLoaded fun(value: ChunkColumnLoadedDelegate): nil
---@field remove_ChunkColumnLoaded fun(value: ChunkColumnLoadedDelegate): nil
---@field add_ChunkColumnUnloaded fun(value: ChunkColumnUnloadDelegate): nil
---@field remove_ChunkColumnUnloaded fun(value: ChunkColumnUnloadDelegate): nil
---@field add_CanUseBlock fun(value: CanUseDelegate): nil
---@field remove_CanUseBlock fun(value: CanUseDelegate): nil
---@field add_OnTrySpawnEntity fun(value: TrySpawnEntityDelegate): nil
---@field remove_OnTrySpawnEntity fun(value: TrySpawnEntityDelegate): nil
---@field add_OnPlayerInteractEntity fun(value: OnInteractDelegate): nil
---@field remove_OnPlayerInteractEntity fun(value: OnInteractDelegate): nil
---@field add_PlayerCreate fun(value: PlayerDelegate): nil
---@field remove_PlayerCreate fun(value: PlayerDelegate): nil
---@field add_PlayerRespawn fun(value: PlayerDelegate): nil
---@field remove_PlayerRespawn fun(value: PlayerDelegate): nil
---@field add_PlayerJoin fun(value: PlayerDelegate): nil
---@field remove_PlayerJoin fun(value: PlayerDelegate): nil
---@field add_PlayerNowPlaying fun(value: PlayerDelegate): nil
---@field remove_PlayerNowPlaying fun(value: PlayerDelegate): nil
---@field add_PlayerLeave fun(value: PlayerDelegate): nil
---@field remove_PlayerLeave fun(value: PlayerDelegate): nil
---@field add_PlayerDisconnect fun(value: PlayerDelegate): nil
---@field remove_PlayerDisconnect fun(value: PlayerDelegate): nil
---@field add_PlayerChat fun(value: PlayerChatDelegate): nil
---@field remove_PlayerChat fun(value: PlayerChatDelegate): nil
---@field add_PlayerDeath fun(value: PlayerDeathDelegate): nil
---@field remove_PlayerDeath fun(value: PlayerDeathDelegate): nil
---@field add_PlayerSwitchGameMode fun(value: PlayerDelegate): nil
---@field remove_PlayerSwitchGameMode fun(value: PlayerDelegate): nil
---@field add_BeforeActiveSlotChanged fun(value: Func`3): nil
---@field remove_BeforeActiveSlotChanged fun(value: Func`3): nil
---@field add_AfterActiveSlotChanged fun(value: Action`2): nil
---@field remove_AfterActiveSlotChanged fun(value: Action`2): nil
---@field add_AssetsFinalizers fun(value: Action): nil
---@field remove_AssetsFinalizers fun(value: Action): nil
---@field add_SaveGameLoaded fun(value: Action): nil
---@field remove_SaveGameLoaded fun(value: Action): nil
---@field add_SaveGameCreated fun(value: Action): nil
---@field remove_SaveGameCreated fun(value: Action): nil
---@field add_WorldgenStartup fun(value: Action): nil
---@field remove_WorldgenStartup fun(value: Action): nil
---@field add_GameWorldSave fun(value: Action): nil
---@field remove_GameWorldSave fun(value: Action): nil
---@field add_ServerSuspend fun(value: SuspendServerDelegate): nil
---@field remove_ServerSuspend fun(value: SuspendServerDelegate): nil
---@field add_ServerResume fun(value: ResumeServerDelegate): nil
---@field remove_ServerResume fun(value: ResumeServerDelegate): nil
---@field ServerRunPhase fun(runPhase: EnumServerRunPhase, handler: Action): nil
---@field Timer fun(handler: Action, interval: Double): nil
---@field add_DidPlaceBlock fun(value: BlockPlacedDelegate): nil
---@field remove_DidPlaceBlock fun(value: BlockPlacedDelegate): nil
---@field add_CanPlaceOrBreakBlock fun(value: CanPlaceOrBreakDelegate): nil
---@field remove_CanPlaceOrBreakBlock fun(value: CanPlaceOrBreakDelegate): nil
---@field add_BreakBlock fun(value: BlockBreakDelegate): nil
---@field remove_BreakBlock fun(value: BlockBreakDelegate): nil
---@field add_DidBreakBlock fun(value: BlockBrokenDelegate): nil
---@field remove_DidBreakBlock fun(value: BlockBrokenDelegate): nil
---@field add_DidUseBlock fun(value: BlockUsedDelegate): nil
---@field remove_DidUseBlock fun(value: BlockUsedDelegate): nil
IServerEventAPI = {}
