---@meta GlobalConstants
---@class GlobalConstants: Object
---@field ctor fun(): GlobalConstants
---@field OutsideWorld fun(x: number, y: number, z: number, blockAccessor: IBlockAccessor): boolean
---@overload fun(x: Double, y: Double, z: Double, blockAccessor: IBlockAccessor): boolean
---@field get_FoodSpoilHealthLossMulHandler fun(): FoodSpoilageCalcDelegate
---@field get_FoodSpoilSatLossMulHandler fun(): FoodSpoilageCalcDelegate
---@field FoodSpoilageHealthLossMul fun(spoilState: Single, stack: ItemStack, byEntity: EntityAgent): Single
---@field FoodSpoilageSatLossMul fun(spoilState: Single, stack: ItemStack, byEntity: EntityAgent): Single
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field FoodSpoilHealthLossMulHandler FoodSpoilageCalcDelegate
---@field FoodSpoilSatLossMulHandler FoodSpoilageCalcDelegate
---@field DefaultCultureInfo FoodSpoilageCalcDelegate
---@field MaxAnimatedElements FoodSpoilageCalcDelegate
---@field CaveArtColsPerRow FoodSpoilageCalcDelegate
---@field PhysicsFrameTime FoodSpoilageCalcDelegate
---@field MaxPhysicsIntervalInSlowTicks FoodSpoilageCalcDelegate
---@field GravityStrengthParticle FoodSpoilageCalcDelegate
---@field DefaultAttackRange FoodSpoilageCalcDelegate
---@field OverallSpeedMultiplier FoodSpoilageCalcDelegate
---@field BaseMoveSpeed FoodSpoilageCalcDelegate
---@field BaseJumpForce FoodSpoilageCalcDelegate
---@field SneakSpeedMultiplier FoodSpoilageCalcDelegate
---@field SprintSpeedMultiplier FoodSpoilageCalcDelegate
---@field AirDragAlways FoodSpoilageCalcDelegate
---@field AirDragFlying FoodSpoilageCalcDelegate
---@field WaterDrag FoodSpoilageCalcDelegate
---@field GravityPerSecond FoodSpoilageCalcDelegate
---@field DefaultSimulationRange FoodSpoilageCalcDelegate
---@field DefaultPickingRange FoodSpoilageCalcDelegate
---@field TimeToDespawnPlayerInventoryDrops FoodSpoilageCalcDelegate
---@field CurrentWindSpeedClient FoodSpoilageCalcDelegate
---@field CurrentDistanceToRainfallClient FoodSpoilageCalcDelegate
---@field CurrentNearbyRelLeavesCountClient FoodSpoilageCalcDelegate
---@field MeltingFreezingEnabled FoodSpoilageCalcDelegate
---@field GuiGearRotJitter FoodSpoilageCalcDelegate
---@field playerColorByEntitlement FoodSpoilageCalcDelegate
---@field playerTagBackgroundByEntitlement FoodSpoilageCalcDelegate
---@field DefaultChatGroups FoodSpoilageCalcDelegate
---@field GeneralChatGroup FoodSpoilageCalcDelegate
---@field ServerInfoChatGroup FoodSpoilageCalcDelegate
---@field DamageLogChatGroup FoodSpoilageCalcDelegate
---@field InfoLogChatGroup FoodSpoilageCalcDelegate
---@field CurrentChatGroup FoodSpoilageCalcDelegate
---@field AllChatGroups FoodSpoilageCalcDelegate
---@field ConsoleGroup FoodSpoilageCalcDelegate
---@field AllowedChatGroupChars FoodSpoilageCalcDelegate
---@field SinglePlayerEntitlements FoodSpoilageCalcDelegate
---@field EntityItemTypeCode FoodSpoilageCalcDelegate
---@field EntityPlayerTypeCode FoodSpoilageCalcDelegate
---@field EntityBlockFallingTypeCode FoodSpoilageCalcDelegate
---@field IgnoredStackAttributes FoodSpoilageCalcDelegate
---@field PerishSpeedModifier FoodSpoilageCalcDelegate
---@field HungerSpeedModifier FoodSpoilageCalcDelegate
---@field CreatureDamageModifier FoodSpoilageCalcDelegate
---@field ToolMiningSpeedModifier FoodSpoilageCalcDelegate
---@field DefaultDomain FoodSpoilageCalcDelegate
---@field MaxWorldSizeXZ FoodSpoilageCalcDelegate
---@field MaxWorldSizeY FoodSpoilageCalcDelegate
---@field ChunkSize FoodSpoilageCalcDelegate
---@field DimensionSizeInChunks FoodSpoilageCalcDelegate
---@field MaxColorMaps FoodSpoilageCalcDelegate
---@field MaxViewDistanceForLodBiases FoodSpoilageCalcDelegate
---@field WorldSaveExtension FoodSpoilageCalcDelegate
---@field hotBarInvClassName FoodSpoilageCalcDelegate
---@field creativeInvClassName FoodSpoilageCalcDelegate
---@field backpackInvClassName FoodSpoilageCalcDelegate
---@field groundInvClassName FoodSpoilageCalcDelegate
---@field mousecursorInvClassName FoodSpoilageCalcDelegate
---@field characterInvClassName FoodSpoilageCalcDelegate
---@field craftingInvClassName FoodSpoilageCalcDelegate
GlobalConstants = {}
