---@meta SetSettingDelegate
---@class SetSettingDelegate: MulticastDelegate
---@field ctor fun(object: table, method: IntPtr): SetSettingDelegate
---@field Invoke fun(session: IntPtr, profile: IntPtr, setting: OptimusSetting&): number
---@field BeginInvoke fun(session: IntPtr, profile: IntPtr, setting: OptimusSetting&, callback: AsyncCallback, object: table): IAsyncResult
---@field EndInvoke fun(setting: OptimusSetting&, result: IAsyncResult): number
---@field GetObjectData fun(info: SerializationInfo, context: StreamingContext): nil
---@field Equals fun(obj: table): boolean
---@field GetInvocationList fun(): Delegate[]
---@field GetHashCode fun(): number
---@field get_Target fun(): table
---@field Clone fun(): table
---@field DynamicInvoke fun(args: table[]): table
---@field get_Method fun(): MethodInfo
---@field GetType fun(): any
---@field ToString fun(): string
---@field Target table
---@field Method table
SetSettingDelegate = {}
