---@meta ICryptoTransform
---@class ICryptoTransform
---@field get_InputBlockSize fun(): number
---@field get_OutputBlockSize fun(): number
---@field get_CanTransformMultipleBlocks fun(): boolean
---@field get_CanReuseTransform fun(): boolean
---@field TransformBlock fun(inputBuffer: number[], inputOffset: number, inputCount: number, outputBuffer: number[], outputOffset: number): number
---@field TransformFinalBlock fun(inputBuffer: number[], inputOffset: number, inputCount: number): number[]
---@field InputBlockSize number
---@field OutputBlockSize number
---@field CanTransformMultipleBlocks number
---@field CanReuseTransform number
ICryptoTransform = {}
