---@meta ClientPlayer
---@class ClientPlayer: Object
---@field ctor fun(game: ClientMain): ClientPlayer
---@field get_Role fun(): IPlayerRole
---@field set_Role fun(value: IPlayerRole): nil
---@field get_PlayerUID fun(): string
---@field get_ClientId fun(): number
---@field get_Entity fun(): EntityPlayer
---@field get_InventoryManager fun(): IPlayerInventoryManager
---@field get_PlayerName fun(): string
---@field get_WorldData fun(): IWorldPlayerData
---@field get_SpawnPosition fun(): BlockPos
---@field set_SpawnPosition fun(value: BlockPos): nil
---@field get_CameraYaw fun(): Single
---@field set_CameraYaw fun(value: Single): nil
---@field get_CameraPitch fun(): Single
---@field set_CameraPitch fun(value: Single): nil
---@field get_CameraRoll fun(): Single
---@field set_CameraRoll fun(value: Single): nil
---@field get_CameraMode fun(): EnumCameraMode
---@field get_Entitlements fun(): any[]
---@field set_Entitlements fun(value: any[]): nil
---@field get_ImmersiveFpMode fun(): boolean
---@field UpdateFromPacket fun(game: ClientMain, packet: Packet_PlayerData): nil
---@overload fun(game: ClientMain, mode: Packet_PlayerMode): nil
---@field ShowChatNotification fun(message: string): nil
---@field TriggerFpAnimation fun(anim: EnumHandInteract): nil
---@field GetGroups fun(): PlayerGroupMembership[]
---@field GetGroup fun(groupId: number): PlayerGroupMembership
---@field get_Groups fun(): PlayerGroupMembership[]
---@field HasPrivilege fun(privilegeCode: string): boolean
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field Role IPlayerRole
---@field PlayerUID IPlayerRole
---@field ClientId IPlayerRole
---@field Entity IPlayerRole
---@field InventoryManager IPlayerRole
---@field PlayerName IPlayerRole
---@field WorldData IPlayerRole
---@field SpawnPosition IPlayerRole
---@field CameraYaw IPlayerRole
---@field CameraPitch IPlayerRole
---@field CameraRoll IPlayerRole
---@field CameraMode IPlayerRole
---@field Entitlements IPlayerRole
---@field ImmersiveFpMode IPlayerRole
---@field Groups IPlayerRole
---@field Privileges IPlayerRole
---@field RoleCode IPlayerRole
---@field Ping IPlayerRole
---@field OverrideCameraMode IPlayerRole
ClientPlayer = {}
