---@meta CraftingRecipeIngredient
---@class CraftingRecipeIngredient: Object
---@field ctor fun(): CraftingRecipeIngredient
---@field get_Code fun(): AssetLocation
---@field set_Code fun(value: AssetLocation): nil
---@field get_Name fun(): string
---@field set_Name fun(value: string): nil
---@field Resolve fun(resolver: IWorldAccessor, sourceForErrorLogging: string): boolean
---@field SatisfiesAsIngredient fun(inputStack: ItemStack, checkStacksize: boolean): boolean
---@field Clone fun(): CraftingRecipeIngredient
---@field CloneTo fun(): T
---@field ToString fun(): string
---@field FillPlaceHolder fun(key: string, value: string): nil
---@field ToBytes fun(writer: BinaryWriter): nil
---@field FromBytes fun(reader: BinaryReader, resolver: IWorldAccessor): nil
---@field GetType fun(): any
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field Code AssetLocation
---@field Name AssetLocation
---@field Type AssetLocation
---@field Quantity AssetLocation
---@field Attributes AssetLocation
---@field RecipeAttributes AssetLocation
---@field IsTool AssetLocation
---@field ToolDurabilityCost AssetLocation
---@field AllowedVariants AssetLocation
---@field SkipVariants AssetLocation
---@field ReturnedStack AssetLocation
---@field ResolvedItemstack AssetLocation
---@field IsWildCard AssetLocation
CraftingRecipeIngredient = {}
