---@meta DummyRenderer
---@class DummyRenderer: Object
---@field ctor fun(): DummyRenderer
---@field get_RenderOrder fun(): Double
---@field set_RenderOrder fun(value: Double): nil
---@field get_RenderRange fun(): number
---@field set_RenderRange fun(value: number): nil
---@field Dispose fun(): nil
---@field OnRenderFrame fun(deltaTime: Single, stage: EnumRenderStage): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field RenderOrder Double
---@field RenderRange Double
---@field action Double
DummyRenderer = {}
