---@meta Packet_ServerReadySerializer
---@class Packet_ServerReadySerializer: Object
---@field ctor fun(): Packet_ServerReadySerializer
---@field DeserializeLengthDelimitedNew fun(stream: CitoMemoryStream): Packet_ServerReady
---@field DeserializeBuffer fun(buffer: number[], length: number, instance: Packet_ServerReady): Packet_ServerReady
---@field Deserialize fun(stream: CitoMemoryStream, instance: Packet_ServerReady): Packet_ServerReady
---@field DeserializeLengthDelimited fun(stream: CitoMemoryStream, instance: Packet_ServerReady): Packet_ServerReady
---@field Serialize fun(stream: CitoStream, instance: Packet_ServerReady): nil
---@field SerializeToBytes fun(instance: Packet_ServerReady): number[]
---@field SerializeLengthDelimited fun(stream: CitoStream, instance: Packet_ServerReady): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_ServerReadySerializer = {}
