---@meta Packet_ServerIdentificationSerializer
---@class Packet_ServerIdentificationSerializer: Object
---@field ctor fun(): Packet_ServerIdentificationSerializer
---@field DeserializeLengthDelimitedNew fun(stream: CitoMemoryStream): Packet_ServerIdentification
---@field DeserializeBuffer fun(buffer: number[], length: number, instance: Packet_ServerIdentification): Packet_ServerIdentification
---@field Deserialize fun(stream: CitoMemoryStream, instance: Packet_ServerIdentification): Packet_ServerIdentification
---@field DeserializeLengthDelimited fun(stream: CitoMemoryStream, instance: Packet_ServerIdentification): Packet_ServerIdentification
---@field Serialize fun(stream: CitoStream, instance: Packet_ServerIdentification): nil
---@field SerializeToBytes fun(instance: Packet_ServerIdentification): number[]
---@field SerializeLengthDelimited fun(stream: CitoStream, instance: Packet_ServerIdentification): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_ServerIdentificationSerializer = {}
