---@meta Packet_PlayerData
---@class Packet_PlayerData: Object
---@field ctor fun(): Packet_PlayerData
---@field SetClientId fun(value: number): nil
---@field SetEntityId fun(value: Int64): nil
---@field SetGameMode fun(value: number): nil
---@field SetMoveSpeed fun(value: number): nil
---@field SetFreeMove fun(value: number): nil
---@field SetNoClip fun(value: number): nil
---@field GetInventoryContents fun(): Packet_InventoryContents[]
---@field SetInventoryContents fun(value: Packet_InventoryContents[], count: number, length: number): nil
---@overload fun(value: Packet_InventoryContents[]): nil
---@field GetInventoryContentsCount fun(): number
---@field InventoryContentsAdd fun(value: Packet_InventoryContents): nil
---@field SetPlayerUID fun(value: string): nil
---@field SetPickingRange fun(value: number): nil
---@field SetFreeMovePlaneLock fun(value: number): nil
---@field SetAreaSelectionMode fun(value: number): nil
---@field GetPrivileges fun(): string[]
---@field SetPrivileges fun(value: string[], count: number, length: number): nil
---@overload fun(value: string[]): nil
---@field GetPrivilegesCount fun(): number
---@field PrivilegesAdd fun(value: string): nil
---@field SetPlayerName fun(value: string): nil
---@field SetEntitlements fun(value: string): nil
---@field SetHotbarSlotId fun(value: number): nil
---@field SetDeaths fun(value: number): nil
---@field SetSpawnx fun(value: number): nil
---@field SetSpawny fun(value: number): nil
---@field SetSpawnz fun(value: number): nil
---@field SetRoleCode fun(value: string): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_PlayerData = {}
