---@meta LongArrayAttribute
---@class LongArrayAttribute: ArrayAttribute`1
---@field ctor fun(): LongArrayAttribute
---@overload fun(value: Int64[]): LongArrayAttribute
---@field ToBytes fun(stream: BinaryWriter): nil
---@field FromBytes fun(stream: BinaryReader): nil
---@field get_AsUint fun(): Unumber[]
---@field GetAttributeId fun(): number
---@field Clone fun(): IAttribute
---@field Equals fun(worldForResolve: IWorldAccessor, attr: IAttribute): boolean
---@field GetValue fun(): table
---@field ToJsonToken fun(): string
---@field ToString fun(): string
---@field GetHashCode fun(): number
---@field GetType fun(): any
---@field Equals fun(obj: table): boolean
---@field AsUint Unumber[]
---@field value Unumber[]
LongArrayAttribute = {}
