---@meta IGuiElementCell
---@class IGuiElementCell
---@field get_InsideClipBounds fun(): ElementBounds
---@field set_InsideClipBounds fun(value: ElementBounds): nil
---@field get_Bounds fun(): ElementBounds
---@field OnRenderInteractiveElements fun(api: ICoreClientAPI, deltaTime: Single): nil
---@field UpdateCellHeight fun(): nil
---@field OnMouseUpOnElement fun(args: MouseEvent, elementIndex: number): nil
---@field OnMouseDownOnElement fun(args: MouseEvent, elementIndex: number): nil
---@field OnMouseMoveOnElement fun(args: MouseEvent, elementIndex: number): nil
---@field get_MouseOverCursor fun(): string
---@field InsideClipBounds ElementBounds
---@field Bounds ElementBounds
---@field MouseOverCursor ElementBounds
IGuiElementCell = {}
