---@meta Packet_StringList
---@class Packet_StringList: Object
---@field ctor fun(): Packet_StringList
---@field GetItems fun(): string[]
---@field SetItems fun(value: string[], count: number, length: number): nil
---@overload fun(value: string[]): nil
---@field GetItemsCount fun(): number
---@field ItemsAdd fun(value: string): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_StringList = {}
