---@meta GuiElementDropDown
---@class GuiElementDropDown: GuiElementTextBase
---@field ctor fun(capi: ICoreClientAPI, values: string[], names: string[], selectedIndex: number, onSelectionChanged: SelectionChangedDelegate, bounds: ElementBounds, font: CairoFont, multiSelect: boolean): GuiElementDropDown
---@field get_DrawOrder fun(): Double
---@field get_Focusable fun(): boolean
---@field get_Scale fun(): Double
---@field set_Scale fun(value: Double): nil
---@field get_SelectedValue fun(): string
---@field get_SelectedIndices fun(): number[]
---@field get_SelectedValues fun(): string[]
---@field get_Enabled fun(): boolean
---@field set_Enabled fun(value: boolean): nil
---@field ComposeElements fun(ctx: Context, surface: ImageSurface): nil
---@field RenderInteractiveElements fun(deltaTime: Single): nil
---@field OnKeyDown fun(api: ICoreClientAPI, args: KeyEvent): nil
---@field OnMouseMove fun(api: ICoreClientAPI, args: MouseEvent): nil
---@field OnMouseWheel fun(api: ICoreClientAPI, args: MouseWheelEventArgs): nil
---@field OnMouseUp fun(api: ICoreClientAPI, args: MouseEvent): nil
---@field IsPositionInside fun(posX: number, posY: number): boolean
---@field OnMouseDown fun(api: ICoreClientAPI, args: MouseEvent): nil
---@field OnFocusLost fun(): nil
---@field SetSelectedIndex fun(selectedIndex: number): nil
---@field SetSelectedValue fun(value: string[]): nil
---@field SetList fun(values: string[], names: string[]): nil
---@field Dispose fun(): nil
---@field get_Text fun(): string
---@field set_Text fun(value: string): nil
---@field ComposeTextElements fun(ctx: Context, surface: ImageSurface): nil
---@field GetMultilineTextHeight fun(): Double
---@field DrawMultilineTextAt fun(ctx: Context, posX: Double, posY: Double, orientation: EnumTextOrientation): Double
---@field DrawTextLineAt fun(ctx: Context, text: string, posX: Double, posY: Double, textPathMode: boolean): nil
---@field GetText fun(): string
---@field get_InsideClipBounds fun(): ElementBounds
---@field set_InsideClipBounds fun(value: ElementBounds): nil
---@field get_RenderAsPremultipliedAlpha fun(): boolean
---@field set_RenderAsPremultipliedAlpha fun(value: boolean): nil
---@field get_HasFocus fun(): boolean
---@field OnFocusGained fun(): nil
---@field PostRenderInteractiveElements fun(deltaTime: Single): nil
---@field RenderFocusOverlay fun(deltaTime: Single): nil
---@field BeforeCalcBounds fun(): nil
---@field DialogRoundRectangle fun(ctx: Context, bounds: ElementBounds): nil
---@field ElementRoundRectangle fun(ctx: Context, bounds: ElementBounds, isBackground: boolean, radius: Double): nil
---@field ShadePath fun(ctx: Context, thickness: Double): nil
---@field EmbossRoundRectangleDialog fun(ctx: Context, x: Double, y: Double, width: Double, height: Double, inverse: boolean): nil
---@field EmbossRoundRectangleElement fun(ctx: Context, x: Double, y: Double, width: Double, height: Double, inverse: boolean, depth: number, radius: number): nil
---@overload fun(ctx: Context, bounds: ElementBounds, inverse: boolean, depth: number, radius: number): nil
---@field RenderBoundsDebug fun(): nil
---@field OnMouseDownOnElement fun(api: ICoreClientAPI, args: MouseEvent): nil
---@field OnMouseUpOnElement fun(api: ICoreClientAPI, args: MouseEvent): nil
---@field OnMouseEnterSlot fun(api: ICoreClientAPI, slot: ItemSlot): boolean
---@field OnMouseLeaveSlot fun(api: ICoreClientAPI, slot: ItemSlot): boolean
---@field OnKeyUp fun(api: ICoreClientAPI, args: KeyEvent): nil
---@field OnKeyPress fun(api: ICoreClientAPI, args: KeyEvent): nil
---@field get_MouseOverCursor fun(): string
---@field OutlineColor fun(): number
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field DrawOrder Double
---@field Focusable Double
---@field Scale Double
---@field SelectedValue Double
---@field SelectedIndices Double
---@field SelectedValues Double
---@field Enabled Double
---@field Text Double
---@field InsideClipBounds Double
---@field RenderAsPremultipliedAlpha Double
---@field HasFocus Double
---@field MouseOverCursor Double
---@field SingularNameCode Double
---@field PluralNameCode Double
---@field PluralMoreNameCode Double
---@field SingularMoreNameCode Double
---@field listMenu Double
---@field richTextElem Double
---@field textUtil Double
---@field textPathMode Double
---@field Font Double
---@field Bounds Double
---@field TabIndex Double
GuiElementDropDown = {}
