---@meta Packet_NutritionProperties
---@class Packet_NutritionProperties: Object
---@field ctor fun(): Packet_NutritionProperties
---@field SetFoodCategory fun(value: number): nil
---@field SetSaturation fun(value: number): nil
---@field SetHealth fun(value: number): nil
---@field SetEatenStack fun(value: number[]): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_NutritionProperties = {}
