---@meta ServerProgramArgs
---@class ServerProgramArgs: Object
---@field ctor fun(): ServerProgramArgs
---@field get_PrintVersion fun(): boolean
---@field set_PrintVersion fun(value: boolean): nil
---@field get_PrintHelp fun(): boolean
---@field set_PrintHelp fun(value: boolean): nil
---@field get_Standby fun(): boolean
---@field set_Standby fun(value: boolean): nil
---@field get_TraceLog fun(): boolean
---@field set_TraceLog fun(value: boolean): nil
---@field get_Append fun(): boolean
---@field set_Append fun(value: boolean): nil
---@field get_GenConfigAndExit fun(): boolean
---@field set_GenConfigAndExit fun(value: boolean): nil
---@field get_SetConfigAndExit fun(): string
---@field set_SetConfigAndExit fun(value: string): nil
---@field get_WithConfig fun(): string
---@field set_WithConfig fun(value: string): nil
---@field get_DataPath fun(): string
---@field set_DataPath fun(value: string): nil
---@field get_LogPath fun(): string
---@field set_LogPath fun(value: string): nil
---@field get_AddOrigin fun(): any[]
---@field set_AddOrigin fun(value: any[]): nil
---@field get_AddModPath fun(): any[]
---@field set_AddModPath fun(value: any[]): nil
---@field get_Ip fun(): string
---@field set_Ip fun(value: string): nil
---@field get_Port fun(): string
---@field set_Port fun(value: string): nil
---@field get_MaxClients fun(): string
---@field set_MaxClients fun(value: string): nil
---@field GetUsage fun(parser: ParserResult`1): string
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field PrintVersion boolean
---@field PrintHelp boolean
---@field Standby boolean
---@field TraceLog boolean
---@field Append boolean
---@field GenConfigAndExit boolean
---@field SetConfigAndExit boolean
---@field WithConfig boolean
---@field DataPath boolean
---@field LogPath boolean
---@field AddOrigin boolean
---@field AddModPath boolean
---@field Ip boolean
---@field Port boolean
---@field MaxClients boolean
ServerProgramArgs = {}
