---@meta IServerChunk
---@class IServerChunk
---@field SetServerModdata fun(key: string, data: number[]): nil
---@field GetServerModdata fun(key: string): number[]
---@field get_GameVersionCreated fun(): string
---@field get_NotAtEdge fun(): boolean
---@field RemoveBlockEntity fun(pos: BlockPos): boolean
---@field get_BlocksPlaced fun(): number
---@field get_BlocksRemoved fun(): number
---@field GameVersionCreated string
---@field NotAtEdge string
---@field BlocksPlaced string
---@field BlocksRemoved string
IServerChunk = {}
