---@meta ServerSystemAsync
---@class ServerSystemAsync: ServerSystem
---@field ctor fun(server: ServerMain, name: string, system: IAsyncServerSystem): ServerSystemAsync
---@field GetUpdateInterval fun(): number
---@field OnSeparateThreadTick fun(): nil
---@field Dispose fun(): nil
---@field OnServerTick fun(dt: Single): nil
---@field OnSeperateThreadTick fun(dt: Single): nil
---@field OnRestart fun(): nil
---@field OnBeginInitialization fun(): nil
---@field OnBeginConfiguration fun(): nil
---@field OnLoadAssets fun(): nil
---@field OnFinalizeAssets fun(): nil
---@field OnBeginModsAndConfigReady fun(): nil
---@field OnBeginGameReady fun(savegame: SaveGame): nil
---@field OnBeginWorldReady fun(): nil
---@field OnSeperateThreadShutDown fun(): nil
---@field OnBeginRunGame fun(): nil
---@field OnBeginShutdown fun(): nil
---@field OnPlayerJoin fun(player: ServerPlayer): nil
---@field OnPlayerSwitchGameMode fun(player: ServerPlayer): nil
---@field OnPlayerDisconnect fun(player: ServerPlayer): nil
---@field OnServerPause fun(): nil
---@field OnServerResume fun(): nil
---@field OnPlayerJoinPost fun(player: ServerPlayer): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
ServerSystemAsync = {}
