---@meta MapUtil
---@class MapUtil: Object
---@field ctor fun(): MapUtil
---@field Index3dL fun(x: number, y: number, z: number, sizex: Int64, sizez: Int64): Int64
---@field Index3d fun(x: number, y: number, z: number, sizex: Int64, sizez: Int64): number
---@overload fun(x: number, y: number, z: number, sizex: number, sizez: number): number
---@field Index2d fun(x: number, y: number, sizex: number): number
---@field Index2dL fun(x: number, y: number, sizex: number): Int64
---@field PosInt3d fun(index: number, sizex: Int64, sizez: Int64, ret: Vec3i): nil
---@overload fun(index: Int64, sizex: Int64, sizez: Int64, ret: Vec3i): nil
---@field PosInt2d fun(index: Int64, sizex: Int64, ret: Vec2i): nil
---@field PosX fun(index: number, sizex: number, sizey: number): number
---@field PosZ fun(index: number, sizex: number, sizey: number): number
---@field PosY fun(index: number, sizex: number, sizey: number): number
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
MapUtil = {}
