---@meta FloatDataMap3D
---@class FloatDataMap3D: Object
---@field ctor fun(): FloatDataMap3D
---@overload fun(width: number, height: number, length: number): FloatDataMap3D
---@field GetValue fun(x: number, y: number, z: number): Single
---@field SetValue fun(x: number, y: number, z: number, value: Single): nil
---@field AddValue fun(x: number, y: number, z: number, value: Single): nil
---@field GetLerped fun(x: Single, y: Single, z: Single): Single
---@field GetLerpedCenterPixel fun(x: Single, y: Single, z: Single): Single
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
FloatDataMap3D = {}
