---@meta MainMenuInputAPI
---@class MainMenuInputAPI: Object
---@field ctor fun(screenManager: ScreenManager): MainMenuInputAPI
---@field add_OnMouseDown fun(value: MouseEventDelegate): nil
---@field remove_OnMouseDown fun(value: MouseEventDelegate): nil
---@field add_OnMouseUp fun(value: MouseEventDelegate): nil
---@field remove_OnMouseUp fun(value: MouseEventDelegate): nil
---@field add_OnMouseMove fun(value: MouseEventDelegate): nil
---@field remove_OnMouseMove fun(value: MouseEventDelegate): nil
---@field add_OnKeyDown fun(value: KeyEventDelegate): nil
---@field remove_OnKeyDown fun(value: KeyEventDelegate): nil
---@field add_OnKeyUp fun(value: KeyEventDelegate): nil
---@field remove_OnKeyUp fun(value: KeyEventDelegate): nil
---@field add_InWorldAction fun(value: OnEntityAction): nil
---@field remove_InWorldAction fun(value: OnEntityAction): nil
---@field get_KeyboardKeyState fun(): boolean[]
---@field get_KeyboardKeyStateRaw fun(): boolean[]
---@field get_MouseButton fun(): MouseButtonState
---@field get_InWorldMouseButton fun(): MouseButtonState
---@field get_MouseWorldInteractAnyway fun(): boolean
---@field set_MouseWorldInteractAnyway fun(value: boolean): nil
---@field get_MouseGrabbed fun(): boolean
---@field get_HotKeys fun(): Orderedtable<any, any>
---@field GetHotKeyByCode fun(toggleKeyCombinationCode: string): HotKey
---@field get_MouseX fun(): number
---@field get_MouseY fun(): number
---@field get_MouseYaw fun(): Single
---@field set_MouseYaw fun(value: Single): nil
---@field get_MousePitch fun(): Single
---@field set_MousePitch fun(value: Single): nil
---@field get_ClipboardText fun(): string
---@field set_ClipboardText fun(value: string): nil
---@field RegisterHotKey fun(hotkeyCode: string, name: string, key: GlKeys, type: Hotkeyany, altPressed: boolean, ctrlPressed: boolean, shiftPressed: boolean): nil
---@field RegisterHotKeyFirst fun(hotkeyCode: string, name: string, key: GlKeys, type: Hotkeyany, altPressed: boolean, ctrlPressed: boolean, shiftPressed: boolean): nil
---@field SetHotKeyHandler fun(hotkeyCode: string, handler: ActionConsumable`1): nil
---@field TriggerOnMouseClickSlot fun(itemSlot: ItemSlot): nil
---@field TriggerOnMouseEnterSlot fun(slot: ItemSlot): nil
---@field TriggerOnMouseLeaveSlot fun(itemSlot: ItemSlot): nil
---@field TriggerMouseDown fun(ev: MouseEvent): nil
---@field TriggerMouseUp fun(ev: MouseEvent): nil
---@field TriggerMouseMove fun(ev: MouseEvent): nil
---@field TriggerKeyUp fun(ev: KeyEvent): nil
---@field TriggerKeyDown fun(ev: KeyEvent): nil
---@field AddHotkeyListener fun(handler: OnHotKeyDelegate): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field KeyboardKeyState boolean[]
---@field KeyboardKeyStateRaw boolean[]
---@field MouseButton boolean[]
---@field InWorldMouseButton boolean[]
---@field MouseWorldInteractAnyway boolean[]
---@field MouseGrabbed boolean[]
---@field HotKeys boolean[]
---@field MouseX boolean[]
---@field MouseY boolean[]
---@field MouseYaw boolean[]
---@field MousePitch boolean[]
---@field ClipboardText boolean[]
---@field OnMouseDown boolean[]
---@field OnMouseUp boolean[]
---@field OnMouseMove boolean[]
---@field OnKeyDown boolean[]
---@field OnKeyUp boolean[]
---@field InWorldAction boolean[]
MainMenuInputAPI = {}
