---@meta ModDbUtil
---@class ModDbUtil: Object
---@field ctor fun(api: ICoreAPI, modDbUrl: string, installPath: string): ModDbUtil
---@field get_IsLoading fun(): boolean
---@field preConsoleCommand fun(): string
---@field onInstallCommand fun(modid: string, forGameVersion: string, onProgressUpdate: any`1): nil
---@field onRemoveCommand fun(modid: string, onProgressUpdate: any`1): nil
---@field onListCommand fun(onProgressUpdate: any`1): nil
---@field onSearchforCommand fun(version: string, modid: string, onProgressUpdate: any`1): nil
---@field onSearchforAndCompatibleCommand fun(version: string, modid: string, onProgressUpdate: any`1): nil
---@field onSearchCommand fun(modid: string, onProgressUpdate: any`1): nil
---@field onSearchCompatibleCommand fun(modid: string, onProgressUpdate: any`1): nil
---@field SearchAndInstall fun(modid: string, forGameVersion: string, onDone: ModInstallProgressUpdate, deletedOutdated: boolean): nil
---@field Search fun(stext: string, onDone: any`1, gameversionIds: number[], mv: string, sortBy: string, limit: number): nil
---@field parseResponse fun(text: string, errorText: string&): T
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field IsLoading boolean
---@field selfGameVersionId boolean
---@field sameMinorVersionIds boolean
ModDbUtil = {}
