---@meta Packet_ItemStackSerializer
---@class Packet_ItemStackSerializer: Object
---@field ctor fun(): Packet_ItemStackSerializer
---@field DeserializeLengthDelimitedNew fun(stream: CitoMemoryStream): Packet_ItemStack
---@field DeserializeBuffer fun(buffer: number[], length: number, instance: Packet_ItemStack): Packet_ItemStack
---@field Deserialize fun(stream: CitoMemoryStream, instance: Packet_ItemStack): Packet_ItemStack
---@field DeserializeLengthDelimited fun(stream: CitoMemoryStream, instance: Packet_ItemStack): Packet_ItemStack
---@field Serialize fun(stream: CitoStream, instance: Packet_ItemStack): nil
---@field SerializeToBytes fun(instance: Packet_ItemStack): number[]
---@field SerializeLengthDelimited fun(stream: CitoStream, instance: Packet_ItemStack): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_ItemStackSerializer = {}
