---@meta PerceptionEffects
---@class PerceptionEffects: Object
---@field ctor fun(capi: ICoreClientAPI): PerceptionEffects
---@field RegisterPerceptionEffect fun(effect: PerceptionEffect, code: string): nil
---@field get_RegisteredEffects fun(): Iany[]
---@field TriggerEffect fun(code: string, intensity: Single, on: Nullable`1): nil
---@field OnBeforeGameRender fun(dt: Single): nil
---@field OnOwnPlayerDataReceived fun(eplr: EntityPlayer): nil
---@field ApplyToFpHand fun(modelMat: Matrixf): nil
---@field ApplyToTpPlayer fun(entityPlr: EntityPlayer, modelMatrix: Single[], playerIntensity: Nullable`1): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field RegisteredEffects Iany[]
PerceptionEffects = {}
