---@meta IShaderProgram
---@class IShaderProgram
---@field get_PassId fun(): number
---@field get_PassName fun(): string
---@field get_ClampTexturesToEdge fun(): boolean
---@field set_ClampTexturesToEdge fun(value: boolean): nil
---@field get_VertexShader fun(): IShader
---@field set_VertexShader fun(value: IShader): nil
---@field get_FragmentShader fun(): IShader
---@field set_FragmentShader fun(value: IShader): nil
---@field get_GeometryShader fun(): IShader
---@field set_GeometryShader fun(value: IShader): nil
---@field Use fun(): nil
---@field Stop fun(): nil
---@field Compile fun(): boolean
---@field Uniform fun(uniformName: string, value: Single): nil
---@overload fun(uniformName: string, value: number): nil
---@overload fun(uniformName: string, value: Vec2f): nil
---@overload fun(uniformName: string, value: Vec3f): nil
---@overload fun(uniformName: string, value: Vec4f): nil
---@field Uniforms4 fun(uniformName: string, count: number, values: Single[]): nil
---@field UniformMatrix fun(uniformName: string, matrix: Single[]): nil
---@field BindTexture2D fun(samplerName: string, textureId: number, textureNumber: number): nil
---@field BindTextureCube fun(samplerName: string, textureId: number, textureNumber: number): nil
---@field UniformMatrices fun(uniformName: string, count: number, matrix: Single[]): nil
---@field UniformMatrices4x3 fun(uniformName: string, count: number, matrix: Single[]): nil
---@field HasUniform fun(uniformName: string): boolean
---@field get_Disposed fun(): boolean
---@field get_LoadError fun(): boolean
---@field PassId number
---@field PassName number
---@field ClampTexturesToEdge number
---@field VertexShader number
---@field FragmentShader number
---@field GeometryShader number
---@field Disposed number
---@field LoadError number
IShaderProgram = {}
