---@meta Packet_GeneratedStructure
---@class Packet_GeneratedStructure: Object
---@field ctor fun(): Packet_GeneratedStructure
---@field SetX1 fun(value: number): nil
---@field SetY1 fun(value: number): nil
---@field SetZ1 fun(value: number): nil
---@field SetX2 fun(value: number): nil
---@field SetY2 fun(value: number): nil
---@field SetZ2 fun(value: number): nil
---@field SetCode fun(value: string): nil
---@field SetGroup fun(value: string): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_GeneratedStructure = {}
