---@meta ShapeUtil
---@class ShapeUtil: Object
---@field GetCachedCubicShellNormalizedVectors fun(radius: number): Vec3f[]
---@field GenCubicShellVectors fun(r: number): Vec3i[]
---@field GetSquarePointsSortedByMDist fun(halflength: number): Vec2i[]
---@field GetHollowSquarePoints fun(halflength: number): Vec2i[]
---@field GetOctagonPoints fun(x: number, y: number, r: number): Vec2i[]
---@field LoadOctagonIndices fun(list: Iany[], x: number, y: number, r: number, mapSizeX: number): nil
---@field GetPointsOfCircle fun(xm: number, ym: number, r: number): Vec2i[]
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
ShapeUtil = {}
