---@meta GltfPrimitive
---@class GltfPrimitive: Object
---@field ctor fun(): GltfPrimitive
---@field get_Attributes fun(): GltfAttributes
---@field set_Attributes fun(value: GltfAttributes): nil
---@field get_Indices fun(): Nullable`1
---@field set_Indices fun(value: Nullable`1): nil
---@field get_Material fun(): Nullable`1
---@field set_Material fun(value: Nullable`1): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field Attributes GltfAttributes
---@field Indices GltfAttributes
---@field Material GltfAttributes
GltfPrimitive = {}
