---@meta ZstdNative
---@class ZstdNative: Object
---@field ZSTD_createCCtx fun(): ZstdCCtx*
---@field ZSTD_CCtx_setParameter fun(cctx: ZstdCCtx*, param: ZstdCParameter, value: number): UIntPtr
---@field ZSTD_compressBound fun(srcSize: UIntPtr): UIntPtr
---@field ZSTD_getFrameContentSize fun(src: nil*, srcSize: UIntPtr): UInt64
---@field ZSTD_compressCCtx fun(cctx: ZstdCCtx*, dst: nil*, dstCapacity: UIntPtr, src: nil*, srcSize: UIntPtr, compressionLevel: number): UIntPtr
---@field ZSTD_createDCtx fun(): ZstdDCtx*
---@field ZSTD_decompressDCtx fun(dctx: ZstdDCtx*, dst: nil*, dstCapacity: UIntPtr, src: nil*, srcSize: UIntPtr): UIntPtr
---@field ZSTD_versionNumber fun(): Unumber
---@field get_Version fun(): Version
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field Version Version
---@field ZstdCCtx Version
---@field ZstdDCtx Version
---@field ZstdCParameter Version
ZstdNative = {}
