---@meta IMapRegion
---@class IMapRegion
---@field get_BlockPatchMaps fun(): table<any, any>
---@field set_BlockPatchMaps fun(value: table<any, any>): nil
---@field get_FlowerMap fun(): IntDataMap2D
---@field set_FlowerMap fun(value: IntDataMap2D): nil
---@field get_ShrubMap fun(): IntDataMap2D
---@field set_ShrubMap fun(value: IntDataMap2D): nil
---@field get_ForestMap fun(): IntDataMap2D
---@field set_ForestMap fun(value: IntDataMap2D): nil
---@field get_BeachMap fun(): IntDataMap2D
---@field set_BeachMap fun(value: IntDataMap2D): nil
---@field get_OceanMap fun(): IntDataMap2D
---@field set_OceanMap fun(value: IntDataMap2D): nil
---@field get_UpheavelMap fun(): IntDataMap2D
---@field set_UpheavelMap fun(value: IntDataMap2D): nil
---@field get_LandformMap fun(): IntDataMap2D
---@field set_LandformMap fun(value: IntDataMap2D): nil
---@field get_ClimateMap fun(): IntDataMap2D
---@field set_ClimateMap fun(value: IntDataMap2D): nil
---@field get_GeologicProvinceMap fun(): IntDataMap2D
---@field set_GeologicProvinceMap fun(value: IntDataMap2D): nil
---@field get_RockStrata fun(): IntDataMap2D[]
---@field set_RockStrata fun(value: IntDataMap2D[]): nil
---@field get_ModData fun(): table<any, any>
---@field get_ModMaps fun(): table<any, any>
---@field get_OreMaps fun(): table<any, any>
---@field get_OreMapVerticalDistortTop fun(): IntDataMap2D
---@field get_OreMapVerticalDistortBottom fun(): IntDataMap2D
---@field get_GeneratedStructures fun(): any[]
---@field get_DirtyForSaving fun(): boolean
---@field set_DirtyForSaving fun(value: boolean): nil
---@field SetModdata fun(key: string, data: number[]): nil
---@field RemoveModdata fun(key: string): nil
---@field GetModdata fun(key: string): number[]
---@overload fun(key: string, data: T): nil
---@overload fun(key: string): T
---@field AddGeneratedStructure fun(generatedStructure: GeneratedStructure): nil
---@field BlockPatchMaps table<any, any>
---@field FlowerMap table<any, any>
---@field ShrubMap table<any, any>
---@field ForestMap table<any, any>
---@field BeachMap table<any, any>
---@field OceanMap table<any, any>
---@field UpheavelMap table<any, any>
---@field LandformMap table<any, any>
---@field ClimateMap table<any, any>
---@field GeologicProvinceMap table<any, any>
---@field RockStrata table<any, any>
---@field ModData table<any, any>
---@field ModMaps table<any, any>
---@field OreMaps table<any, any>
---@field OreMapVerticalDistortTop table<any, any>
---@field OreMapVerticalDistortBottom table<any, any>
---@field GeneratedStructures table<any, any>
---@field DirtyForSaving table<any, any>
IMapRegion = {}
