---@meta ModInfoAttribute
---@class ModInfoAttribute: Attribute
---@field ctor fun(name: string, modID: string): ModInfoAttribute
---@overload fun(name: string): ModInfoAttribute
---@field get_Name fun(): string
---@field get_IconPath fun(): string
---@field set_IconPath fun(value: string): nil
---@field get_ModID fun(): string
---@field get_Version fun(): string
---@field set_Version fun(value: string): nil
---@field get_CoreMod fun(): boolean
---@field set_CoreMod fun(value: boolean): nil
---@field get_NetworkVersion fun(): string
---@field set_NetworkVersion fun(value: string): nil
---@field get_Description fun(): string
---@field set_Description fun(value: string): nil
---@field get_Website fun(): string
---@field set_Website fun(value: string): nil
---@field get_Authors fun(): string[]
---@field set_Authors fun(value: string[]): nil
---@field get_Contributors fun(): string[]
---@field set_Contributors fun(value: string[]): nil
---@field get_Side fun(): string
---@field set_Side fun(value: string): nil
---@field get_RequiredOnClient fun(): boolean
---@field set_RequiredOnClient fun(value: boolean): nil
---@field get_RequiredOnServer fun(): boolean
---@field set_RequiredOnServer fun(value: boolean): nil
---@field get_WorldConfig fun(): string
---@field set_WorldConfig fun(value: string): nil
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field get_TypeId fun(): table
---@field Match fun(obj: table): boolean
---@field IsDefaultAttribute fun(): boolean
---@field GetType fun(): any
---@field ToString fun(): string
---@field Name string
---@field IconPath string
---@field ModID string
---@field Version string
---@field CoreMod string
---@field NetworkVersion string
---@field Description string
---@field Website string
---@field Authors string
---@field Contributors string
---@field Side string
---@field RequiredOnClient string
---@field RequiredOnServer string
---@field WorldConfig string
---@field TypeId string
ModInfoAttribute = {}
