---@meta IChunkBlocks
---@class IChunkBlocks
---@field get_Item fun(index3d: number): number
---@field set_Item fun(index3d: number, value: number): nil
---@field get_Length fun(): number
---@field ClearBlocks fun(): nil
---@field ClearBlocksAndPrepare fun(): nil
---@field SetBlockBulk fun(index3d: number, lenX: number, lenZ: number, value: number): nil
---@field SetBlockUnsafe fun(index3d: number, value: number): nil
---@field SetBlockAir fun(index3d: number): nil
---@field SetFluid fun(index3d: number, value: number): nil
---@field GetBlockId fun(index3d: number, layer: number): number
---@field GetFluid fun(index3d: number): number
---@field GetBlockIdUnsafe fun(index3d: number): number
---@field TakeBulkReadLock fun(): nil
---@field ReleaseBulkReadLock fun(): nil
---@field ContainsBlock fun(blockId: number): boolean
---@field FuzzyListBlockIds fun(reusableList: any[]): nil
---@field Item number
---@field Length number
IChunkBlocks = {}
