---@meta ClientWorldPlayerData
---@class ClientWorldPlayerData: Object
---@field get_CurrentGameMode fun(): EnumGameMode
---@field set_CurrentGameMode fun(value: EnumGameMode): nil
---@field get_RenderMetablocks fun(): boolean
---@field set_RenderMetablocks fun(value: boolean): nil
---@field get_MoveSpeedMultiplier fun(): Single
---@field set_MoveSpeedMultiplier fun(value: Single): nil
---@field get_PickingRange fun(): Single
---@field set_PickingRange fun(value: Single): nil
---@field get_FreeMove fun(): boolean
---@field set_FreeMove fun(value: boolean): nil
---@field get_NoClip fun(): boolean
---@field set_NoClip fun(value: boolean): nil
---@field get_Deaths fun(): number
---@field set_Deaths fun(value: number): nil
---@field get_FreeMovePlaneLock fun(): EnumFreeMovAxisLock
---@field set_FreeMovePlaneLock fun(value: EnumFreeMovAxisLock): nil
---@field get_AreaSelectionMode fun(): boolean
---@field set_AreaSelectionMode fun(value: boolean): nil
---@field get_EntityPlayer fun(): EntityPlayer
---@field set_EntityPlayer fun(value: EntityPlayer): nil
---@field get_EntityControls fun(): EntityControls
---@field get_LastApprovedViewDistance fun(): number
---@field set_LastApprovedViewDistance fun(value: number): nil
---@field get_CurrentClientId fun(): number
---@field get_Connected fun(): boolean
---@field get_DidSelectSkin fun(): boolean
---@field set_DidSelectSkin fun(value: boolean): nil
---@field get_DesiredViewDistance fun(): number
---@field set_DesiredViewDistance fun(value: number): nil
---@field RequestNewViewDistance fun(game: ClientMain): nil
---@field RequestMode fun(game: ClientMain): nil
---@field SetMode fun(game: ClientMain, moveSpeedMultiplier: Single): nil
---@field RequestMode fun(game: ClientMain, noClip: boolean, freeMove: boolean): nil
---@overload fun(game: ClientMain, FreeMovePlaneLock: EnumFreeMovAxisLock): nil
---@field RequestModeNoClip fun(game: ClientMain, noClip: boolean): nil
---@field RequestModeFreeMove fun(game: ClientMain, freeMove: boolean): nil
---@field RequestMode fun(game: ClientMain, moveSpeed: Single, pickRange: Single, gameMode: EnumGameMode, freeMove: boolean, noClip: boolean, freeMovePlaneLock: EnumFreeMovAxisLock, renderMetaBlocks: boolean): nil
---@field CreateNew fun(): ClientWorldPlayerData
---@field Clone fun(): ClientWorldPlayerData
---@field UpdateFromPacket fun(game: ClientMain, packet: Packet_PlayerData): nil
---@overload fun(game: ClientMain, mode: Packet_PlayerMode): nil
---@field SetModdata fun(key: string, data: number[]): nil
---@field RemoveModdata fun(key: string): nil
---@field GetModdata fun(key: string): number[]
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field CurrentGameMode EnumGameMode
---@field RenderMetablocks EnumGameMode
---@field MoveSpeedMultiplier EnumGameMode
---@field PickingRange EnumGameMode
---@field FreeMove EnumGameMode
---@field NoClip EnumGameMode
---@field Deaths EnumGameMode
---@field FreeMovePlaneLock EnumGameMode
---@field AreaSelectionMode EnumGameMode
---@field EntityPlayer EnumGameMode
---@field EntityControls EnumGameMode
---@field LastApprovedViewDistance EnumGameMode
---@field CurrentClientId EnumGameMode
---@field Connected EnumGameMode
---@field DidSelectSkin EnumGameMode
---@field DesiredViewDistance EnumGameMode
---@field ClientId EnumGameMode
---@field PlayerUID EnumGameMode
---@field PlayerName EnumGameMode
ClientWorldPlayerData = {}
