---@meta ServerConsoleClient
---@class ServerConsoleClient: ConnectedClient
---@field ctor fun(clientId: number): ServerConsoleClient
---@field get_ServerData fun(): ServerPlayerData
---@field get_IsPlayingClient fun(): boolean
---@field ToString fun(): string
---@field get_Entityplayer fun(): EntityPlayer
---@field get_WorldData fun(): ServerWorldPlayerData
---@field set_WorldData fun(value: ServerWorldPlayerData): nil
---@field get_Position fun(): EntityPos
---@field get_ChunkPos fun(): BlockPos
---@field get_PlayerName fun(): string
---@field get_IsLocalConnection fun(): boolean
---@field get_ServerAssetsSent fun(): boolean
---@field set_ServerAssetsSent fun(value: boolean): nil
---@field get_State fun(): EnumClientState
---@field set_State fun(value: EnumClientState): nil
---@field get_LastChatMessageTotalMs fun(): Int64
---@field set_LastChatMessageTotalMs fun(value: Int64): nil
---@field get_Socket fun(): NetConnection
---@field set_Socket fun(value: NetConnection): nil
---@field LoadOrCreatePlayerData fun(server: ServerMain, playername: string, playerUid: string): nil
---@field DidSendChunk fun(index3d: Int64): boolean
---@field DidSendMapChunk fun(index2d: Int64): boolean
---@field DidSendMapRegion fun(index2d: Int64): boolean
---@field SetMapRegionSent fun(index2d: Int64): nil
---@field SetChunkSent fun(index3d: Int64): nil
---@field SetMapChunkSent fun(index2d: Int64): nil
---@field RemoveMapRegionSent fun(index2d: Int64): nil
---@field RemoveChunkSent fun(index3d: Int64): nil
---@field RemoveMapChunkSent fun(index2d: Int64): nil
---@field CloseConnection fun(): nil
---@field ShouldReceiveUpdatesForPos fun(pos: BlockPos): boolean
---@field GetType fun(): any
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field ServerData ServerPlayerData
---@field IsPlayingClient ServerPlayerData
---@field Entityplayer ServerPlayerData
---@field WorldData ServerPlayerData
---@field Position ServerPlayerData
---@field ChunkPos ServerPlayerData
---@field PlayerName ServerPlayerData
---@field IsLocalConnection ServerPlayerData
---@field ServerAssetsSent ServerPlayerData
---@field State ServerPlayerData
---@field LastChatMessageTotalMs ServerPlayerData
---@field Socket ServerPlayerData
---@field serverdata ServerPlayerData
---@field AuditFlySuspicion ServerPlayerData
---@field AuditFlySuspicionPrintedTotalMs ServerPlayerData
---@field LastAuditFlySuspicionTotalMs ServerPlayerData
---@field TotalFlySuspicions ServerPlayerData
---@field TotalTeleSupicions ServerPlayerData
---@field LoginToken ServerPlayerData
---@field previousControls ServerPlayerData
---@field Player ServerPlayerData
---@field SentPlayerUid ServerPlayerData
---@field IsNewEntityPlayer ServerPlayerData
---@field stopSent ServerPlayerData
---@field MillisecsAtConnect ServerPlayerData
---@field ChunkSent ServerPlayerData
---@field MapChunkSent ServerPlayerData
---@field MapRegionSent ServerPlayerData
---@field CurrentChunkSentRadius ServerPlayerData
---@field IsInventoryDirty ServerPlayerData
---@field IsPlayerStatsDirty ServerPlayerData
---@field TrackedEntities ServerPlayerData
---@field Id ServerPlayerData
---@field forceSendChunks ServerPlayerData
---@field forceSendMapChunks ServerPlayerData
---@field IsQueryClient ServerPlayerData
---@field FromSocketListener ServerPlayerData
---@field Received ServerPlayerData
---@field Ping ServerPlayerData
---@field LastPing ServerPlayerData
---@field FallbackPlayerName ServerPlayerData
ServerConsoleClient = {}
