---@meta ServerWorldPlayerData
---@class ServerWorldPlayerData: Object
---@field ctor fun(): ServerWorldPlayerData
---@field get_EntityPlayer fun(): EntityPlayer
---@field set_EntityPlayer fun(value: EntityPlayer): nil
---@field get_SpawnPosition fun(): PlayerSpawnPos
---@field set_SpawnPosition fun(value: PlayerSpawnPos): nil
---@field get_EntityControls fun(): EntityControls
---@field get_LastApprovedViewDistance fun(): number
---@field set_LastApprovedViewDistance fun(value: number): nil
---@field get_AreaSelectionMode fun(): boolean
---@field set_AreaSelectionMode fun(value: boolean): nil
---@field get_FreeMovePlaneLock fun(): EnumFreeMovAxisLock
---@field set_FreeMovePlaneLock fun(value: EnumFreeMovAxisLock): nil
---@field get_CurrentClientId fun(): number
---@field get_Connected fun(): boolean
---@field get_DidSelectSkin fun(): boolean
---@field set_DidSelectSkin fun(value: boolean): nil
---@field get_SelectedHotbarSlot fun(): number
---@field set_SelectedHotbarSlot fun(value: number): nil
---@field get_DesiredViewDistance fun(): number
---@field set_DesiredViewDistance fun(value: number): nil
---@field CreateNew fun(playername: string, playerUID: string): ServerWorldPlayerData
---@field Init fun(server: ServerMain): nil
---@field BeforeSerialization fun(): nil
---@field ToPacket fun(owningPlayer: IServerPlayer, sendInventory: boolean, sendPrivileges: boolean): Packet_Server
---@field ToPacketForOtherPlayers fun(owningPlayer: IServerPlayer): Packet_Server
---@field SetModdata fun(key: string, data: number[]): nil
---@field RemoveModdata fun(key: string): nil
---@field GetModdata fun(key: string): number[]
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field EntityPlayer EntityPlayer
---@field SpawnPosition EntityPlayer
---@field EntityControls EntityPlayer
---@field LastApprovedViewDistance EntityPlayer
---@field AreaSelectionMode EntityPlayer
---@field FreeMovePlaneLock EntityPlayer
---@field CurrentClientId EntityPlayer
---@field Connected EntityPlayer
---@field DidSelectSkin EntityPlayer
---@field SelectedHotbarSlot EntityPlayer
---@field DesiredViewDistance EntityPlayer
---@field GameMode EntityPlayer
---@field MoveSpeedMultiplier EntityPlayer
---@field PickingRange EntityPlayer
---@field FreeMove EntityPlayer
---@field NoClip EntityPlayer
---@field Viewdistance EntityPlayer
---@field ModData EntityPlayer
---@field PreviousPickingRange EntityPlayer
---@field Deaths EntityPlayer
---@field RenderMetaBlocks EntityPlayer
ServerWorldPlayerData = {}
