---@meta ItemstackAttribute
---@class ItemstackAttribute: Object
---@field ctor fun(): ItemstackAttribute
---@overload fun(value: ItemStack): ItemstackAttribute
---@field GetAttributeId fun(): number
---@field GetValue fun(): table
---@field FromBytes fun(stream: BinaryReader): nil
---@field ToBytes fun(stream: BinaryWriter): nil
---@field Equals fun(worldForResolve: IWorldAccessor, attr: IAttribute): boolean
---@field ToJsonToken fun(): string
---@field GetHashCode fun(): number
---@field Clone fun(): IAttribute
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
ItemstackAttribute = {}
