---@meta Packet_MoveItemstackSerializer
---@class Packet_MoveItemstackSerializer: Object
---@field ctor fun(): Packet_MoveItemstackSerializer
---@field DeserializeLengthDelimitedNew fun(stream: CitoMemoryStream): Packet_MoveItemstack
---@field DeserializeBuffer fun(buffer: number[], length: number, instance: Packet_MoveItemstack): Packet_MoveItemstack
---@field Deserialize fun(stream: CitoMemoryStream, instance: Packet_MoveItemstack): Packet_MoveItemstack
---@field DeserializeLengthDelimited fun(stream: CitoMemoryStream, instance: Packet_MoveItemstack): Packet_MoveItemstack
---@field Serialize fun(stream: CitoStream, instance: Packet_MoveItemstack): nil
---@field SerializeToBytes fun(instance: Packet_MoveItemstack): number[]
---@field SerializeLengthDelimited fun(stream: CitoStream, instance: Packet_MoveItemstack): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_MoveItemstackSerializer = {}
