---@meta WeightedValue`1
---@class WeightedValue`1: Object
---@field ctor fun(): WeightedValue`1
---@overload fun(value: Single[], weight: Single): WeightedValue`1
---@field New fun(value: Single[], weight: Single): WeightedValue`1
---@field Set fun(value: Single[], weight: Single): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
WeightedValue`1 = {}
