---@meta GltfNode
---@class GltfNode: Object
---@field ctor fun(): GltfNode
---@field get_Mesh fun(): Int64
---@field set_Mesh fun(value: Int64): nil
---@field get_Name fun(): string
---@field set_Name fun(value: string): nil
---@field get_Rotation fun(): Double[]
---@field set_Rotation fun(value: Double[]): nil
---@field get_Scale fun(): Double[]
---@field set_Scale fun(value: Double[]): nil
---@field get_Translation fun(): Double[]
---@field set_Translation fun(value: Double[]): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field Mesh Int64
---@field Name Int64
---@field Rotation Int64
---@field Scale Int64
---@field Translation Int64
GltfNode = {}
