---@meta GuiElementChatInput
---@class GuiElementChatInput: GuiElementEditableTextBase
---@field ctor fun(capi: ICoreClientAPI, bounds: ElementBounds, OnTextChanged: any`1): GuiElementChatInput
---@field ComposeTextElements fun(ctx: Context, surface: ImageSurface): nil
---@field RenderInteractiveElements fun(deltaTime: Single): nil
---@field Dispose fun(): nil
---@field GetLines fun(): any[]
---@field get_TextLengthWithoutLineBreaks fun(): number
---@field get_CaretPosWithoutLineBreaks fun(): number
---@field set_CaretPosWithoutLineBreaks fun(value: number): nil
---@field get_CaretPosLine fun(): number
---@field set_CaretPosLine fun(value: number): nil
---@field get_CaretPosInLine fun(): number
---@field set_CaretPosInLine fun(value: number): nil
---@field get_Focusable fun(): boolean
---@field OnFocusGained fun(): nil
---@field OnFocusLost fun(): nil
---@field SetCaretPos fun(x: Double, y: Double): nil
---@overload fun(posInLine: number, posLine: number): nil
---@field SetValue fun(value: Single): nil
---@overload fun(text: string, setCaretPosToEnd: boolean): nil
---@field LoadValue fun(newLines: any[]): nil
---@field Lineize fun(text: string): any[]
---@field OnMouseDownOnElement fun(api: ICoreClientAPI, args: MouseEvent): nil
---@field OnKeyDown fun(api: ICoreClientAPI, args: KeyEvent): nil
---@field GetText fun(): string
---@field OnKeyPress fun(api: ICoreClientAPI, args: KeyEvent): nil
---@field MoveCursor fun(dir: number, wholeWord: boolean): nil
---@field SetMaxLines fun(maxlines: number): nil
---@field SetMaxHeight fun(maxheight: number): nil
---@field get_Text fun(): string
---@field set_Text fun(value: string): nil
---@field ComposeElements fun(ctx: Context, surface: ImageSurface): nil
---@field GetMultilineTextHeight fun(): Double
---@field DrawMultilineTextAt fun(ctx: Context, posX: Double, posY: Double, orientation: EnumTextOrientation): Double
---@field DrawTextLineAt fun(ctx: Context, text: string, posX: Double, posY: Double, textPathMode: boolean): nil
---@field get_Enabled fun(): boolean
---@field set_Enabled fun(value: boolean): nil
---@field get_InsideClipBounds fun(): ElementBounds
---@field set_InsideClipBounds fun(value: ElementBounds): nil
---@field get_RenderAsPremultipliedAlpha fun(): boolean
---@field set_RenderAsPremultipliedAlpha fun(value: boolean): nil
---@field get_HasFocus fun(): boolean
---@field get_DrawOrder fun(): Double
---@field get_Scale fun(): Double
---@field set_Scale fun(value: Double): nil
---@field PostRenderInteractiveElements fun(deltaTime: Single): nil
---@field RenderFocusOverlay fun(deltaTime: Single): nil
---@field BeforeCalcBounds fun(): nil
---@field DialogRoundRectangle fun(ctx: Context, bounds: ElementBounds): nil
---@field ElementRoundRectangle fun(ctx: Context, bounds: ElementBounds, isBackground: boolean, radius: Double): nil
---@field ShadePath fun(ctx: Context, thickness: Double): nil
---@field EmbossRoundRectangleDialog fun(ctx: Context, x: Double, y: Double, width: Double, height: Double, inverse: boolean): nil
---@field EmbossRoundRectangleElement fun(ctx: Context, x: Double, y: Double, width: Double, height: Double, inverse: boolean, depth: number, radius: number): nil
---@overload fun(ctx: Context, bounds: ElementBounds, inverse: boolean, depth: number, radius: number): nil
---@field RenderBoundsDebug fun(): nil
---@field OnMouseDown fun(api: ICoreClientAPI, mouse: MouseEvent): nil
---@field OnMouseUpOnElement fun(api: ICoreClientAPI, args: MouseEvent): nil
---@field OnMouseUp fun(api: ICoreClientAPI, args: MouseEvent): nil
---@field OnMouseEnterSlot fun(api: ICoreClientAPI, slot: ItemSlot): boolean
---@field OnMouseLeaveSlot fun(api: ICoreClientAPI, slot: ItemSlot): boolean
---@field OnMouseMove fun(api: ICoreClientAPI, args: MouseEvent): nil
---@field OnMouseWheel fun(api: ICoreClientAPI, args: MouseWheelEventArgs): nil
---@field OnKeyUp fun(api: ICoreClientAPI, args: KeyEvent): nil
---@field IsPositionInside fun(posX: number, posY: number): boolean
---@field get_MouseOverCursor fun(): string
---@field OutlineColor fun(): number
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field TextLengthWithoutLineBreaks number
---@field CaretPosWithoutLineBreaks number
---@field CaretPosLine number
---@field CaretPosInLine number
---@field Focusable number
---@field Text number
---@field Enabled number
---@field InsideClipBounds number
---@field RenderAsPremultipliedAlpha number
---@field HasFocus number
---@field DrawOrder number
---@field Scale number
---@field MouseOverCursor number
---@field OnCaretPositionChanged number
---@field OnTextChanged number
---@field OnTryTextChangeText number
---@field OnCursorMoved number
---@field OnKeyPressed number
---@field WordWrap number
---@field textUtil number
---@field textPathMode number
---@field Font number
---@field Bounds number
---@field TabIndex number
GuiElementChatInput = {}
