---@meta Packet_LandClaims
---@class Packet_LandClaims: Object
---@field ctor fun(): Packet_LandClaims
---@field GetAllclaims fun(): Packet_LandClaim[]
---@field SetAllclaims fun(value: Packet_LandClaim[], count: number, length: number): nil
---@overload fun(value: Packet_LandClaim[]): nil
---@field GetAllclaimsCount fun(): number
---@field AllclaimsAdd fun(value: Packet_LandClaim): nil
---@field GetAddclaims fun(): Packet_LandClaim[]
---@field SetAddclaims fun(value: Packet_LandClaim[], count: number, length: number): nil
---@overload fun(value: Packet_LandClaim[]): nil
---@field GetAddclaimsCount fun(): number
---@field AddclaimsAdd fun(value: Packet_LandClaim): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_LandClaims = {}
