---@meta MultiTextureMeshRef
---@class MultiTextureMeshRef: Object
---@field ctor fun(meshrefs: MeshRef[], textureids: number[]): MultiTextureMeshRef
---@field get_Disposed fun(): boolean
---@field get_Initialized fun(): boolean
---@field Dispose fun(): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field Disposed boolean
---@field Initialized boolean
---@field meshrefs boolean
---@field textureids boolean
MultiTextureMeshRef = {}
