---@meta Packet_Roles
---@class Packet_Roles: Object
---@field ctor fun(): Packet_Roles
---@field GetRoles fun(): Packet_Role[]
---@field SetRoles fun(value: Packet_Role[], count: number, length: number): nil
---@overload fun(value: Packet_Role[]): nil
---@field GetRolesCount fun(): number
---@field RolesAdd fun(value: Packet_Role): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_Roles = {}
