---@meta ChunkData
---@class ChunkData: Object
---@field CreateNew fun(chunksize: number, chunkDataPool: ChunkDataPool): ChunkData
---@field GetBlockId fun(index: number, layer: number): number
---@field GetSolidBlock fun(index3d: number): number
---@field get_Item fun(index3d: number): number
---@field set_Item fun(index3d: number, value: number): nil
---@field GetFluid fun(index3d: number): number
---@field SetFluid fun(index3d: number, value: number): nil
---@field SetLight fun(index3d: number, value: Unumber): nil
---@field GetBlockIdUnsafe fun(index3d: number): number
---@overload fun(index3d: number, layer: number): number
---@field TakeBulkReadLock fun(): nil
---@field ReleaseBulkReadLock fun(): nil
---@field SetBlockBulk fun(index3d: number, lenX: number, lenZ: number, value: number): nil
---@field SetBlockUnsafe fun(index3d: number, value: number): nil
---@field SetBlockAir fun(index3d: number): nil
---@field get_Length fun(): number
---@field ClearBlocks fun(): nil
---@field ClearBlocksAndPrepare fun(): nil
---@field ClearWithSunlight fun(sunlight: UInt16): nil
---@field FloodWithSunlight fun(sunlight: UInt16): nil
---@field ClearAllSunlight fun(): nil
---@field ClearLight fun(): nil
---@field GetEnumerator fun(): IEnumerator`1
---@field GetSunlight fun(index3d: number): number
---@field SetSunlight fun(index3d: number, sunLevel: number): nil
---@field SetSunlight_Buffered fun(index3d: number, sunLevel: number): nil
---@field GetBlocklight fun(index3d: number): number
---@field SetBlocklight fun(index3d: number, lightLevel: number): nil
---@field SetBlocklight_Buffered fun(index3d: number, lightLevel: number): nil
---@field ContainsBlock fun(id: number): boolean
---@field FuzzyListBlockIds fun(reusableList: any[]): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field Item number
---@field Length number
---@field blocksLayer number
---@field fluidsLayer number
---@field lightLayer number
---@field NON_LIGHTSAT_MASK_INT number
ChunkData = {}
