---@meta IconRendererDelegate
---@class IconRendererDelegate: MulticastDelegate
---@field ctor fun(object: table, method: IntPtr): IconRendererDelegate
---@field Invoke fun(ctx: Context, x: number, y: number, w: Single, h: Single, rgba: Double[]): nil
---@field BeginInvoke fun(ctx: Context, x: number, y: number, w: Single, h: Single, rgba: Double[], callback: AsyncCallback, object: table): IAsyncResult
---@field EndInvoke fun(result: IAsyncResult): nil
---@field GetObjectData fun(info: SerializationInfo, context: StreamingContext): nil
---@field Equals fun(obj: table): boolean
---@field GetInvocationList fun(): Delegate[]
---@field GetHashCode fun(): number
---@field get_Target fun(): table
---@field Clone fun(): table
---@field DynamicInvoke fun(args: table[]): table
---@field get_Method fun(): MethodInfo
---@field GetType fun(): any
---@field ToString fun(): string
---@field Target table
---@field Method table
IconRendererDelegate = {}
