---@meta Packet_Server
---@class Packet_Server: Object
---@field ctor fun(): Packet_Server
---@field SerializeTo fun(stream: CitoStream): nil
---@field SetId fun(value: number): nil
---@field SetToken fun(value: Packet_LoginTokenAnswer): nil
---@field SetIdentification fun(value: Packet_ServerIdentification): nil
---@field SetLevelInitialize fun(value: Packet_ServerLevelInitialize): nil
---@field SetLevelDataChunk fun(value: Packet_ServerLevelProgress): nil
---@field SetLevelFinalize fun(value: Packet_ServerLevelFinalize): nil
---@field SetSetBlock fun(value: Packet_ServerSetBlock): nil
---@field SetChatline fun(value: Packet_ChatLine): nil
---@field SetDisconnectPlayer fun(value: Packet_ServerDisconnectPlayer): nil
---@field SetChunks fun(value: Packet_ServerChunks): nil
---@field SetUnloadChunk fun(value: Packet_UnloadServerChunk): nil
---@field SetCalendar fun(value: Packet_ServerCalendar): nil
---@field SetMapChunk fun(value: Packet_ServerMapChunk): nil
---@field SetPing fun(value: Packet_ServerPing): nil
---@field SetPlayerPing fun(value: Packet_ServerPlayerPing): nil
---@field SetSound fun(value: Packet_ServerSound): nil
---@field SetAssets fun(value: Packet_ServerAssets): nil
---@field SetWorldMetaData fun(value: Packet_WorldMetaData): nil
---@field SetQueryAnswer fun(value: Packet_ServerQueryAnswer): nil
---@field SetRedirect fun(value: Packet_ServerRedirect): nil
---@field SetInventoryContents fun(value: Packet_InventoryContents): nil
---@field SetInventoryUpdate fun(value: Packet_InventoryUpdate): nil
---@field SetInventoryDoubleUpdate fun(value: Packet_InventoryDoubleUpdate): nil
---@field SetEntity fun(value: Packet_Entity): nil
---@field SetEntitySpawn fun(value: Packet_EntitySpawn): nil
---@field SetEntityDespawn fun(value: Packet_EntityDespawn): nil
---@field SetEntityMoved fun(value: Packet_EntityMoved): nil
---@field SetEntityAttributes fun(value: Packet_EntityAttributes): nil
---@field SetEntityAttributeUpdate fun(value: Packet_EntityAttributeUpdate): nil
---@field SetEntityPacket fun(value: Packet_EntityPacket): nil
---@field SetEntities fun(value: Packet_Entities): nil
---@field SetPlayerData fun(value: Packet_PlayerData): nil
---@field SetMapRegion fun(value: Packet_MapRegion): nil
---@field SetBlockEntityMessage fun(value: Packet_BlockEntityMessage): nil
---@field SetPlayerDeath fun(value: Packet_PlayerDeath): nil
---@field SetModeChange fun(value: Packet_PlayerMode): nil
---@field SetSetBlocks fun(value: Packet_ServerSetBlocks): nil
---@field SetBlockEntities fun(value: Packet_BlockEntities): nil
---@field SetPlayerGroups fun(value: Packet_PlayerGroups): nil
---@field SetPlayerGroup fun(value: Packet_PlayerGroup): nil
---@field SetSpawnPosition fun(value: Packet_EntityPosition): nil
---@field SetHighlightBlocks fun(value: Packet_HighlightBlocks): nil
---@field SetSelectedHotbarSlot fun(value: Packet_SelectedHotbarSlot): nil
---@field SetCustomPacket fun(value: Packet_CustomPacket): nil
---@field SetNetworkChannels fun(value: Packet_NetworkChannels): nil
---@field SetGotoGroup fun(value: Packet_GotoGroup): nil
---@field SetExchangeBlock fun(value: Packet_ServerExchangeBlock): nil
---@field SetBulkEntityAttributes fun(value: Packet_BulkEntityAttributes): nil
---@field SetSpawnParticles fun(value: Packet_SpawnParticles): nil
---@field SetBulkEntityDebugAttributes fun(value: Packet_BulkEntityDebugAttributes): nil
---@field SetSetBlocksNoRelight fun(value: Packet_ServerSetBlocks): nil
---@field SetBlockDamage fun(value: Packet_BlockDamage): nil
---@field SetAmbient fun(value: Packet_Ambient): nil
---@field SetNotifySlot fun(value: Packet_NotifySlot): nil
---@field SetIngameError fun(value: Packet_IngameError): nil
---@field SetIngameDiscovery fun(value: Packet_IngameDiscovery): nil
---@field SetSetBlocksMinimal fun(value: Packet_ServerSetBlocks): nil
---@field SetSetDecors fun(value: Packet_ServerSetDecors): nil
---@field SetRemoveBlockLight fun(value: Packet_RemoveBlockLight): nil
---@field SetServerReady fun(value: Packet_ServerReady): nil
---@field SetUnloadMapRegion fun(value: Packet_UnloadMapRegion): nil
---@field SetLandClaims fun(value: Packet_LandClaims): nil
---@field SetRoles fun(value: Packet_Roles): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_Server = {}
