---@meta ObjectConverter
---@class ObjectConverter: Object
---@field FromJson fun(utf8Text: string): T
---@overload fun(data: number[]): T
---@field FromBinary fun(data: number[]): T
---@field ToBinary fun(obj: T): number[]
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
ObjectConverter = {}
