---@meta ThreadSafeRandom
---@class ThreadSafeRandom: Random
---@field ctor fun(seed: number): ThreadSafeRandom
---@overload fun(): ThreadSafeRandom
---@field Next fun(maxValue: number): number
---@field NextDouble fun(): Double
---@field Next fun(): number
---@overload fun(minValue: number, maxValue: number): number
---@field NextBytes fun(buffer: number[]): nil
---@field NextInt64 fun(): Int64
---@overload fun(maxValue: Int64): Int64
---@overload fun(minValue: Int64, maxValue: Int64): Int64
---@field NextSingle fun(): Single
---@field NextBytes fun(buffer: Span`1): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
ThreadSafeRandom = {}
