---@meta ServerThread
---@class ServerThread: Object
---@field ctor fun(server: ServerMain, threadName: string, cancellationToken: CancellationToken): ServerThread
---@field get_Alive fun(): boolean
---@field Process fun(): nil
---@field ShutDown fun(): nil
---@field Update fun(): boolean
---@field OnBeginInitialization fun(): nil
---@field OnBeginConfiguration fun(): nil
---@field OnPrepareAssets fun(): nil
---@field OnBeginLoadGamePre fun(): nil
---@field OnBeginLoadGame fun(savegame: SaveGame): nil
---@field OnBeginRunGame fun(): nil
---@field OnBeginShutdown fun(): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field Alive boolean
---@field ShouldPause boolean
---@field serversystems boolean
---@field SleepMs boolean
ServerThread = {}
