---@meta ClientEventAPI
---@class ClientEventAPI: Object
---@field ctor fun(game: ClientMain): ClientEventAPI
---@field add_MouseDown fun(value: MouseEventDelegate): nil
---@field remove_MouseDown fun(value: MouseEventDelegate): nil
---@field add_MouseUp fun(value: MouseEventDelegate): nil
---@field remove_MouseUp fun(value: MouseEventDelegate): nil
---@field add_MouseMove fun(value: MouseEventDelegate): nil
---@field remove_MouseMove fun(value: MouseEventDelegate): nil
---@field add_KeyDown fun(value: KeyEventDelegate): nil
---@field remove_KeyDown fun(value: KeyEventDelegate): nil
---@field add_KeyUp fun(value: KeyEventDelegate): nil
---@field remove_KeyUp fun(value: KeyEventDelegate): nil
---@field add_FileDrop fun(value: FileDropDelegate): nil
---@field remove_FileDrop fun(value: FileDropDelegate): nil
---@field add_PlayerJoin fun(value: PlayerEventDelegate): nil
---@field remove_PlayerJoin fun(value: PlayerEventDelegate): nil
---@field add_PlayerLeave fun(value: PlayerEventDelegate): nil
---@field remove_PlayerLeave fun(value: PlayerEventDelegate): nil
---@field add_PlayerEntitySpawn fun(value: PlayerEventDelegate): nil
---@field remove_PlayerEntitySpawn fun(value: PlayerEventDelegate): nil
---@field add_PlayerEntityDespawn fun(value: PlayerEventDelegate): nil
---@field remove_PlayerEntityDespawn fun(value: PlayerEventDelegate): nil
---@field add_BlockTexturesLoaded fun(value: Action): nil
---@field remove_BlockTexturesLoaded fun(value: Action): nil
---@field add_IsPlayerReady fun(value: IsPlayerReadyDelegate): nil
---@field remove_IsPlayerReady fun(value: IsPlayerReadyDelegate): nil
---@field add_PauseResume fun(value: OnGamePauseResume): nil
---@field remove_PauseResume fun(value: OnGamePauseResume): nil
---@field add_LeaveWorld fun(value: Action): nil
---@field remove_LeaveWorld fun(value: Action): nil
---@field add_LeftWorld fun(value: Action): nil
---@field remove_LeftWorld fun(value: Action): nil
---@field add_ChatMessage fun(value: ChatLineDelegate): nil
---@field remove_ChatMessage fun(value: ChatLineDelegate): nil
---@field add_BlockChanged fun(value: BlockChangedDelegate): nil
---@field remove_BlockChanged fun(value: BlockChangedDelegate): nil
---@field add_BeforeActiveSlotChanged fun(value: fun(outResult: any): any): nil
---@field remove_BeforeActiveSlotChanged fun(value: fun(outResult: any): any): nil
---@field add_AfterActiveSlotChanged fun(value: any`1): nil
---@field remove_AfterActiveSlotChanged fun(value: any`1): nil
---@field add_ChunkDirty fun(value: ChunkDirtyDelegate): nil
---@field remove_ChunkDirty fun(value: ChunkDirtyDelegate): nil
---@field add_LevelFinalize fun(value: Action): nil
---@field remove_LevelFinalize fun(value: Action): nil
---@field add_HotkeysChanged fun(value: Action): nil
---@field remove_HotkeysChanged fun(value: Action): nil
---@field add_OnSendChatMessage fun(value: ClientChatLineDelegate): nil
---@field remove_OnSendChatMessage fun(value: ClientChatLineDelegate): nil
---@field add_OnEntityDeath fun(value: EntityDeathDelegate): nil
---@field remove_OnEntityDeath fun(value: EntityDeathDelegate): nil
---@field add_MatchesGridRecipe fun(value: MatchGridRecipeDelegate): nil
---@field remove_MatchesGridRecipe fun(value: MatchGridRecipeDelegate): nil
---@field add_PlayerDeath fun(value: PlayerEventDelegate): nil
---@field remove_PlayerDeath fun(value: PlayerEventDelegate): nil
---@field add_OnTestBlockAccess fun(value: TestBlockAccessDelegate): nil
---@field remove_OnTestBlockAccess fun(value: TestBlockAccessDelegate): nil
---@field add_MapRegionLoaded fun(value: MapRegionLoadedDelegate): nil
---@field remove_MapRegionLoaded fun(value: MapRegionLoadedDelegate): nil
---@field add_MapRegionUnloaded fun(value: MapRegionUnloadDelegate): nil
---@field remove_MapRegionUnloaded fun(value: MapRegionUnloadDelegate): nil
---@field add_OnGetClimate fun(value: OnGetClimateDelegate): nil
---@field remove_OnGetClimate fun(value: OnGetClimateDelegate): nil
---@field add_TestBlockAccess fun(value: TestBlockAccessDelegate): nil
---@field remove_TestBlockAccess fun(value: TestBlockAccessDelegate): nil
---@field add_OnGetWindSpeed fun(value: OnGetWindSpeedDelegate): nil
---@field remove_OnGetWindSpeed fun(value: OnGetWindSpeedDelegate): nil
---@field add_InGameError fun(value: IngameErrorDelegate): nil
---@field remove_InGameError fun(value: IngameErrorDelegate): nil
---@field add_InGameDiscovery fun(value: IngameDiscoveryDelegate): nil
---@field remove_InGameDiscovery fun(value: IngameDiscoveryDelegate): nil
---@field add_ColorsPresetChanged fun(value: Action): nil
---@field remove_ColorsPresetChanged fun(value: Action): nil
---@field add_OnEntitySpawn fun(value: EntityDelegate): nil
---@field remove_OnEntitySpawn fun(value: EntityDelegate): nil
---@field add_OnEntityLoaded fun(value: EntityDelegate): nil
---@field remove_OnEntityLoaded fun(value: EntityDelegate): nil
---@field add_OnEntityDespawn fun(value: EntityDespawnDelegate): nil
---@field remove_OnEntityDespawn fun(value: EntityDespawnDelegate): nil
---@field add_ReloadShader fun(value: ActionBoolReturn): nil
---@field remove_ReloadShader fun(value: ActionBoolReturn): nil
---@field add_ReloadTextures fun(value: Action): nil
---@field remove_ReloadTextures fun(value: Action): nil
---@field add_ReloadShapes fun(value: Action): nil
---@field remove_ReloadShapes fun(value: Action): nil
---@field TriggerTestBlockAccess fun(player: IPlayer, blockSel: BlockSelection, accessType: EnumBlockAccessFlags, claimant: string, response: EnumWorldAccessResponse): EnumWorldAccessResponse
---@field TriggerMapregionLoaded fun(mapCoord: Vec2i, mapregion: IMapRegion): nil
---@field TriggerMapregionUnloaded fun(mapCoord: Vec2i, mapregion: IMapRegion): nil
---@field TriggerChunkDirty fun(chunkCoord: Vec3i, chunk: IWorldChunk, reason: EnumChunkDirtyReason): nil
---@field TriggerBlockChanged fun(pos: BlockPos, oldBlock: Block): nil
---@field TriggerPlayerJoin fun(plr: IClientPlayer): nil
---@field TriggerPlayerLeave fun(plr: IClientPlayer): nil
---@field TriggerPlayerEntitySpawn fun(plr: IClientPlayer): nil
---@field TriggerPlayerEntityDespawn fun(plr: IClientPlayer): nil
---@field TriggerFileDrop fun(filename: string): boolean
---@field TriggerPauseResume fun(pause: boolean): nil
---@field TriggerMouseDown fun(ev: MouseEvent): nil
---@field TriggerMouseUp fun(ev: MouseEvent): nil
---@field TriggerMouseMove fun(ev: MouseEvent): nil
---@field TriggerKeyDown fun(ev: KeyEvent): nil
---@field TriggerKeyUp fun(ev: KeyEvent): nil
---@field TriggerLevelFinalize fun(): nil
---@field TriggerLeaveWorld fun(): nil
---@field TriggerLeftWorld fun(): nil
---@field TriggerHotkeysChanged fun(): nil
---@field TriggerBlockTexturesLoaded fun(): nil
---@field TriggerIsPlayerReady fun(): boolean
---@field RegisterRenderer fun(renderer: IRenderer, stage: EnumRenderStage, profilingName: string): nil
---@field RegisterItemstackRenderer fun(forObj: Collectibletable, rendererDelegate: ItemRenderDelegate, target: EnumItemRenderTarget): nil
---@field UnregisterItemstackRenderer fun(forObj: Collectibletable, target: EnumItemRenderTarget): nil
---@field UnregisterRenderer fun(renderer: IRenderer, stage: EnumRenderStage): nil
---@field RegisterReloadShapes fun(handler: Action): nil
---@field UnregisterReloadShapes fun(handler: Action): nil
---@field RegisterOnLeaveWorld fun(handler: Action): nil
---@field PushEvent fun(eventName: string, data: IAttribute): nil
---@field RegisterEventBusListener fun(OnEvent: EventBusListenerDelegate, priority: Double, filterByEventName: string): nil
---@field RegisterGameTickListener fun(OnGameTick: any`1, millisecondInterval: number, initialDelayOffsetMs: number): Int64
---@overload fun(OnGameTick: any`1, errorHandler: any`1, millisecondInterval: number, initialDelayOffsetMs: number): Int64
---@overload fun(OnGameTick: Action`3, pos: BlockPos, millisecondInterval: number, initialDelayOffsetMs: number): Int64
---@field RegisterCallback fun(OnTimePassed: any`1, millisecondDelay: number): Int64
---@overload fun(OnTimePassed: any`1, millisecondDelay: number, permittedWhilePaused: boolean): Int64
---@overload fun(OnTimePassed: Action`3, pos: BlockPos, millisecondDelay: number): Int64
---@field UnregisterCallback fun(listenerId: Int64): nil
---@field UnregisterGameTickListener fun(listenerId: Int64): nil
---@field EnqueueMainThreadTask fun(action: Action, code: string): nil
---@field RegisterAsyncParticleSpawner fun(handler: ContinousParticleSpawnTaskDelegate): nil
---@field TriggerEntityDeath fun(entity: Entity, damageSourceForDeath: DamageSource): nil
---@field TriggerMatchesRecipe fun(forPlayer: IPlayer, gridRecipe: GridRecipe, ingredients: ItemSlot[], gridWidth: number): boolean
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
ClientEventAPI = {}
