---@meta Packet_ServerCalendarSerializer
---@class Packet_ServerCalendarSerializer: Object
---@field ctor fun(): Packet_ServerCalendarSerializer
---@field DeserializeLengthDelimitedNew fun(stream: CitoMemoryStream): Packet_ServerCalendar
---@field DeserializeBuffer fun(buffer: number[], length: number, instance: Packet_ServerCalendar): Packet_ServerCalendar
---@field Deserialize fun(stream: CitoMemoryStream, instance: Packet_ServerCalendar): Packet_ServerCalendar
---@field DeserializeLengthDelimited fun(stream: CitoMemoryStream, instance: Packet_ServerCalendar): Packet_ServerCalendar
---@field Serialize fun(stream: CitoStream, instance: Packet_ServerCalendar): nil
---@field SerializeToBytes fun(instance: Packet_ServerCalendar): number[]
---@field SerializeLengthDelimited fun(stream: CitoStream, instance: Packet_ServerCalendar): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_ServerCalendarSerializer = {}
