---@meta Packet_IngameDiscoverySerializer
---@class Packet_IngameDiscoverySerializer: Object
---@field ctor fun(): Packet_IngameDiscoverySerializer
---@field DeserializeLengthDelimitedNew fun(stream: CitoMemoryStream): Packet_IngameDiscovery
---@field DeserializeBuffer fun(buffer: number[], length: number, instance: Packet_IngameDiscovery): Packet_IngameDiscovery
---@field Deserialize fun(stream: CitoMemoryStream, instance: Packet_IngameDiscovery): Packet_IngameDiscovery
---@field DeserializeLengthDelimited fun(stream: CitoMemoryStream, instance: Packet_IngameDiscovery): Packet_IngameDiscovery
---@field Serialize fun(stream: CitoStream, instance: Packet_IngameDiscovery): nil
---@field SerializeToBytes fun(instance: Packet_IngameDiscovery): number[]
---@field SerializeLengthDelimited fun(stream: CitoStream, instance: Packet_IngameDiscovery): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_IngameDiscoverySerializer = {}
