---@meta ModInfo
---@class ModInfo: Object
---@field ctor fun(): ModInfo
---@overload fun(type: EnumModany, name: string, modID: string, version: string, description: string, authors: any[], contributors: any[], website: string, side: EnumAppSide, requiredOnClient: boolean, requiredOnServer: boolean, dependencies: any[]): ModInfo
---@field get_ModID fun(): string
---@field set_ModID fun(value: string): nil
---@field get_Authors fun(): IReadOnlyany[]
---@field set_Authors fun(value: IReadOnlyany[]): nil
---@field get_Contributors fun(): IReadOnlyany[]
---@field set_Contributors fun(value: IReadOnlyany[]): nil
---@field get_Side fun(): EnumAppSide
---@field set_Side fun(value: EnumAppSide): nil
---@field get_RequiredOnClient fun(): boolean
---@field set_RequiredOnClient fun(value: boolean): nil
---@field get_RequiredOnServer fun(): boolean
---@field set_RequiredOnServer fun(value: boolean): nil
---@field get_Dependencies fun(): IReadOnlyany[]
---@field set_Dependencies fun(value: IReadOnlyany[]): nil
---@field Init fun(): nil
---@field ToModID fun(name: string): string
---@field IsValidModID fun(str: string): boolean
---@field CompareTo fun(other: ModInfo): number
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field ModID string
---@field Authors string
---@field Contributors string
---@field Side string
---@field RequiredOnClient string
---@field RequiredOnServer string
---@field Dependencies string
---@field Type string
---@field TextureSize string
---@field Name string
---@field Version string
---@field NetworkVersion string
---@field Description string
---@field Website string
---@field CoreMod string
ModInfo = {}
