---@meta NetConnection
---@class NetConnection: Object
---@field RemoteEndPoint fun(): IPEndPointCi
---@field Send fun(data: number[], compressed: boolean): EnumSendResult
---@field HiPerformanceSend fun(box: BoxedPacket, logger: ILogger, compressionAllowed: boolean): EnumSendResult
---@field EqualsConnection fun(connection: NetConnection): boolean
---@field Shutdown fun(): nil
---@field Close fun(): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
NetConnection = {}
