---@meta ZStdWrapper
---@class ZStdWrapper: Object
---@field ctor fun(): ZStdWrapper
---@field ConstructCompressor fun(compressionLevel: number): IZStdCompressor
---@field CreateDecompressor fun(): IZStdDecompressor
---@field GetDecompressedSize fun(compressedFrame: ReadOnlySpan`1): UInt64
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
ZStdWrapper = {}
