---@meta Packet_ClientBlockPlaceOrBreak
---@class Packet_ClientBlockPlaceOrBreak: Object
---@field ctor fun(): Packet_ClientBlockPlaceOrBreak
---@field SetX fun(value: number): nil
---@field SetY fun(value: number): nil
---@field SetZ fun(value: number): nil
---@field SetMode fun(value: number): nil
---@field SetBlockType fun(value: number): nil
---@field SetOnBlockFace fun(value: number): nil
---@field SetHitX fun(value: Int64): nil
---@field SetHitY fun(value: Int64): nil
---@field SetHitZ fun(value: Int64): nil
---@field SetSelectionBoxIndex fun(value: number): nil
---@field SetDidOffset fun(value: number): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_ClientBlockPlaceOrBreak = {}
