---@meta ParticleManager
---@class ParticleManager: Object
---@field ctor fun(): ParticleManager
---@field Init fun(particleSystem: SystemRenderParticles): nil
---@field SpawnParticles fun(quantity: Single, color: number, minPos: Vec3d, maxPos: Vec3d, minVelocity: Vec3f, maxVelocity: Vec3f, lifeLength: Single, gravityEffect: Single, scale: Single, model: EnumParticleModel): nil
---@field EnqueueAsyncParticles fun(props: IParticlePropertiesProvider): nil
---@field SpawnParticles fun(properties: IParticlePropertiesProvider): nil
---@field SpawnBlockBreakingParticles fun(blockdamage: BlockDamage): nil
---@field SpawnParticlesOffThread fun(particleProperties: IParticlePropertiesProvider): number
---@field ParticlesAlive fun(model: EnumParticleModel): number
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
ParticleManager = {}
