---@meta ShaderProgramFinal
---@class ShaderProgramFinal: ShaderProgram
---@field ctor fun(): ShaderProgramFinal
---@field set_PrimaryScene2D fun(value: number): nil
---@field set_GlowParts2D fun(value: number): nil
---@field set_BloomParts2D fun(value: number): nil
---@field set_GodrayParts2D fun(value: number): nil
---@field set_SsaoScene2D fun(value: number): nil
---@field set_GammaLevel fun(value: Single): nil
---@field set_BrightnessLevel fun(value: Single): nil
---@field set_SepiaLevel fun(value: Single): nil
---@field set_DamageVignetting fun(value: Single): nil
---@field set_DamageVignettingSide fun(value: Single): nil
---@field set_FrostVignetting fun(value: Single): nil
---@field set_ExtraGamma fun(value: Single): nil
---@field set_WindWaveCounter fun(value: Single): nil
---@field set_GlitchEffectStrength fun(value: Single): nil
---@field set_Minlight fun(value: Single): nil
---@field set_Maxlight fun(value: Single): nil
---@field set_Minsat fun(value: Single): nil
---@field set_Maxsat fun(value: Single): nil
---@field set_InvFrameSizeIn fun(value: Vec2f): nil
---@field set_SunPosScreenIn fun(value: Vec3f): nil
---@field set_SunPos3dIn fun(value: Vec3f): nil
---@field set_PlayerViewVector fun(value: Vec3f): nil
---@field Compile fun(): boolean
---@field get_Disposed fun(): boolean
---@field get_ClampTexturesToEdge fun(): boolean
---@field set_ClampTexturesToEdge fun(value: boolean): nil
---@field get_LoadError fun(): boolean
---@field set_LoadError fun(value: boolean): nil
---@field SetCustomSampler fun(uniformName: string, isLinear: boolean): nil
---@field Uniform fun(uniformName: string, value: Single): nil
---@overload fun(uniformName: string, value: number): nil
---@overload fun(uniformName: string, value: Vec2f): nil
---@overload fun(uniformName: string, value: Vec3f): nil
---@overload fun(uniformName: string, value: Vec3i): nil
---@field Uniforms2 fun(uniformName: string, count: number, values: Single[]): nil
---@field Uniforms3 fun(uniformName: string, count: number, values: Single[]): nil
---@field Uniform fun(uniformName: string, value: Vec4f): nil
---@field Uniforms4 fun(uniformName: string, count: number, values: Single[]): nil
---@field UniformMatrix fun(uniformName: string, matrix: Single[]): nil
---@overload fun(uniformName: string, matrix: Matrix4&): nil
---@field HasUniform fun(uniformName: string): boolean
---@field BindTexture2D fun(samplerName: string, textureId: number, textureNumber: number): nil
---@overload fun(samplerName: string, textureId: number): nil
---@field BindTextureCube fun(samplerName: string, textureId: number, textureNumber: number): nil
---@field UniformMatrices4x3 fun(uniformName: string, count: number, matrix: Single[]): nil
---@field UniformMatrices fun(uniformName: string, count: number, matrix: Single[]): nil
---@field Use fun(): nil
---@field Stop fun(): nil
---@field Dispose fun(): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field PrimaryScene2D number
---@field GlowParts2D number
---@field BloomParts2D number
---@field GodrayParts2D number
---@field SsaoScene2D number
---@field GammaLevel number
---@field BrightnessLevel number
---@field SepiaLevel number
---@field DamageVignetting number
---@field DamageVignettingSide number
---@field FrostVignetting number
---@field ExtraGamma number
---@field WindWaveCounter number
---@field GlitchEffectStrength number
---@field Minlight number
---@field Maxlight number
---@field Minsat number
---@field Maxsat number
---@field InvFrameSizeIn number
---@field SunPosScreenIn number
---@field SunPos3dIn number
---@field PlayerViewVector number
---@field Disposed number
---@field ClampTexturesToEdge number
---@field LoadError number
---@field attributes number
---@field LoadFromFile number
---@field AssetDomain number
---@field PassId number
---@field ProgramId number
---@field PassName number
---@field VertexShader number
---@field GeometryShader number
---@field FragmentShader number
---@field uniformLocations number
---@field textureLocations number
---@field clampTToEdge number
---@field includes number
---@field customSamplers number
ShaderProgramFinal = {}
