---@meta Packet_CompositeTexture
---@class Packet_CompositeTexture: Object
---@field ctor fun(): Packet_CompositeTexture
---@field SetBase fun(value: string): nil
---@field GetOverlays fun(): Packet_BlendedOverlayTexture[]
---@field SetOverlays fun(value: Packet_BlendedOverlayTexture[], count: number, length: number): nil
---@overload fun(value: Packet_BlendedOverlayTexture[]): nil
---@field GetOverlaysCount fun(): number
---@field OverlaysAdd fun(value: Packet_BlendedOverlayTexture): nil
---@field GetAlternates fun(): Packet_CompositeTexture[]
---@field SetAlternates fun(value: Packet_CompositeTexture[], count: number, length: number): nil
---@overload fun(value: Packet_CompositeTexture[]): nil
---@field GetAlternatesCount fun(): number
---@field AlternatesAdd fun(value: Packet_CompositeTexture): nil
---@field SetRotation fun(value: number): nil
---@field SetAlpha fun(value: number): nil
---@field GetTiles fun(): Packet_CompositeTexture[]
---@field SetTiles fun(value: Packet_CompositeTexture[], count: number, length: number): nil
---@overload fun(value: Packet_CompositeTexture[]): nil
---@field GetTilesCount fun(): number
---@field TilesAdd fun(value: Packet_CompositeTexture): nil
---@field SetTilesWidth fun(value: number): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_CompositeTexture = {}
