---@meta ChunkColumnLoadRequest
---@class ChunkColumnLoadRequest: Object
---@field ctor fun(index2d: Int64, chunkX: number, chunkZ: number, clientId: number, untilPass: number, server: IShutDownMonitor): ChunkColumnLoadRequest
---@field get_Index fun(): Int64
---@field get_GenerateUntilPass fun(): EnumWorldGenPass
---@field get_CurrentIncompletePass fun(): EnumWorldGenPass
---@field set_CurrentIncompletePass fun(value: EnumWorldGenPass): nil
---@field get_CurrentIncompletePass_AsInt fun(): number
---@field get_ChunkX fun(): number
---@field get_ChunkZ fun(): number
---@field get_ChunkGenParams fun(): ITreeAttribute
---@field get_NeighbourTerrainHeight fun(): UInt16[][]
---@field set_NeighbourTerrainHeight fun(value: UInt16[][]): nil
---@field get_RequiresChunkBorderSmoothing fun(): boolean
---@field set_RequiresChunkBorderSmoothing fun(value: boolean): nil
---@field FlagToDispose fun(): nil
---@field FlagToRequeue fun(): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field Index Int64
---@field GenerateUntilPass Int64
---@field CurrentIncompletePass Int64
---@field CurrentIncompletePass_AsInt Int64
---@field ChunkX Int64
---@field ChunkZ Int64
---@field ChunkGenParams Int64
---@field NeighbourTerrainHeight Int64
---@field RequiresChunkBorderSmoothing Int64
ChunkColumnLoadRequest = {}
