---@meta ChunkTesselatorManager
---@class ChunkTesselatorManager: ClientSystem
---@field ctor fun(game: ClientMain): ChunkTesselatorManager
---@field get_Name fun(): string
---@field Dispose fun(game: ClientMain): nil
---@field SeperateThreadTickIntervalMs fun(): number
---@field OnBlockTexturesLoaded fun(): nil
---@field OnBeforeFrame fun(dt: Single): nil
---@field OnSeperateThreadGameTick fun(dt: Single): nil
---@field TesselateChunk fun(chunkX: number, chunkY: number, chunkZ: number, priority: boolean, skipChunkCenter: boolean, requeue: boolean&): number
---@field GetSystemType fun(): EnumClientSystemany
---@field OnNewFrameReadOnlyMainThread fun(deltaTime: Single): nil
---@field OnKeyDown fun(args: KeyEvent): nil
---@field OnKeyPress fun(args: KeyEvent): nil
---@field OnMouseUp fun(args: MouseEvent): nil
---@field OnKeyUp fun(args: KeyEvent): nil
---@field OnMouseDown fun(args: MouseEvent): nil
---@field OnMouseMove fun(args: MouseEvent): nil
---@field OnMouseWheel fun(args: MouseWheelEventArgs): nil
---@field OnTouchStart fun(e: TouchEventArgs): nil
---@field OnTouchMove fun(e: TouchEventArgs): nil
---@field OnTouchEnd fun(e: TouchEventArgs): nil
---@field OnUseEntity fun(e: OnUseEntityArgs): nil
---@field OnHitEntity fun(e: OnUseEntityArgs): nil
---@field OnOwnPlayerDataReceived fun(): nil
---@field OnMouseEnterSlot fun(slot: ItemSlot): boolean
---@field OnMouseLeaveSlot fun(itemSlot: ItemSlot): boolean
---@field OnMouseClickSlot fun(itemSlot: ItemSlot): boolean
---@field OnServerIdentificationReceived fun(): nil
---@field CaptureAllInputs fun(): boolean
---@field CaptureRawMouse fun(): boolean
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field Name string
---@field cumulativeTime string
---@field cumulativeCount string
ChunkTesselatorManager = {}
