---@meta FastLargeSetOfLongs
---@class FastLargeSetOfLongs: Object
---@field ctor fun(numbuckets: number): FastLargeSetOfLongs
---@field get_Count fun(): number
---@field Clear fun(): nil
---@field Add fun(value: Int64): boolean
---@field GetEnumerator fun(): IEnumerator`1
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field Count number
FastLargeSetOfLongs = {}
