---@meta EntityTalkUtil
---@class EntityTalkUtil: Object
---@field ctor fun(api: ICoreAPI, atEntity: Entity): EntityTalkUtil
---@field SetModifiers fun(chordDelayMul: Single, pitchModifier: Single, volumneModifier: Single): nil
---@field OnGameTick fun(dt: Single): nil
---@field Talk fun(talkType: EnumTalkany): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
EntityTalkUtil = {}
