---@meta Packet_NutritionPropertiesSerializer
---@class Packet_NutritionPropertiesSerializer: Object
---@field ctor fun(): Packet_NutritionPropertiesSerializer
---@field DeserializeLengthDelimitedNew fun(stream: CitoMemoryStream): Packet_NutritionProperties
---@field DeserializeBuffer fun(buffer: number[], length: number, instance: Packet_NutritionProperties): Packet_NutritionProperties
---@field Deserialize fun(stream: CitoMemoryStream, instance: Packet_NutritionProperties): Packet_NutritionProperties
---@field DeserializeLengthDelimited fun(stream: CitoMemoryStream, instance: Packet_NutritionProperties): Packet_NutritionProperties
---@field Serialize fun(stream: CitoStream, instance: Packet_NutritionProperties): nil
---@field SerializeToBytes fun(instance: Packet_NutritionProperties): number[]
---@field SerializeLengthDelimited fun(stream: CitoStream, instance: Packet_NutritionProperties): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_NutritionPropertiesSerializer = {}
