---@meta TextureSource
---@class TextureSource: Object
---@field ctor fun(game: ClientMain, atlasSize: Size2i, block: Block, forInventory: boolean): TextureSource
---@overload fun(game: ClientMain, atlasSize: Size2i, item: Item): TextureSource
---@overload fun(game: ClientMain, atlasSize: Size2i, entity: Entity, extraTextures: table<any, any>, altTextureNumber: number): TextureSource
---@overload fun(game: ClientMain, atlasSize: Size2i, block: Block, altTextureNumber: number): TextureSource
---@field get_AtlasSize fun(): Size2i
---@field UpdateVariant fun(block: Block, altTextureNumber: number): nil
---@field get_Item fun(textureCode: string): TextureAtlasPosition
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field AtlasSize Size2i
---@field Item Size2i
---@field atlasSize Size2i
---@field entity Size2i
---@field block Size2i
---@field item Size2i
---@field isDecalUv Size2i
---@field returnNullWhenMissing Size2i
---@field atlasMgr Size2i
TextureSource = {}
