---@meta Packet_VariantPartSerializer
---@class Packet_VariantPartSerializer: Object
---@field ctor fun(): Packet_VariantPartSerializer
---@field DeserializeLengthDelimitedNew fun(stream: CitoMemoryStream): Packet_VariantPart
---@field DeserializeBuffer fun(buffer: number[], length: number, instance: Packet_VariantPart): Packet_VariantPart
---@field Deserialize fun(stream: CitoMemoryStream, instance: Packet_VariantPart): Packet_VariantPart
---@field DeserializeLengthDelimited fun(stream: CitoMemoryStream, instance: Packet_VariantPart): Packet_VariantPart
---@field Serialize fun(stream: CitoStream, instance: Packet_VariantPart): nil
---@field SerializeToBytes fun(instance: Packet_VariantPart): number[]
---@field SerializeLengthDelimited fun(stream: CitoStream, instance: Packet_VariantPart): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_VariantPartSerializer = {}
