---@meta Packet_EntityMovedSerializer
---@class Packet_EntityMovedSerializer: Object
---@field ctor fun(): Packet_EntityMovedSerializer
---@field DeserializeLengthDelimitedNew fun(stream: CitoMemoryStream): Packet_EntityMoved
---@field DeserializeBuffer fun(buffer: number[], length: number, instance: Packet_EntityMoved): Packet_EntityMoved
---@field Deserialize fun(stream: CitoMemoryStream, instance: Packet_EntityMoved): Packet_EntityMoved
---@field DeserializeLengthDelimited fun(stream: CitoMemoryStream, instance: Packet_EntityMoved): Packet_EntityMoved
---@field Serialize fun(stream: CitoStream, instance: Packet_EntityMoved): nil
---@field SerializeToBytes fun(instance: Packet_EntityMoved): number[]
---@field SerializeLengthDelimited fun(stream: CitoStream, instance: Packet_EntityMoved): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_EntityMovedSerializer = {}
