---@meta Cuboidd
---@class Cuboidd: Object
---@field ctor fun(): Cuboidd
---@overload fun(x1: Double, y1: Double, z1: Double, x2: Double, y2: Double, z2: Double): Cuboidd
---@field get_Width fun(): Double
---@field get_Height fun(): Double
---@field get_Length fun(): Double
---@field get_MinX fun(): Double
---@field get_MinY fun(): Double
---@field get_MinZ fun(): Double
---@field get_MaxX fun(): Double
---@field get_MaxY fun(): Double
---@field get_MaxZ fun(): Double
---@field get_Start fun(): Vec3d
---@field get_End fun(): Vec3d
---@field Set fun(x1: Double, y1: Double, z1: Double, x2: Double, y2: Double, z2: Double): Cuboidd
---@overload fun(min: IVec3, max: IVec3): Cuboidd
---@overload fun(selectionBox: Cuboidf): Cuboidd
---@overload fun(other: Cuboidd): nil
---@field SetAndTranslate fun(selectionBox: Cuboidf, vec: Vec3d): Cuboidd
---@overload fun(selectionBox: Cuboidf, dX: Double, dY: Double, dZ: Double): Cuboidd
---@field RemoveRoundingErrors fun(): nil
---@field Translate fun(vec: IVec3): Cuboidd
---@overload fun(posX: Double, posY: Double, posZ: Double): Cuboidd
---@field GrowBy fun(dx: Double, dy: Double, dz: Double): Cuboidd
---@field ContainsOrTouches fun(x: Double, y: Double, z: Double): boolean
---@field Contains fun(x: Double, y: Double, z: Double): boolean
---@field ContainsOrTouches fun(vec: IVec3): boolean
---@field GrowToInclude fun(x: number, y: number, z: number): Cuboidd
---@overload fun(vec: IVec3): Cuboidd
---@field ShortestDistanceFrom fun(x: Double, y: Double, z: Double): Double
---@field ToCuboidi fun(): Cuboidi
---@field ShortestVerticalDistanceFrom fun(y: Double): Double
---@overload fun(cuboid: Cuboidd): Double
---@overload fun(cuboid: Cuboidf, offset: EntityPos): Double
---@overload fun(cuboid: Cuboidd): Double
---@overload fun(cuboid: Cuboidf, offset: BlockPos): Double
---@field ShortestHorizontalDistanceFrom fun(cuboid: Cuboidf, offset: BlockPos): Double
---@overload fun(x: Double, z: Double): Double
---@overload fun(vec: IVec3): Double
---@field pushOutX fun(from: Cuboidd, motx: Double, direction: EnumPushDirection&): Double
---@field pushOutY fun(from: Cuboidd, moty: Double, direction: EnumPushDirection&): Double
---@field pushOutZ fun(from: Cuboidd, motz: Double, direction: EnumPushDirection&): Double
---@field RotatedCopy fun(degX: Double, degY: Double, degZ: Double, origin: Vec3d): Cuboidd
---@overload fun(vec: IVec3, origin: Vec3d): Cuboidd
---@field OffsetCopy fun(x: Double, y: Double, z: Double): Cuboidd
---@overload fun(vec: IVec3): Cuboidd
---@field Intersects fun(other: Cuboidd): boolean
---@overload fun(other: Cuboidf): boolean
---@overload fun(other: Cuboidf, offset: Vec3d): boolean
---@overload fun(other: Cuboidf, offsetx: Double, offsety: Double, offsetz: Double): boolean
---@field IntersectsOrTouches fun(other: Cuboidd): boolean
---@overload fun(other: Cuboidf, offset: Vec3d): boolean
---@overload fun(other: Cuboidf, offsetX: Double, offsetY: Double, offsetZ: Double): boolean
---@field ToFloat fun(): Cuboidf
---@field Clone fun(): Cuboidd
---@field Equals fun(other: Cuboidd): boolean
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field Width Double
---@field Height Double
---@field Length Double
---@field MinX Double
---@field MinY Double
---@field MinZ Double
---@field MaxX Double
---@field MaxY Double
---@field MaxZ Double
---@field Start Double
---@field End Double
---@field X1 Double
---@field Y1 Double
---@field Z1 Double
---@field X2 Double
---@field Y2 Double
---@field Z2 Double
Cuboidd = {}
