---@meta Attribute
---@class Attribute: Object
---@field GetCustomAttributes fun(element: MemberInfo, attributeType: any): Attribute[]
---@overload fun(element: MemberInfo, attributeType: any, inherit: boolean): Attribute[]
---@overload fun(element: MemberInfo): Attribute[]
---@overload fun(element: MemberInfo, inherit: boolean): Attribute[]
---@field IsDefined fun(element: MemberInfo, attributeType: any): boolean
---@overload fun(element: MemberInfo, attributeType: any, inherit: boolean): boolean
---@field GetCustomAttribute fun(element: MemberInfo, attributeType: any): Attribute
---@overload fun(element: MemberInfo, attributeType: any, inherit: boolean): Attribute
---@overload fun(element: ParameterInfo): Attribute[]
---@overload fun(element: ParameterInfo, attributeType: any): Attribute[]
---@overload fun(element: ParameterInfo, attributeType: any, inherit: boolean): Attribute[]
---@overload fun(element: ParameterInfo, inherit: boolean): Attribute[]
---@overload fun(element: ParameterInfo, attributeType: any): boolean
---@overload fun(element: ParameterInfo, attributeType: any, inherit: boolean): boolean
---@overload fun(element: ParameterInfo, attributeType: any): Attribute
---@overload fun(element: ParameterInfo, attributeType: any, inherit: boolean): Attribute
---@overload fun(element: Module, attributeType: any): Attribute[]
---@overload fun(element: Module): Attribute[]
---@overload fun(element: Module, inherit: boolean): Attribute[]
---@overload fun(element: Module, attributeType: any, inherit: boolean): Attribute[]
---@overload fun(element: Module, attributeType: any): boolean
---@overload fun(element: Module, attributeType: any, inherit: boolean): boolean
---@overload fun(element: Module, attributeType: any): Attribute
---@overload fun(element: Module, attributeType: any, inherit: boolean): Attribute
---@overload fun(element: Assembly, attributeType: any): Attribute[]
---@overload fun(element: Assembly, attributeType: any, inherit: boolean): Attribute[]
---@overload fun(element: Assembly): Attribute[]
---@overload fun(element: Assembly, inherit: boolean): Attribute[]
---@overload fun(element: Assembly, attributeType: any): boolean
---@overload fun(element: Assembly, attributeType: any, inherit: boolean): boolean
---@overload fun(element: Assembly, attributeType: any): Attribute
---@overload fun(element: Assembly, attributeType: any, inherit: boolean): Attribute
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field get_TypeId fun(): table
---@field Match fun(obj: table): boolean
---@field IsDefaultAttribute fun(): boolean
---@field GetType fun(): any
---@field ToString fun(): string
---@field TypeId table
Attribute = {}
