---@meta Packet_ServerChunk
---@class Packet_ServerChunk: Object
---@field ctor fun(): Packet_ServerChunk
---@field SetBlocks fun(value: number[]): nil
---@field SetLight fun(value: number[]): nil
---@field SetLightSat fun(value: number[]): nil
---@field SetLiquids fun(value: number[]): nil
---@field GetLightPositions fun(): number[]
---@field SetLightPositions fun(value: number[], count: number, length: number): nil
---@overload fun(value: number[]): nil
---@field GetLightPositionsCount fun(): number
---@field LightPositionsAdd fun(value: number): nil
---@field SetX fun(value: number): nil
---@field SetY fun(value: number): nil
---@field SetZ fun(value: number): nil
---@field GetEntities fun(): Packet_Entity[]
---@field SetEntities fun(value: Packet_Entity[], count: number, length: number): nil
---@overload fun(value: Packet_Entity[]): nil
---@field GetEntitiesCount fun(): number
---@field EntitiesAdd fun(value: Packet_Entity): nil
---@field GetBlockEntities fun(): Packet_BlockEntity[]
---@field SetBlockEntities fun(value: Packet_BlockEntity[], count: number, length: number): nil
---@overload fun(value: Packet_BlockEntity[]): nil
---@field GetBlockEntitiesCount fun(): number
---@field BlockEntitiesAdd fun(value: Packet_BlockEntity): nil
---@field SetModdata fun(value: number[]): nil
---@field SetEmpty fun(value: number): nil
---@field GetDecorsPos fun(): number[]
---@field SetDecorsPos fun(value: number[], count: number, length: number): nil
---@overload fun(value: number[]): nil
---@field GetDecorsPosCount fun(): number
---@field DecorsPosAdd fun(value: number): nil
---@field GetDecorsIds fun(): number[]
---@field SetDecorsIds fun(value: number[], count: number, length: number): nil
---@overload fun(value: number[]): nil
---@field GetDecorsIdsCount fun(): number
---@field DecorsIdsAdd fun(value: number): nil
---@field SetCompver fun(value: number): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_ServerChunk = {}
