---@meta FastList`1
---@class FastList`1: Object
---@field ctor fun(): FastList`1
---@field get_Count fun(): number
---@field Add fun(elem: TElem): nil
---@field Clear fun(): nil
---@field RemoveAt fun(index: number): nil
---@field get_Item fun(index: number): TElem
---@field set_Item fun(index: number, value: TElem): nil
---@field GetEnumerator fun(): IEnumerator
---@field Contains fun(needle: TElem): boolean
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field Count number
---@field Item number
FastList`1 = {}
