---@meta IMacroManager
---@class IMacroManager
---@field DeleteMacro fun(macroIndex: number): nil
---@field LoadMacros fun(): nil
---@field RunMacro fun(macroIndex: number, world: IClientWorldAccessor): boolean
---@field SaveMacro fun(macroIndex: number): boolean
---@field SetMacro fun(macroIndex: number, macro: IMacroBase): nil
---@field get_MacrosByIndex fun(): Sortedtable<any, any>
---@field set_MacrosByIndex fun(value: Sortedtable<any, any>): nil
---@field MacrosByIndex Sortedtable<any, any>
IMacroManager = {}
