---@meta IClientWorldAccessor
---@class IClientWorldAccessor
---@field GetColorMapData fun(block: Block, posX: number, posY: number, posZ: number): ColorMapData
---@field get_Calendar fun(): IClientGameCalendar
---@field ApplyColorMapOnRgba fun(climateColorMap: string, seasonColorMap: string, color: number, posX: number, posY: number, posZ: number, flipRb: boolean): number
---@overload fun(climateColorMap: ColorMap, seasonColorMap: ColorMap, color: number, posX: number, posY: number, posZ: number, flipRb: boolean): number
---@overload fun(climateColorMap: string, seasonColorMap: string, color: number, rain: number, temp: number, flipRb: boolean): number
---@field get_ForceLiquidSelectable fun(): boolean
---@field set_ForceLiquidSelectable fun(value: boolean): nil
---@field get_AmbientParticles fun(): boolean
---@field set_AmbientParticles fun(value: boolean): nil
---@field get_Player fun(): IClientPlayer
---@field LoadSound fun(param: SoundParams): ILoadedSound
---@field AddCameraShake fun(strengh: Single): nil
---@field SetCameraShake fun(strengh: Single): nil
---@field ReduceCameraShake fun(amount: Single): nil
---@field IncurBlockDamage fun(blockSelection: BlockSelection, withTool: Nullable`1, damage: Single): nil
---@field CloneBlockDamage fun(sourcePos: BlockPos, targetPos: BlockPos): nil
---@field TryAttackEntity fun(sele: EntitySelection): nil
---@field get_LoadedEntities fun(): table<any, any>
---@field get_Dimensions fun(): table<any, any>
---@field GetOrCreateDimension fun(dimId: number, pos: Vec3d): IMiniDimension
---@field TryGetMiniDimension fun(origin: Vec3i, dimension: IMiniDimension&): boolean
---@field SetBlocksPreviewDimension fun(dimId: number): nil
---@field PlaySoundAtAndGetDuration fun(sound: AssetLocation, x: Double, y: Double, z: Double, ignorePlayerUid: IPlayer, randomizePitch: boolean, range: Single, volume: Single): number
---@field Calendar IClientGameCalendar
---@field ForceLiquidSelectable IClientGameCalendar
---@field AmbientParticles IClientGameCalendar
---@field Player IClientGameCalendar
---@field LoadedEntities IClientGameCalendar
---@field Dimensions IClientGameCalendar
IClientWorldAccessor = {}
