---@meta Packet_BulkEntityAttributesSerializer
---@class Packet_BulkEntityAttributesSerializer: Object
---@field ctor fun(): Packet_BulkEntityAttributesSerializer
---@field DeserializeLengthDelimitedNew fun(stream: CitoMemoryStream): Packet_BulkEntityAttributes
---@field DeserializeBuffer fun(buffer: number[], length: number, instance: Packet_BulkEntityAttributes): Packet_BulkEntityAttributes
---@field Deserialize fun(stream: CitoMemoryStream, instance: Packet_BulkEntityAttributes): Packet_BulkEntityAttributes
---@field DeserializeLengthDelimited fun(stream: CitoMemoryStream, instance: Packet_BulkEntityAttributes): Packet_BulkEntityAttributes
---@field Serialize fun(stream: CitoStream, instance: Packet_BulkEntityAttributes): nil
---@field SerializeToBytes fun(instance: Packet_BulkEntityAttributes): number[]
---@field SerializeLengthDelimited fun(stream: CitoStream, instance: Packet_BulkEntityAttributes): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_BulkEntityAttributesSerializer = {}
