---@meta MultiblockStructure
---@class MultiblockStructure: Object
---@field ctor fun(): MultiblockStructure
---@field GetOrCreateBlockNumber fun(block: Block): number
---@field InitForUse fun(rotateYDeg: Single): nil
---@field WalkMatchingBlocks fun(world: IWorldAccessor, centerPos: BlockPos, onBlock: Action`2): nil
---@field InCompleteBlockCount fun(world: IWorldAccessor, centerPos: BlockPos, onMismatch: PositionMismatchDelegate): number
---@field ClearHighlights fun(world: IWorldAccessor, player: IPlayer): nil
---@field HighlightIncompleteParts fun(world: IWorldAccessor, player: IPlayer, centerPos: BlockPos): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
MultiblockStructure = {}
