---@meta Packet_IntMapSerializer
---@class Packet_IntMapSerializer: Object
---@field ctor fun(): Packet_IntMapSerializer
---@field DeserializeLengthDelimitedNew fun(stream: CitoMemoryStream): Packet_IntMap
---@field DeserializeBuffer fun(buffer: number[], length: number, instance: Packet_IntMap): Packet_IntMap
---@field Deserialize fun(stream: CitoMemoryStream, instance: Packet_IntMap): Packet_IntMap
---@field DeserializeLengthDelimited fun(stream: CitoMemoryStream, instance: Packet_IntMap): Packet_IntMap
---@field Serialize fun(stream: CitoStream, instance: Packet_IntMap): nil
---@field SerializeToBytes fun(instance: Packet_IntMap): number[]
---@field SerializeLengthDelimited fun(stream: CitoStream, instance: Packet_IntMap): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_IntMapSerializer = {}
