---@meta ShadowBox
---@class ShadowBox: Object
---@field ctor fun(lightViewMatrix: Double[], game: ClientMain): ShadowBox
---@field update fun(): nil
---@field get_Width fun(): Double
---@field get_Height fun(): Double
---@field get_Length fun(): Double
---@field calculateFrustumVertices fun(rotation: Double[], forwardVector: Vec4d, centerNear: Vec3d, centerFar: Vec3d): Vec4d[]
---@field calculateLightSpaceFrustumCorner fun(startPoint: Vec3d, direction: Vec3d, width: Double, target: Vec4d): nil
---@field getCameraRotationMatrix fun(): Double[]
---@field calculateWidthsAndHeights fun(): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field Width Double
---@field Height Double
---@field Length Double
---@field minX Double
---@field maxX Double
---@field minY Double
---@field maxY Double
---@field minZ Double
---@field maxZ Double
---@field lightViewMatrix Double
---@field farHeight Double
---@field farWidth Double
---@field nearHeight Double
---@field nearWidth Double
---@field ShadowBoxZExtend Double
---@field ShadowBoxYExtend Double
---@field UP Double
---@field FORWARD Double
---@field SHADOW_DISTANCE Double
ShadowBox = {}
