---@meta GamePaths
---@class GamePaths: Object
---@field get_AssetsPath fun(): string
---@field get_Binaries fun(): string
---@field get_BinariesMods fun(): string
---@field get_Config fun(): string
---@field get_ModConfig fun(): string
---@field get_Cache fun(): string
---@field get_Saves fun(): string
---@field get_OldSaves fun(): string
---@field get_BackupSaves fun(): string
---@field get_PlayerData fun(): string
---@field get_Backups fun(): string
---@field get_Logs fun(): string
---@field get_Macros fun(): string
---@field get_Screenshots fun(): string
---@field get_Videos fun(): string
---@field get_DataPathMods fun(): string
---@field get_DataPathServerMods fun(): string
---@field EnsurePathExists fun(path: string): nil
---@field EnsurePathsExist fun(): nil
---@field IsValidName fun(s: string): boolean
---@field ReplaceInvalidChars fun(filename: string): string
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field AssetsPath string
---@field Binaries string
---@field BinariesMods string
---@field Config string
---@field ModConfig string
---@field Cache string
---@field Saves string
---@field OldSaves string
---@field BackupSaves string
---@field PlayerData string
---@field Backups string
---@field Logs string
---@field Macros string
---@field Screenshots string
---@field Videos string
---@field DataPathMods string
---@field DataPathServerMods string
---@field AllowedNameChars string
---@field DataPath string
---@field CustomLogPath string
---@field DefaultSaveFilenameWithoutExtension string
GamePaths = {}
