---@meta GltfScene
---@class GltfScene: Object
---@field ctor fun(): GltfScene
---@field get_Name fun(): string
---@field set_Name fun(value: string): nil
---@field get_Nodes fun(): Int64[]
---@field set_Nodes fun(value: Int64[]): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field Name string
---@field Nodes string
GltfScene = {}
