---@meta Packet_EntityMoved
---@class Packet_EntityMoved: Object
---@field ctor fun(): Packet_EntityMoved
---@field SetEntityId fun(value: Int64): nil
---@field SetEntityPosition fun(value: Packet_EntityPosition): nil
---@field SetMotionX fun(value: number): nil
---@field SetMotionY fun(value: number): nil
---@field SetMotionZ fun(value: number): nil
---@field SetIsTeleport fun(value: number): nil
---@field SetControls fun(value: number): nil
---@field GetActiveAnimations fun(): number[]
---@field SetActiveAnimations fun(value: number[], count: number, length: number): nil
---@overload fun(value: number[]): nil
---@field GetActiveAnimationsCount fun(): number
---@field ActiveAnimationsAdd fun(value: number): nil
---@field GetActiveAnimationSpeeds fun(): number[]
---@field SetActiveAnimationSpeeds fun(value: number[], count: number, length: number): nil
---@overload fun(value: number[]): nil
---@field GetActiveAnimationSpeedsCount fun(): number
---@field ActiveAnimationSpeedsAdd fun(value: number): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_EntityMoved = {}
