---@meta GltfPbrMetallicRoughness
---@class GltfPbrMetallicRoughness: Object
---@field ctor fun(): GltfPbrMetallicRoughness
---@field get_BaseColorTexture fun(): GltfMatTexture
---@field set_BaseColorTexture fun(value: GltfMatTexture): nil
---@field get_BaseColorFactor fun(): Single[]
---@field set_BaseColorFactor fun(value: Single[]): nil
---@field get_MetallicFactor fun(): Nullable`1
---@field set_MetallicFactor fun(value: Nullable`1): nil
---@field get_RoughnessFactor fun(): Nullable`1
---@field set_RoughnessFactor fun(value: Nullable`1): nil
---@field get_PbrFactor fun(): Single[]
---@field get_MetallicRoughnessTexture fun(): GltfMatTexture
---@field set_MetallicRoughnessTexture fun(value: GltfMatTexture): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field BaseColorTexture GltfMatTexture
---@field BaseColorFactor GltfMatTexture
---@field MetallicFactor GltfMatTexture
---@field RoughnessFactor GltfMatTexture
---@field PbrFactor GltfMatTexture
---@field MetallicRoughnessTexture GltfMatTexture
GltfPbrMetallicRoughness = {}
