---@meta Packet_BehaviorSerializer
---@class Packet_BehaviorSerializer: Object
---@field ctor fun(): Packet_BehaviorSerializer
---@field DeserializeLengthDelimitedNew fun(stream: CitoMemoryStream): Packet_Behavior
---@field DeserializeBuffer fun(buffer: number[], length: number, instance: Packet_Behavior): Packet_Behavior
---@field Deserialize fun(stream: CitoMemoryStream, instance: Packet_Behavior): Packet_Behavior
---@field DeserializeLengthDelimited fun(stream: CitoMemoryStream, instance: Packet_Behavior): Packet_Behavior
---@field Serialize fun(stream: CitoStream, instance: Packet_Behavior): nil
---@field SerializeToBytes fun(instance: Packet_Behavior): number[]
---@field SerializeLengthDelimited fun(stream: CitoStream, instance: Packet_Behavior): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_BehaviorSerializer = {}
