---@meta NativeTypeNameAttribute
---@class NativeTypeNameAttribute: Attribute
---@field ctor fun(name: string): NativeTypeNameAttribute
---@field get_Name fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field get_TypeId fun(): table
---@field Match fun(obj: table): boolean
---@field IsDefaultAttribute fun(): boolean
---@field GetType fun(): any
---@field ToString fun(): string
---@field Name string
---@field TypeId string
NativeTypeNameAttribute = {}
