---@meta Packet_EntityMovedMinimalSerializer
---@class Packet_EntityMovedMinimalSerializer: Object
---@field ctor fun(): Packet_EntityMovedMinimalSerializer
---@field DeserializeLengthDelimitedNew fun(stream: CitoMemoryStream): Packet_EntityMovedMinimal
---@field DeserializeBuffer fun(buffer: number[], length: number, instance: Packet_EntityMovedMinimal): Packet_EntityMovedMinimal
---@field Deserialize fun(stream: CitoMemoryStream, instance: Packet_EntityMovedMinimal): Packet_EntityMovedMinimal
---@field DeserializeLengthDelimited fun(stream: CitoMemoryStream, instance: Packet_EntityMovedMinimal): Packet_EntityMovedMinimal
---@field Serialize fun(stream: CitoStream, instance: Packet_EntityMovedMinimal): nil
---@field SerializeToBytes fun(instance: Packet_EntityMovedMinimal): number[]
---@field SerializeLengthDelimited fun(stream: CitoStream, instance: Packet_EntityMovedMinimal): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_EntityMovedMinimalSerializer = {}
