---@meta Packet_ClientLeaveSerializer
---@class Packet_ClientLeaveSerializer: Object
---@field ctor fun(): Packet_ClientLeaveSerializer
---@field DeserializeLengthDelimitedNew fun(stream: CitoMemoryStream): Packet_ClientLeave
---@field DeserializeBuffer fun(buffer: number[], length: number, instance: Packet_ClientLeave): Packet_ClientLeave
---@field Deserialize fun(stream: CitoMemoryStream, instance: Packet_ClientLeave): Packet_ClientLeave
---@field DeserializeLengthDelimited fun(stream: CitoMemoryStream, instance: Packet_ClientLeave): Packet_ClientLeave
---@field Serialize fun(stream: CitoStream, instance: Packet_ClientLeave): nil
---@field SerializeToBytes fun(instance: Packet_ClientLeave): number[]
---@field SerializeLengthDelimited fun(stream: CitoStream, instance: Packet_ClientLeave): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_ClientLeaveSerializer = {}
