---@meta ModSystem
---@class ModSystem: Object
---@field get_Mod fun(): Mod
---@field ShouldLoad fun(forSide: EnumAppSide): boolean
---@field ExecuteOrder fun(): Double
---@field StartPre fun(api: ICoreAPI): nil
---@field Start fun(api: ICoreAPI): nil
---@field AssetsLoaded fun(api: ICoreAPI): nil
---@field AssetsFinalize fun(api: ICoreAPI): nil
---@field StartClientSide fun(api: ICoreClientAPI): nil
---@field StartServerSide fun(api: ICoreServerAPI): nil
---@field Dispose fun(): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field Mod Mod
ModSystem = {}
