---@meta GltfAnimationChannel
---@class GltfAnimationChannel: Object
---@field ctor fun(): GltfAnimationChannel
---@field get_Sampler fun(): Int64
---@field set_Sampler fun(value: Int64): nil
---@field get_Target fun(): GltfAnimationChannelTarget
---@field set_Target fun(value: GltfAnimationChannelTarget): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field Sampler Int64
---@field Target Int64
GltfAnimationChannel = {}
