---@meta Packet_RoleSerializer
---@class Packet_RoleSerializer: Object
---@field ctor fun(): Packet_RoleSerializer
---@field DeserializeLengthDelimitedNew fun(stream: CitoMemoryStream): Packet_Role
---@field DeserializeBuffer fun(buffer: number[], length: number, instance: Packet_Role): Packet_Role
---@field Deserialize fun(stream: CitoMemoryStream, instance: Packet_Role): Packet_Role
---@field DeserializeLengthDelimited fun(stream: CitoMemoryStream, instance: Packet_Role): Packet_Role
---@field Serialize fun(stream: CitoStream, instance: Packet_Role): nil
---@field SerializeToBytes fun(instance: Packet_Role): number[]
---@field SerializeLengthDelimited fun(stream: CitoStream, instance: Packet_Role): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_RoleSerializer = {}
