---@meta GltfAnimation
---@class GltfAnimation: Object
---@field ctor fun(): GltfAnimation
---@field get_Channels fun(): GltfAnimationChannel[]
---@field set_Channels fun(value: GltfAnimationChannel[]): nil
---@field get_Samplers fun(): GltfAnimationChannel[]
---@field set_Samplers fun(value: GltfAnimationChannel[]): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field Channels GltfAnimationChannel[]
---@field Samplers GltfAnimationChannel[]
GltfAnimation = {}
