---@meta IMountable
---@class IMountable
---@field get_CanControl fun(): boolean
---@field get_MountedBy fun(): Entity
---@field get_MountSupplier fun(): IMountableSupplier
---@field get_MountPosition fun(): EntityPos
---@field get_AngleMode fun(): EnumMountAngleMode
---@field get_SuggestedAnimation fun(): string
---@field get_LocalEyePos fun(): Vec3f
---@field get_Controls fun(): EntityControls
---@field MountableToTreeAttributes fun(tree: TreeAttribute): nil
---@field DidUnmount fun(entityAgent: EntityAgent): nil
---@field DidMount fun(entityAgent: EntityAgent): nil
---@field CanControl boolean
---@field MountedBy boolean
---@field MountSupplier boolean
---@field MountPosition boolean
---@field AngleMode boolean
---@field SuggestedAnimation boolean
---@field LocalEyePos boolean
---@field Controls boolean
IMountable = {}
