---@meta Packet_EntityAttributeUpdateSerializer
---@class Packet_EntityAttributeUpdateSerializer: Object
---@field ctor fun(): Packet_EntityAttributeUpdateSerializer
---@field DeserializeLengthDelimitedNew fun(stream: CitoMemoryStream): Packet_EntityAttributeUpdate
---@field DeserializeBuffer fun(buffer: number[], length: number, instance: Packet_EntityAttributeUpdate): Packet_EntityAttributeUpdate
---@field Deserialize fun(stream: CitoMemoryStream, instance: Packet_EntityAttributeUpdate): Packet_EntityAttributeUpdate
---@field DeserializeLengthDelimited fun(stream: CitoMemoryStream, instance: Packet_EntityAttributeUpdate): Packet_EntityAttributeUpdate
---@field Serialize fun(stream: CitoStream, instance: Packet_EntityAttributeUpdate): nil
---@field SerializeToBytes fun(instance: Packet_EntityAttributeUpdate): number[]
---@field SerializeLengthDelimited fun(stream: CitoStream, instance: Packet_EntityAttributeUpdate): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_EntityAttributeUpdateSerializer = {}
