---@meta IBlockFlowing
---@class IBlockFlowing
---@field get_Flow fun(): string
---@field set_Flow fun(value: string): nil
---@field get_FlowNormali fun(): Vec3i
---@field set_FlowNormali fun(value: Vec3i): nil
---@field get_IsLava fun(): boolean
---@field Flow string
---@field FlowNormali string
---@field IsLava string
IBlockFlowing = {}
