---@meta Packet_InventoryDoubleUpdate
---@class Packet_InventoryDoubleUpdate: Object
---@field ctor fun(): Packet_InventoryDoubleUpdate
---@field SetClientId fun(value: number): nil
---@field SetInventoryId1 fun(value: string): nil
---@field SetInventoryId2 fun(value: string): nil
---@field SetSlotId1 fun(value: number): nil
---@field SetSlotId2 fun(value: number): nil
---@field SetItemStack1 fun(value: Packet_ItemStack): nil
---@field SetItemStack2 fun(value: Packet_ItemStack): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_InventoryDoubleUpdate = {}
