---@meta ItemStack
---@class ItemStack: Object
---@field ctor fun(): ItemStack
---@overload fun(id: number, itemClass: EnumItemClass, stacksize: number, stackAttributes: TreeAttribute, resolver: IWorldAccessor): ItemStack
---@overload fun(reader: BinaryReader): ItemStack
---@overload fun(data: number[]): ItemStack
---@overload fun(reader: BinaryReader, resolver: IWorldAccessor): ItemStack
---@overload fun(collectible: Collectibletable, stacksize: number): ItemStack
---@overload fun(item: Item, stacksize: number): ItemStack
---@overload fun(block: Block, stacksize: number): ItemStack
---@field get_Collectible fun(): Collectibletable
---@field get_Item fun(): Item
---@field get_Block fun(): Block
---@field get_StackSize fun(): number
---@field set_StackSize fun(value: number): nil
---@field get_Attributes fun(): ITreeAttribute
---@field set_Attributes fun(value: ITreeAttribute): nil
---@field get_TempAttributes fun(): ITreeAttribute
---@field set_TempAttributes fun(value: ITreeAttribute): nil
---@field get_ItemAttributes fun(): Jsontable
---@field Equals fun(worldForResolve: IWorldAccessor, sourceStack: ItemStack, ignoreAttributeSubTrees: string[]): boolean
---@field Satisfies fun(sourceStack: ItemStack): boolean
---@field SetFrom fun(stack: ItemStack): nil
---@field ToString fun(): string
---@field ToBytes fun(): number[]
---@overload fun(stream: BinaryWriter): nil
---@field FromBytes fun(stream: BinaryReader): nil
---@field ResolveBlockOrItem fun(resolver: IWorldAccessor): boolean
---@field MatchesSearchText fun(world: IWorldAccessor, searchText: string): boolean
---@field GetName fun(): string
---@field GetDescription fun(world: IWorldAccessor, inSlot: ItemSlot, debug: boolean): string
---@field Clone fun(): ItemStack
---@field GetEmptyClone fun(): ItemStack
---@field FixMapping fun(oldBlockMapping: table<any, any>, oldItemMapping: table<any, any>, worldForNewMapping: IWorldAccessor): boolean
---@field GetHashCode fun(): number
---@overload fun(ignoredAttributes: string[]): number
---@field GetType fun(): any
---@field Equals fun(obj: table): boolean
---@field Collectible Collectibletable
---@field Item Collectibletable
---@field Block Collectibletable
---@field StackSize Collectibletable
---@field Attributes Collectibletable
---@field TempAttributes Collectibletable
---@field ItemAttributes Collectibletable
---@field Class Collectibletable
---@field Id Collectibletable
ItemStack = {}
