---@meta Packet_EntityPacket
---@class Packet_EntityPacket: Object
---@field ctor fun(): Packet_EntityPacket
---@field SetEntityId fun(value: Int64): nil
---@field SetPacketid fun(value: number): nil
---@field SetData fun(value: number[]): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_EntityPacket = {}
