---@meta Packet_ServerDisconnectPlayerSerializer
---@class Packet_ServerDisconnectPlayerSerializer: Object
---@field ctor fun(): Packet_ServerDisconnectPlayerSerializer
---@field DeserializeLengthDelimitedNew fun(stream: CitoMemoryStream): Packet_ServerDisconnectPlayer
---@field DeserializeBuffer fun(buffer: number[], length: number, instance: Packet_ServerDisconnectPlayer): Packet_ServerDisconnectPlayer
---@field Deserialize fun(stream: CitoMemoryStream, instance: Packet_ServerDisconnectPlayer): Packet_ServerDisconnectPlayer
---@field DeserializeLengthDelimited fun(stream: CitoMemoryStream, instance: Packet_ServerDisconnectPlayer): Packet_ServerDisconnectPlayer
---@field Serialize fun(stream: CitoStream, instance: Packet_ServerDisconnectPlayer): nil
---@field SerializeToBytes fun(instance: Packet_ServerDisconnectPlayer): number[]
---@field SerializeLengthDelimited fun(stream: CitoStream, instance: Packet_ServerDisconnectPlayer): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_ServerDisconnectPlayerSerializer = {}
