---@meta Packet_BlockSoundSetSerializer
---@class Packet_BlockSoundSetSerializer: Object
---@field ctor fun(): Packet_BlockSoundSetSerializer
---@field DeserializeLengthDelimitedNew fun(stream: CitoMemoryStream): Packet_BlockSoundSet
---@field DeserializeBuffer fun(buffer: number[], length: number, instance: Packet_BlockSoundSet): Packet_BlockSoundSet
---@field Deserialize fun(stream: CitoMemoryStream, instance: Packet_BlockSoundSet): Packet_BlockSoundSet
---@field DeserializeLengthDelimited fun(stream: CitoMemoryStream, instance: Packet_BlockSoundSet): Packet_BlockSoundSet
---@field Serialize fun(stream: CitoStream, instance: Packet_BlockSoundSet): nil
---@field SerializeToBytes fun(instance: Packet_BlockSoundSet): number[]
---@field SerializeLengthDelimited fun(stream: CitoStream, instance: Packet_BlockSoundSet): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_BlockSoundSetSerializer = {}
