---@meta MeshDataPoolManager
---@class MeshDataPoolManager: Object
---@field ctor fun(masterPool: MeshDataPoolMasterManager, frustumCuller: FrustumCulling, capi: ICoreClientAPI, defaultVertexPoolSize: number, defaultIndexPoolSize: number, maxPartsPerPool: number, customFloats: CustomMeshDataPartFloat, customShorts: CustomMeshDataPartShort, customBytes: CustomMeshDataPartnumber, customInts: CustomMeshDataPartInt): MeshDataPoolManager
---@field AddModel fun(modeldata: MeshData, modelOrigin: Vec3i, dimension: number, frustumCullSphere: Sphere): ModelDataPoolLocation
---@field Render fun(playerpos: Vec3d, originUniformName: string, frustumCullMode: EnumFrustumCullMode): nil
---@field GetStats fun(usedVideoMemory: Int64&, renderedTris: Int64&, allocatedTris: Int64&): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
MeshDataPoolManager = {}
