---@meta Packet_InventoryUpdate
---@class Packet_InventoryUpdate: Object
---@field ctor fun(): Packet_InventoryUpdate
---@field SetClientId fun(value: number): nil
---@field SetInventoryId fun(value: string): nil
---@field SetSlotId fun(value: number): nil
---@field SetItemStack fun(value: Packet_ItemStack): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
Packet_InventoryUpdate = {}
