---@meta NetworkChannelBase
---@class NetworkChannelBase: Object
---@field ctor fun(channelId: number, channelName: string): NetworkChannelBase
---@field get_ChannelName fun(): string
---@field RegisterMessageType fun(type: any): INetworkChannel
---@overload fun(): INetworkChannel
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field ChannelName string
NetworkChannelBase = {}
