---@meta IEventAPI
---@class IEventAPI
---@field add_OnTestBlockAccess fun(value: TestBlockAccessDelegate): nil
---@field remove_OnTestBlockAccess fun(value: TestBlockAccessDelegate): nil
---@field add_OnEntitySpawn fun(value: EntityDelegate): nil
---@field remove_OnEntitySpawn fun(value: EntityDelegate): nil
---@field add_OnEntityLoaded fun(value: EntityDelegate): nil
---@field remove_OnEntityLoaded fun(value: EntityDelegate): nil
---@field add_OnEntityDeath fun(value: EntityDeathDelegate): nil
---@field remove_OnEntityDeath fun(value: EntityDeathDelegate): nil
---@field add_OnEntityDespawn fun(value: EntityDespawnDelegate): nil
---@field remove_OnEntityDespawn fun(value: EntityDespawnDelegate): nil
---@field add_ChunkDirty fun(value: ChunkDirtyDelegate): nil
---@field remove_ChunkDirty fun(value: ChunkDirtyDelegate): nil
---@field add_MapRegionLoaded fun(value: MapRegionLoadedDelegate): nil
---@field remove_MapRegionLoaded fun(value: MapRegionLoadedDelegate): nil
---@field add_MapRegionUnloaded fun(value: MapRegionUnloadDelegate): nil
---@field remove_MapRegionUnloaded fun(value: MapRegionUnloadDelegate): nil
---@field add_OnGetClimate fun(value: OnGetClimateDelegate): nil
---@field remove_OnGetClimate fun(value: OnGetClimateDelegate): nil
---@field add_OnGetWindSpeed fun(value: OnGetWindSpeedDelegate): nil
---@field remove_OnGetWindSpeed fun(value: OnGetWindSpeedDelegate): nil
---@field add_MatchesGridRecipe fun(value: MatchGridRecipeDelegate): nil
---@field remove_MatchesGridRecipe fun(value: MatchGridRecipeDelegate): nil
---@field PushEvent fun(eventName: string, data: IAttribute): nil
---@field RegisterEventBusListener fun(OnEvent: EventBusListenerDelegate, priority: Double, filterByEventName: string): nil
---@field RegisterGameTickListener fun(onGameTick: any`1, millisecondInterval: number, initialDelayOffsetMs: number): Int64
---@overload fun(onGameTick: any`1, errorHandler: any`1, millisecondInterval: number, initialDelayOffsetMs: number): Int64
---@overload fun(onGameTick: Action`3, pos: BlockPos, millisecondInterval: number, initialDelayOffsetMs: number): Int64
---@field RegisterCallback fun(OnTimePassed: any`1, millisecondDelay: number): Int64
---@overload fun(OnTimePassed: any`1, millisecondDelay: number, permittedWhilePaused: boolean): Int64
---@overload fun(OnTimePassed: Action`3, pos: BlockPos, millisecondDelay: number): Int64
---@field UnregisterCallback fun(listenerId: Int64): nil
---@field UnregisterGameTickListener fun(listenerId: Int64): nil
---@field EnqueueMainThreadTask fun(action: Action, code: string): nil
---@field TriggerEntityDeath fun(entity: Entity, damageSourceForDeath: DamageSource): nil
---@field TriggerMatchesRecipe fun(forPlayer: IPlayer, gridRecipe: GridRecipe, ingredients: ItemSlot[], gridWidth: number): boolean
IEventAPI = {}
