---@meta LightSourcesAtBlock
---@class LightSourcesAtBlock: Object
---@field ctor fun(): LightSourcesAtBlock
---@field get_LastBrightness fun(): number
---@field AddHsv fun(h: number, s: number, v: number): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field LastBrightness number
---@field lightHsvs number
---@field lightCount number
LightSourcesAtBlock = {}
