---@meta TrackToLoad
---@class TrackToLoad: Object
---@field ctor fun(): TrackToLoad
---@field get_SoundType fun(): EnumSoundany
---@field set_SoundType fun(value: EnumSoundany): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field SoundType EnumSoundany
---@field ByTrack EnumSoundany
---@field Location EnumSoundany
---@field volume EnumSoundany
---@field pitch EnumSoundany
---@field OnLoaded EnumSoundany
TrackToLoad = {}
