---@meta IStandardShaderProgram
---@class IStandardShaderProgram
---@field set_Tex2D fun(value: number): nil
---@field set_ShadowMapNear2D fun(value: number): nil
---@field set_ShadowMapFar2D fun(value: number): nil
---@field set_NormalShaded fun(value: number): nil
---@field set_ZNear fun(value: Single): nil
---@field set_ZFar fun(value: Single): nil
---@field set_AlphaTest fun(value: Single): nil
---@field set_DamageEffect fun(value: Single): nil
---@field set_ExtraZOffset fun(value: Single): nil
---@field set_ExtraGodray fun(value: Single): nil
---@field set_RgbaAmbientIn fun(value: Vec3f): nil
---@field set_RgbaLightIn fun(value: Vec4f): nil
---@field set_RgbaGlowIn fun(value: Vec4f): nil
---@field set_RgbaFogIn fun(value: Vec4f): nil
---@field set_RgbaTint fun(value: Vec4f): nil
---@field set_FogMinIn fun(value: Single): nil
---@field set_FogDensityIn fun(value: Single): nil
---@field set_ProjectionMatrix fun(value: Single[]): nil
---@field set_ModelMatrix fun(value: Single[]): nil
---@field set_ViewMatrix fun(value: Single[]): nil
---@field set_ExtraGlow fun(value: number): nil
---@field set_ToShadowMapSpaceMatrixFar fun(value: Single[]): nil
---@field set_ToShadowMapSpaceMatrixNear fun(value: Single[]): nil
---@field set_WaterWaveCounter fun(value: Single): nil
---@field set_DontWarpVertices fun(value: number): nil
---@field set_AddRenderFlags fun(value: number): nil
---@field set_Tex2dOverlay2D fun(value: number): nil
---@field set_OverlayOpacity fun(value: Single): nil
---@field set_SsaoAttn fun(value: Single): nil
---@field set_OverlayTextureSize fun(value: Vec2f): nil
---@field set_BaseTextureSize fun(value: Vec2f): nil
---@field set_BaseUvOrigin fun(value: Vec2f): nil
---@field Tex2D number
---@field ShadowMapNear2D number
---@field ShadowMapFar2D number
---@field NormalShaded number
---@field ZNear number
---@field ZFar number
---@field AlphaTest number
---@field DamageEffect number
---@field ExtraZOffset number
---@field ExtraGodray number
---@field RgbaAmbientIn number
---@field RgbaLightIn number
---@field RgbaGlowIn number
---@field RgbaFogIn number
---@field RgbaTint number
---@field FogMinIn number
---@field FogDensityIn number
---@field ProjectionMatrix number
---@field ModelMatrix number
---@field ViewMatrix number
---@field ExtraGlow number
---@field ToShadowMapSpaceMatrixFar number
---@field ToShadowMapSpaceMatrixNear number
---@field WaterWaveCounter number
---@field DontWarpVertices number
---@field AddRenderFlags number
---@field Tex2dOverlay2D number
---@field OverlayOpacity number
---@field SsaoAttn number
---@field OverlayTextureSize number
---@field BaseTextureSize number
---@field BaseUvOrigin number
IStandardShaderProgram = {}
