---@meta GltfBufferView
---@class GltfBufferView: Object
---@field ctor fun(): GltfBufferView
---@field get_Buffer fun(): Int64
---@field set_Buffer fun(value: Int64): nil
---@field get_ByteLength fun(): Int64
---@field set_ByteLength fun(value: Int64): nil
---@field get_ByteOffset fun(): Int64
---@field set_ByteOffset fun(value: Int64): nil
---@field GetType fun(): any
---@field ToString fun(): string
---@field Equals fun(obj: table): boolean
---@field GetHashCode fun(): number
---@field Buffer Int64
---@field ByteLength Int64
---@field ByteOffset Int64
GltfBufferView = {}
