---@meta

---@enum EnumTransformFunction
EnumTransformFunction = {
	IDENTICAL = 0,
	LINEAR = 1,
	LINEARNULLIFY = 2,
	LINEARREDUCE = 3,
	LINEARINCREASE = 4,
	QUADRATIC = 5,
	INVERSELINEAR = 6,
	ROOT = 7,
	SINUS = 8,
	CLAMPEDPOSITIVESINUS = 9,
	COSINUS = 10,
	SMOOTHSTEP = 11
}
